-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 04-10-2025 21:43
module( ..., package.seeall )
require( "ui.widgets.GenericSelectionButton" )
require( "ui.frontEnd.mp.GenericHeader" )
require( "ui.widgets.MenuTitle" )
local f0_local0 = function ( f4_arg0, f4_arg1, f4_arg2 )
	assert( f4_arg0.MenuTitle )
	assert( f4_arg0.RarityHeader )
	assert( f4_arg0.RarityHighButton )
	assert( f4_arg0.RarityLowButton )
	assert( f4_arg0.OwnershipAcquiredButton )
	assert( f4_arg0.OwnershipUnacquiredButton )
	assert( f4_arg0.OwnershipNoneButton )
	assert( f4_arg0.OwnershipHeader )
	local f4_local0 = f4_arg2.menu
	f4_arg0._filterValueChanged = false
	f4_arg0._sortingValueChanged = false
	local f4_local1 = function ( f14_arg0 )
		local f14_local0 = f4_arg0.OwnershipAcquiredButton
		local f14_local1 = f14_local0
		f14_local0 = f14_local0.SetEquipped
		local f14_local2
		if f14_arg0 then
			f14_local2 = f14_arg0
		else
			f14_local2 = f14_arg0 == LOOT.lockedSortingOptions.HIDE
		end
		f14_local0( f14_local1, f14_local2 )
		f14_local0 = f4_arg0.OwnershipUnacquiredButton
		f14_local1 = f14_local0
		f14_local0 = f14_local0.SetEquipped
		if f14_arg0 then
			f14_local2 = f14_arg0
		else
			f14_local2 = f14_arg0 == LOOT.lockedSortingOptions.SHOW
		end
		f14_local0( f14_local1, f14_local2 )
		f4_arg0.OwnershipNoneButton:SetEquipped( f14_arg0 == nil )
	end
	
	f4_arg0.OwnershipAcquiredButton:addEventHandler( "button_action", function ( f13_arg0, f13_arg1 )
		f4_arg0._filterValueChanged = true
		f4_arg0.ownershipSortingOption = LOOT.lockedSortingOptions.HIDE
		f4_arg0( f4_arg0.ownershipSortingOption )
	end )
	f4_arg0.OwnershipUnacquiredButton:addEventHandler( "button_action", function ( f12_arg0, f12_arg1 )
		f4_arg0._filterValueChanged = true
		f4_arg0.ownershipSortingOption = LOOT.lockedSortingOptions.SHOW
		f4_arg0( f4_arg0.ownershipSortingOption )
	end )
	f4_arg0.OwnershipNoneButton:addEventHandler( "button_action", function ( f11_arg0, f11_arg1 )
		f4_arg0._filterValueChanged = true
		f4_arg0.ownershipSortingOption = nil
		f4_arg0( f4_arg0.ownershipSortingOption )
	end )
	local f4_local2 = function ( f10_arg0 )
		if f10_arg0 == nil then
			return 
		end
		f4_arg0.RarityLowButton:SetEquipped( f10_arg0 == LOOT.raritySortingOptions.LOW_FIRST )
		f4_arg0.RarityHighButton:SetEquipped( f10_arg0 == LOOT.raritySortingOptions.HIGH_FIRST )
		if not CONDITIONS.IsLanguageAsian() then
			f4_arg0.RarityNoneButton:SetEquipped( f10_arg0 == LOOT.raritySortingOptions.NONE )
		end
	end
	
	f4_arg0.RarityLowButton:addEventHandler( "button_action", function ( f9_arg0, f9_arg1 )
		f4_arg0._sortingValueChanged = true
		f4_arg0.raritySortingType = LOOT.raritySortingOptions.LOW_FIRST
		f4_arg0( f4_arg0.raritySortingType )
	end )
	f4_arg0.RarityHighButton:addEventHandler( "button_action", function ( f8_arg0, f8_arg1 )
		f4_arg0._sortingValueChanged = true
		f4_arg0.raritySortingType = LOOT.raritySortingOptions.HIGH_FIRST
		f4_arg0( f4_arg0.raritySortingType )
	end )
	if not CONDITIONS.IsLanguageAsian() then
		f4_arg0.RarityNoneButton:addEventHandler( "button_action", function ( f7_arg0, f7_arg1 )
			f4_arg0._sortingValueChanged = true
			f4_arg0.raritySortingType = LOOT.raritySortingOptions.NONE
			f4_arg0( f4_arg0.raritySortingType )
		end )
	end
	local f4_local3 = f4_local2
	local f4_local4 = f4_local0.raritySortingType
	if not f4_local4 then
		f4_local4 = LOOT.raritySortingOptions.NONE
	end
	f4_local3( f4_local4 )
	f4_local1( f4_local0.ownershipSortingOption or nil )
	f4_arg0.bindButton = LUI.UIBindButton.new()
	f4_arg0.bindButton.id = "selfBindButton"
	f4_arg0:addElement( f4_arg0.bindButton )
	f4_arg0.bindButton:addEventHandler( "button_secondary", function ( f6_arg0, f6_arg1 )
		if f6_arg1.qualifier == "keyboard" or f6_arg1.qualifier == "gamepad" then
			f4_arg0.expandScrollBarOnClose = true
		end
	end )
	f4_arg0:addEventHandler( "menu_close", function ( f5_arg0, f5_arg1 )
		if f4_arg0.expandScrollBarOnClose then
			f4_arg0:dispatchEventToChildren( {
				name = "expand"
			} )
		end
	end )
	if IsLanguageArabic() then
		ACTIONS.AnimateSequence( f4_arg0, "AR" )
	end
end

function ArmorySortingPopup( menu, controller )
	local self = LUI.UIVerticalNavigator.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 600 * _1080p, 0, 1080 * _1080p )
	self.id = "ArmorySortingPopup"
	self._animationSets = self._animationSets or {}
	self._sequences = self._sequences or {}
	self._sequenceLengths = self._sequenceLengths or {}
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	f1_local1 = LUI.ValidateControllerIndex( self, f1_local1 )
	local f1_local2 = self
	local RarityLowButton = nil
	
	RarityLowButton = MenuBuilder.BuildRegisteredType( "GenericSelectionButton", {
		controllerIndex = f1_local1
	} )
	RarityLowButton.id = "RarityLowButton"
	RarityLowButton.GenericButton.Text:setText( ToUpperCase( Engine[0xED84C33EC5F01EA]( "LUA_MENU/COMMON_FIRST" ) ), 0 )
	RarityLowButton:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 100, _1080p * 500, _1080p * 241, _1080p * 297 )
	self:addElement( RarityLowButton )
	self.RarityLowButton = RarityLowButton
	
	local RarityHighButton = nil
	
	RarityHighButton = MenuBuilder.BuildRegisteredType( "GenericSelectionButton", {
		controllerIndex = f1_local1
	} )
	RarityHighButton.id = "RarityHighButton"
	RarityHighButton.GenericButton.Text:setText( ToUpperCase( Engine[0xED84C33EC5F01EA]( "LUA_MENU/LEGENDARY_FIRST" ) ), 0 )
	RarityHighButton:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 100, _1080p * 500, _1080p * 303, _1080p * 359 )
	self:addElement( RarityHighButton )
	self.RarityHighButton = RarityHighButton
	
	local f1_local5 = nil
	if not CONDITIONS.IsLanguageAsian() then
		f1_local5 = MenuBuilder.BuildRegisteredType( "GenericSelectionButton", {
			controllerIndex = f1_local1
		} )
		f1_local5.id = "RarityNoneButton"
		f1_local5.GenericButton.Text:setText( ToUpperCase( Engine[0xED84C33EC5F01EA]( "LUA_MENU/OFF" ) ), 0 )
		f1_local5:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 100, _1080p * 500, _1080p * 365, _1080p * 421 )
		self:addElement( f1_local5 )
		self.RarityNoneButton = f1_local5
	end
	local RarityHeader = nil
	
	RarityHeader = MenuBuilder.BuildRegisteredType( "GenericHeader", {
		controllerIndex = f1_local1
	} )
	RarityHeader.id = "RarityHeader"
	RarityHeader.Title:SetRGBFromTable( SWATCHES.genericMenu.featuredHeader, 0 )
	RarityHeader.Title:setText( Engine[0xED84C33EC5F01EA]( "LUA_MENU/SORT_RARITY" ), 0 )
	RarityHeader:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 100, _1080p * 506, _1080p * 199, _1080p * 235 )
	self:addElement( RarityHeader )
	self.RarityHeader = RarityHeader
	
	local OwnershipAcquiredButton = nil
	
	OwnershipAcquiredButton = MenuBuilder.BuildRegisteredType( "GenericSelectionButton", {
		controllerIndex = f1_local1
	} )
	OwnershipAcquiredButton.id = "OwnershipAcquiredButton"
	OwnershipAcquiredButton.GenericButton.Text:setText( ToUpperCase( Engine[0xED84C33EC5F01EA]( "LUA_MENU/ACQUIRED" ) ), 0 )
	OwnershipAcquiredButton:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 100, _1080p * 500, _1080p * 512, _1080p * 568 )
	self:addElement( OwnershipAcquiredButton )
	self.OwnershipAcquiredButton = OwnershipAcquiredButton
	
	local OwnershipUnacquiredButton = nil
	
	OwnershipUnacquiredButton = MenuBuilder.BuildRegisteredType( "GenericSelectionButton", {
		controllerIndex = f1_local1
	} )
	OwnershipUnacquiredButton.id = "OwnershipUnacquiredButton"
	OwnershipUnacquiredButton.GenericButton.Text:setText( ToUpperCase( Engine[0xED84C33EC5F01EA]( "LUA_MENU/UNACQUIRED" ) ), 0 )
	OwnershipUnacquiredButton:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 100, _1080p * 500, _1080p * 574, _1080p * 630 )
	self:addElement( OwnershipUnacquiredButton )
	self.OwnershipUnacquiredButton = OwnershipUnacquiredButton
	
	local OwnershipNoneButton = nil
	
	OwnershipNoneButton = MenuBuilder.BuildRegisteredType( "GenericSelectionButton", {
		controllerIndex = f1_local1
	} )
	OwnershipNoneButton.id = "OwnershipNoneButton"
	OwnershipNoneButton.GenericButton.Text:setText( ToUpperCase( Engine[0xED84C33EC5F01EA]( "LUA_MENU/OFF" ) ), 0 )
	OwnershipNoneButton:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 100, _1080p * 500, _1080p * 636, _1080p * 692 )
	self:addElement( OwnershipNoneButton )
	self.OwnershipNoneButton = OwnershipNoneButton
	
	local OwnershipHeader = nil
	
	OwnershipHeader = MenuBuilder.BuildRegisteredType( "GenericHeader", {
		controllerIndex = f1_local1
	} )
	OwnershipHeader.id = "OwnershipHeader"
	OwnershipHeader.Title:SetRGBFromTable( SWATCHES.genericMenu.featuredHeader, 0 )
	OwnershipHeader.Title:setText( Engine[0xED84C33EC5F01EA]( "LUA_MENU/SORT_OWNERSHIP" ), 0 )
	OwnershipHeader:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 100, _1080p * 506, _1080p * 470, _1080p * 506 )
	self:addElement( OwnershipHeader )
	self.OwnershipHeader = OwnershipHeader
	
	local MenuTitle = nil
	
	MenuTitle = MenuBuilder.BuildRegisteredType( "MenuTitle", {
		controllerIndex = f1_local1
	} )
	MenuTitle.id = "MenuTitle"
	MenuTitle.MenuTitle:SetAlpha( 0.15, 0 )
	MenuTitle.MenuTitle:setText( Engine[0xED84C33EC5F01EA]( "LUA_MENU/SORT_FILTER" ), 0 )
	MenuTitle.Line:SetLeft( 0, 0 )
	MenuTitle:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 1024, 0, _1080p * 100 )
	self:addElement( MenuTitle )
	self.MenuTitle = MenuTitle
	
	self._sequences.DefaultSequence = function ()
		
	end
	
	self._sequenceLengths.DefaultSequence = 0
	local f1_local12 = nil
	RarityHeader:RegisterAnimationSequence( "AR", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Bottom,
			value = _1080p * 234
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Top,
			value = _1080p * 198
		}
	} )
	OwnershipHeader:RegisterAnimationSequence( "AR", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Bottom,
			value = _1080p * 505
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Top,
			value = _1080p * 469
		}
	} )
	self._sequences.AR = function ()
		menu:AnimateSequence( "AR" )
		menu:AnimateSequence( "AR" )
	end
	
	self._sequenceLengths.AR = 0
	f0_local0( self, f1_local1, controller )
	return self
end

MenuBuilder.registerType( "ArmorySortingPopup", ArmorySortingPopup )
LockTable( _M )
