-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 04-10-2025 21:42
module( ..., package.seeall )
require( "ui.widgets.DoubleNotchedBacker" )
require( "ui.widgets.AARContentHeader" )
require( "ui.widgets.LootItemCardMini" )
require( "ui.frontEnd.BarracksChallengeStatusLockBanner" )
local f0_local0 = function ( f10_arg0, f10_arg1 )
	if f10_arg1 and f10_arg1.rewards and 0 < #f10_arg1.rewards then
		f10_arg0:SetAlpha( 1 )
		local f10_local0 = math.min( #f10_arg1.rewards, #f10_arg0._rewardWidgets )
		ACTIONS.AnimateSequence( f10_arg0, "ShowIcon" .. f10_local0 )
		for f10_local1 = 1, f10_local0, 1 do
			local f10_local4 = f10_arg1.rewards[f10_local1]
			local f10_local5 = f10_arg0._rewardWidgets[f10_local1]
			local f10_local6 = f10_arg0._nameWidgets[f10_local1]
			f10_arg0.PreivewPrompt:SetAlpha( 0 )
			f10_arg0._previewData = nil
			if f10_local4.lootItemID then
				f10_arg0._previewData = f10_local4
				f10_arg0.PreivewPrompt:SetAlpha( 1 )
			end
			f10_local5:UpdateCardConfig( f10_local4 )
			f10_local6:setText( f10_local4.typeName or "" )
		end
	else
		f10_arg0:SetAlpha( 0 )
	end
end

local f0_local1 = function ( f9_arg0, f9_arg1 )
	if f9_arg1 then
		if not f9_arg0._bannerShown then
			f9_arg0.LockBanner:SetAlpha( 1 )
			ACTIONS.AnimateSequence( f9_arg0.LockBanner, "ShowLock" )
			f9_arg0._bannerShown = true
		end
	else
		f9_arg0.LockBanner:SetAlpha( 0 )
		f9_arg0._bannerShown = false
	end
end

local f0_local2 = function ( f8_arg0, f8_arg1 )
	local f8_local0 = Challenge.GetDifficulty( f8_arg1.id, f8_arg1.type )
	if f8_local0 ~= Challenge.Difficulty.NONE then
		f8_arg0.DifficultyImage:SetAlpha( 1 )
		f8_arg0.ChallengeDifficultyText:SetAlpha( 1 )
		f8_arg0.Difficulty:SetAlpha( 1 )
		if f8_local0 == Challenge.Difficulty.REGULAR then
			f8_arg0.DifficultyImage:setImage( RegisterMaterial( "icon_challenge_difficulty_regular" ) )
			f8_arg0.Difficulty:setText( Engine[0xED84C33EC5F01EA]( "MENU/REGULAR" ) )
		elseif f8_local0 == Challenge.Difficulty.HARDENED then
			f8_arg0.DifficultyImage:setImage( RegisterMaterial( "icon_challenge_difficulty_hard" ) )
			f8_arg0.Difficulty:setText( Engine[0xED84C33EC5F01EA]( "MENU/HARDENED" ) )
		elseif f8_local0 == Challenge.Difficulty.VETERAN then
			f8_arg0.DifficultyImage:setImage( RegisterMaterial( "icon_challenge_difficulty_veteran" ) )
			f8_arg0.Difficulty:setText( Engine[0xED84C33EC5F01EA]( "MENU/VETERAN" ) )
		end
	else
		f8_arg0.DifficultyImage:SetAlpha( 0 )
		f8_arg0.ChallengeDifficultyText:SetAlpha( 0 )
		f8_arg0.Difficulty:SetAlpha( 0 )
	end
end

local f0_local3 = function ( f6_arg0, f6_arg1, f6_arg2 )
	assert( f6_arg0.RewardName1 )
	assert( f6_arg0.Reward1 )
	assert( f6_arg0.RewardName2 )
	assert( f6_arg0.Reward2 )
	f6_arg0._bannerShown = false
	f6_arg0._nameWidgets = {
		f6_arg0.RewardName1,
		f6_arg0.RewardName2
	}
	f6_arg0._rewardWidgets = {
		f6_arg0.Reward1,
		f6_arg0.Reward2
	}
	f6_arg0.SetData = f0_local0
	f6_arg0.SetChallengeLocked = f0_local0
	f6_arg0.BindButton = LUI.UIBindButton.new()
	f6_arg0.BindButton.id = "BindButton"
	f6_arg0:addElement( f6_arg0.BindButton )
	f6_arg0.BindButton:registerEventHandler( "button_right_stick", function ( element, event )
		if f6_arg0._previewData then
			STORE.PreviewItem( f6_arg0, f6_arg0._previewData.type, f6_arg0._previewData.itemID )
			if event.qualifier then
				Engine[0xC4146BA76D0F982]( SOUND_SETS.default.menuDecode )
			end
		end
	end )
	f6_arg0.SetDifficulty = f0_local0
end

function BarracksChallengeStatus( menu, controller )
	local self = LUI.UIElement.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 425 * _1080p, 0, 400 * _1080p )
	self.id = "BarracksChallengeStatus"
	self._animationSets = self._animationSets or {}
	self._sequences = self._sequences or {}
	self._sequenceLengths = self._sequenceLengths or {}
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine[0x12586A3F4FB490E]() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1, "Missing controllerIndex!" )
	local f1_local2 = self
	local DoubleNotchedBacker = nil
	
	DoubleNotchedBacker = MenuBuilder.BuildRegisteredType( "DoubleNotchedBacker", {
		controllerIndex = f1_local1
	} )
	DoubleNotchedBacker.id = "DoubleNotchedBacker"
	DoubleNotchedBacker:SetAlpha( 0.5, 0 )
	DoubleNotchedBacker.Background:SetRGBFromTable( SWATCHES.CAC.panelBacker, 0 )
	DoubleNotchedBacker:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 425, 0, _1080p * 400 )
	self:addElement( DoubleNotchedBacker )
	self.DoubleNotchedBacker = DoubleNotchedBacker
	
	local RewardName2 = nil
	
	RewardName2 = LUI.UIStyledText.new()
	RewardName2.id = "RewardName2"
	RewardName2:SetRGBFromTable( SWATCHES.genericMenu.bodycopy, 0 )
	RewardName2:setText( "", 0 )
	RewardName2:SetFont( FONTS.GetFont( FONTS.MainRegularHeader.File ) )
	RewardName2:SetFontSize( 22 * _PT )
	RewardName2:SetMinFontSize( 16 * _PT )
	RewardName2:SetAlignment( LUI.Alignment.Left )
	RewardName2:SetAnchorsAndPosition( 0, 0, 0, 1, _1080p * 138, _1080p * -137, _1080p * 70, _1080p * 92 )
	self:addElement( RewardName2 )
	self.RewardName2 = RewardName2
	
	local RewardName1 = nil
	
	RewardName1 = LUI.UIStyledText.new()
	RewardName1.id = "RewardName1"
	RewardName1:SetRGBFromTable( SWATCHES.genericMenu.bodycopy, 0 )
	RewardName1:setText( "", 0 )
	RewardName1:SetFont( FONTS.GetFont( FONTS.MainRegularHeader.File ) )
	RewardName1:SetFontSize( 22 * _PT )
	RewardName1:SetMinFontSize( 16 * _PT )
	RewardName1:SetAlignment( LUI.Alignment.Left )
	RewardName1:SetAnchorsAndPosition( 0, 0, 0, 1, _1080p * 138, _1080p * -137, _1080p * 70, _1080p * 92 )
	self:addElement( RewardName1 )
	self.RewardName1 = RewardName1
	
	local ChallengeHeader = nil
	
	ChallengeHeader = MenuBuilder.BuildRegisteredType( "AARContentHeader", {
		controllerIndex = f1_local1
	} )
	ChallengeHeader.id = "ChallengeHeader"
	ChallengeHeader.Text:setText( Engine[0xED84C33EC5F01EA]( "LUA_MENU/REWARD" ), 0 )
	ChallengeHeader:SetAnchorsAndPosition( 0, 0, 0, 1, 0, 0, _1080p * 2, _1080p * 48 )
	self:addElement( ChallengeHeader )
	self.ChallengeHeader = ChallengeHeader
	
	local Reward2 = nil
	
	Reward2 = MenuBuilder.BuildRegisteredType( "LootItemCardMini", {
		controllerIndex = f1_local1
	} )
	Reward2.id = "Reward2"
	Reward2:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 138, _1080p * 288, _1080p * 97, _1080p * 297 )
	self:addElement( Reward2 )
	self.Reward2 = Reward2
	
	local Reward1 = nil
	
	Reward1 = MenuBuilder.BuildRegisteredType( "LootItemCardMini", {
		controllerIndex = f1_local1
	} )
	Reward1.id = "Reward1"
	Reward1:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 138, _1080p * 288, _1080p * 97, _1080p * 297 )
	self:addElement( Reward1 )
	self.Reward1 = Reward1
	
	local PreivewPrompt = nil
	
	PreivewPrompt = LUI.UIStyledText.new()
	PreivewPrompt.id = "PreivewPrompt"
	PreivewPrompt:SetRGBFromTable( SWATCHES.genericMenu.bodycopy, 0 )
	PreivewPrompt:setText( Engine[0xED84C33EC5F01EA]( "LUA_MENU/PREVIEW_LOOT_ITEM" ), 0 )
	PreivewPrompt:SetFont( FONTS.GetFont( FONTS.MainRegularHeader.File ) )
	PreivewPrompt:SetFontSize( 24 * _PT )
	PreivewPrompt:SetMinFontSize( 16 * _PT )
	PreivewPrompt:SetWordWrap( false )
	PreivewPrompt:SetAlignment( LUI.Alignment.Left )
	PreivewPrompt:SetTintFontIcons( true )
	PreivewPrompt:SetAnchorsAndPosition( 0, 1, 1, 0, 0, _1080p * 162, _1080p * 9, _1080p * 33 )
	self:addElement( PreivewPrompt )
	self.PreivewPrompt = PreivewPrompt
	
	local LockBanner = nil
	
	LockBanner = MenuBuilder.BuildRegisteredType( "BarracksChallengeStatusLockBanner", {
		controllerIndex = f1_local1
	} )
	LockBanner.id = "LockBanner"
	LockBanner:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 426, _1080p * -50, _1080p * 20 )
	self:addElement( LockBanner )
	self.LockBanner = LockBanner
	
	local ChallengeDifficultyText = nil
	
	ChallengeDifficultyText = LUI.UIStyledText.new()
	ChallengeDifficultyText.id = "ChallengeDifficultyText"
	ChallengeDifficultyText:SetAlpha( 0, 0 )
	ChallengeDifficultyText:setText( Engine[0xED84C33EC5F01EA]( "LUA_MENU_MP/CHALLENGE_DIFFICULTY" ), 0 )
	ChallengeDifficultyText:SetFont( FONTS.GetFont( FONTS.MainRegularHeader.File ) )
	ChallengeDifficultyText:SetFontSize( 22 * _PT )
	ChallengeDifficultyText:SetMinFontSize( 16 * _PT )
	ChallengeDifficultyText:SetAlignment( LUI.Alignment.Left )
	ChallengeDifficultyText:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 22, _1080p * 223, _1080p * 324, _1080p * 344 )
	self:addElement( ChallengeDifficultyText )
	self.ChallengeDifficultyText = ChallengeDifficultyText
	
	local DifficultyImage = nil
	
	DifficultyImage = LUI.UIImage.new()
	DifficultyImage.id = "DifficultyImage"
	DifficultyImage:SetAlpha( 0, 0 )
	DifficultyImage:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 24, _1080p * 52, _1080p * 354, _1080p * 382 )
	self:addElement( DifficultyImage )
	self.DifficultyImage = DifficultyImage
	
	local Difficulty = nil
	
	Difficulty = LUI.UIStyledText.new()
	Difficulty.id = "Difficulty"
	Difficulty:SetAlpha( 0, 0 )
	Difficulty:setText( Engine[0xED84C33EC5F01EA]( "MENU/HARDENED" ), 0 )
	Difficulty:SetFont( FONTS.GetFont( FONTS.MainRegularHeader.File ) )
	Difficulty:SetFontSize( 16 * _PT )
	Difficulty:SetMinFontSize( 16 * _PT )
	Difficulty:SetAlignment( LUI.Alignment.Left )
	Difficulty:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 63, _1080p * 223, _1080p * 359, _1080p * 377 )
	self:addElement( Difficulty )
	self.Difficulty = Difficulty
	
	self._sequences.DefaultSequence = function ()
		
	end
	
	self._sequenceLengths.DefaultSequence = 0
	local f1_local14 = nil
	RewardName2:RegisterAnimationSequence( "HideIcon", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	RewardName1:RegisterAnimationSequence( "HideIcon", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Reward2:RegisterAnimationSequence( "HideIcon", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Reward1:RegisterAnimationSequence( "HideIcon", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.HideIcon = function ()
		menu:AnimateSequence( "HideIcon" )
		menu:AnimateSequence( "HideIcon" )
		menu:AnimateSequence( "HideIcon" )
		menu:AnimateSequence( "HideIcon" )
	end
	
	self._sequenceLengths.HideIcon = 0
	local f1_local15 = nil
	RewardName2:RegisterAnimationSequence( "ShowIcon1", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	RewardName1:RegisterAnimationSequence( "ShowIcon1", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * 138
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * -107
		},
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Reward2:RegisterAnimationSequence( "ShowIcon1", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * 138
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 288
		}
	} )
	Reward1:RegisterAnimationSequence( "ShowIcon1", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * 138
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 288
		}
	} )
	self._sequences.ShowIcon1 = function ()
		menu:AnimateSequence( "ShowIcon1" )
		menu:AnimateSequence( "ShowIcon1" )
		menu:AnimateSequence( "ShowIcon1" )
		menu:AnimateSequence( "ShowIcon1" )
	end
	
	self._sequenceLengths.ShowIcon1 = 0
	local f1_local16 = nil
	RewardName2:RegisterAnimationSequence( "ShowIcon2", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * 235
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * -40
		},
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	RewardName1:RegisterAnimationSequence( "ShowIcon2", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * 40
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * -235
		},
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Reward2:RegisterAnimationSequence( "ShowIcon2", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * 235
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 385
		},
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Reward1:RegisterAnimationSequence( "ShowIcon2", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * 40
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 190
		}
	} )
	self._sequences.ShowIcon2 = function ()
		menu:AnimateSequence( "ShowIcon2" )
		menu:AnimateSequence( "ShowIcon2" )
		menu:AnimateSequence( "ShowIcon2" )
		menu:AnimateSequence( "ShowIcon2" )
	end
	
	self._sequenceLengths.ShowIcon2 = 0
	f0_local0( self, f1_local1, controller )
	return self
end

MenuBuilder.registerType( "BarracksChallengeStatus", BarracksChallengeStatus )
LockTable( _M )
