-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 04-10-2025 21:42
module( ..., package.seeall )
local f0_local0 = _1080p * 10
local f0_local1 = 5
local f0_local2 = function ( f4_arg0 )
	local f4_local0, f4_local1, f4_local2, f4_local3, f4_local4, f4_local5, f4_local6, f4_local7 = LAYOUT.GetAnchorsAndPositionsFromElement( f4_arg0.Label )
	local f4_local8 = LAYOUT.GetTextHeight( f4_arg0.Label, f4_arg0._controllerIndex )
	local f4_local9 = LAYOUT.GetTextWidth( f4_arg0.Label, f4_arg0._controllerIndex ) * -1 - f0_local0
	f4_arg0.Icon:SetTop( f4_local6 )
	f4_arg0.Icon:SetRight( f4_local9 )
	f4_arg0.Icon:SetLeft( f4_local9 - f4_local8 )
	f4_arg0.Icon:SetBottom( f4_local6 + f4_local8 )
end

local f0_local3 = function ( f2_arg0, f2_arg1, f2_arg2 )
	f2_arg0.UpdateWarningIconPosition = f0_local0
	f2_arg0._controllerIndex = f2_arg1
	f2_arg0.Icon:SetAlpha( 0 )
	local f2_local0 = f2_arg0:Wait( f0_local0 )
	f2_local0.onComplete = function ()
		f2_arg0:UpdateWarningIconPosition()
		f2_arg0.Icon:SetAlpha( 1 )
	end
	
end

function RightAlignedWarningLabel( menu, controller )
	local self = LUI.UIElement.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 300 * _1080p, 0, 20 * _1080p )
	self.id = "RightAlignedWarningLabel"
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	f1_local1 = LUI.ValidateControllerIndex( self, f1_local1 )
	local f1_local2 = self
	local Icon = nil
	
	Icon = LUI.UIImage.new()
	Icon.id = "Icon"
	Icon:setImage( RegisterMaterial( "ui_streak_warning" ), 0 )
	Icon:SetAnchorsAndPosition( 1, 0, 0, 1, _1080p * -300, _1080p * -280, 0, _1080p * 20 )
	self:addElement( Icon )
	self.Icon = Icon
	
	local Label = nil
	
	Label = LUI.UIStyledText.new()
	Label.id = "Label"
	Label:SetRGBFromInt( 12472362, 0 )
	Label:setText( "", 0 )
	Label:SetFont( FONTS.GetFont( FONT_STYLES.fontStyle_SHeader.font.File ) )
	Label:SetFontSize( FONT_STYLES.fontStyle_SHeader.size )
	Label:SetMinFontSize( FONT_STYLES.fontStyle_SHeader.minSize )
	Label:SetWordWrap( false )
	Label:SetAlignment( LUI.Alignment.Right )
	self:addElement( Label )
	self.Label = Label
	
	f0_local0( self, f1_local1, controller )
	return self
end

MenuBuilder.registerType( "RightAlignedWarningLabel", RightAlignedWarningLabel )
LockTable( _M )
