-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 27-09-2025 22:41
module( ..., package.seeall )
local f0_local0 = function ( f8_arg0, f8_arg1, f8_arg2, f8_arg3 )
	assert( f8_arg3 )
	assert( f8_arg2 )
	local f8_local0 = "Relic" .. tostring( f8_arg3 )
	local f8_local1 = 4
	local f8_local2 = 0
	local f8_local3 = Engine.CBBHFCGDIC( "LUA_MENU_CP/SURVIVAL" )
	local f8_local4 = 0
	local f8_local5 = 0
	if f8_arg2 and f8_arg2 ~= "" then
		f8_arg0[f8_local0].RelicDesc:setText( f8_local3 )
		f8_local4 = LAYOUT.GetTextHeightWithWrapping( f8_arg0[f8_local0].RelicDesc, f8_local3 )
		local f8_local6 = tonumber( f8_arg2 )
		local f8_local7 = StringTable.DIFCHIGDFB( CSV.cpRelicTable.file, CSV.cpRelicTable.cols.idx, f8_local6, CSV.cpRelicTable.cols.icon )
		local f8_local8 = ToUpperCase( Engine.CBBHFCGDIC( StringTable.DIFCHIGDFB( CSV.cpRelicTable.file, CSV.cpRelicTable.cols.idx, f8_local6, CSV.cpRelicTable.cols.name ) ) )
		local f8_local9 = Engine.CBBHFCGDIC( StringTable.DIFCHIGDFB( CSV.cpRelicTable.file, CSV.cpRelicTable.cols.idx, f8_local6, CSV.cpRelicTable.cols.desc ) )
		if f8_local7 and f8_local7 ~= "" then
			f8_arg0[f8_local0].RelicIcon:setImage( RegisterMaterial( f8_local7 ), 0 )
		end
		if f8_local8 then
			f8_arg0[f8_local0].RelicText:setText( f8_local8 )
		end
		if f8_local9 == f8_local8 then
			f8_local9 = f8_local9 .. " add a description in cp_relic_table.csv."
		end
		if f8_local9 then
			f8_arg0[f8_local0].RelicDesc:setText( f8_local9 )
			f8_local2 = LAYOUT.GetTextHeightWithWrapping( f8_arg0[f8_local0].RelicDesc, f8_local9 )
		end
		ACTIONS.AnimateSequenceByElement( f8_arg0, {
			sequenceName = "Display",
			elementName = f8_local0,
			elementPath = f8_arg0[f8_local0]
		} )
	else
		ACTIONS.AnimateSequenceByElement( f8_arg0, {
			sequenceName = "Hide",
			elementName = f8_local0,
			elementPath = f8_arg0[f8_local0]
		} )
	end
	f8_local2 = tonumber( string.format( "%." .. 2 .. "f", f8_local2 ) )
	f8_local4 = tonumber( string.format( "%." .. 2 .. "f", f8_local4 ) )
	local f8_local6 = f8_local2 / f8_local4
	if 2 <= f8_local6 and f8_local6 <= 3 then
		f8_local5 = f8_local4
	elseif 1 <= f8_local6 and f8_local6 <= 2 then
		f8_local5 = f8_local4 * 2
	else
		f8_local5 = 0
	end
	return f8_local5 - f8_local1
end

local f0_local1 = function ( f6_arg0, f6_arg1, f6_arg2 )
	f6_arg0:SetAlpha( 0 )
	f6_arg0:SubscribeToDataSourceThroughElement( f6_arg0, nil, function ()
		local f7_local0 = f6_arg0:GetDataSource()
		if f7_local0 then
			local f7_local1 = f7_local0.numRounds:GetValue( f6_arg0 )
			if 0 < f7_local1 then
				local f7_local2 = tostring( f7_local1 )
				local f7_local3 = f6_arg0( f6_arg0, f6_arg0, string.sub( f7_local2, 1, 2 ), 1 )
				local f7_local4 = f6_arg0( f6_arg0, f6_arg0, string.sub( f7_local2, 3, 4 ), 2 )
				local f7_local5 = f6_arg0( f6_arg0, f6_arg0, string.sub( f7_local2, 5, 6 ), 3 )
				local f7_local6 = f6_arg0( f6_arg0, f6_arg0, string.sub( f7_local2, 7, 8 ), 4 )
				f6_arg0:SetAlpha( 1 )
				f6_arg0.Relic1:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 380, _1080p * 45, _1080p * 145 )
				f6_arg0.Relic2:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 380, _1080p * 145 - f7_local3, _1080p * 245 - f7_local3 )
				f6_arg0.Relic3:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 380, _1080p * 245 - f7_local3 - f7_local4, _1080p * 345 - f7_local3 - f7_local4 )
				f6_arg0.Relic4:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 380, _1080p * 345 - f7_local3 - f7_local4 - f7_local5, _1080p * 445 - f7_local3 - f7_local4 - f7_local5 )
			else
				f6_arg0:SetAlpha( 0 )
			end
		end
	end )
	if IsLanguageArabic() then
		ACTIONS.AnimateSequence( f6_arg0, "AR" )
	end
end

function CPRelicsActiveFrontEnd( menu, controller )
	local self = LUI.UIElement.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 380 * _1080p, 0, 445 * _1080p )
	self.id = "CPRelicsActiveFrontEnd"
	self._animationSets = self._animationSets or {}
	self._sequences = self._sequences or {}
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine.DDJFBBJAIG() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1 )
	local f1_local2 = self
	local Background = nil
	
	Background = LUI.UIImage.new()
	Background.id = "Background"
	Background:SetRGBFromTable( SWATCHES.CAC.panelBacker, 0 )
	Background:SetAlpha( 0.5, 0 )
	Background:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 375, 0, _1080p * 445 )
	self:addElement( Background )
	self.Background = Background
	
	local Relic4 = nil
	
	Relic4 = MenuBuilder.BuildRegisteredType( "CPRelicsWidgetFrontEnd", {
		controllerIndex = f1_local1
	} )
	Relic4.id = "Relic4"
	Relic4.RelicText:setText( ToUpperCase( Engine.CBBHFCGDIC( "MENU/NEW" ) ), 0 )
	Relic4.RelicText:SetShadowUOffset( -0.001, 0 )
	Relic4.RelicDesc:setText( Engine.CBBHFCGDIC( "MENU/NEW" ), 0 )
	Relic4.RelicDesc:SetShadowMaxDistance( 0, 0 )
	Relic4:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 380, _1080p * 345, _1080p * 445 )
	self:addElement( Relic4 )
	self.Relic4 = Relic4
	
	local Relic3 = nil
	
	Relic3 = MenuBuilder.BuildRegisteredType( "CPRelicsWidgetFrontEnd", {
		controllerIndex = f1_local1
	} )
	Relic3.id = "Relic3"
	Relic3.RelicText:setText( ToUpperCase( Engine.CBBHFCGDIC( "MENU/NEW" ) ), 0 )
	Relic3.RelicText:SetShadowUOffset( 0, 0 )
	Relic3.RelicDesc:setText( Engine.CBBHFCGDIC( "MENU/NEW" ), 0 )
	Relic3.RelicDesc:SetShadowMaxDistance( 0, 0 )
	Relic3.RelicDesc:SetShadowUOffset( -0.002, 0 )
	Relic3:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 380, _1080p * 245, _1080p * 345 )
	self:addElement( Relic3 )
	self.Relic3 = Relic3
	
	local Relic2 = nil
	
	Relic2 = MenuBuilder.BuildRegisteredType( "CPRelicsWidgetFrontEnd", {
		controllerIndex = f1_local1
	} )
	Relic2.id = "Relic2"
	Relic2.RelicText:setText( ToUpperCase( Engine.CBBHFCGDIC( "MENU/NEW" ) ), 0 )
	Relic2.RelicText:SetShadowUOffset( 0, 0 )
	Relic2.RelicDesc:setText( Engine.CBBHFCGDIC( "MENU/NEW" ), 0 )
	Relic2.RelicDesc:SetShadowMaxDistance( 0, 0 )
	Relic2.RelicDesc:SetShadowUOffset( 0.002, 0 )
	Relic2:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 380, _1080p * 145, _1080p * 245 )
	self:addElement( Relic2 )
	self.Relic2 = Relic2
	
	local Relic1 = nil
	
	Relic1 = MenuBuilder.BuildRegisteredType( "CPRelicsWidgetFrontEnd", {
		controllerIndex = f1_local1
	} )
	Relic1.id = "Relic1"
	Relic1.RelicText:setText( ToUpperCase( Engine.CBBHFCGDIC( "MENU/NEW" ) ), 0 )
	Relic1.RelicText:SetShadowUOffset( 0, 0 )
	Relic1.RelicDesc:setText( Engine.CBBHFCGDIC( "MENU/NEW" ), 0 )
	Relic1.RelicDesc:SetShadowMaxDistance( 0, 0 )
	Relic1:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 380, _1080p * 45, _1080p * 145 )
	self:addElement( Relic1 )
	self.Relic1 = Relic1
	
	local Header = nil
	
	Header = LUI.UIStyledText.new()
	Header.id = "Header"
	Header:SetRGBFromTable( SWATCHES.genericMenu.featuredHeader, 0 )
	Header:setText( Engine.CBBHFCGDIC( "LUA_MENU_CP/RELIC_HEADER_MAIN" ), 0 )
	Header:SetFont( FONTS.GetFont( FONTS.MainRegular.File ) )
	Header:SetWordWrap( false )
	Header:SetAlignment( LUI.Alignment.Left )
	Header:SetShadowUOffset( -0.002, 0 )
	Header:SetShadowRGBFromTable( SWATCHES.HUD.HUDShadow, 0 )
	Header:SetAnchorsAndPosition( 0, 0, 0, 1, _1080p * 17, _1080p * -17, _1080p * 7, _1080p * 31 )
	self:addElement( Header )
	self.Header = Header
	
	self._sequences.DefaultSequence = function ()
		
	end
	
	self._sequences.InfoLayout = function ()
		
	end
	
	self._sequences.IconStripLayout = function ()
		
	end
	
	local f1_local9 = nil
	Header:RegisterAnimationSequence( "AR", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Bottom,
			value = _1080p * 37
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Top,
			value = _1080p * 7
		}
	} )
	self._sequences.AR = function ()
		menu:AnimateSequence( "AR" )
	end
	
	f0_local0( self, f1_local1, controller )
	return self
end

MenuBuilder.registerType( "CPRelicsActiveFrontEnd", CPRelicsActiveFrontEnd )
LockTable( _M )
