-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 17-11-2025 01:21
module( ..., package.seeall )
local f0_local0 = function ( f18_arg0, f18_arg1 )
	assert( f18_arg0.Text )
	f18_arg0.Text:setText( f18_arg1 )
end

function RefreshAnimation( f17_arg0, f17_arg1, f17_arg2 )
	if f17_arg0._lastState ~= f17_arg1 then
		f17_arg0._lastState = f17_arg1
		if f17_arg2 then
			f17_arg1 = f17_arg1 .. "Snap"
		end
		ACTIONS.AnimateSequence( f17_arg0, f17_arg1 )
	end
end

function PostLoadFunc( f12_arg0, f12_arg1, f12_arg2 )
	f12_arg0:SetNotifyOnLayoutInit( true )
	f12_arg0:addEventHandler( "button_over", function ( f16_arg0, f16_arg1 )
		f12_arg0.isInHoverState = true
		RefreshAnimation( f16_arg0, "ButtonOver" )
	end )
	f12_arg0:addEventHandler( "button_up", function ( f15_arg0, f15_arg1 )
		f12_arg0.isInHoverState = false
		RefreshAnimation( f15_arg0, "ButtonUp", f15_arg1.snap )
	end )
	f12_arg0:addEventHandler( "button_disable", function ( f14_arg0, f14_arg1 )
		RefreshAnimation( f14_arg0, "ButtonUpDisabled", f14_arg1.snap )
	end )
	f12_arg0:addEventHandler( "button_over_disable", function ( f13_arg0, f13_arg1 )
		RefreshAnimation( f13_arg0, "ButtonOverDisabled" )
	end )
	if IsLanguageArabic() then
		ACTIONS.AnimateSequence( f12_arg0, "AR" )
	end
	f12_arg0.SetText = f0_local0
end

function MaintenanceButton( menu, controller )
	local self = LUI.UIButton.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 420 * _1080p, 0, 38 * _1080p )
	self.id = "MaintenanceButton"
	self._animationSets = self._animationSets or {}
	self._sequences = self._sequences or {}
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine.DDJFBBJAIG() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1 )
	local f1_local2 = self
	local Background = nil
	
	Background = LUI.UIImage.new()
	Background.id = "Background"
	Background:SetRGBFromTable( SWATCHES.CH2.NeutralGray, 0 )
	Background:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 420, 0, _1080p * 38 )
	self:addElement( Background )
	self.Background = Background
	
	local Text = nil
	
	Text = LUI.UIStyledText.new()
	Text.id = "Text"
	Text:SetRGBFromTable( SWATCHES.CH2.White, 0 )
	Text:setText( ToUpperCase( "" ), 0 )
	Text:SetFont( FONTS.GetFont( FONTS.MainBold.File ) )
	Text:SetAlignment( LUI.Alignment.Center )
	Text:SetAutoScrollStyle( LUI.UIStyledText.AutoScrollStyle.ScrollH )
	Text:SetStartupDelay( 2000 )
	Text:SetLineHoldTime( 400 )
	Text:SetAnimMoveTime( 300 )
	Text:SetAnimMoveSpeed( 50 )
	Text:SetEndDelay( 1500 )
	Text:SetCrossfadeTime( 750 )
	Text:SetFadeInTime( 300 )
	Text:SetFadeOutTime( 300 )
	Text:SetMaxVisibleLines( 1 )
	Text:SetShadowRGBFromTable( SWATCHES.genericButton.textGlow, 0 )
	Text:SetOutlineRGBFromInt( 0, 0 )
	Text:SetAnchorsAndPosition( 0, 0, 0.5, 0.5, _1080p * 20, _1080p * -20, _1080p * -15, _1080p * 15 )
	self:addElement( Text )
	self.Text = Text
	
	local Lock = nil
	
	Lock = LUI.UIImage.new()
	Lock.id = "Lock"
	Lock:SetRGBFromTable( SWATCHES.Global.lockColor, 0 )
	Lock:SetAlpha( 0, 0 )
	Lock:setImage( RegisterMaterial( "icon_lock" ), 0 )
	Lock:SetAnchorsAndPosition( 1, 0, 0.5, 0.5, _1080p * -36, _1080p * -10, _1080p * -13, _1080p * 13 )
	self:addElement( Lock )
	self.Lock = Lock
	
	self._sequences.DefaultSequence = function ()
		
	end
	
	local f1_local6 = nil
	Text:RegisterAnimationSequence( "AR", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Top,
			value = _1080p * -16
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Bottom,
			value = _1080p * 16
		}
	} )
	Lock:RegisterAnimationSequence( "AR", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Left_Anchor
		},
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Right_Anchor
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * 10
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 36
		}
	} )
	self._sequences.AR = function ()
		menu:AnimateSequence( "AR" )
		menu:AnimateSequence( "AR" )
	end
	
	local f1_local7 = nil
	Background:RegisterAnimationSequence( "ButtonOver", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.WZCH3.WZCH3CortezGreen
		},
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Text:RegisterAnimationSequence( "ButtonOver", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.CH2.Ch2DarkGrey
		},
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Lock:RegisterAnimationSequence( "ButtonOver", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.ButtonOver = function ()
		menu:AnimateSequence( "ButtonOver" )
		menu:AnimateSequence( "ButtonOver" )
		menu:AnimateSequence( "ButtonOver" )
	end
	
	local f1_local8 = nil
	Background:RegisterAnimationSequence( "ButtonUp", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.CH2.NeutralGray
		},
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Text:RegisterAnimationSequence( "ButtonUp", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.CH2.White
		},
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Lock:RegisterAnimationSequence( "ButtonUp", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.ButtonUp = function ()
		menu:AnimateSequence( "ButtonUp" )
		menu:AnimateSequence( "ButtonUp" )
		menu:AnimateSequence( "ButtonUp" )
	end
	
	local f1_local9 = nil
	Background:RegisterAnimationSequence( "ButtonOverDisabled", {
		{
			value = 8.02989250855909E+283,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.WZCH3.WZCH3CortezGreen
		}
	} )
	Text:RegisterAnimationSequence( "ButtonOverDisabled", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.CH2.Ch2DarkGrey
		},
		{
			value = 5.29462817E-315,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Lock:RegisterAnimationSequence( "ButtonOverDisabled", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.ButtonOverDisabled = function ()
		menu:AnimateSequence( "ButtonOverDisabled" )
		menu:AnimateSequence( "ButtonOverDisabled" )
		menu:AnimateSequence( "ButtonOverDisabled" )
	end
	
	local f1_local10 = nil
	Background:RegisterAnimationSequence( "ButtonUpDisabled", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.CH2.NeutralGray
		}
	} )
	Text:RegisterAnimationSequence( "ButtonUpDisabled", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.CH2.White
		},
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Lock:RegisterAnimationSequence( "ButtonUpDisabled", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.ButtonUpDisabled = function ()
		menu:AnimateSequence( "ButtonUpDisabled" )
		menu:AnimateSequence( "ButtonUpDisabled" )
		menu:AnimateSequence( "ButtonUpDisabled" )
	end
	
	local f1_local11 = nil
	Background:RegisterAnimationSequence( "ButtonUpSnap", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.WZCH3.WZCH3CortezGreen
		},
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Text:RegisterAnimationSequence( "ButtonUpSnap", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.CH2.Ch2DarkGrey
		}
	} )
	Lock:RegisterAnimationSequence( "ButtonUpSnap", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.ButtonUpSnap = function ()
		menu:AnimateSequence( "ButtonUpSnap" )
		menu:AnimateSequence( "ButtonUpSnap" )
		menu:AnimateSequence( "ButtonUpSnap" )
	end
	
	local f1_local12 = nil
	Background:RegisterAnimationSequence( "ButtonUpDisabledSnap", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.CH2.NeutralGray
		}
	} )
	Text:RegisterAnimationSequence( "ButtonUpDisabledSnap", {
		{
			value = 5.29462817E-315,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.CH2.White
		}
	} )
	Lock:RegisterAnimationSequence( "ButtonUpDisabledSnap", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.ButtonUpDisabledSnap = function ()
		menu:AnimateSequence( "ButtonUpDisabledSnap" )
		menu:AnimateSequence( "ButtonUpDisabledSnap" )
		menu:AnimateSequence( "ButtonUpDisabledSnap" )
	end
	
	local f1_local13 = nil
	Text:RegisterAnimationSequence( "Enabled", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Lock:RegisterAnimationSequence( "Enabled", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.Enabled = function ()
		menu:AnimateSequence( "Enabled" )
		menu:AnimateSequence( "Enabled" )
	end
	
	local f1_local14 = nil
	Text:RegisterAnimationSequence( "Disabled", {
		{
			value = 4.667261642226141E-62,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Lock:RegisterAnimationSequence( "Disabled", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.Disabled = function ()
		menu:AnimateSequence( "Disabled" )
		menu:AnimateSequence( "Disabled" )
	end
	
	PostLoadFunc( self, f1_local1, controller )
	return self
end

MenuBuilder.registerType( "MaintenanceButton", MaintenanceButton )
LockTable( _M )
