-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 04-10-2025 21:42
module( ..., package.seeall )
FencePremiumInterface = LUI.Class( LUI.Fence )
FencePremiumInterface.init = function ( f11_arg0 )
	FencePremiumInterface.super.init( f11_arg0 )
end

FencePremiumInterface.UpdateState = function ( f10_arg0 )
	f10_arg0._state = LUI.Fence.STATE.fail
	for f10_local0 = 0, Engine[0xB686A0A723E6442]() - 1, 1 do
		if not Engine[0xEB0606D5D898BA6]( f10_local0 ) then
			f10_arg0._state = LUI.Fence.STATE.block
		end
		if f10_arg0:PassCondition( f10_local0 ) then
			f10_arg0._state = LUI.Fence.STATE.pass
			break
		end
	end
end

FencePremium = LUI.Class( FencePremiumInterface )
FencePremium.PassCondition = function ( f9_arg0, f9_arg1 )
	return Engine[0x8B495DC361731F7]( f9_arg1 )
end

FencePremium.PostFail = function ( f8_arg0 )
	if f8_arg0._state == LUI.Fence.STATE.fail then
		local f8_local0 = Engine[0x45B054C920178E9]()
		Engine[0xB81A5136C5503E4]( "xstopprivateparty", f8_local0 )
		Engine[0xB81A5136C5503E4]( "xstartprivateparty" )
		LUI.FlowManager.RequestPopupMenu( nil, "BlockedPremiumMenuPopup", true, f8_local0, false, {}, nil, true, true )
	end
end

LUI.Fence.Register( "premium", FencePremium )
FencePremiumOrLaunchChunk = LUI.Class( FencePremiumInterface )
FencePremiumOrLaunchChunk.PassCondition = function ( f7_arg0, f7_arg1 )
	local f7_local0 = Engine[0x8B495DC361731F7]( f7_arg1 )
	if not f7_local0 then
		f7_local0 = CONDITIONS.IsLaunchChunk()
	end
	return f7_local0
end

FencePremiumOrLaunchChunk.PostFail = function ( f6_arg0 )
	if f6_arg0._state == LUI.Fence.STATE.fail then
		Engine[0xB81A5136C5503E4]( "xstopprivateparty", Engine[0x45B054C920178E9]() )
		Engine[0xB81A5136C5503E4]( "xstartprivateparty" )
	end
end

LUI.Fence.Register( "premiumOrLaunchChunk", FencePremiumOrLaunchChunk )
FencePremiumOrTrialActive = LUI.Class( FencePremiumInterface )
FencePremiumOrTrialActive.PassCondition = function ( f5_arg0, f5_arg1 )
	local f5_local0 = Engine[0x8B495DC361731F7]( f5_arg1 )
	if not f5_local0 then
		f5_local0 = CONDITIONS.IsWithinFreeTrialPeriod()
	end
	return f5_local0
end

FencePremiumOrTrialActive.PostFail = function ( f4_arg0 )
	if f4_arg0._state == LUI.Fence.STATE.fail then
		local f4_local0 = Engine[0x45B054C920178E9]()
		Engine[0xB81A5136C5503E4]( "xstopprivateparty", f4_local0 )
		Engine[0xB81A5136C5503E4]( "xstartprivateparty" )
		LUI.FlowManager.RequestPopupMenu( nil, "BlockedPremiumMenuPopup", true, f4_local0, false, {}, nil, true, true )
	end
end

LUI.Fence.Register( "premiumOrTrialActive", FencePremiumOrTrialActive )
function BlockedPremiumMenuPopup( f1_arg0, f1_arg1 )
	local f1_local0 = {
		headerText = Engine[0xED84C33EC5F01EA]( "LUA_MENU/NOT_AVAILABLE" ),
		messageText = Engine[0xED84C33EC5F01EA]( "STORE/UPSELL_MENU_BLOCKED" ),
		buttons = {}
	}
	if CONDITIONS.ShouldDisplayUpsellPopup( f1_arg1.controllerIndex ) then
		table.insert( f1_local0.buttons, {
			label = Engine[0xED84C33EC5F01EA]( "LUA_MENU/PURCHASE_MW" ),
			action = function ( f3_arg0 )
				LUI.FlowManager.RequestPopupMenu( nil, "StoreGameUpsellPopup", true, f1_arg0.controllerIndex, true, nil )
			end
		} )
	end
	table.insert( f1_local0.buttons, {
		label = Engine[0xED84C33EC5F01EA]( "MENU/BACK" ),
		action = function ( f2_arg0 )
			LUI.FlowManager.RequestLeaveMenu( f2_arg0 )
		end
	} )
	f1_local0.controllerIndex = f1_arg1.controllerIndex
	local f1_local1 = MenuBuilder.BuildRegisteredType( "MessagePopup", f1_local0 )
	f1_local1.id = "BlockedPremiumMenuPopup"
	return f1_local1
end

MenuBuilder.registerType( "BlockedPremiumMenuPopup", BlockedPremiumMenuPopup )
LockTable( _M )
