-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 21-11-2025 08:49
GLOBAL_PANEL = GLOBAL_PANEL or {}
GLOBAL_PANEL.TAB_INDEX = {
	OPTIONS = 4,
	PLAYER = 5,
	NOTIFICATIONS = 3,
	CHANNELS = 2,
	NAVIGATION = 1
}
GLOBAL_PANEL_SOUNDS = {
	PANEL_OPEN = CoD.SFX.GlobalPanelOpen,
	PANEL_CLOSE = CoD.SFX.GlobalPanelClose,
	TAB_HIGHLIGHT = CoD.SFX.MouseOver,
	TAB_SELECT = CoD.SFX.GlobalPanelTabSelect
}
GLOBAL_PANEL.LOBBY_TO_HOME_MENU_MAP = {
	[PartyUIRoot.MP_PRIVATE_MATCH] = PartyUIRoot.MP_MAIN_MENU,
	[PartyUIRoot.MP_PUBLIC_MATCH_LOBBY] = PartyUIRoot.MP_MAIN_MENU,
	[PartyUIRoot.LP_PUBLIC_MATCH_LOBBY] = PartyUIRoot.MP_MAIN_MENU,
	[PartyUIRoot.LP_BR_PUBLIC_MATCH_LOBBY] = PartyUIRoot.BR_MAIN_MENU,
	[PartyUIRoot.PRE_LOBBY_MENU] = PartyUIRoot.MP_MAIN_MENU,
	[PartyUIRoot.CP_PUBLIC_MATCH_LOBBY] = PartyUIRoot.CP_MAIN_MENU,
	[PartyUIRoot.BR_PRE_LOBBY_MENU] = PartyUIRoot.BR_MAIN_MENU,
	[PartyUIRoot.CP_SYSTEM_LINK_LOBBY] = PartyUIRoot.CP_SYSTEM_LINK,
	[PartyUIRoot.DMZ_MAIN_MENU] = PartyUIRoot.MAIN_MENU,
	[PartyUIRoot.LP_MAIN_MENU] = PartyUIRoot.MAIN_MENU,
	[PartyUIRoot.WZ_PRIVATE_MATCH_LOBBY] = PartyUIRoot.BR_MAIN_MENU
}
GLOBAL_PANEL.MAIN_MENU_LIST = {
	PartyUIRoot.MP_MAIN_MENU,
	PartyUIRoot.BR_MAIN_MENU,
	PartyUIRoot.CP_MAIN_MENU,
	PartyUIRoot.MAIN_MENU
}
local f0_local0 = function ( f84_arg0, f84_arg1 )
	if 0 < Lobby[0x5C3F0A14700EFD9]() then
		Lobby[0x94C721C0A23A515]( 0 )
	end
	if Lobby[0x18BBD42C62BEAF8]( f84_arg1 ) then
		Lobby[0x502F273847E8B58]( f84_arg1 )
	end
	Lobby.LeaveCustomGameLobby()
	if Lobby[0x867E2628CAA1981]() and Lobby[0xE9670E0E1EF3730]() then
		Lobby[0x2E0D4E2CD0FA6DE]()
	end
end

local f0_local1 = function ( f83_arg0, f83_arg1 )
	if Lobby[0x6957722EF74F5D2]() then
		Lobby.LeavePublicLobby()
	end
end

local f0_local2 = function ( f82_arg0, f82_arg1 )
	if 0 < Lobby[0x5C3F0A14700EFD9]() then
		Lobby[0x94C721C0A23A515]( 0 )
	end
	f0_local0( f82_arg0, f82_arg1 )
end

local f0_local3 = function ( f81_arg0, f81_arg1 )
	Lobby.LeaveCustomGameLobby( true )
end

GLOBAL_PANEL.HandleMenuChange = function ( f80_arg0, f80_arg1, f80_arg2 )
	if CONDITIONS.IsMenuInStack( OPTIONS.MENU_NAME ) then
		local f80_local0 = LUI.FlowManager.GetMenuByName( "OptionsMenuLayout" )
		if f80_local0.menu and 0 < #f80_local0.menu.modifiedOptions then
			f80_local0.menu:HandleApplyableTabLeave( f80_arg0, f80_arg1, f80_arg2 )
			return 
		end
	end
	f80_arg1( f80_arg0, f80_arg2 )
end

local f0_local4 = {
	[PartyUIRoot.MP_PRIVATE_MATCH] = f0_local0,
	[PartyUIRoot.MP_PUBLIC_MATCH_LOBBY] = f0_local1,
	[PartyUIRoot.LP_PUBLIC_MATCH_LOBBY] = f0_local1,
	[PartyUIRoot.LP_BR_PUBLIC_MATCH_LOBBY] = f0_local1,
	[PartyUIRoot.PRE_LOBBY_MENU] = nil,
	[PartyUIRoot.CP_PUBLIC_MATCH_LOBBY] = f0_local2,
	[PartyUIRoot.BR_PRE_LOBBY_MENU] = f0_local1,
	[PartyUIRoot.CP_SYSTEM_LINK_LOBBY] = nil,
	[PartyUIRoot.WZ_PRIVATE_MATCH_LOBBY] = f0_local3
}
GLOBAL_PANEL.MENU_NAME = "GlobalPanelBase"
GLOBAL_PANEL.INTRO_ANIMATION = "Intro"
GLOBAL_PANEL.OUTRO_ANIMATION = "Outro"
GLOBAL_PANEL.TAB_OFFLINE_WIDGET = "GlobalPanelOffline"
GLOBAL_PANEL.CHANNELS_MAX_VISIBLE_COUNT = 10
GLOBAL_PANEL.CHANNELS_MAX_VISIBLE_COUNT_SPLITSCREEN = 4
GLOBAL_PANEL.NOTIFICATION_MAX_VISIBLE_COUNT_SPLITSCREEN = 4
GLOBAL_PANEL.TELESCOPE_STATS_RANK_REQUIREMENT = 10
GLOBAL_PANEL.GetGlobalPanelTabs = function ( f74_arg0 )
	local f74_local0 = GLOBAL_PANEL.TAB_INDEX
	local f74_local1 = {}
	local f74_local2 = f74_local0.NAVIGATION
	local f74_local3 = {
		name = 0x5968D802208F8B5,
		tooltipTitle = 0x85A234D661D8264,
		disabled = false,
		icon = "icon_global_navigation",
		menuName = "GlobalPanelNavigation"
	}
	if CONDITIONS.IsSingleplayer() then
		local f74_local4 = CONDITIONS.InFrontend()
		local f74_local5 = CONDITIONS.IsConsoleGame()
	end
	f74_local3.hidden = f74_local4 and f74_local5 or CONDITIONS.IsInOfflineMenus()
	f74_local3.contextualMenu = function ( f79_arg0, f79_arg1 )
		return GLOBAL_PANEL.SetPanelPromptContextualMenu( f79_arg0, f79_arg1 )
	end
	
	f74_local1[f74_local2] = f74_local3
	f74_local2 = f74_local0.CHANNELS
	f74_local3 = {
		name = 0xB1465762CECDDAB,
		menuName = "GlobalPanelChannels",
		icon = "icon_global_channels",
		onlineRequired = true,
		contextualMenuRefresh = true,
		disabled = not CONDITIONS.IsChannelsEnabled( f74_arg0 )
	}
	local f74_local6
	if CONDITIONS.IsChannelsEnabled( f74_arg0 ) then
		f74_local6 = CONDITIONS.IsSPEarlyAccessBuildEnabled()
	else
		f74_local6 = true
	end
	f74_local3.hidden = f74_local6
	f74_local3.contextualMenu = function ( f78_arg0, f78_arg1 )
		return GLOBAL_PANEL.SetChannelsContextualMenu( f78_arg0, f78_arg1, true )
	end
	
	f74_local1[f74_local2] = f74_local3
	f74_local2 = f74_local0.NOTIFICATIONS
	f74_local3 = {
		name = 0x4A412CD54B5790D,
		menuName = "GlobalPanelNotifications",
		icon = "icon_global_notifications",
		onlineRequired = true,
		disabled = not NOTIFICATIONS.IsMenuEnabled( f74_arg0 )
	}
	if NOTIFICATIONS.IsMenuEnabled( f74_arg0 ) then
		f74_local6 = CONDITIONS.IsSPEarlyAccessBuildEnabled()
	else
		f74_local6 = true
	end
	f74_local3.hidden = f74_local6
	f74_local3.breadcrumbDataSource = DataSources.alwaysLoaded.notifications.unreadCount
	f74_local3.contextualMenu = function ( f77_arg0, f77_arg1 )
		return GLOBAL_PANEL.SetNotificationsContextualMenu( f77_arg0, f77_arg1 )
	end
	
	f74_local1[f74_local2] = f74_local3
	f74_local1[f74_local0.OPTIONS] = {
		name = 0xDE7B3C94B0B0F67,
		menuName = "GlobalPanelOptions",
		disabled = false,
		hidden = false,
		icon = "icon_global_options",
		contextualMenu = function ( f76_arg0, f76_arg1 )
			return GLOBAL_PANEL.SetOptionsContextualMenu( f76_arg0, f76_arg1 )
		end
	}
	f74_local2 = f74_local0.PLAYER
	f74_local3 = {
		menuName = "GlobalPanelPlayer",
		disabled = false,
		widget = "PlayerRadialProgression",
		tooltipTitle = 0x68482A15C97DEFB,
		onlineRequired = true,
		name = 0xF903D47BC8F2015
	}
	if SOCIAL.IsPlayerProfileEnabled( f74_arg0 ) then
		f74_local6 = CONDITIONS.IsSPEarlyAccessBuildEnabled()
	else
		f74_local6 = true
	end
	f74_local3.hidden = f74_local6
	f74_local3.contextualMenu = function ( f75_arg0, f75_arg1 )
		if CONDITIONS.InFrontend() then
			return GLOBAL_PANEL.SetPlayerContextualMenu( f75_arg0, f75_arg1 )
		else
			
		end
	end
	
	f74_local1[f74_local2] = f74_local3
	return f74_local1
end

GLOBAL_PANEL.GetActiveTabId = function ()
	local f73_local0 = LUI.FlowManager.IsMenuOnTop( GLOBAL_PANEL.MENU_NAME )
	local f73_local1 = LUI.FlowManager.GetMenuByName( GLOBAL_PANEL.MENU_NAME )
	f73_local1 = f73_local0 and f73_local1.menu or false
	local f73_local2
	if f73_local1 then
		f73_local2 = f73_local1.GlobalPanel:GetCurrentTabIndex()
		if not f73_local2 then
		
		else
			return f73_local2
		end
	end
	f73_local2 = false
end

GLOBAL_PANEL.IsGlobalPanelChannelTabOpen = function ()
	return GLOBAL_PANEL.GetActiveTabId() == GLOBAL_PANEL.TAB_INDEX.CHANNELS
end

local f0_local5 = function ( f70_arg0, f70_arg1, f70_arg2 )
	local f70_local0 = nil
	if Lobby.IsOurPrivatePartyHostInLobby() then
		f70_local0 = Engine[0xED84C33EC5F01EA]( 0x3770EE4D0EBEC14 )
	elseif CONDITIONS.UseCortezEjectedMenus() then
		f70_local0 = Engine[0xED84C33EC5F01EA]( 0xB4F5B62D33F2C7C )
	else
		f70_local0 = Engine[0xED84C33EC5F01EA]( 0x3704312575A17C7 )
	end
	local f70_local1 = f0_local0[f70_arg0]
	return {
		yesAction = function ( f71_arg0, f71_arg1 )
			if f70_arg0 then
				f70_arg0( f71_arg0, f71_arg1 )
			end
			GLOBAL_PANEL.CloseGlobalPanel()
			if CONDITIONS.UseCortezEjectedMenus() then
				CROSS_LAUNCH.OpenCODHQ( f71_arg1, true )
			elseif (f70_arg0 == PartyUIRoot.CP_PUBLIC_MATCH_LOBBY or f70_arg0 == PartyUIRoot.CP_PRIVATE_MATCH) and GL_HACK.ShouldAutoNavigateToMPMainMenuFromCPPublicMatchMenu() then
				LUI.FlowManager.RequestAutomaticNavigation( PartyUIRoot.MP_MAIN_MENU )
			else
				LUI.FlowManager.RequestAutomaticNavigation( f70_arg0 )
			end
		end
		,
		message = f70_local0,
		actionSFX = SOUND_SETS.popups.privateSelect,
		popupSFX = SOUND_SETS.popups.privatePopup
	}
end

GLOBAL_PANEL.GetNavigationButtons = function ( f47_arg0, f47_arg1 )
	local f47_local0 = {}
	local f47_local1 = {
		name = 0x69C38CB94FFBBC,
		id = "home",
		icon = "icon_global_home",
		buttonAction = function ( f67_arg0, f67_arg1 )
			if CONDITIONS.IsSingleplayer() then
				if CONDITIONS.UseCortezEjectedMenus() then
					LUI.FlowManager.RequestPopupMenu( f67_arg0, "PopupYesNo", true, f47_arg0, false, f47_arg0( nil, nil, f67_arg1.controller ) )
				else
					SPSharedUtils.OpenSPExitPopup( f47_arg0 )
				end
			else
				if not Lobby.CanLeaveLobby() then
					
				else
					
				end
				for f67_local3, f67_local4 in pairs( GLOBAL_PANEL.LOBBY_TO_HOME_MENU_MAP ) do
					if LUI.FlowManager.IsInStack( LUI.FlowManager.FlowMenus[f67_local3] ) then
						LUI.FlowManager.RequestPopupMenu( f67_arg0, "PopupYesNo", true, f47_arg0, false, f47_arg0( f67_local3, f67_local4, f47_arg0 ) )
					end
				end
				if CONDITIONS.UseCortezEjectedMenus() then
					LUI.FlowManager.RequestPopupMenu( f67_arg0, "PopupYesNo", true, f47_arg0, false, f47_arg0( nil, nil, f67_arg1.controller ) )
				end
				for f67_local3, f67_local4 in pairs( GLOBAL_PANEL.MAIN_MENU_LIST ) do
					local f67_local6 = LUI.FlowManager.FlowMenus[f67_local4]
					if LUI.FlowManager.IsInStack( f67_local6 ) then
						if LUI.FlowManager.IsInStack( "FiringRangeMenu" ) then
							local f67_local5 = LUI.FlowManager.GetMainScopedData()
							f67_local5.backingToMainMenu = true
						end
						GLOBAL_PANEL.HandleMenuChange( f47_arg0, function ( f69_arg0, f69_arg1 )
							LUI.FlowManager.PopMenuStackUpToMenu( f69_arg1.mainMenuName )
							local f69_local0 = LUI.FlowManager.GetTopmostMenu()
							if f69_local0.menu and f69_local0.menu.MainMenuTabs then
								f69_local0.menu.MainMenuTabs.Tabs:FocusTab( f69_arg0, 0 )
							end
						end, {
							mainMenuName = f67_local6
						} )
						return 
					end
				end
				if not f47_arg0 then
					GLOBAL_PANEL.CloseGlobalPanel()
				end
				if LUI.FlowManager.IsInStack( LUI.FlowManager.FlowMenus[PartyUIRoot.MAIN_MENU] ) then
					if CONDITIONS.IsMagmaGameMode() and CONDITIONS.IsPrivateMatchCondition() then
						LUI.FlowManager.RequestPopupMenu( f67_arg0, "PopupYesNo", true, f67_arg1.controller, false, {
							yesAction = function ()
								Lobby.LeaveCustomGameLobby()
								LUI.FlowManager.RequestAutomaticNavigation( PartyUIRoot.MAIN_MENU )
							end,
							message = Engine[0xED84C33EC5F01EA]( Lobby.IsOurPrivatePartyHostInLobby() and 0x3770EE4D0EBEC14 or 0x3704312575A17C7 ),
							actionSFX = SOUND_SETS.popups.privateSelect,
							popupSFX = SOUND_SETS.popups.privatePopup
						} )
					end
				end
				LUI.FlowManager.RequestAutomaticNavigation( PartyUIRoot.MAIN_MENU )
			end
		end,
		disabled = not Lobby.CanLeaveLobby(),
		lobbySubscriptionFunc = function ( f66_arg0, f66_arg1 )
			if not Lobby.CanLeaveLobby() then
				f66_arg0:SetButtonDisabled( true )
			else
				f66_arg0:SetButtonDisabled( false )
			end
			return false
		end
	}
	local f47_local2 = Engine[0x344BE1C778BAA54]()
	if not f47_local2 then
		f47_local2 = Dvar[0x9E5BE3B4BBA4E0E]( 0x4E962395D7F6DB3 )
	end
	f47_local1.hidden = f47_local2
	f47_local0[1] = f47_local1
	f47_local0[2] = {
		name = 0x722AAF0023EBAFC,
		id = "challenges",
		icon = "icon_global_challenges",
		buttonAction = function ()
			GLOBAL_PANEL.HandleMenuChange( f47_arg0, function ( f65_arg0 )
				if CONDITIONS.IsSeasonChallengeEnabled() then
					LUI.FlowManager.RequestAddMenu( "ChallengesMenu", true, f65_arg0, false, nil )
				end
			end )
		end,
		disabled = not CONDITIONS.IsSeasonChallengeEnabled(),
		hidden = not CONDITIONS.IsSeasonChallengeEnabled()
	}
	f47_local1 = {
		disabled = false,
		name = 0x5C2E89BEAEC8F2A,
		id = "social",
		icon = "icon_global_social",
		buttonAction = function ()
			GLOBAL_PANEL.HandleMenuChange( f47_arg0, function ( f63_arg0 )
				if CONDITIONS.IsMenuInStack( SOCIAL.MENU_NAME ) then
					local f63_local0 = LUI.FlowManager.GetMenuByName( SOCIAL.MENU_NAME )
					ACTIONS.PopMenuStackUpToMenu( SOCIAL.MENU_NAME, false )
					f63_local0.menu:SetDefaultTabActive()
				else
					FRIENDS.HandleSocial( f63_arg0 )
				end
			end )
		end
	}
	if CONDITIONS.IsSocialShortcutAllowed() and CONDITIONS.IsSocialMenuEnabled( f47_arg0 ) then
		f47_local2 = CONDITIONS.IsSPEarlyAccessBuildEnabled()
	else
		f47_local2 = true
	end
	f47_local1.hidden = f47_local2
	f47_local0[3] = f47_local1
	f47_local1 = {
		disabled = false,
		name = 0x7AAFEA7122E0D5A,
		id = "barracks",
		icon = "icon_global_barracks",
		buttonAction = function ()
			GLOBAL_PANEL.HandleMenuChange( f47_arg0, function ( f61_arg0 )
				LUI.FlowManager.RequestAddMenu( "ProgressionUnlockMenu", true, f61_arg0, false, nil )
			end )
		end
	}
	if PROGRESSION.IsProgressionMenuEnabled() then
		f47_local2 = CONDITIONS.IsSPEarlyAccessBuildEnabled()
	else
		f47_local2 = true
	end
	f47_local1.hidden = f47_local2
	f47_local0[4] = f47_local1
	f47_local1 = {
		name = 0xE35946AD981641C,
		id = "achievements",
		icon = "icon_global_achievements",
		buttonAction = function ()
			GLOBAL_PANEL.HandleMenuChange( f47_arg0, function ( f59_arg0 )
				if CONDITIONS.InFrontend() and CONDITIONS.IsPC() then
					LUI.FlowManager.RequestAddMenu( "PCAchievementsMenu", true, f59_arg0, false, nil )
				end
			end )
		end
	}
	if CONDITIONS.InFrontend() then
		f47_local2 = not CONDITIONS.IsPC()
	else
		f47_local2 = true
	end
	f47_local1.disabled = f47_local2
	if CONDITIONS.InFrontend() then
		f47_local2 = not CONDITIONS.IsPC()
	else
		f47_local2 = true
	end
	f47_local1.hidden = f47_local2
	f47_local0[5] = f47_local1
	f47_local0[6] = {
		disabled = false,
		name = 0xDE7B3C94B0B0F67,
		hidden = true,
		id = "options",
		icon = "icon_global_options",
		buttonAction = function ()
			if CONDITIONS.IsMenuInStack( OPTIONS.MENU_NAME ) then
				ACTIONS.PopMenuStackUpToMenu( OPTIONS.MENU_NAME, false )
			else
				ACTIONS.OpenOptionsMenu( f47_arg0, nil, true )
			end
		end
	}
	f47_local1 = {
		name = 0xFBB03F2C6F6A42E,
		id = "stats",
		icon = "icon_global_stats",
		buttonAction = function ()
			GLOBAL_PANEL.HandleMenuChange( f47_arg0, function ( f56_arg0 )
				local f56_local0 = LUI.WebViewManager.Instance()
				f56_local0:OpenStats()
			end )
		end,
		disabled = not LUI.WebViewManager.StatsOpenEnabled()
	}
	if LUI.WebViewManager.StatsEnabled() then
		f47_local2 = CONDITIONS.IsSPEarlyAccessBuildEnabled()
	else
		f47_local2 = true
	end
	f47_local1.hidden = f47_local2
	f47_local0[7] = f47_local1
	f47_local1 = {
		disabled = false,
		name = 0xDF24FDAC82B9AC,
		id = "cdl",
		icon = "icon_global_cdl",
		buttonAction = function ()
			GLOBAL_PANEL.HandleMenuChange( f47_arg0, function ( f54_arg0 )
				local f54_local0 = LUI.WebViewManager.Instance()
				f54_local0:OpenCdl()
			end )
		end
	}
	if LUI.WebViewManager.CdlGlobalPanelEnabled() then
		f47_local2 = CONDITIONS.UseCortezEjectedMenus()
	else
		f47_local2 = true
	end
	f47_local1.hidden = f47_local2
	f47_local0[8] = f47_local1
	f47_local0[9] = {
		disabled = false,
		name = 0x2B9FA0A3DFFE6C3,
		id = "login_reward",
		icon = "icon_global_login_rewards",
		buttonAction = function ()
			GLOBAL_PANEL.HandleMenuChange( f47_arg0, function ( f52_arg0 )
				local f52_local0 = LUI.WebViewManager.Instance()
				f52_local0:SetForceOpen()
				LUI.FlowManager.RequestPopupMenu( nil, "LoginReward", true, Engine[0x45B054C920178E9](), false, {
					reaccess = true
				}, nil, false, true )
				LUI.LoginRewardDlog.RecordEvent_OpenFromGlobalNav()
			end )
		end,
		hidden = not LUI.WebViewManager.LoginRewardEntryEnabled()
	}
	if not Dvar[0x9E5BE3B4BBA4E0E]( 0xE1B05C953001A32 ) and (not CONDITIONS.UseCortezEjectedMenus() or CONDITIONS.IsUbiconnect()) then
		table.remove( f47_local0, 1 )
	end
	if CONDITIONS.InFrontend() and CONDITIONS.IsUserSignedInDemonware( f47_arg0 ) then
		f47_local1 = MenuUtils.GetPreviousMenu()
		if f47_local1 then
			f47_local1 = MenuUtils.GetPreviousMenu()
			f47_local1 = f47_local1.id == "MainMenu"
		end
		f47_local2 = {
			name = 0x9314BF295F932EC,
			id = "store",
			icon = "icon_global_store",
			buttonAction = function ()
				GLOBAL_PANEL.HandleMenuChange( f47_arg0, function ( f50_arg0 )
					STORE.UI.OpenStore( f50_arg0 )
				end )
			end,
			disabled = function ()
				local f48_local0 = IsPublicMatch()
				if f48_local0 then
					f48_local0 = CONDITIONS.IsDMZMatch()
					if f48_local0 then
						f48_local0 = Lobby[0x61016770AE2BCA7]()
					end
				end
				return f48_local0
			end
		}
		local f47_local3
		if Dvar[0x9E5BE3B4BBA4E0E]( 0xF366E1D958B2193 ) and STORE.UI.GetStoreMenuIndexAndTabMenu( f47_arg0 ) then
			if f47_local1 then
				f47_local3 = f47_local1
			else
				f47_local3 = not CONDITIONS.UseCortezEjectedMenus()
			end
		else
			f47_local3 = true
		end
		f47_local2.hidden = f47_local3
		table.insert( f47_local0, 2, f47_local2 )
	end
	f47_local1 = {}
	f47_local2 = 0
	for f47_local3 = 1, #f47_local0, 1 do
		if not f47_local0[f47_local3].hidden then
			f47_local2 = f47_local2 + 1
			if 9 < f47_local2 then
				f47_local2 = 7
			end
			if not f47_local0[f47_local3].background or f47_local0[f47_local3].background == "" then
				f47_local0[f47_local3].background = "global_gridbuttonbg_" .. f47_local2
			end
			table.insert( f47_local1, f47_local0[f47_local3] )
		end
	end
	return f47_local1
end

GLOBAL_PANEL.OpenGlobalPanel = function ( f46_arg0, f46_arg1, f46_arg2, f46_arg3, f46_arg4 )
	if not f46_arg3 then
		f46_arg3 = {}
	end
	if not Dvar[0x9E5BE3B4BBA4E0E]( 0x688342254973B95 ) then
		ACTIONS.OpenOptionsMenu( f46_arg1 )
		return 
	elseif LUI.FlowManager.IsInStack( GLOBAL_PANEL.MENU_NAME ) then
		LUI.FlowManager.RequestLeaveMenuByName( GLOBAL_PANEL.MENU_NAME, true )
	end
	LUI.FlowManager.RequestPopupMenu( f46_arg0, GLOBAL_PANEL.MENU_NAME, true, f46_arg1, false, f46_arg4 )
	local f46_local0 = LUI.FlowManager.GetMenuByName( GLOBAL_PANEL.MENU_NAME )
	f46_local0 = f46_local0.menu
	assert( f46_local0 )
	if f46_local0 then
		assert( f46_local0.GlobalPanel )
		LUI.ToastManager.DismissToastsOnScreen()
		if f46_arg2 and 1 < f46_arg2 and f46_arg2 ~= f46_local0.GlobalPanel:GetCurrentTabIndex() then
			f46_local0.GlobalPanel:ChangeTab( f46_arg2 )
		end
		if f46_arg3.hidden then
			f46_local0.GlobalPanel:SetVisibility( LUI.Visibility.Hidden )
		else
			if not f46_arg3.immediate then
				ACTIONS.AnimateSequence( f46_local0, GLOBAL_PANEL.INTRO_ANIMATION )
			end
			Engine[0xC4146BA76D0F982]( GLOBAL_PANEL_SOUNDS.PANEL_OPEN )
		end
	end
end

GLOBAL_PANEL.CloseGlobalPanelNow = function ()
	if CONDITIONS.InGame() then
		LUI.FlowManager.RequestCloseAllMenus()
	else
		LUI.FlowManager.RequestLeaveMenuByName( GLOBAL_PANEL.MENU_NAME, true, true )
	end
end

GLOBAL_PANEL.CloseGlobalPanel = function ()
	local f43_local0 = function ()
		GLOBAL_PANEL.CloseGlobalPanelNow()
	end
	
	local f43_local1 = LUI.FlowManager.GetMenuByName( GLOBAL_PANEL.MENU_NAME )
	assert( f43_local1 )
	local f43_local2 = f43_local1.menu
	local f43_local3 = f43_local2:isInFocus()
	if not f43_local3 then
		f43_local3 = 0 < #f43_local2:getAllFocusedChildren()
	end
	if f43_local3 and f43_local2.GlobalPanel.Tabs.saveData then
		local f43_local4 = f43_local2.GlobalPanel.Tabs.saveData.currentTab
		if f43_local4 and f43_local4 ~= 0 then
			ACTIONS.LoseFocus( f43_local2, f43_local2.GlobalPanel.Tabs._tabs[f43_local4], f43_local1.controller )
		end
	end
	if CONDITIONS.InGame() then
		f43_local0()
	elseif f43_local2 ~= nil then
		Engine[0xC4146BA76D0F982]( GLOBAL_PANEL_SOUNDS.PANEL_CLOSE )
		ACTIONS.AnimateSequence( f43_local2, GLOBAL_PANEL.OUTRO_ANIMATION, {
			onComplete = f43_local0
		} )
	else
		f43_local0()
	end
end

GLOBAL_PANEL.HideGlobalPanel = function ()
	local f42_local0 = LUI.FlowManager.GetMenuByName( GLOBAL_PANEL.MENU_NAME )
	local f42_local1
	if f42_local0 then
		f42_local1 = f42_local0
	else
		f42_local1 = f42_local0.menu
	end
	if f42_local1 ~= nil then
		f42_local1.GlobalPanel:SetVisibility( LUI.Visibility.Hidden )
	end
end

GLOBAL_PANEL.FocusTab = function ( f41_arg0, f41_arg1 )
	assert( f41_arg1 )
	local f41_local0 = LUI.FlowManager.GetMenuByName( GLOBAL_PANEL.MENU_NAME )
	f41_local0 = f41_local0.menu
	assert( f41_local0 )
	if f41_local0 ~= nil then
		assert( f41_local0.GlobalPanel )
		if f41_arg1 ~= f41_local0.GlobalPanel:GetCurrentTabIndex() then
			f41_local0.GlobalPanel:ChangeTab( f41_arg1 )
		end
	end
end

GLOBAL_PANEL.IsOpen = function ()
	return LUI.FlowManager.IsInStack( GLOBAL_PANEL.MENU_NAME )
end

GLOBAL_PANEL.IsTabAvailable = function ( f39_arg0, f39_arg1 )
	local f39_local0 = GLOBAL_PANEL.GetGlobalPanelTabs( f39_arg1 )
	return not f39_local0[f39_arg0].disabled
end

GLOBAL_PANEL.SetButtonGridFocus = function ( f38_arg0, f38_arg1 )
	assert( f38_arg1 <= f38_arg0:GetNumChildren(), "Invalid index" )
	f38_arg0:SetFocusedPosition( {
		x = 0,
		y = f38_arg1
	}, true )
end

GLOBAL_PANEL.SetPanelPromptContextualMenu = function ( f34_arg0, f34_arg1 )
	f34_arg0:SetupContextualMenu()
	if CONDITIONS.InFrontend() then
		for f34_local3, f34_local4 in ipairs( GLOBAL_PANEL.GetNavigationButtons( f34_arg1, true ) ) do
			f34_arg0:AddContextualMenuAction( {
				actionName = Engine[0xED84C33EC5F01EA]( f34_local4.name ),
				actionFunction = f34_local4.buttonAction,
				conditionFunction = function ()
					return not (type( f34_arg0.disabled ) and f34_arg0.disabled() or f34_arg0.disabled)
				end,
				id = "nav" .. f34_local4.id
			} )
		end
	end
	f34_arg0:AddContextualMenuAction( {
		id = "exitToDesktop",
		actionName = Engine[0xED84C33EC5F01EA]( 0x4E76830223A336F ),
		actionFunction = function ()
			ACTIONS.OpenPopupMenu( f34_arg0, "quit_popmenu", false, f34_arg0 )
		end,
		conditionFunction = function ()
			return CONDITIONS.IsPC()
		end
	} )
end

GLOBAL_PANEL.SetChannelsContextualMenu = function ( f17_arg0, f17_arg1, f17_arg2 )
	local f17_local0 = function ( f33_arg0, f33_arg1, f33_arg2 )
		if CONDITIONS.IsMenuInStack( OPTIONS.MENU_NAME ) then
			local f33_local0 = LUI.FlowManager.GetMenuByName( OPTIONS.MENU_NAME )
			local f33_local1
			if f33_local0 then
				f33_local1 = f33_local0
			else
				f33_local1 = f33_local0.menu
			end
			if f33_local1 and f33_arg2 then
				local f33_local2 = OPTIONS.Menu.GetOptionWidget( f33_local1, f33_arg2 )
				if f33_local2 then
					f33_local2:processEvent( {
						name = "seek_value",
						controllerIndex = f33_arg1
					} )
				end
			end
		end
	end
	
	local f17_local1 = Social[0xB74F196EE36B11]( f17_arg1 )
	local f17_local2 = function ()
		return CHANNELS.GetChannelName( f17_arg0, Social[0xF12FC4AFD7A2A6D]( f17_arg0 ), true, true )
	end
	
	f17_arg0:SetupContextualMenu( {
		showRankInfo = false,
		title = f17_local2()
	} )
	local f17_local3 = function ()
		return Engine[0xED84C33EC5F01EA]( 0x1CD1E825D753521, Engine[0xED84C33EC5F01EA]( 0x540BC86FF88E278 ), CHANNELS.GetMuteStrategyOptionsString( CHANNELS.GetMuteStrategyToOptions( CHANNELS.GetMuteStrategy() ) ) )
	end
	
	f17_arg0:AddContextualMenuAction( {
		id = "voiceMenu",
		actionName = f17_local3(),
		actionFunction = function ()
			CHANNELS.OpenMuteStrategySelectPopup( f17_arg0, Lobby[0xF1D2956B0C99DF6](), true )
		end,
		conditionFunction = function ()
			return CHANNELS.IsConnectedToGameChannel( f17_arg0 )
		end
	} )
	local f17_local4 = function ()
		local f28_local0
		if OPTIONS.GetPlayerDataValue( f17_arg0, CoD.StatsGroup.NonGame, "disableProximityVoice" ) == 0 then
			f28_local0 = 0xBFCBC07702C9C88
			if not f28_local0 then
			
			else
				return Engine[0xED84C33EC5F01EA]( 0x1CD1E825D753521, Engine[0xED84C33EC5F01EA]( 0x7953F23C924FD6D ), f28_local0 )
			end
		end
		f28_local0 = 0x9A7F5409B4666E3
	end
	
	f17_arg0:AddContextualMenuAction( {
		id = "proximityChatMenu",
		actionName = f17_local4(),
		actionFunction = function ()
			local f27_local0
			if OPTIONS.GetPlayerDataValue( f17_arg0, CoD.StatsGroup.NonGame, "disableProximityVoice" ) == 0 then
				f27_local0 = 0
			else
				f27_local0 = 1
			end
			Social[0x48B9F3A8FB58EE6]( f17_arg0, f27_local0 )
			f17_arg0:processEvent( {
				name = "refresh_contextual_menu"
			} )
			f17_arg0( f17_arg0, f17_arg0, "DisableProximityVoice" )
		end,
		conditionFunction = function ()
			return CHANNELS.IsConnectedToGameChannel( f17_arg0 )
		end
	} )
	f17_arg0:AddContextualMenuAction( {
		id = "selfMute",
		actionName = Engine[0xED84C33EC5F01EA]( 0x5D0BE6F381D1BC1 ),
		actionFunction = function ()
			CHANNELS.ToggleSelfMute( f17_arg0, true )
		end,
		conditionFunction = function ()
			local f24_local0 = Social[0xB74F196EE36B11]( f17_arg0 )
			if f24_local0 then
				f24_local0 = CHANNELS.IsConnectedToAnyChannel( f17_arg0 )
			end
			return f24_local0
		end
	} )
	f17_arg0:AddContextualMenuAction( {
		id = "selfUnMute",
		actionName = Engine[0xED84C33EC5F01EA]( 0x6BD2099AA9CEE20 ),
		actionFunction = function ()
			CHANNELS.ToggleSelfMute( f17_arg0, true )
		end,
		conditionFunction = function ()
			local f22_local0
			if not Social[0xB74F196EE36B11]( f17_arg0 ) then
				f22_local0 = CHANNELS.IsConnectedToAnyChannel( f17_arg0 )
			else
				f22_local0 = false
			end
			return f22_local0
		end
	} )
	f17_arg0:AddContextualMenuAction( {
		id = "disconnectMenu",
		actionName = Engine[0xED84C33EC5F01EA]( 0x29FF64A87EDF295 ),
		actionFunction = function ()
			CHANNELS.ToggleVoicePartyConnection( f17_arg0, Social[0xF12FC4AFD7A2A6D]( f17_arg0 ) )
		end,
		conditionFunction = function ()
			return CHANNELS.IsConnectedToAnyChannel( f17_arg0 )
		end
	} )
	if not f17_arg2 then
		f17_arg0:AddContextualMenuAction( {
			isSeparator = true
		} )
		f17_arg0:AddContextualMenuAction( {
			id = "openChannels",
			actionName = Engine[0xED84C33EC5F01EA]( 0xB808BC29C8E24E8 ),
			actionFunction = function ()
				GLOBAL_PANEL.OpenGlobalPanel( f17_arg0, f17_arg0, GLOBAL_PANEL.TAB_INDEX.CHANNELS )
			end,
			conditionFunction = function ()
				return CHANNELS.IsConnectedToAnyChannel( f17_arg0 )
			end
		} )
	end
end

GLOBAL_PANEL.SetNotificationsContextualMenu = function ( f11_arg0, f11_arg1 )
	f11_arg0:SetupContextualMenu()
	f11_arg0:AddContextualMenuAction( {
		id = "manageToasts",
		actionName = Engine[0xED84C33EC5F01EA]( 0xCED3E75D6C73D ),
		actionFunction = function ()
			GLOBAL_PANEL.HandleMenuChange( f11_arg0, function ( f16_arg0, f16_arg1 )
				LUI.FlowManager.RequestPopupMenu( nil, "SettingsNotificationsPopupLayout", false, f16_arg0, false, f16_arg1.options )
			end, {
				options = {
					menuTitleRef = 0x470B77F98226DCD,
					openGlobalPanel = false
				}
			} )
		end,
		conditionFunction = function ()
			return NOTIFICATIONS.NotificationSettingsReady( f11_arg0 )
		end
	} )
	f11_arg0:AddContextualMenuAction( {
		id = "ClearNewNotifs",
		actionName = Engine[0xED84C33EC5F01EA]( 0x4D3F9E7FFD36CBF ),
		actionFunction = function ()
			Notifications[0xE80204D543B6483]( f11_arg0 )
		end,
		conditionFunction = function ()
			return 0 < (DataSources.alwaysLoaded.notifications.unreadCount:GetValue( f11_arg0 ) or 0)
		end
	} )
end

GLOBAL_PANEL.SetOptionsContextualMenu = function ( f6_arg0, f6_arg1 )
	f6_arg0:SetupContextualMenu()
	local f6_local0, f6_local1 = OPTIONS.GetSettingsTabsData( f6_arg1 )
	local f6_local2 = 1
	for f6_local6, f6_local7 in ipairs( f6_local0 ) do
		f6_local7._indexVal = f6_local2
		f6_arg0:AddContextualMenuAction( {
			actionName = f6_local7.name,
			actionFunction = function ()
				GLOBAL_PANEL.HandleMenuChange( f6_arg0, function ( f10_arg0, f10_arg1 )
					OPTIONS.ButtonAction( f10_arg0, f10_arg1.optionData, f10_arg1.optionData._indexVal )
				end, {
					optionData = f6_arg0
				} )
			end,
			id = "nav" .. f6_local7.id
		} )
		f6_local2 = f6_local2 + 1
	end
	if CONDITIONS.InFrontend() then
		f6_arg0:AddContextualMenuAction( {
			id = "goToAccessibility",
			actionName = Engine[0xED84C33EC5F01EA]( 0x62E417733615681 ),
			actionFunction = function ()
				LUI.FlowManager.RequestAddMenu( "BootAccessibilitySetting", false, f6_arg0, false )
			end,
			conditionFunction = function ()
				return not CONDITIONS.IsSplitScreenMenuInUse()
			end
		} )
	end
end

GLOBAL_PANEL.SetPlayerContextualMenu = function ( f1_arg0, f1_arg1 )
	f1_arg0:SetupContextualMenu()
	f1_arg0:AddContextualMenuAction( {
		id = "editShowcase",
		actionName = Engine[0xED84C33EC5F01EA]( 0xCF9AB4CFB68DDED ),
		actionFunction = function ()
			LUI.FlowManager.RequestAddMenu( "SocialShowcaseEditSelf", true, f1_arg0, false, nil, true )
		end
	} )
	f1_arg0:AddContextualMenuAction( {
		id = "editCallingCard",
		actionName = Engine[0xED84C33EC5F01EA]( 0xED1D1721616CEDF ),
		actionFunction = function ()
			local f4_local0 = LUI.FlowManager.RequestAddMenu
			local f4_local1
			if GL_HACK.CallingCardChallengeMenuEnabled() then
				f4_local1 = "CallingCardSelect"
			else
				f4_local1 = "PlayerCardSelect"
			end
			f4_local0( f4_local1, true, f1_arg0, false, nil, true )
		end
	} )
	f1_arg0:AddContextualMenuAction( {
		id = "editEmblem",
		actionName = Engine[0xED84C33EC5F01EA]( 0x62D093881BC51D6 ),
		actionFunction = function ()
			LUI.FlowManager.RequestAddMenu( "EmblemSelectMenu", true, f1_arg0, false, nil, true )
		end
	} )
	f1_arg0:AddContextualMenuAction( {
		id = "editClanTag",
		actionName = Engine[0xED84C33EC5F01EA]( 0xBF9E4E4477B183F ),
		actionFunction = function ()
			PLAYER_DATA.EditClanTag( f1_arg0, f1_arg0 )
		end
	} )
end

