-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 02-09-2025 10:42
module( ..., package.seeall )
local f0_local0 = function ( f3_arg0, f3_arg1, f3_arg2 )
	assert( f3_arg2.areWeHost )
	assert( f3_arg0.MenuTitle )
	f3_arg0.MenuTitle:SetTitle( Engine.CBBHFCGDIC( "LUA_MENU/PARTY_SETTINGS" ) )
	f3_arg0._currentSetting = Lobby.BCBBBABFFB()
	if f3_arg0._currentSetting == CoD.PartyPrivacySetting.CLOSED then
		f3_arg0.Buttons.ClosedButton:SetValue( true )
		f3_arg0.Buttons.InviteOnlyButton:SetValue( false )
		f3_arg0.Buttons.FriendsOnlyButton:SetValue( false )
		f3_arg0.Buttons.PublicButton:SetValue( false )
	elseif f3_arg0._currentSetting == CoD.PartyPrivacySetting.INVITE_ONLY then
		f3_arg0.Buttons.ClosedButton:SetValue( false )
		f3_arg0.Buttons.InviteOnlyButton:SetValue( true )
		f3_arg0.Buttons.FriendsOnlyButton:SetValue( false )
		f3_arg0.Buttons.PublicButton:SetValue( false )
	elseif f3_arg0._currentSetting == CoD.PartyPrivacySetting.JOINABLE_BY_FRIENDS then
		f3_arg0.Buttons.ClosedButton:SetValue( false )
		f3_arg0.Buttons.InviteOnlyButton:SetValue( false )
		f3_arg0.Buttons.FriendsOnlyButton:SetValue( true )
		f3_arg0.Buttons.PublicButton:SetValue( false )
	else
		f3_arg0.Buttons.ClosedButton:SetValue( false )
		f3_arg0.Buttons.InviteOnlyButton:SetValue( false )
		f3_arg0.Buttons.FriendsOnlyButton:SetValue( false )
		f3_arg0.Buttons.PublicButton:SetValue( true )
	end
	f3_arg0.Buttons.PublicButton:addEventHandler( "button_action", function ( f7_arg0, f7_arg1 )
		if f3_arg0._currentSetting ~= CoD.PartyPrivacySetting.PUBLIC then
			Lobby.DDEDGGBHJ( f7_arg1.controller, CoD.PartyPrivacySetting.PUBLIC )
			ACTIONS.PlaySoundSetSound( f3_arg0, "selectAlt", false )
			f3_arg0.Buttons.ClosedButton:SetValue( false )
			f3_arg0.Buttons.InviteOnlyButton:SetValue( false )
			f3_arg0.Buttons.FriendsOnlyButton:SetValue( false )
			f3_arg0.Buttons.PublicButton:SetValue( true )
			f3_arg0._currentSetting = CoD.PartyPrivacySetting.Public
		end
	end )
	f3_arg0.Buttons.InviteOnlyButton:addEventHandler( "button_action", function ( f6_arg0, f6_arg1 )
		if f3_arg0._currentSetting ~= CoD.PartyPrivacySetting.INVITE_ONLY then
			Lobby.DDEDGGBHJ( f6_arg1.controller, CoD.PartyPrivacySetting.INVITE_ONLY )
			ACTIONS.PlaySoundSetSound( f3_arg0, "selectAlt", false )
			f3_arg0.Buttons.ClosedButton:SetValue( false )
			f3_arg0.Buttons.InviteOnlyButton:SetValue( true )
			f3_arg0.Buttons.FriendsOnlyButton:SetValue( false )
			f3_arg0.Buttons.PublicButton:SetValue( false )
			f3_arg0._currentSetting = CoD.PartyPrivacySetting.INVITE_ONLY
		end
	end )
	f3_arg0.Buttons.FriendsOnlyButton:addEventHandler( "button_action", function ( f5_arg0, f5_arg1 )
		if f3_arg0._currentSetting ~= CoD.PartyPrivacySetting.JOINABLE_BY_FRIENDS then
			Lobby.DDEDGGBHJ( f5_arg1.controller, CoD.PartyPrivacySetting.JOINABLE_BY_FRIENDS )
			ACTIONS.PlaySoundSetSound( f3_arg0, "selectAlt", false )
			f3_arg0.Buttons.ClosedButton:SetValue( false )
			f3_arg0.Buttons.InviteOnlyButton:SetValue( false )
			f3_arg0.Buttons.FriendsOnlyButton:SetValue( true )
			f3_arg0.Buttons.PublicButton:SetValue( false )
			f3_arg0._currentSetting = CoD.PartyPrivacySetting.JOINABLE_BY_FRIENDS
		end
	end )
	f3_arg0.Buttons.ClosedButton:addEventHandler( "button_action", function ( f4_arg0, f4_arg1 )
		if f3_arg0._currentSetting ~= CoD.PartyPrivacySetting.CLOSED then
			Lobby.DDEDGGBHJ( f4_arg1.controller, CoD.PartyPrivacySetting.CLOSED )
			ACTIONS.PlaySoundSetSound( f3_arg0, "selectAlt", false )
			f3_arg0.Buttons.ClosedButton:SetValue( true )
			f3_arg0.Buttons.InviteOnlyButton:SetValue( false )
			f3_arg0.Buttons.FriendsOnlyButton:SetValue( false )
			f3_arg0.Buttons.PublicButton:SetValue( false )
			f3_arg0._currentSetting = CoD.PartyPrivacySetting.Closed
		end
	end )
	if CONDITIONS.InGame( f3_arg0 ) then
		if CONDITIONS.IsPublicMatch( f3_arg0 ) then
			f3_arg0.Buttons.PublicButton:SetButtonDisabled( true )
			f3_arg0.Buttons.InviteOnlyButton:SetButtonDisabled( true )
			f3_arg0.Buttons.FriendsOnlyButton:SetButtonDisabled( true )
			f3_arg0.Buttons.ClosedButton:SetButtonDisabled( true )
		end
	elseif LUI.FlowManager.IsInStack( "MPPublicLobby" ) then
		f3_arg0.Buttons.PublicButton:SetButtonDisabled( true )
		f3_arg0.Buttons.InviteOnlyButton:SetButtonDisabled( true )
		f3_arg0.Buttons.FriendsOnlyButton:SetButtonDisabled( true )
		f3_arg0.Buttons.ClosedButton:SetButtonDisabled( true )
	end
end

function SocialPartySettingsPopup( menu, controller )
	local self = LUI.UIVerticalNavigator.new()
	self:SetAnchorsAndPosition( 0.5, 0.5, 0.5, 0.5, -412.5 * _1080p, 412.5 * _1080p, -540 * _1080p, 540 * _1080p )
	self.id = "SocialPartySettingsPopup"
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine.DDJFBBJAIG() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1 )
	local f1_local2 = self
	local Buttons = nil
	
	Buttons = MenuBuilder.BuildRegisteredType( "SocialPartySettingsPopupButtons", {
		controllerIndex = f1_local1
	} )
	Buttons.id = "Buttons"
	Buttons:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 130, _1080p * 630, _1080p * 216, _1080p * 561 )
	self:addElement( Buttons )
	self.Buttons = Buttons
	
	local MenuTitle = nil
	
	MenuTitle = MenuBuilder.BuildRegisteredType( "MenuTitle", {
		controllerIndex = f1_local1
	} )
	MenuTitle.id = "MenuTitle"
	MenuTitle.MenuTitle:setText( ToUpperCase( Engine.CBBHFCGDIC( "LUA_MENU/PARTY_SETTINGS" ) ), 0 )
	MenuTitle:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 1020, 0, _1080p * 100 )
	self:addElement( MenuTitle )
	self.MenuTitle = MenuTitle
	
	local bindButton = LUI.UIBindButton.new()
	bindButton.id = "selfBindButton"
	self:addElement( bindButton )
	self.bindButton = bindButton
	
	self.bindButton:addEventHandler( "button_secondary", function ( f2_arg0, f2_arg1 )
		local f2_local0 = f2_arg1.controller or menu
		if CONDITIONS.IsGamepadEnabled( menu ) then
			ACTIONS.LeaveMenu( menu )
		end
	end )
	f0_local0( self, f1_local1, controller )
	return self
end

MenuBuilder.registerType( "SocialPartySettingsPopup", SocialPartySettingsPopup )
LockTable( _M )
