-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 04-10-2025 21:43
module( ..., package.seeall )
CoD.PrintModuleLoad( _NAME )
local f0_local0 = 1.2
function invalidCmdHintDef()
	local self = LUI.UIElement.new()
	self.id = "invalidCmdHintId"
	self:setupOwnerdraw( CoD.Ownerdraw.CGInvalidCmdHint, f0_local0, CoD.TextStyle.Shadowed )
	self:SetAnchorsAndPosition( 0.5, 0.5, 0, 1, -32, 32, 162, 226 )
	self:SetAlpha( 0.6 )
	self:SetFont( CoD.TextSettings.HudEuroMedSmallFont.Font )
	self:SetAlignment( LUI.Alignment.Center )
	return self
end

MenuBuilder.registerType( "Hints", function ()
	local self = LUI.UIElement.new()
	self.id = "Hints"
	local f1_local1 = false
	if Engine[0xD151EC5B41223B5]() and GameX.IsRealismMode() then
		return self
	else
		self:addElement( invalidCmdHintDef() )
		return self
	end
end )
LockTable( _M )
