-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 13-07-2025 21:51
module( ..., package.seeall )
local f0_local0 = function ( f10_arg0, f10_arg1 )
	local f10_local0 = DataModel.JJEHAEBDF( f10_arg1 )
	if f10_arg0 and f10_local0 then
		f10_arg0:UpdateEntityID( f10_local0 )
	end
end

local f0_local1 = function ( f9_arg0, f9_arg1 )
	local f9_local0 = DataModel.JJEHAEBDF( f9_arg1 )
	local f9_local1 = BitwiseOperators.band( f9_local0, 1 ) == 1
	local f9_local2 = BitwiseOperators.band( BitwiseOperators.rshift( f9_local0, 1 ), 16383 ) * 250
	local f9_local3 = BitwiseOperators.band( BitwiseOperators.rshift( f9_local0, 15 ), 511 ) * 500
	f9_arg0:UpdateVisibility( f9_local1 )
	f9_arg0:UpdateTimer( f9_local2 )
	f9_arg0:UpdateProgress( f9_local3 )
end

local f0_local2 = function ( f2_arg0, f2_arg1, f2_arg2 )
	local f2_local0 = LUI.DataSourceFromOmnvar.new( "ui_br_plunder_repo_ent_1" )
	local f2_local1 = LUI.DataSourceFromOmnvar.new( "ui_br_plunder_repo_ent_2" )
	local f2_local2 = LUI.DataSourceFromOmnvar.new( "ui_br_plunder_repo_ent_3" )
	local f2_local3 = LUI.DataSourceFromOmnvar.new( "ui_br_plunder_repo_info_1" )
	local f2_local4 = LUI.DataSourceFromOmnvar.new( "ui_br_plunder_repo_info_2" )
	local f2_local5 = LUI.DataSourceFromOmnvar.new( "ui_br_plunder_repo_info_3" )
	f2_arg0:SubscribeToModel( f2_local0:GetModel( f2_arg1 ), function ( f8_arg0 )
		f2_arg0( f2_arg0.BRFultonMarker1, f8_arg0 )
	end )
	f2_arg0:SubscribeToModel( f2_local1:GetModel( f2_arg1 ), function ( f7_arg0 )
		f2_arg0( f2_arg0.BRFultonMarker2, f7_arg0 )
	end )
	f2_arg0:SubscribeToModel( f2_local2:GetModel( f2_arg1 ), function ( f6_arg0 )
		f2_arg0( f2_arg0.BRFultonMarker3, f6_arg0 )
	end )
	f2_arg0:SubscribeToModel( f2_local3:GetModel( f2_arg1 ), function ( f5_arg0 )
		f2_arg0( f2_arg0.BRFultonMarker1, f5_arg0 )
	end )
	f2_arg0:SubscribeToModel( f2_local4:GetModel( f2_arg1 ), function ( f4_arg0 )
		f2_arg0( f2_arg0.BRFultonMarker2, f4_arg0 )
	end )
	f2_arg0:SubscribeToModel( f2_local5:GetModel( f2_arg1 ), function ( f3_arg0 )
		f2_arg0( f2_arg0.BRFultonMarker3, f3_arg0 )
	end )
end

function BRFultonMarkerContainer( menu, controller )
	local self = LUI.UIElement.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 1920 * _1080p, 0, 1080 * _1080p )
	self.id = "BRFultonMarkerContainer"
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine.DDJFBBJAIG() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1 )
	local f1_local2 = self
	local BRFultonMarker1 = nil
	
	BRFultonMarker1 = MenuBuilder.BuildRegisteredType( "BRFultonMarker", {
		controllerIndex = f1_local1
	} )
	BRFultonMarker1.id = "BRFultonMarker1"
	BRFultonMarker1:SetAnchorsAndPosition( 0.5, 0.5, 0.5, 0.5, _1080p * -16, _1080p * 16, _1080p * -16, _1080p * 16 )
	self:addElement( BRFultonMarker1 )
	self.BRFultonMarker1 = BRFultonMarker1
	
	local BRFultonMarker2 = nil
	
	BRFultonMarker2 = MenuBuilder.BuildRegisteredType( "BRFultonMarker", {
		controllerIndex = f1_local1
	} )
	BRFultonMarker2.id = "BRFultonMarker2"
	BRFultonMarker2:SetAnchorsAndPosition( 0.5, 0.5, 0.5, 0.5, _1080p * -16, _1080p * 16, _1080p * -16, _1080p * 16 )
	self:addElement( BRFultonMarker2 )
	self.BRFultonMarker2 = BRFultonMarker2
	
	local BRFultonMarker3 = nil
	
	BRFultonMarker3 = MenuBuilder.BuildRegisteredType( "BRFultonMarker", {
		controllerIndex = f1_local1
	} )
	BRFultonMarker3.id = "BRFultonMarker3"
	BRFultonMarker3:SetAnchorsAndPosition( 0.5, 0.5, 0.5, 0.5, _1080p * -16, _1080p * 16, _1080p * -16, _1080p * 16 )
	self:addElement( BRFultonMarker3 )
	self.BRFultonMarker3 = BRFultonMarker3
	
	f0_local0( self, f1_local1, controller )
	return self
end

MenuBuilder.registerType( "BRFultonMarkerContainer", BRFultonMarkerContainer )
LockTable( _M )
