-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 13-07-2025 21:52
module( ..., package.seeall )
function BRX2Info( menu, controller )
	local self = LUI.UIElement.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 400 * _1080p, 0, 130 * _1080p )
	self.id = "BRX2Info"
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine.DDJFBBJAIG() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1 )
	local f1_local2 = self
	local BackgroundContainer = nil
	
	BackgroundContainer = MenuBuilder.BuildRegisteredType( "DoubleNotchedBacker", {
		controllerIndex = f1_local1
	} )
	BackgroundContainer.id = "BackgroundContainer"
	BackgroundContainer:SetAlpha( 0.5, 0 )
	BackgroundContainer:SetAnchorsAndPosition( 0, 0, 0, 0, 0, 0, 0, 0 )
	self:addElement( BackgroundContainer )
	self.BackgroundContainer = BackgroundContainer
	
	local Title = nil
	
	Title = LUI.UIText.new()
	Title.id = "Title"
	Title:SetRGBFromTable( SWATCHES.Global.keyColorMid, 0 )
	Title:setText( Engine.CBBHFCGDIC( "BR_REVEAL_X2_EVENT/EVENT_TITLE_X2" ), 0 )
	Title:SetFont( FONTS.GetFont( FONTS.MainRegular.File ) )
	Title:SetAlignment( LUI.Alignment.Left )
	Title:SetOptOutRightToLeftAlignmentFlip( true )
	Title:SetAnchorsAndPosition( 0, 0, 0, 1, _1080p * 30, _1080p * -19, _1080p * 15, _1080p * 45 )
	self:addElement( Title )
	self.Title = Title
	
	local PlaylistIcon = nil
	
	PlaylistIcon = LUI.UIImage.new()
	PlaylistIcon.id = "PlaylistIcon"
	PlaylistIcon:setImage( RegisterMaterial( "icon_mode_wz_br_x2" ), 0 )
	PlaylistIcon:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 30, _1080p * 75, _1080p * 57, _1080p * 101 )
	self:addElement( PlaylistIcon )
	self.PlaylistIcon = PlaylistIcon
	
	local SubDesc = nil
	
	SubDesc = LUI.UIStyledText.new()
	SubDesc.id = "SubDesc"
	SubDesc:SetRGBFromTable( SWATCHES.HUD.HUDSecondary, 0 )
	SubDesc:setText( Engine.CBBHFCGDIC( "BR_REVEAL_X2_EVENT/PLAYLIST_DESC_X2" ), 0 )
	SubDesc:SetFont( FONTS.GetFont( FONTS.MainRegular.File ) )
	SubDesc:SetAlignment( LUI.Alignment.Left )
	SubDesc:SetOptOutRightToLeftAlignmentFlip( true )
	SubDesc:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 86, _1080p * 370, _1080p * 57, _1080p * 77 )
	self:addElement( SubDesc )
	self.SubDesc = SubDesc
	
	return self
end

MenuBuilder.registerType( "BRX2Info", BRX2Info )
LockTable( _M )
