-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 13-07-2025 21:51
module( ..., package.seeall )
local f0_local0 = function ( f10_arg0, f10_arg1 )
	local f10_local0 = DataSources.inGame.player.perkPackageState:GetValue( f10_arg1.controllerIndex )
	if f10_local0 == PERK.PERK_PACKAGE_STATES.Upgrade1Selected or f10_local0 == PERK.PERK_PACKAGE_STATES.Upgrade2Selected then
		local f10_local1 = nil
		if f10_local0 == PERK.PERK_PACKAGE_STATES.Upgrade1Selected then
			f10_local1 = DataSources.inGame.player.perkPackageSuper1:GetValue( f10_arg1.controllerIndex )
		elseif f10_local0 == PERK.PERK_PACKAGE_STATES.Upgrade2Selected then
			f10_local1 = DataSources.inGame.player.perkPackageSuper2:GetValue( f10_arg1.controllerIndex )
		end
		local f10_local2 = StringTable.CBGJCDIHCE( CSV.supers.file, f10_local1, CSV.supers.cols.uiName )
		local f10_local3 = StringTable.CBGJCDIHCE( CSV.supers.file, f10_local1, CSV.supers.cols.uiImageSmall )
		if f10_local2 ~= nil and 0 < #f10_local2 then
			LAYOUT.SetTextBoxSize( f10_arg0.Banner.Header, f10_arg0.Banner, ToUpperCase( Engine.CBBHFCGDIC( "MPUI/FIELDUPGRADE_AVAILABLE", f10_local2 ) ), 25, nil, LUI.Alignment.Center, 0 )
		end
		if f10_local3 ~= nil and 0 < #f10_local3 then
			f10_arg0.Icon:setImage( RegisterMaterial( f10_local3 ), 0 )
		end
	else
		LAYOUT.SetTextBoxSize( f10_arg0.Banner.Header, f10_arg0.Banner, ToUpperCase( Engine.CBBHFCGDIC( "MPUI/FIELD_UPGRADE_AVAILABLE" ) ), 25, nil, LUI.Alignment.Center, 0 )
		f10_arg0.Icon:setImage( RegisterMaterial( "hud_icon_fieldupgrade" ), 0 )
	end
	ACTIONS.AnimateSequence( f10_arg0, "Ready" )
	ACTIONS.AnimateSequence( f10_arg0.Banner, "Show" )
	Engine.BJDBIAGIDA( SOUND_SETS.inGame.fieldUpgradePopup )
end

local f0_local1 = function ( f9_arg0 )
	local f9_local0 = f9_arg0:getParent()
	ACTIONS.AnimateSequence( f9_local0.Banner, "Hide" )
end

local f0_local2 = function ( f6_arg0, f6_arg1, f6_arg2 )
	assert( f6_arg0.Banner )
	f6_arg0.ShowSplash = f0_local0
	ACTIONS.AnimateSequence( f6_arg0, "NotReady" )
	local f6_local0 = function ( f8_arg0, f8_arg1 )
		if CONDITIONS.IsGamepadEnabled() then
			if CONDITIONS.IsBrButtonLayoutActive( f8_arg1.controllerIndex ) then
				f8_arg0.instructionTextRef = "MPUI/SUPER_ABILITY_HINT_BR_LAYOUT"
			else
				f8_arg0.instructionTextRef = "MPUI/SUPER_ABILITY_HINT"
			end
		else
			f8_arg0.instructionTextRef = "MPUI/SUPER_ABILITY_HINT_PC"
		end
		f8_arg0.InstructionText:setText( Engine.CBBHFCGDIC( f8_arg0.instructionTextRef ) )
	end
	
	f6_arg0:registerEventHandler( "empty_menu_stack", f6_local0 )
	f6_local0( f6_arg0, {
		controllerIndex = f6_arg1
	} )
	local f6_local1 = LUI.DataSourceFromOmnvar.new( "ui_super_reminder" )
	f6_arg0:SubscribeToModel( f6_local1:GetModel( f6_arg1 ), function ( f7_arg0 )
		local f7_local0 = DataModel.JJEHAEBDF( f7_arg0 )
		if f7_local0 ~= nil and f7_local0 then
			f6_arg0:dispatchEventToRoot( {
				name = "add_message_splash_manager",
				immediate = true,
				options = {
					displayLocation = "super",
					controllerIndex = f6_arg0
				}
			} )
		end
	end )
end

function FieldUpgradeNotification( menu, controller )
	local self = LUI.UIElement.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 500 * _1080p, 0, 36 * _1080p )
	self.id = "FieldUpgradeNotification"
	self._animationSets = self._animationSets or {}
	self._sequences = self._sequences or {}
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine.DDJFBBJAIG() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1 )
	local f1_local2 = self
	local InstructionText = nil
	
	InstructionText = LUI.UIStyledText.new()
	InstructionText.id = "InstructionText"
	InstructionText:SetRGBFromTable( SWATCHES.HUD.HUDMain, 0 )
	InstructionText:setText( "", 0 )
	InstructionText:SetFont( FONTS.GetFont( FONTS.MainRegular.File ) )
	InstructionText:SetWordWrap( false )
	InstructionText:SetAlignment( LUI.Alignment.Center )
	InstructionText:SetTintFontIcons( true )
	InstructionText:SetShadowMinDistance( -0.02, 0 )
	InstructionText:SetShadowMaxDistance( 0.02, 0 )
	InstructionText:SetShadowUOffset( -0.001, 0 )
	InstructionText:SetShadowVOffset( -0.001, 0 )
	InstructionText:SetShadowRGBFromTable( SWATCHES.HUD.HUDShadow, 0 )
	InstructionText:SetAnchorsAndPosition( 0, 0, 1, 0, 0, 0, 0, _1080p * 28 )
	self:addElement( InstructionText )
	self.InstructionText = InstructionText
	
	local Banner = nil
	
	Banner = MenuBuilder.BuildRegisteredType( "LocalPlayerSplashBanner", {
		controllerIndex = f1_local1
	} )
	Banner.id = "Banner"
	Banner.BG:SetRGBFromTable( SWATCHES.CAC.attachShade, 0 )
	Banner.Bar:SetRGBFromTable( SWATCHES.MPArmory.bundleBG, 0 )
	Banner:SetAnchorsAndPosition( 0.5, 0.5, 0, 1, _1080p * -250, _1080p * 250, 0, _1080p * 36 )
	self:addElement( Banner )
	self.Banner = Banner
	
	local IconBacker = nil
	
	IconBacker = LUI.UIImage.new()
	IconBacker.id = "IconBacker"
	IconBacker:SetRGBFromTable( SWATCHES.CAC.attachShade, 0 )
	IconBacker:SetAlpha( 0, 0 )
	IconBacker:SetPixelGridEnabled( true )
	IconBacker:SetPixelGridContrast( 0.2, 0 )
	IconBacker:SetPixelGridBlockWidth( 2, 0 )
	IconBacker:SetPixelGridBlockHeight( 2, 0 )
	IconBacker:SetPixelGridGutterWidth( 1, 0 )
	IconBacker:SetPixelGridGutterHeight( 1, 0 )
	IconBacker:setImage( RegisterMaterial( "ui_generic_glow" ), 0 )
	IconBacker:SetAnchorsAndPosition( 0.5, 0.5, 0, 1, _1080p * -120, _1080p * 120, _1080p * -181, _1080p * 59 )
	self:addElement( IconBacker )
	self.IconBacker = IconBacker
	
	local Icon = nil
	
	Icon = LUI.UIImage.new()
	Icon.id = "Icon"
	Icon:setImage( RegisterMaterial( "hud_icon_fieldupgrade" ), 0 )
	Icon:SetAnchorsAndPosition( 0.5, 0.5, 0, 1, _1080p * -58, _1080p * 58, _1080p * -119, _1080p * -3 )
	self:addElement( Icon )
	self.Icon = Icon
	
	InstructionText:RegisterAnimationSequence( "DefaultSequence", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Banner:RegisterAnimationSequence( "DefaultSequence", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.DefaultSequence = function ()
		menu:AnimateSequence( "DefaultSequence" )
		menu:AnimateSequence( "DefaultSequence" )
	end
	
	InstructionText:RegisterAnimationSequence( "Ready", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 400,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 40,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 40,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 40,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 2330,
			property = TWEEN_PROPERTY.Alpha,
			onComplete = f0_local0
		},
		{
			value = 0,
			duration = 150,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Banner:RegisterAnimationSequence( "Ready", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 3000,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.snap
		}
	} )
	IconBacker:RegisterAnimationSequence( "Ready", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 2,
			duration = 0,
			property = TWEEN_PROPERTY.Scale
		},
		{
			value = 0,
			duration = -28,
			property = TWEEN_PROPERTY.Scale
		},
		{
			value = -2.353438279577766E-185,
			duration = -28,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = -2.353438279577766E-185,
			duration = 2750,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 150,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Icon:RegisterAnimationSequence( "Ready", {
		{
			value = 2,
			duration = 0,
			property = TWEEN_PROPERTY.Scale
		},
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = -28,
			property = TWEEN_PROPERTY.Scale
		},
		{
			value = 1,
			duration = -28,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 2750,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 150,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.Ready = function ()
		menu:AnimateSequence( "Ready" )
		menu:AnimateSequence( "Ready" )
		menu:AnimateSequence( "Ready" )
		menu:AnimateSequence( "Ready" )
	end
	
	InstructionText:RegisterAnimationSequence( "NotReady", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Banner:RegisterAnimationSequence( "NotReady", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	IconBacker:RegisterAnimationSequence( "NotReady", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Icon:RegisterAnimationSequence( "NotReady", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.NotReady = function ()
		menu:AnimateSequence( "NotReady" )
		menu:AnimateSequence( "NotReady" )
		menu:AnimateSequence( "NotReady" )
		menu:AnimateSequence( "NotReady" )
	end
	
	self._sequences.HideIcon = function ()
		
	end
	
	f0_local0( self, f1_local1, controller )
	ACTIONS.AnimateSequence( self, "DefaultSequence" )
	return self
end

MenuBuilder.registerType( "FieldUpgradeNotification", FieldUpgradeNotification )
LockTable( _M )
