-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 13-07-2025 21:51
module( ..., package.seeall )
function GameTimerWarning( menu, controller )
	local self = LUI.UIElement.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 73 * _1080p, 0, 36 * _1080p )
	self.id = "GameTimerWarning"
	self._animationSets = {}
	self._sequences = {}
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine.DDJFBBJAIG() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1 )
	local f1_local2 = self
	local GameTimerBackgroundRight = nil
	
	GameTimerBackgroundRight = LUI.UIImage.new()
	GameTimerBackgroundRight.id = "GameTimerBackgroundRight"
	GameTimerBackgroundRight:SetAlpha( 0, 0 )
	GameTimerBackgroundRight:setImage( RegisterMaterial( "codcaster_timer_warning" ), 0 )
	GameTimerBackgroundRight:SetUMin( 1, 0 )
	GameTimerBackgroundRight:SetUMax( 0.5, 0 )
	GameTimerBackgroundRight:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 67, _1080p * 75, _1080p * 2, _1080p * 34 )
	self:addElement( GameTimerBackgroundRight )
	self.GameTimerBackgroundRight = GameTimerBackgroundRight
	
	local GameTimerBackgroundRightCopy0 = nil
	
	GameTimerBackgroundRightCopy0 = LUI.UIImage.new()
	GameTimerBackgroundRightCopy0.id = "GameTimerBackgroundRightCopy0"
	GameTimerBackgroundRightCopy0:SetRGBFromInt( 6710886, 0 )
	GameTimerBackgroundRightCopy0:SetAlpha( 0, 0 )
	GameTimerBackgroundRightCopy0:setImage( RegisterMaterial( "codcaster_timer_warning" ), 0 )
	GameTimerBackgroundRightCopy0:SetUMin( 1, 0 )
	GameTimerBackgroundRightCopy0:SetUMax( 0, 0 )
	GameTimerBackgroundRightCopy0:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 29.5, _1080p * 45.5, _1080p * 2, _1080p * 34 )
	self:addElement( GameTimerBackgroundRightCopy0 )
	self.GameTimerBackgroundRightCopy0 = GameTimerBackgroundRightCopy0
	
	local GameTimerBackgroundRightCopy1 = nil
	
	GameTimerBackgroundRightCopy1 = LUI.UIImage.new()
	GameTimerBackgroundRightCopy1.id = "GameTimerBackgroundRightCopy1"
	GameTimerBackgroundRightCopy1:SetRGBFromInt( 11776947, 0 )
	GameTimerBackgroundRightCopy1:SetAlpha( 0, 0 )
	GameTimerBackgroundRightCopy1:setImage( RegisterMaterial( "codcaster_timer_warning" ), 0 )
	GameTimerBackgroundRightCopy1:SetUMin( 1, 0 )
	GameTimerBackgroundRightCopy1:SetUMax( 0, 0 )
	GameTimerBackgroundRightCopy1:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 48.5, _1080p * 64.5, _1080p * 2, _1080p * 34 )
	self:addElement( GameTimerBackgroundRightCopy1 )
	self.GameTimerBackgroundRightCopy1 = GameTimerBackgroundRightCopy1
	
	self._sequences.DefaultSequence = function ()
		
	end
	
	GameTimerBackgroundRight:RegisterAnimationSequence( "TimeLimitWarning", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 400,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	GameTimerBackgroundRightCopy0:RegisterAnimationSequence( "TimeLimitWarning", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 600,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 600,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	GameTimerBackgroundRightCopy1:RegisterAnimationSequence( "TimeLimitWarning", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 400,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 500,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.TimeLimitWarning = function ()
		menu:AnimateLoop( "TimeLimitWarning" )
		menu:AnimateLoop( "TimeLimitWarning" )
		menu:AnimateLoop( "TimeLimitWarning" )
	end
	
	GameTimerBackgroundRight:RegisterAnimationSequence( "ResetSequence", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	GameTimerBackgroundRightCopy0:RegisterAnimationSequence( "ResetSequence", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	GameTimerBackgroundRightCopy1:RegisterAnimationSequence( "ResetSequence", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.ResetSequence = function ()
		menu:AnimateSequence( "ResetSequence" )
		menu:AnimateSequence( "ResetSequence" )
		menu:AnimateSequence( "ResetSequence" )
	end
	
	return self
end

MenuBuilder.registerType( "GameTimerWarning", GameTimerWarning )
LockTable( _M )
