-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 13-07-2025 21:52
module( ..., package.seeall )
local f0_local0 = function ( f14_arg0, f14_arg1, f14_arg2 )
	assert( f14_arg2 )
	assert( f14_arg0.RespawnMessage )
	assert( f14_arg0.WeaponInfo )
	assert( f14_arg0.VictimText )
	f14_arg0.VictimText:SetFont( FONTS.GetFont( FONTS.BattleNetRegular.File ) )
	f14_arg0.VictimText:SetFontSize( 24 * _1080p )
	f14_arg0.VictimText:SetMask( f14_arg0.VictimTextMask )
	f14_arg0.VictimText:SubscribeToModel( DataSources.inGame.MP.killcam.killedby.victimPlayerCard.fullName:GetModel( f14_arg1 ), function ()
		local f25_local0 = DataSources.inGame.MP.killcam.killedby.victimPlayerCard.fullName:GetValue( f14_arg0 )
		if f25_local0 ~= nil then
			if MLG.FBFGBEC() then
				local f25_local1 = CODCASTER_PLAYERLIST.GetCompetitiveName( f25_local0, DataSources.inGame.MP.killcam.victimClientId:GetValue( f14_arg0 ), true )
				if f25_local1 then
					f25_local0 = f25_local1
				end
			end
			f14_arg0.VictimText:setText( LocalizeIntoString( MarkLocalized( f25_local0 ), "CGAME/VICTIM" ), 0 )
		end
	end )
	local f14_local0 = f14_arg2.isFinal
	local f14_local1 = f14_arg2.isRoundEnd
	local f14_local2 = f14_arg2.isPOTG
	local f14_local3 = false
	if CONDITIONS.IsMagmaGameMode() then
		local f14_local4 = DataSources.inGame.MP.brSquadEliminatedActive:GetValue( f14_arg1 )
		if f14_local4 then
			f14_local3 = f14_local4 == 1
		end
	end
	local f14_local4
	if not f14_local0 then
		f14_local4 = f14_local0
	elseif not f14_local1 then
		f14_local4 = f14_local1
	elseif not f14_local2 then
		f14_local4 = f14_local2
	else
		f14_local4 = f14_local3
	end
	local f14_local5 = false
	local self = f14_arg0.CountdownTimer
	local ThermalVision = self
	self = self.SetAlpha
	local NetStatsIcons
	if f14_local4 then
		NetStatsIcons = 0
	else
		NetStatsIcons = 1
	end
	self( ThermalVision, NetStatsIcons )
	self = f14_arg0.RespawnMessage
	ThermalVision = self
	self = self.SetAlpha
	if f14_local4 then
		NetStatsIcons = 0
	else
		NetStatsIcons = 1
	end
	self( ThermalVision, NetStatsIcons )
	if f14_local2 then
		ACTIONS.AnimateSequence( f14_arg0, "PlayOfTheGame" )
	end
	if LUI.PostGameManager.IsPostGame( f14_arg1 ) then
		self = LUI.UIElement.new()
		self:setPriority( -1 )
		f14_arg0:addElement( self )
		local f14_local9 = LUI.UIElement.new()
		f14_local9:setPriority( -100 )
		f14_arg0:addElement( f14_local9 )
		if MP.IsBRGameType( Lobby.GetCurrentGameType() ) then
			f14_arg0._overlay = LUI.BROverlayHUD.new( f14_arg1, self, f14_local9 )
		else
			f14_arg0._overlay = LUI.MPOverlayHUD.new( f14_arg1, self, f14_local9 )
		end
		f14_arg0:addElement( f14_arg0._overlay )
		ThermalVision = MenuBuilder.BuildRegisteredType( "ThermalVision", {
			controllerIndex = f14_arg1
		} )
		ThermalVision.id = "ThermalVision"
		ThermalVision:setPriority( -1 )
		f14_arg0:addElement( ThermalVision )
		f14_arg0.ThermalVision = ThermalVision
		
		if not GameX.IsRealismMode() then
			NetStatsIcons = MenuBuilder.BuildRegisteredType( "HitMarker", {
				controllerIndex = f14_arg1
			} )
			NetStatsIcons.id = "HitMarker"
			NetStatsIcons:SetAnchors( 0.5, 0.5, 0.5, 0.5, 0 )
			NetStatsIcons:SetLeft( _1080p * -11, 0 )
			NetStatsIcons:SetRight( _1080p * 11, 0 )
			NetStatsIcons:SetTop( _1080p * -11, 0 )
			NetStatsIcons:SetBottom( _1080p * 11, 0 )
			NetStatsIcons:setPriority( -2 )
			f14_arg0:addElement( NetStatsIcons )
			f14_arg0.HitMarker = NetStatsIcons
		end
		NetStatsIcons = MenuBuilder.BuildRegisteredType( "NetStatsIcons", {
			controllerIndex = f14_arg1
		} )
		NetStatsIcons.id = "NetStatsIcons"
		NetStatsIcons:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, _1080p * 10, _1080p * 42, _1080p * -64, _1080p * 64 )
		NetStatsIcons:setPriority( -2 )
		f14_arg0:addElement( NetStatsIcons )
		f14_arg0.NetStatsIcons = NetStatsIcons
		
		local Nameplates = MenuBuilder.BuildRegisteredType( "playerNameplateContainer", {
			controllerIndex = f14_arg1
		} )
		Nameplates.id = "playerNameplateContainer"
		Nameplates:setPriority( -2 )
		f14_arg0:addElement( Nameplates )
		f14_arg0.Nameplates = Nameplates
		
		local HeartbeatSensorTablet = MenuBuilder.BuildRegisteredType( "HeartbeatSensorTablet", {
			controllerIndex = f14_arg1
		} )
		HeartbeatSensorTablet.id = "HeartbeatSensorTablet"
		HeartbeatSensorTablet:setPriority( -2 )
		f14_arg0:addElement( HeartbeatSensorTablet )
		f14_arg0.HeartbeatSensorTablet = HeartbeatSensorTablet
		
		local CyberEMPSensor = MenuBuilder.BuildRegisteredType( "CyberEMPSensor", {
			controllerIndex = f14_arg1
		} )
		CyberEMPSensor.id = "CyberEMPSensor"
		CyberEMPSensor:setPriority( -2 )
		f14_arg0:addElement( CyberEMPSensor )
		f14_arg0.CyberEMPSensor = CyberEMPSensor
		
		if CONDITIONS.IsBombGametype( f14_arg0 ) then
			f14_arg0:SubscribeToModel( DataSources.inGame.player.currentWeapon.bombBriefcase:GetModel( f14_arg1 ), function ( f24_arg0 )
				if not f14_arg0.BriefcaseBombScreen then
					local f24_local0 = MenuBuilder.BuildRegisteredType( "BombBriefcaseTablet", {
						controllerIndex = f14_arg0
					} )
					f24_local0.id = "BombBriefcaseTablet"
					f24_local0:setPriority( -2 )
					f14_arg0:addElement( f24_local0 )
					f14_arg0.BriefcaseBombScreen = f24_local0
				end
			end )
		end
		local f14_local13 = LUI.DataSourceFromOmnvar.new( "ui_remote_control_sequence" )
		f14_arg0:SubscribeToModel( f14_local13:GetModel( f14_arg1 ), function ( f23_arg0 )
			local f23_local0 = DataModel.JJEHAEBDF( f23_arg0 )
			if f23_local0 and 0 < f23_local0 and not f14_arg0.StreakActivationTablet then
				local f23_local1 = MenuBuilder.BuildRegisteredType( "StreakActivationTablet", {
					controllerIndex = f14_arg0
				} )
				f23_local1.id = "StreakActivationTablet"
				f23_local1:setPriority( -2 )
				f14_arg0:addElement( f23_local1 )
				f14_arg0.StreakActivationTablet = f23_local1
			end
		end )
	end
	f14_arg0:SubscribeToModel( DataSources.inGame.MP.killcam.killedby.itemType:GetModel( f14_arg1 ), function ( f22_arg0 )
		if DataModel.JJEHAEBDF( f22_arg0 ) == 0 then
			ACTIONS.AnimateSequence( f14_arg0, "KilledByGun" )
		else
			ACTIONS.AnimateSequence( f14_arg0, "KilledByOther" )
		end
	end )
	f14_arg0:SubscribeToModel( DataSources.inGame.player.inKillCam:GetModel( f14_arg1 ), function ( f21_arg0 )
		if DataModel.JJEHAEBDF( f21_arg0 ) == true then
			if f14_arg0 then
				Engine.BJDBIAGIDA( SOUND_SETS.inGame.potgPopup )
			else
				if f14_arg0 or f14_arg0 then
					local f21_local0 = ToUpperCase( Engine.CBBHFCGDIC( "MP/ROUND_KILLCAM" ) )
					f14_arg0 = true
					f14_arg0.HeaderText:setText( f21_local0, 0 )
					ACTIONS.AnimateSequence( f14_arg0.WeaponInfo, "FinalKillcam" )
				else
					f14_arg0.HeaderText:setText( ToUpperCase( Engine.CBBHFCGDIC( "LUA_MENU/KILLCAM_CAPS" ) ), 0 )
					ACTIONS.AnimateSequence( f14_arg0.WeaponInfo, "Killcam" )
				end
				ACTIONS.AnimateSequence( f14_arg0, "Boot" )
				ACTIONS.AnimateSequence( f14_arg0, "LoopReplay" )
				Engine.BJDBIAGIDA( SOUND_SETS.inGame.killcamPopup )
				f14_arg0.WeaponInfo.KilledWithText:setText( Engine.CBBHFCGDIC( "KILLSTREAKS/KILLED_WITH", 0 ) )
				if f14_arg0.WeaponInfo.CopyLoadoutText ~= nil then
					if MLG.IsCDLActive( f14_arg0 ) then
						f14_arg0.WeaponInfo.CopyLoadoutText:SetAlpha( 0 )
					else
						f14_arg0.WeaponInfo.CopyLoadoutText:SetAlpha( 1 )
						f14_arg0.WeaponInfo.CopyLoadoutText:setText( Engine.CBBHFCGDIC( "LUA_MENU/COPYCAT_LOADOUT", 0 ) )
					end
				end
				f14_arg0.KillcamPerkInfoContainer.PerksLabel:setText( Engine.CBBHFCGDIC( "LUA_MENU_MP/RULES_PERKS" ), 0 )
				f14_arg0.ReplayText:setText( ToUpperCase( Engine.CBBHFCGDIC( "LUA_MENU/REPLAY" ) ), 0 )
			end
		end
	end )
	local f14_local9 = LUI.DataSourceFromOmnvar.new( "ui_killcam_killedby_id" )
	f14_arg0:SubscribeToModel( f14_local9:GetModel( f14_arg1 ), function ()
		local f20_local0 = f14_arg0:GetValue( f14_arg0 )
		if f20_local0 ~= nil and 0 <= f20_local0 then
			if CONDITIONS.IsCoreMultiplayerNotBr() then
				f14_arg0.PlayerCard:FillWithClientNum( f20_local0, f14_arg0 )
			else
				f14_arg0.WZSmallPlayerCard:FillWithClientNum( f20_local0, f14_arg0 )
			end
			local f20_local1 = Game.DHEDEIHGF( f20_local0 )
			local f20_local2 = MP.GetTeamInfo( f20_local1 )
			local f20_local3 = DataSources.inGame.MP.match.gameType:GetValue( f14_arg0 )
			if CONDITIONS.IsCoreMultiplayer() and f20_local0 ~= Game.DBACJGFHDD( f14_arg0 ) and not Game.BHGFGIJJFD( f14_arg0, f20_local0 ) and Engine.CJJAFGIFAC( f14_arg0 ) and not CODCASTER.IsCODCaster() then
				f14_arg0.ReportButton:SetAlpha( 1 )
			else
				f14_arg0.ReportButton:SetAlpha( 0 )
			end
			if not (not MLG.DBIBHEAEGD() or not CODCASTER_CONDITIONS.IsMPCODCaster()) or f20_local3 == MP.GameMode.FFAGameType or f20_local3 == MP.GameMode.OICGameType then
				f14_arg0 = false
			end
			if f14_arg0 then
				if CODCASTER.CanCODCast() and CODCASTER.IsCODCaster() then
					local f20_local4 = f20_local1
					if not MLG.DIJEHAFJDJ() then
						if f20_local1 == 1 then
							f20_local4 = 2
						else
							f20_local4 = 1
						end
					end
					CODCASTER.SetTeamColorLogo( f14_arg0.teamIcon, f14_arg0, f20_local4, false )
				else
					f14_arg0.teamIcon:setImage( RegisterMaterial( f20_local2.largeLogo ), 0 )
				end
				ACTIONS.AnimateSequence( f14_arg0, "TeamIconOn" )
			else
				ACTIONS.AnimateSequence( f14_arg0, "TeamIconOff" )
			end
			local f20_local4 = Game.DHEDEIHGF()
			if CODCASTER.CanCODCast() and CODCASTER.IsCODCaster() then
				local f20_local5 = f20_local1
				if not MLG.DIJEHAFJDJ() then
					if f20_local1 == 1 then
						f20_local5 = 2
					else
						f20_local5 = 1
					end
				end
				local f20_local6, f20_local7 = CODCASTER.GetTeamColor( f14_arg0, f20_local5 )
				f14_arg0.BG1:SetRGBFromInt( f20_local6, 0 )
				f14_arg0.BG2:SetRGBFromInt( f20_local6, 0 )
				f14_arg0.TopLine:SetRGBFromInt( f20_local6, 0 )
			elseif f20_local4 == f20_local1 then
				f14_arg0.BG1:SetRGBFromTable( SWATCHES.Global.keyColor, 0 )
				f14_arg0.BG2:SetRGBFromTable( SWATCHES.Global.keyColor, 0 )
				f14_arg0.TopLine:SetRGBFromTable( SWATCHES.Global.keyColor, 0 )
			else
				f14_arg0.BG1:SetRGBFromTable( SWATCHES.HUD.enemyTeamName, 0 )
				f14_arg0.BG2:SetRGBFromTable( SWATCHES.HUD.enemyTeamName, 0 )
				f14_arg0.TopLine:SetRGBFromTable( SWATCHES.HUD.enemyTeam, 0 )
			end
		end
	end )
	ACTIONS.ScaleFullscreen( f14_arg0.WhiteFlash )
	if not CONDITIONS.IsSplitscreen() then
		ACTIONS.ScaleFullscreen( f14_arg0.Darkener )
		ACTIONS.ScaleFullscreen( f14_arg0.DotPitchBG )
		ACTIONS.ScaleFullscreen( f14_arg0.nvgVignette )
		f14_arg0.DotPitchBG:PixelGridOverlayLayer()
	end
	f14_arg0:registerEventHandler( "empty_menu_stack", function ( element )
		if element.WeaponInfo.CopyLoadoutText ~= nil then
			element.WeaponInfo.CopyLoadoutText:setText( Engine.CBBHFCGDIC( "LUA_MENU/COPYCAT_LOADOUT", 0 ) )
		end
	end )
	ThermalVision = LUI.DataSourceFromOmnvar.new( "ui_overcharge" )
	f14_arg0:SubscribeToModel( ThermalVision:GetModel( f14_arg1 ), function ()
		local f17_local0 = f14_arg0:GetValue( f14_arg0 )
		if f17_local0 then
			local f17_local1 = f14_arg0:Wait( 300 )
			f17_local1.onComplete = function ()
				f17_local0.StoppingPowerIcon:SetAlpha( 1, 150 )
			end
			
		else
			f14_arg0.StoppingPowerIcon:SetAlpha( 0 )
		end
	end )
	NetStatsIcons = {
		Off = 2,
		On = 0,
		Reset = 1
	}
	local Nameplates = LUI.DataSourceFromOmnvar.new( "ui_deadsilence_overlay" )
	f14_arg0:SubscribeToModel( Nameplates:GetModel( f14_arg1 ), function ()
		local f15_local0 = f14_arg0:GetValue( f14_arg0 )
		if f15_local0 == f14_arg0.On or f15_local0 == f14_arg0.Reset then
			local f15_local1 = f14_arg0:Wait( 300 )
			f15_local1.onComplete = function ()
				f15_local0.DeadsilenceIcon:SetAlpha( 1, 150 )
			end
			
		else
			f14_arg0.DeadsilenceIcon:SetAlpha( 0 )
		end
	end )
end

function Killcam( menu, controller )
	local self = LUI.UIElement.new()
	self.id = "Killcam"
	self._animationSets = self._animationSets or {}
	self._sequences = self._sequences or {}
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine.DDJFBBJAIG() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1 )
	local f1_local2 = self
	local f1_local3 = nil
	if not CONDITIONS.IsSplitscreen() then
		f1_local3 = LUI.UIImage.new()
		f1_local3.id = "DotPitchBG"
		f1_local3:SetRGBFromTable( SWATCHES.genericMenu.warningDark, 0 )
		f1_local3:SetAlpha( 0, 0 )
		f1_local3:SetPixelGridEnabled( true )
		f1_local3:SetPixelGridContrast( 1, 0 )
		f1_local3:SetPixelGridBlockWidth( 1, 0 )
		f1_local3:SetPixelGridBlockHeight( 1, 0 )
		f1_local3:SetPixelGridGutterWidth( 1, 0 )
		f1_local3:SetPixelGridGutterHeight( 1, 0 )
		f1_local3:SetBlendMode( BLEND_MODE.multiply )
		self:addElement( f1_local3 )
		self.DotPitchBG = f1_local3
	end
	local f1_local4 = nil
	if not CONDITIONS.IsSplitscreen() then
		f1_local4 = MenuBuilder.BuildRegisteredType( "nvgVignette", {
			controllerIndex = f1_local1
		} )
		f1_local4.id = "nvgVignette"
		f1_local4:SetRGBFromInt( 0, 0 )
		f1_local4:SetAlpha( 0, 0 )
		f1_local4:SetAnchorsAndPosition( 0, 0, 0, 0, 0, 0, 0, 0 )
		self:addElement( f1_local4 )
		self.nvgVignette = f1_local4
	end
	local FancyFrame = nil
	
	FancyFrame = MenuBuilder.BuildRegisteredType( "FancyFrame", {
		controllerIndex = f1_local1
	} )
	FancyFrame.id = "FancyFrame"
	FancyFrame:SetAlpha( 0, 0 )
	FancyFrame:SetAnchorsAndPosition( 0, 0, 0, 0, _1080p * 96, _1080p * -96, _1080p * 154, _1080p * -227 )
	self:addElement( FancyFrame )
	self.FancyFrame = FancyFrame
	
	local KillcamYouIndicator = nil
	
	KillcamYouIndicator = MenuBuilder.BuildRegisteredType( "KillcamYouIndicator", {
		controllerIndex = f1_local1
	} )
	KillcamYouIndicator.id = "KillcamYouIndicator"
	KillcamYouIndicator:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 837, _1080p * 925, _1080p * 216, _1080p * 238 )
	self:addElement( KillcamYouIndicator )
	self.KillcamYouIndicator = KillcamYouIndicator
	
	local KillcamPerkInfoContainer = nil
	
	KillcamPerkInfoContainer = MenuBuilder.BuildRegisteredType( "KillcamPerkInfoContainer", {
		controllerIndex = f1_local1
	} )
	KillcamPerkInfoContainer.id = "KillcamPerkInfoContainer"
	KillcamPerkInfoContainer:SetAlpha( 0, 0 )
	KillcamPerkInfoContainer:SetAnchorsAndPosition( 1, 0, 1, 0, _1080p * -460, _1080p * -60, _1080p * -322, _1080p * -222 )
	self:addElement( KillcamPerkInfoContainer )
	self.KillcamPerkInfoContainer = KillcamPerkInfoContainer
	
	local BG2 = nil
	
	BG2 = LUI.UIImage.new()
	BG2.id = "BG2"
	BG2:SetRGBFromTable( SWATCHES.Scoreboard.enemyTeam, 0 )
	BG2:SetAlpha( 0, 0 )
	BG2:Setup3SliceHorizontalImage( _1080p * 136, 0.4 )
	BG2:SetAnchorsAndPosition( 0.5, 0.5, 1, 0, 0, 0, _1080p * -148, _1080p * -44 )
	self:addElement( BG2 )
	self.BG2 = BG2
	
	local BG1 = nil
	
	BG1 = LUI.UIImage.new()
	BG1.id = "BG1"
	BG1:SetRGBFromTable( SWATCHES.HUD.enemyTeamName, 0 )
	BG1:SetAlpha( 0, 0 )
	BG1:SetPixelGridEnabled( true )
	BG1:SetPixelGridContrast( 0.5, 0 )
	BG1:SetPixelGridBlockWidth( 2, 0 )
	BG1:SetPixelGridBlockHeight( 2, 0 )
	BG1:SetPixelGridGutterWidth( 1, 0 )
	BG1:SetPixelGridGutterHeight( 1, 0 )
	BG1:setImage( RegisterMaterial( "hud_glow" ), 0 )
	BG1:Setup3SliceHorizontalImage( _1080p * 242, 0.34 )
	BG1:SetAnchorsAndPosition( 0.5, 0.5, 1, 0, 0, 0, _1080p * -211, _1080p * 20 )
	self:addElement( BG1 )
	self.BG1 = BG1
	
	local TopLine = nil
	
	TopLine = LUI.UIImage.new()
	TopLine.id = "TopLine"
	TopLine:SetRGBFromTable( SWATCHES.HUD.enemyTeamName, 0 )
	TopLine:SetAlpha( 0, 0 )
	TopLine:setImage( RegisterMaterial( "hud_glow" ), 0 )
	TopLine:Setup3SliceHorizontalImage( _1080p * 113, 0.32 )
	TopLine:SetAnchorsAndPosition( 0.5, 0.5, 0, 1, _1080p * -123, _1080p * 123, _1080p * 930, _1080p * 944 )
	self:addElement( TopLine )
	self.TopLine = TopLine
	
	local WeaponInfo = nil
	
	WeaponInfo = MenuBuilder.BuildRegisteredType( "KillcamWeaponInfo", {
		controllerIndex = f1_local1
	} )
	WeaponInfo.id = "WeaponInfo"
	WeaponInfo:SetAlpha( 0, 0 )
	WeaponInfo:SetAnchorsAndPosition( 0, 1, 1, 0, _1080p * 96, _1080p * 426, _1080p * -230, _1080p * -140 )
	self:addElement( WeaponInfo )
	self.WeaponInfo = WeaponInfo
	
	local RespawnMessage = nil
	
	RespawnMessage = MenuBuilder.BuildRegisteredType( "KillcamRespawnMessage", {
		controllerIndex = f1_local1
	} )
	RespawnMessage.id = "RespawnMessage"
	RespawnMessage:SetRGBFromTable( SWATCHES.killcam.headerText, 0 )
	RespawnMessage:SetAlpha( 0, 0 )
	RespawnMessage:SetAnchorsAndPosition( 0.5, 0.5, 1, 0, _1080p * -204, _1080p * 204, _1080p * -397, _1080p * -367 )
	self:addElement( RespawnMessage )
	self.RespawnMessage = RespawnMessage
	
	local VictimText = nil
	
	VictimText = LUI.UIStyledText.new()
	VictimText.id = "VictimText"
	VictimText:SetRGBFromTable( SWATCHES.HUD.HUDMain, 0 )
	VictimText:SetAlpha( 0, 0 )
	VictimText:setText( LocalizeIntoString( "", "CGAME/VICTIM" ), 0 )
	VictimText:SetFont( FONTS.GetFont( FONTS.MainRegular.File ) )
	VictimText:SetAlignment( LUI.Alignment.Right )
	VictimText:SetAnchorsAndPosition( 1, 0, 0, 1, _1080p * -825, _1080p * -130, _1080p * 170, _1080p * 192 )
	self:addElement( VictimText )
	self.VictimText = VictimText
	
	local teamIcon = nil
	
	teamIcon = LUI.UIImage.new()
	teamIcon.id = "teamIcon"
	teamIcon:SetAlpha( 0, 0 )
	teamIcon:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 610, _1080p * 700, _1080p * 915, _1080p * 1005 )
	self:addElement( teamIcon )
	self.teamIcon = teamIcon
	
	local CountdownTimer = nil
	
	CountdownTimer = MenuBuilder.BuildRegisteredType( "UICountdown", {
		controllerIndex = f1_local1
	} )
	CountdownTimer.id = "CountdownTimer"
	CountdownTimer:SetRGBFromTable( SWATCHES.HUD.HUDMain, 0 )
	CountdownTimer:SetAlpha( 0, 0 )
	CountdownTimer:SetFont( FONTS.GetFont( FONTS.MainRegular.File ) )
	CountdownTimer:SetAlignment( LUI.Alignment.Left )
	CountdownTimer:SetAnchorsAndPosition( 0.5, 0.5, 0.5, 0.5, _1080p * -79, _1080p * 119, _1080p * -370, _1080p * -340 )
	CountdownTimer:SubscribeToModel( DataSources.inGame.MP.killcam.countdown:GetModel( f1_local1 ), function ()
		local f13_local0 = DataSources.inGame.MP.killcam.countdown:GetValue( menu )
		if f13_local0 ~= nil then
			menu:setEndTime( f13_local0 )
		end
	end )
	self:addElement( CountdownTimer )
	self.CountdownTimer = CountdownTimer
	
	local HeaderText = nil
	
	HeaderText = LUI.UIStyledText.new()
	HeaderText.id = "HeaderText"
	HeaderText:SetRGBFromTable( SWATCHES.killcam.headerText, 0 )
	HeaderText:SetAlpha( 0, 0 )
	HeaderText:setText( Engine.CBBHFCGDIC( "LUA_MENU/KILLCAM_CAPS" ), 0 )
	HeaderText:SetFont( FONTS.GetFont( FONTS.MainRegular.File ) )
	HeaderText:SetWordWrap( false )
	HeaderText:SetAlignment( LUI.Alignment.Left )
	HeaderText:SetOptOutRightToLeftAlignmentFlip( true )
	HeaderText:SetDecodeLetterLength( 50 )
	HeaderText:SetDecodeMaxRandChars( 15 )
	HeaderText:SetDecodeUpdatesPerLetter( 5 )
	HeaderText:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 64, _1080p * 612, _1080p * 54, _1080p * 114 )
	self:addElement( HeaderText )
	self.HeaderText = HeaderText
	
	local ReplayText = nil
	
	ReplayText = LUI.UIStyledText.new()
	ReplayText.id = "ReplayText"
	ReplayText:SetRGBFromTable( SWATCHES.HUD.enemyTeamName, 0 )
	ReplayText:SetAlpha( 0, 0 )
	ReplayText:setText( ToUpperCase( Engine.CBBHFCGDIC( "LUA_MENU/REPLAY" ) ), 0 )
	ReplayText:SetFont( FONTS.GetFont( FONTS.MainRegular.File ) )
	ReplayText:SetWordWrap( false )
	ReplayText:SetAlignment( LUI.Alignment.Left )
	ReplayText:SetOptOutRightToLeftAlignmentFlip( true )
	ReplayText:SetShadowMinDistance( -0.6, 0 )
	ReplayText:SetShadowMaxDistance( 0.6, 0 )
	ReplayText:SetShadowRGBFromTable( SWATCHES.HUD.enemyTeamName, 0 )
	ReplayText:SetDecodeLetterLength( 50 )
	ReplayText:SetDecodeMaxRandChars( 15 )
	ReplayText:SetDecodeUpdatesPerLetter( 5 )
	ReplayText:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 137, _1080p * 837, _1080p * 170, _1080p * 200 )
	self:addElement( ReplayText )
	self.ReplayText = ReplayText
	
	local ReplayBox = nil
	
	ReplayBox = LUI.UIImage.new()
	ReplayBox.id = "ReplayBox"
	ReplayBox:SetRGBFromTable( SWATCHES.HUD.enemyTeamName, 0 )
	ReplayBox:SetAlpha( 0, 0 )
	ReplayBox:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 118, _1080p * 124, _1080p * 185, _1080p * 191 )
	self:addElement( ReplayBox )
	self.ReplayBox = ReplayBox
	
	local FrameBlock1 = nil
	
	FrameBlock1 = LUI.UIImage.new()
	FrameBlock1.id = "FrameBlock1"
	FrameBlock1:SetRGBFromTable( SWATCHES.HUD.HUDMain, 0 )
	FrameBlock1:SetAlpha( 0, 0 )
	FrameBlock1:SetAnchorsAndPosition( 0, 0, 0, 1, _1080p * 251, _1080p * -60, _1080p * 114, _1080p * 124 )
	self:addElement( FrameBlock1 )
	self.FrameBlock1 = FrameBlock1
	
	local FrameBlock2 = nil
	
	FrameBlock2 = LUI.UIImage.new()
	FrameBlock2.id = "FrameBlock2"
	FrameBlock2:SetRGBFromTable( SWATCHES.HUD.HUDMain, 0 )
	FrameBlock2:SetAlpha( 0, 0 )
	FrameBlock2:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 147, _1080p * 247, _1080p * 114, _1080p * 124 )
	self:addElement( FrameBlock2 )
	self.FrameBlock2 = FrameBlock2
	
	local FrameBlock3 = nil
	
	FrameBlock3 = LUI.UIImage.new()
	FrameBlock3.id = "FrameBlock3"
	FrameBlock3:SetRGBFromTable( SWATCHES.HUD.HUDMain, 0 )
	FrameBlock3:SetAlpha( 0, 0 )
	FrameBlock3:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 64, _1080p * 89, _1080p * 114, _1080p * 124 )
	self:addElement( FrameBlock3 )
	self.FrameBlock3 = FrameBlock3
	
	local FrameBlock4 = nil
	
	FrameBlock4 = LUI.UIImage.new()
	FrameBlock4.id = "FrameBlock4"
	FrameBlock4:SetRGBFromTable( SWATCHES.HUD.HUDMain, 0 )
	FrameBlock4:SetAlpha( 0, 0 )
	FrameBlock4:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 93, _1080p * 143, _1080p * 114, _1080p * 124 )
	self:addElement( FrameBlock4 )
	self.FrameBlock4 = FrameBlock4
	
	local f1_local23 = nil
	if not CONDITIONS.IsSplitscreen() then
		f1_local23 = LUI.UIImage.new()
		f1_local23.id = "RightLine"
		f1_local23:SetRGBFromTable( SWATCHES.HUD.HUDMain, 0 )
		f1_local23:SetAlpha( 0, 0 )
		f1_local23:SetAnchorsAndPosition( 1, 0, 0, 1, _1080p * -175, _1080p * -47, _1080p * 495, _1080p * 497 )
		self:addElement( f1_local23 )
		self.RightLine = f1_local23
	end
	local f1_local24 = nil
	if not CONDITIONS.IsSplitscreen() then
		f1_local24 = LUI.UIImage.new()
		f1_local24.id = "LeftLine"
		f1_local24:SetRGBFromTable( SWATCHES.HUD.HUDMain, 0 )
		f1_local24:SetAlpha( 0, 0 )
		f1_local24:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 54, _1080p * 182, _1080p * 495, _1080p * 497 )
		self:addElement( f1_local24 )
		self.LeftLine = f1_local24
	end
	local VictimTextMask = nil
	
	VictimTextMask = LUI.UIImage.new()
	VictimTextMask.id = "VictimTextMask"
	VictimTextMask:SetAlpha( 0, 0 )
	VictimTextMask:setImage( RegisterMaterial( "stencil_mask" ), 0 )
	VictimTextMask:SetAnchorsAndPosition( 1, 0, 0, 1, _1080p * -864, 0, _1080p * 154, _1080p * 216 )
	self:addElement( VictimTextMask )
	self.VictimTextMask = VictimTextMask
	
	local f1_local26 = nil
	if CONDITIONS.IsCoreMultiplayerNotBr() then
		f1_local26 = MenuBuilder.BuildRegisteredType( "SmallPlayerCard", {
			controllerIndex = f1_local1
		} )
		f1_local26.id = "PlayerCard"
		f1_local26:SetAlpha( 0, 0 )
		if CONDITIONS.IsCoreMultiplayerNotBr() then
			f1_local26:SetDataSource( DataSources.inGame.MP.killcam.killedby.playerCard, f1_local1 )
		end
		f1_local26:SetAnchorsAndPosition( 0.5, 0.5, 1, 0, _1080p * -260, _1080p * 260, _1080p * -182, _1080p * -58 )
		self:addElement( f1_local26 )
		self.PlayerCard = f1_local26
	end
	local f1_local27 = nil
	if not CONDITIONS.IsCoreMultiplayerNotBr() then
		f1_local27 = MenuBuilder.BuildRegisteredType( "WZSmallPlayerCard", {
			controllerIndex = f1_local1
		} )
		f1_local27.id = "WZSmallPlayerCard"
		f1_local27:SetAlpha( 0, 0 )
		if not CONDITIONS.IsCoreMultiplayerNotBr() then
			f1_local27:SetDataSource( DataSources.inGame.MP.killcam.killedby.playerCard, f1_local1 )
		end
		f1_local27:SetAnchorsAndPosition( 0.5, 0.5, 1, 0, _1080p * -260, _1080p * 260, _1080p * -182, _1080p * -58 )
		self:addElement( f1_local27 )
		self.WZSmallPlayerCard = f1_local27
	end
	local ReportButton = nil
	
	ReportButton = LUI.UIStyledText.new()
	ReportButton.id = "ReportButton"
	ReportButton:SetRGBFromTable( SWATCHES.genericButton.description, 0 )
	ReportButton:SetAlpha( 0, 0 )
	ReportButton:setText( Engine.CBBHFCGDIC( "MENU/REPORT_PLAYER_PROMPT" ), 0 )
	ReportButton:SetFont( FONTS.GetFont( FONTS.MainRegular.File ) )
	ReportButton:SetWordWrap( false )
	ReportButton:SetAlignment( LUI.Alignment.Center )
	ReportButton:SetVerticalAlignment( LUI.Alignment.Center )
	ReportButton:SetTintFontIcons( true )
	ReportButton:SetAnchorsAndPosition( 0.5, 0.5, 1, 0, _1080p * -250, _1080p * 250, _1080p * -48, _1080p * -24 )
	self:addElement( ReportButton )
	self.ReportButton = ReportButton
	
	local f1_local29 = nil
	if not CONDITIONS.IsSplitscreen() then
		f1_local29 = LUI.UIImage.new()
		f1_local29.id = "Darkener"
		f1_local29:SetRGBFromInt( 0, 0 )
		f1_local29:SetAlpha( 0, 0 )
		self:addElement( f1_local29 )
		self.Darkener = f1_local29
	end
	local DeadsilenceIcon = nil
	
	DeadsilenceIcon = LUI.UIImage.new()
	DeadsilenceIcon.id = "DeadsilenceIcon"
	DeadsilenceIcon:SetAlpha( 0, 0 )
	DeadsilenceIcon:setImage( RegisterMaterial( "hud_icon_fieldupgrade_deadsilence" ), 0 )
	DeadsilenceIcon:SetAnchorsAndPosition( 0, 1, 1, 0, _1080p * 137, _1080p * 187, _1080p * -309, _1080p * -259 )
	self:addElement( DeadsilenceIcon )
	self.DeadsilenceIcon = DeadsilenceIcon
	
	local StoppingPowerIcon = nil
	
	StoppingPowerIcon = LUI.UIImage.new()
	StoppingPowerIcon.id = "StoppingPowerIcon"
	StoppingPowerIcon:SetAlpha( 0, 0 )
	StoppingPowerIcon:setImage( RegisterMaterial( "hud_icon_fieldupgrade_stopping_power" ), 0 )
	StoppingPowerIcon:SetAnchorsAndPosition( 0, 1, 1, 0, _1080p * 201, _1080p * 251, _1080p * -309, _1080p * -259 )
	self:addElement( StoppingPowerIcon )
	self.StoppingPowerIcon = StoppingPowerIcon
	
	local f1_local32 = nil
	if CONDITIONS.IsMagmaGameMode() then
		f1_local32 = MenuBuilder.BuildRegisteredType( "BRHealthAndArmorBarsKillCam", {
			controllerIndex = f1_local1
		} )
		f1_local32.id = "BRHealthAndArmorBarsKillCam"
		f1_local32:SetAlpha( 0, 0 )
		f1_local32:SetScale( -0.15, 0 )
		f1_local32:SetAnchorsAndPosition( 0.5, 0.5, 1, 0, _1080p * -220, _1080p * 220, _1080p * -277, _1080p * -227 )
		self:addElement( f1_local32 )
		self.BRHealthAndArmorBarsKillCam = f1_local32
	end
	local KilledByText = nil
	
	KilledByText = LUI.UIStyledText.new()
	KilledByText.id = "KilledByText"
	KilledByText:SetRGBFromTable( SWATCHES.HUD.HUDMain, 0 )
	KilledByText:SetAlpha( 0, 0 )
	KilledByText:setText( Engine.CBBHFCGDIC( "MP/KILLED_BY" ), 0 )
	KilledByText:SetFont( FONTS.GetFont( FONTS.MainRegular.File ) )
	KilledByText:SetAlignment( LUI.Alignment.Center )
	KilledByText:SetAnchorsAndPosition( 0.5, 0.5, 1, 0, _1080p * -225, _1080p * 225, _1080p * -220, _1080p * -190 )
	self:addElement( KilledByText )
	self.KilledByText = KilledByText
	
	local WhiteFlash = nil
	
	WhiteFlash = LUI.UIImage.new()
	WhiteFlash.id = "WhiteFlash"
	WhiteFlash:SetAlpha( 0, 0 )
	WhiteFlash:SetAnchorsAndPosition( 0.5, 0.5, 0.5, 0.5, _1080p * 20, _1080p * 20, _1080p * -26, _1080p * -26 )
	self:addElement( WhiteFlash )
	self.WhiteFlash = WhiteFlash
	
	self._sequences.DefaultSequence = function ()
		
	end
	
	self._sequences.LocalPlay = function ()
		
	end
	
	self._sequences.KilledByGun = function ()
		
	end
	
	self._sequences.KilledByOther = function ()
		
	end
	
	local f1_local35 = nil
	if not CONDITIONS.IsSplitscreen() then
		f1_local3:RegisterAnimationSequence( "PlayOfTheGame", {
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.Left,
				value = _1080p * 57
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.Top,
				value = _1080p * 87
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.Right,
				value = _1080p * -57
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.Bottom,
				value = _1080p * -85
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.RGB,
				value = SWATCHES.Global.keyColorDark
			},
			{
				value = 2,
				duration = 0,
				property = TWEEN_PROPERTY.Pixel_Grid_Block_Height
			},
			{
				value = 2,
				duration = 0,
				property = TWEEN_PROPERTY.Pixel_Grid_Block_Width
			},
			{
				value = 0,
				duration = 1800,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = -2.3534382788928255E-185,
				duration = 200,
				property = TWEEN_PROPERTY.Alpha
			}
		} )
	end
	if not CONDITIONS.IsSplitscreen() then
		f1_local4:RegisterAnimationSequence( "PlayOfTheGame", {
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = 4.667261642226141E-62,
				duration = 300,
				property = TWEEN_PROPERTY.Alpha
			}
		} )
	end
	FancyFrame:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 5.29462817E-315,
			duration = 0,
			property = TWEEN_PROPERTY.Left_Anchor
		},
		{
			value = 5.29462817E-315,
			duration = 0,
			property = TWEEN_PROPERTY.Right_Anchor
		},
		{
			value = 5.29462817E-315,
			duration = 0,
			property = TWEEN_PROPERTY.Top_Anchor
		},
		{
			value = 5.29462817E-315,
			duration = 0,
			property = TWEEN_PROPERTY.Bottom_Anchor
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * -905
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Top,
			value = _1080p * -455
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 905
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Bottom,
			value = _1080p * 457
		}
	} )
	KillcamPerkInfoContainer:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	BG2:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	BG1:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	TopLine:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	WeaponInfo:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	RespawnMessage:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	VictimText:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	teamIcon:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	CountdownTimer:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	HeaderText:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	ReplayText:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	ReplayBox:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	FrameBlock1:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	FrameBlock2:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	FrameBlock3:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	FrameBlock4:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	if not CONDITIONS.IsSplitscreen() then
		f1_local23:RegisterAnimationSequence( "PlayOfTheGame", {
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			}
		} )
	end
	if not CONDITIONS.IsSplitscreen() then
		f1_local24:RegisterAnimationSequence( "PlayOfTheGame", {
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			}
		} )
	end
	VictimTextMask:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	if CONDITIONS.IsCoreMultiplayerNotBr() then
		f1_local26:RegisterAnimationSequence( "PlayOfTheGame", {
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Scale
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.Left,
				value = _1080p * -882
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.Top,
				value = _1080p * -876
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.Right,
				value = _1080p * -362
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.Bottom,
				value = _1080p * -752
			},
			{
				value = 0,
				duration = 2800,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = 1,
				duration = 200,
				property = TWEEN_PROPERTY.Alpha
			}
		} )
	end
	if not CONDITIONS.IsCoreMultiplayerNotBr() then
		f1_local27:RegisterAnimationSequence( "PlayOfTheGame", {
			{
				duration = 0,
				property = TWEEN_PROPERTY.Left,
				value = _1080p * -882
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.Right,
				value = _1080p * -362
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.Top,
				value = _1080p * -876
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.Bottom,
				value = _1080p * -752
			},
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Scale
			},
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = 0,
				duration = 2800,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = 1,
				duration = 200,
				property = TWEEN_PROPERTY.Alpha
			}
		} )
	end
	if not CONDITIONS.IsSplitscreen() then
		f1_local29:RegisterAnimationSequence( "PlayOfTheGame", {
			{
				value = -2.3534382788928255E-185,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Top_Anchor
			},
			{
				value = 1,
				duration = 0,
				property = TWEEN_PROPERTY.Bottom_Anchor
			},
			{
				value = 0,
				duration = -28,
				property = TWEEN_PROPERTY.Top_Anchor,
				easing = LUI.EASING.inOutQuadratic
			},
			{
				value = 0,
				duration = -28,
				property = TWEEN_PROPERTY.Bottom_Anchor,
				easing = LUI.EASING.inOutQuadratic
			}
		} )
	end
	KilledByText:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	WhiteFlash:RegisterAnimationSequence( "PlayOfTheGame", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.PlayOfTheGame = function ()
		if not CONDITIONS.IsSplitscreen() then
			menu:AnimateSequence( "PlayOfTheGame" )
		end
		if not CONDITIONS.IsSplitscreen() then
			menu:AnimateSequence( "PlayOfTheGame" )
		end
		menu:AnimateSequence( "PlayOfTheGame" )
		menu:AnimateSequence( "PlayOfTheGame" )
		menu:AnimateSequence( "PlayOfTheGame" )
		menu:AnimateSequence( "PlayOfTheGame" )
		menu:AnimateSequence( "PlayOfTheGame" )
		menu:AnimateSequence( "PlayOfTheGame" )
		menu:AnimateSequence( "PlayOfTheGame" )
		menu:AnimateSequence( "PlayOfTheGame" )
		menu:AnimateSequence( "PlayOfTheGame" )
		menu:AnimateSequence( "PlayOfTheGame" )
		menu:AnimateSequence( "PlayOfTheGame" )
		menu:AnimateSequence( "PlayOfTheGame" )
		menu:AnimateSequence( "PlayOfTheGame" )
		menu:AnimateSequence( "PlayOfTheGame" )
		menu:AnimateSequence( "PlayOfTheGame" )
		menu:AnimateSequence( "PlayOfTheGame" )
		menu:AnimateSequence( "PlayOfTheGame" )
		if not CONDITIONS.IsSplitscreen() then
			menu:AnimateSequence( "PlayOfTheGame" )
		end
		if not CONDITIONS.IsSplitscreen() then
			menu:AnimateSequence( "PlayOfTheGame" )
		end
		menu:AnimateSequence( "PlayOfTheGame" )
		if CONDITIONS.IsCoreMultiplayerNotBr() then
			menu:AnimateSequence( "PlayOfTheGame" )
		end
		if not CONDITIONS.IsCoreMultiplayerNotBr() then
			menu:AnimateSequence( "PlayOfTheGame" )
		end
		if not CONDITIONS.IsSplitscreen() then
			menu:AnimateSequence( "PlayOfTheGame" )
		end
		menu:AnimateSequence( "PlayOfTheGame" )
		menu:AnimateSequence( "PlayOfTheGame" )
	end
	
	self._sequences.OnlinePlay = function ()
		
	end
	
	local f1_local36 = nil
	if not CONDITIONS.IsSplitscreen() then
		f1_local3:RegisterAnimationSequence( "Boot", {
			{
				value = -2.3534382792352958E-185,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = 7622222,
				duration = 0,
				property = TWEEN_PROPERTY.RGB
			},
			{
				value = 2,
				duration = 0,
				property = TWEEN_PROPERTY.Pixel_Grid_Block_Width
			},
			{
				value = 2,
				duration = 0,
				property = TWEEN_PROPERTY.Pixel_Grid_Block_Height
			},
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Left
			},
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Right
			},
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Top
			},
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Bottom
			}
		} )
	end
	if not CONDITIONS.IsSplitscreen() then
		f1_local4:RegisterAnimationSequence( "Boot", {
			{
				value = 1,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			}
		} )
	end
	FancyFrame:RegisterAnimationSequence( "Boot", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Top,
			value = _1080p * 430
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * -850
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * 850
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Bottom,
			value = _1080p * -430
		},
		{
			duration = 300,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * 96
		},
		{
			duration = 300,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * -96
		},
		{
			duration = 300,
			property = TWEEN_PROPERTY.Top,
			value = _1080p * 154
		},
		{
			duration = 300,
			property = TWEEN_PROPERTY.Bottom,
			value = _1080p * -230
		},
		{
			value = 1,
			duration = 300,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	KillcamPerkInfoContainer:RegisterAnimationSequence( "Boot", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 700,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 300,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	BG2:RegisterAnimationSequence( "Boot", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			duration = 600,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * -70
		},
		{
			duration = 600,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 70
		},
		{
			value = 0,
			duration = 640,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			duration = 400,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * -830
		},
		{
			duration = 400,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 830
		},
		{
			value = 4.667261642226141E-62,
			duration = 60,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 300,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	BG1:RegisterAnimationSequence( "Boot", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			duration = 600,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * -70
		},
		{
			duration = 600,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 70
		},
		{
			value = 0,
			duration = 620,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			duration = 400,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * -830
		},
		{
			duration = 400,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 830
		},
		{
			value = 4.667261642226141E-62,
			duration = -48,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 300,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	TopLine:RegisterAnimationSequence( "Boot", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			duration = 600,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * -123
		},
		{
			duration = 600,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 123
		},
		{
			value = 0,
			duration = 620,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			duration = 400,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * -953
		},
		{
			duration = 400,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 953
		},
		{
			value = 4.667261642226141E-62,
			duration = -48,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 300,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	WeaponInfo:RegisterAnimationSequence( "Boot", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 700,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 300,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	VictimText:RegisterAnimationSequence( "Boot", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 800,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 40,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.snap
		},
		{
			value = 1,
			duration = 40,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.snap
		},
		{
			value = 0,
			duration = 40,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.snap
		},
		{
			value = 1,
			duration = 40,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.snap
		},
		{
			value = 0,
			duration = 40,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.snap
		},
		{
			value = 1,
			duration = 40,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.snap
		}
	} )
	HeaderText:RegisterAnimationSequence( "Boot", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	ReplayText:RegisterAnimationSequence( "Boot", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	ReplayBox:RegisterAnimationSequence( "Boot", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	FrameBlock1:RegisterAnimationSequence( "Boot", {
		{
			value = -2.3534382792352958E-185,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	FrameBlock2:RegisterAnimationSequence( "Boot", {
		{
			value = -2.3534382792352958E-185,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	FrameBlock3:RegisterAnimationSequence( "Boot", {
		{
			value = -2.3534382792352958E-185,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	FrameBlock4:RegisterAnimationSequence( "Boot", {
		{
			value = -2.3534382792352958E-185,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	if not CONDITIONS.IsSplitscreen() then
		f1_local23:RegisterAnimationSequence( "Boot", {
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = 0,
				duration = 600,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = -2.3534382792352958E-185,
				duration = 200,
				property = TWEEN_PROPERTY.Alpha
			}
		} )
	end
	if not CONDITIONS.IsSplitscreen() then
		f1_local24:RegisterAnimationSequence( "Boot", {
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = 0,
				duration = 600,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = -2.3534382792352958E-185,
				duration = 200,
				property = TWEEN_PROPERTY.Alpha
			}
		} )
	end
	VictimTextMask:RegisterAnimationSequence( "Boot", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * -864
		},
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			duration = 540,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * -864
		},
		{
			value = 0,
			duration = 260,
			property = TWEEN_PROPERTY.Right
		}
	} )
	if CONDITIONS.IsCoreMultiplayerNotBr() then
		f1_local26:RegisterAnimationSequence( "Boot", {
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = 1,
				duration = 0,
				property = TWEEN_PROPERTY.Scale
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.Left,
				value = _1080p * -260
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.Right,
				value = _1080p * 260
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.Top,
				value = _1080p * -182
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.Bottom,
				value = _1080p * -58
			},
			{
				value = 0,
				duration = 600,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = 1,
				duration = 600,
				property = TWEEN_PROPERTY.Scale
			},
			{
				value = 1,
				duration = -48,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = 0,
				duration = 200,
				property = TWEEN_PROPERTY.Scale,
				easing = LUI.EASING.outQuadratic
			}
		} )
	end
	if not CONDITIONS.IsCoreMultiplayerNotBr() then
		f1_local27:RegisterAnimationSequence( "Boot", {
			{
				value = 1,
				duration = 0,
				property = TWEEN_PROPERTY.Scale
			},
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.Left,
				value = _1080p * -260
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.Right,
				value = _1080p * 260
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.Top,
				value = _1080p * -182
			},
			{
				duration = 0,
				property = TWEEN_PROPERTY.Bottom,
				value = _1080p * -58
			},
			{
				value = 1,
				duration = 600,
				property = TWEEN_PROPERTY.Scale
			},
			{
				value = 0,
				duration = 600,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = 1,
				duration = -48,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = 0,
				duration = 200,
				property = TWEEN_PROPERTY.Scale,
				easing = LUI.EASING.outQuadratic
			}
		} )
	end
	if not CONDITIONS.IsSplitscreen() then
		f1_local29:RegisterAnimationSequence( "Boot", {
			{
				value = 1,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Top_Anchor
			},
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Bottom_Anchor
			},
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Bottom
			},
			{
				value = 1,
				duration = 140,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = 1,
				duration = -48,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				value = 0,
				duration = 180,
				property = TWEEN_PROPERTY.Alpha
			}
		} )
	end
	if CONDITIONS.IsMagmaGameMode() then
		f1_local32:RegisterAnimationSequence( "Boot", {
			{
				value = 1,
				duration = 1040,
				property = TWEEN_PROPERTY.Alpha
			}
		} )
	end
	KilledByText:RegisterAnimationSequence( "Boot", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 580,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 420,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	WhiteFlash:RegisterAnimationSequence( "Boot", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * -3
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Top,
			value = _1080p * 55
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 3
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Bottom,
			value = _1080p * 61
		},
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			duration = 220,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * -960,
			easing = LUI.EASING.inQuadratic
		},
		{
			duration = 220,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 960,
			easing = LUI.EASING.inQuadratic
		},
		{
			duration = 220,
			property = TWEEN_PROPERTY.Top,
			value = _1080p * 55
		},
		{
			duration = 220,
			property = TWEEN_PROPERTY.Bottom,
			value = _1080p * 61
		},
		{
			value = 1,
			duration = 220,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			duration = 180,
			property = TWEEN_PROPERTY.Top,
			value = _1080p * -592
		},
		{
			duration = 180,
			property = TWEEN_PROPERTY.Bottom,
			value = _1080p * 656
		},
		{
			value = 0,
			duration = 180,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.outQuadratic
		}
	} )
	self._sequences.Boot = function ()
		if not CONDITIONS.IsSplitscreen() then
			menu:AnimateSequence( "Boot" )
		end
		if not CONDITIONS.IsSplitscreen() then
			menu:AnimateSequence( "Boot" )
		end
		menu:AnimateSequence( "Boot" )
		menu:AnimateSequence( "Boot" )
		menu:AnimateSequence( "Boot" )
		menu:AnimateSequence( "Boot" )
		menu:AnimateSequence( "Boot" )
		menu:AnimateSequence( "Boot" )
		menu:AnimateSequence( "Boot" )
		menu:AnimateSequence( "Boot" )
		menu:AnimateSequence( "Boot" )
		menu:AnimateSequence( "Boot" )
		menu:AnimateSequence( "Boot" )
		menu:AnimateSequence( "Boot" )
		menu:AnimateSequence( "Boot" )
		menu:AnimateSequence( "Boot" )
		if not CONDITIONS.IsSplitscreen() then
			menu:AnimateSequence( "Boot" )
		end
		if not CONDITIONS.IsSplitscreen() then
			menu:AnimateSequence( "Boot" )
		end
		menu:AnimateSequence( "Boot" )
		if CONDITIONS.IsCoreMultiplayerNotBr() then
			menu:AnimateSequence( "Boot" )
		end
		if not CONDITIONS.IsCoreMultiplayerNotBr() then
			menu:AnimateSequence( "Boot" )
		end
		if not CONDITIONS.IsSplitscreen() then
			menu:AnimateSequence( "Boot" )
		end
		if CONDITIONS.IsMagmaGameMode() then
			menu:AnimateSequence( "Boot" )
		end
		menu:AnimateSequence( "Boot" )
		menu:AnimateSequence( "Boot" )
	end
	
	local f1_local37 = nil
	ReplayText:RegisterAnimationSequence( "LoopReplay", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	ReplayBox:RegisterAnimationSequence( "LoopReplay", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.LoopReplay = function ()
		menu:AnimateLoop( "LoopReplay" )
		menu:AnimateLoop( "LoopReplay" )
	end
	
	local f1_local38 = nil
	teamIcon:RegisterAnimationSequence( "TeamIconOn", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 700,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 300,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.TeamIconOn = function ()
		menu:AnimateSequence( "TeamIconOn" )
	end
	
	local f1_local39 = nil
	teamIcon:RegisterAnimationSequence( "TeamIconOff", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.TeamIconOff = function ()
		menu:AnimateSequence( "TeamIconOff" )
	end
	
	local f1_local40 = nil
	RespawnMessage:RegisterAnimationSequence( "SplitScreen", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Top,
			value = _1080p * -241
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Bottom,
			value = _1080p * -211
		}
	} )
	self._sequences.SplitScreen = function ()
		menu:AnimateSequence( "SplitScreen" )
	end
	
	if CONDITIONS.IsCoreMultiplayerNotBr() then
		f1_local26:SetDataSource( DataSources.inGame.MP.killcam.killedby.playerCard, f1_local1 )
	end
	if not CONDITIONS.IsCoreMultiplayerNotBr() then
		f1_local27:SetDataSource( DataSources.inGame.MP.killcam.killedby.playerCard, f1_local1 )
	end
	f0_local0( self, f1_local1, controller )
	if CONDITIONS.IsPublicMatch() then
		ACTIONS.AnimateSequence( self, "OnlinePlay" )
	end
	if not CONDITIONS.IsPublicMatch() then
		ACTIONS.AnimateSequence( self, "LocalPlay" )
	end
	if CONDITIONS.IsSplitscreen() then
		ACTIONS.AnimateSequence( self, "SplitScreen" )
	end
	return self
end

MenuBuilder.registerType( "Killcam", Killcam )
LockTable( _M )
