-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 13-07-2025 21:51
module( ..., package.seeall )
local f0_local0 = function ( f14_arg0, f14_arg1 )
	local f14_local0 = f14_arg0._playerData
	local f14_local1 = f14_local0.xuid
	local f14_local2 = f14_local0.platformId
	local f14_local3 = f14_local0.isCrossplayPlayer
	if type( f14_local1 ) ~= "userdata" then
		f14_local1 = Friends.CAIJHBHGGC( f14_local1 )
	end
	if Engine.BAHIIBFDDG() or Engine.BEFACAIFDD() or not Lobby.CHBBHFHJEH( f14_local1 ) then
		LUI.FlowManager.RequestPopupMenu( nil, "LobbyMemberActions", true, f14_arg1, false, {
			isWZPrivateMatch = true,
			xuid = f14_local1,
			platformId = f14_local2,
			isCrossplayPlayer = f14_local3
		} )
	end
end

local f0_local1 = function ( f13_arg0, f13_arg1, f13_arg2 )
	local f13_local0
	if type( f13_arg2 ) == "table" then
		f13_local0 = f13_arg2.enableButtonAction
	else
		f13_local0 = false
	end
	f13_arg0._enableButtonAction = f13_local0
	f13_arg0._playerData = f13_arg2
	if f13_arg2 and type( f13_arg2 ) == "number" then
		f13_local0 = f13_arg2
		f13_arg0.TeamIndex:setText( f13_local0 )
		f13_arg0.TeamIndex:SetAlpha( 1 )
		if SWATCHES.BRSquad["player" .. f13_local0] then
			f13_arg0.TeamIndex:SetRGBFromTable( SWATCHES.BRSquad["player" .. f13_local0] )
		end
		f13_arg0.Gamertag:setText( Engine.CBBHFCGDIC( "LUA_MENU_MP/AVAILABLE_SLOT" ) )
		f13_arg0.Gamertag:SetRGBFromTable( SWATCHES.genericButton.listButtonDefault )
		ACTIONS.AnimateSequence( f13_arg0, "Empty" )
		return 
	end
	ACTIONS.AnimateSequence( f13_arg0, "Available" )
	if f13_arg2.isLobbyHost then
		f13_arg0.HostIcon:SetAlpha( 1 )
		f13_arg0.TeamIndex:SetAlpha( 0 )
	else
		f13_arg0.HostIcon:SetAlpha( 0 )
		f13_arg0.TeamIndex:SetAlpha( 1 )
	end
	f13_arg0.TeamIndex:setText( f13_arg2.index )
	local f13_local1 = PROGRESSION.GetPlayerProgressionData( {
		_combinedRankNum = tonumber( f13_arg2.rank ) or 0,
		_prestigeLevel = PROGRESSION.ValidatePrestigeLevel( tonumber( f13_arg2.prestige ) or 0, {
			_isBackendPrestigeLevel = true
		} )
	} )
	local f13_local2 = f13_local1._rank
	local f13_local3 = f13_local1._rankDisplay
	local f13_local4 = f13_local1._rankIcon
	f13_arg0.Rank:setText( f13_local3 )
	f13_arg0.RankIcon:setImage( RegisterMaterial( f13_local4 ) )
	f13_arg0.ClanTag:setText( f13_arg2.clanTag )
	local f13_local5 = f13_arg2.microphoneState
	local f13_local6 = Mic.GetIcon( f13_local5 )
	f13_arg0.MicIcon:SetAlpha( Mic.GetIconAlpha( f13_local5 ) )
	f13_arg0.MicIcon:setImage( RegisterMaterial( f13_local6 ) )
	local f13_local7 = f13_arg2.gamertag
	local f13_local8 = f13_arg2.gamertagWithHash
	local f13_local9
	if f13_local8 then
		f13_local9 = f13_local8
	elseif 0 < #f13_local8 then
		f13_local9 = CONDITIONS.IsDisplayNameTag()
		if f13_local9 then
			f13_local9 = Engine.DDHAAEGIEI( f13_arg1 )
		end
	else
		f13_local9 = false
	end
	if f13_local9 then
		f13_local7 = f13_local8
	end
	if f13_local7 then
		f13_arg0.Gamertag:setText( f13_local7 )
	end
	if f13_arg2.isUsingGamePad then
		f13_arg0.InputMethod:setImage( f13_arg0._GPDImg )
	else
		f13_arg0.InputMethod:setImage( f13_arg0._KBMImg )
	end
	f13_arg0.SocialPlatformPresence:SetPlatformPresence( ClientPlatformToPresencePlatform[f13_arg2.platform] )
	if f13_arg2.isMyPlayer then
		f13_arg0.Gamertag:SetRGBFromTable( SWATCHES.Scoreboard.highlight )
		f13_arg0.ClanTag:SetRGBFromTable( SWATCHES.Scoreboard.highlight )
		f13_arg0.Rank:SetRGBFromTable( SWATCHES.Scoreboard.highlight )
		f13_arg0.HostIcon:SetRGBFromTable( SWATCHES.Scoreboard.highlight )
	else
		f13_arg0.Gamertag:SetRGBFromTable( SWATCHES.genericButton.listButtonDefault )
		f13_arg0.ClanTag:SetRGBFromTable( SWATCHES.genericButton.listButtonDefault )
		f13_arg0.Rank:SetRGBFromTable( SWATCHES.genericButton.listButtonDefault )
		f13_arg0.HostIcon:SetRGBFromTable( SWATCHES.genericButton.listButtonDefault )
	end
	if f13_arg0._onFocused and f13_arg0:getParent() then
		local f13_local10 = f13_arg0:getParent()
		if f13_local10:getParent() then
			f13_local10 = f13_arg0:getParent()
			f13_local10 = f13_local10:getParent()
			f13_local10:processEvent( {
				name = "wz_private_match_player_on_focus",
				playerData = f13_arg0._playerData
			} )
		end
	end
end

local f0_local2 = function ( f9_arg0, f9_arg1 )
	f9_arg0:addEventHandler( "button_over", function ( f12_arg0, f12_arg1 )
		if f9_arg0._enableButtonAction then
			f9_arg0._onFocused = true
			local f12_local0 = f12_arg1.controller or f9_arg0
			ACTIONS.AnimateSequence( f9_arg0, "ButtonOver" )
			if f9_arg0:getParent() then
				local f12_local1 = f9_arg0:getParent()
				if f12_local1:getParent() then
					f12_local1 = f9_arg0:getParent()
					f12_local1 = f12_local1:getParent()
					f12_local1:processEvent( {
						name = "wz_private_match_player_on_focus",
						playerData = f12_arg0._playerData
					} )
				end
			end
		end
	end )
	f9_arg0:addEventHandler( "button_up", function ( f11_arg0, f11_arg1 )
		if f9_arg0._enableButtonAction then
			f9_arg0._onFocused = false
			local f11_local0 = f11_arg1.controller or f9_arg0
			ACTIONS.AnimateSequence( f9_arg0, "ButtonUp" )
		end
	end )
	f9_arg0:addEventHandler( "button_action", function ( f10_arg0, f10_arg1 )
		if f9_arg0._enableButtonAction then
			f9_arg0( f10_arg0, f10_arg1.controller or f9_arg0 )
		end
	end )
end

local f0_local3 = function ( f8_arg0, f8_arg1, f8_arg2 )
	f8_arg0._GPDImg = RegisterMaterial( "icon_platform_controller" )
	f8_arg0._KBMImg = RegisterMaterial( "icon_platform_mousekeyboard" )
	f8_arg0.SetupSquadMember = f0_local0
	f0_local0( f8_arg0, f8_arg1 )
end

function WarzonePrivateMatchSquadTeamMember( menu, controller )
	local self = LUI.UIButton.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 450 * _1080p, 0, 38 * _1080p )
	self.id = "WarzonePrivateMatchSquadTeamMember"
	self._animationSets = self._animationSets or {}
	self._sequences = self._sequences or {}
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine.DDJFBBJAIG() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1 )
	local f1_local2 = self
	local TextBacker = nil
	
	TextBacker = LUI.UIImage.new()
	TextBacker.id = "TextBacker"
	TextBacker:SetRGBFromTable( SWATCHES.genericButton.background, 0 )
	TextBacker:SetAlpha( 0.2, 0 )
	self:addElement( TextBacker )
	self.TextBacker = TextBacker
	
	local MicIcon = nil
	
	MicIcon = LUI.UIImage.new()
	MicIcon.id = "MicIcon"
	MicIcon:SetRGBFromTable( SWATCHES.text.primaryText, 0 )
	MicIcon:SetAnchorsAndPosition( 1, 0, 0.5, 0.5, _1080p * -32, _1080p * -8, _1080p * -12, _1080p * 12 )
	self:addElement( MicIcon )
	self.MicIcon = MicIcon
	
	local SocialPlatformPresence = nil
	
	SocialPlatformPresence = MenuBuilder.BuildRegisteredType( "SocialPlatformPresence", {
		controllerIndex = f1_local1
	} )
	SocialPlatformPresence.id = "SocialPlatformPresence"
	SocialPlatformPresence:SetAlpha( 0.75, 0 )
	SocialPlatformPresence:SetAnchorsAndPosition( 1, 0, 0, 1, _1080p * -56, _1080p * -38, _1080p * 10, _1080p * 28 )
	self:addElement( SocialPlatformPresence )
	self.SocialPlatformPresence = SocialPlatformPresence
	
	local InputMethod = nil
	
	InputMethod = LUI.UIImage.new()
	InputMethod.id = "InputMethod"
	InputMethod:SetRGBFromTable( SWATCHES.text.primaryText, 0 )
	InputMethod:SetAnchorsAndPosition( 1, 0, 0.5, 0.5, _1080p * -87, _1080p * -63, _1080p * -12, _1080p * 12 )
	self:addElement( InputMethod )
	self.InputMethod = InputMethod
	
	local Gamertag = nil
	
	Gamertag = LUI.UIStyledText.new()
	Gamertag.id = "Gamertag"
	Gamertag:SetRGBFromTable( SWATCHES.genericButton.listButtonDefault, 0 )
	Gamertag:setText( "WWWWWWWWWWWWWWWW", 0 )
	Gamertag:SetFont( FONTS.GetFont( FONTS.BattleNetRegular.File ) )
	Gamertag:SetWordWrap( false )
	Gamertag:SetAlignment( LUI.Alignment.Left )
	Gamertag:SetOptOutRightToLeftAlignmentFlip( true )
	Gamertag:SetAutoScrollStyle( LUI.UIStyledText.AutoScrollStyle.ScrollH )
	Gamertag:SetUseEllipses( ELLIPSES.enabled_default )
	Gamertag:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, _1080p * 166, _1080p * 331, _1080p * -8, _1080p * 9 )
	self:addElement( Gamertag )
	self.Gamertag = Gamertag
	
	local ClanTag = nil
	
	ClanTag = LUI.UIText.new()
	ClanTag.id = "ClanTag"
	ClanTag:SetRGBFromTable( SWATCHES.genericButton.listButtonDefault, 0 )
	ClanTag:setText( "", 0 )
	ClanTag:SetFont( FONTS.GetFont( FONTS.BattleNetRegular.File ) )
	ClanTag:SetWordWrap( false )
	ClanTag:SetAlignment( LUI.Alignment.Center )
	ClanTag:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, _1080p * 98, _1080p * 165, _1080p * -8, _1080p * 9 )
	self:addElement( ClanTag )
	self.ClanTag = ClanTag
	
	local RankIcon = nil
	
	RankIcon = LUI.UIImage.new()
	RankIcon.id = "RankIcon"
	RankIcon:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, _1080p * 74, _1080p * 98, _1080p * -12, _1080p * 12 )
	self:addElement( RankIcon )
	self.RankIcon = RankIcon
	
	local Rank = nil
	
	Rank = LUI.UIText.new()
	Rank.id = "Rank"
	Rank:SetRGBFromTable( SWATCHES.genericButton.listButtonDefault, 0 )
	Rank:setText( "", 0 )
	Rank:SetFont( FONTS.GetFont( FONTS.MainBold.File ) )
	Rank:SetWordWrap( false )
	Rank:SetAlignment( LUI.Alignment.Center )
	Rank:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, _1080p * 43, _1080p * 72, _1080p * -9, _1080p * 9 )
	self:addElement( Rank )
	self.Rank = Rank
	
	local HostIcon = nil
	
	HostIcon = LUI.UIImage.new()
	HostIcon.id = "HostIcon"
	HostIcon:SetRGBFromTable( SWATCHES.genericButton.listButtonDefault, 0 )
	HostIcon:setImage( RegisterMaterial( "icon_party_leader_crown" ), 0 )
	HostIcon:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, _1080p * 10, _1080p * 30, _1080p * -10, _1080p * 10 )
	self:addElement( HostIcon )
	self.HostIcon = HostIcon
	
	local Divider = nil
	
	Divider = LUI.UIImage.new()
	Divider.id = "Divider"
	Divider:SetRGBFromTable( SWATCHES.genericButton.listButtonDefault, 0 )
	Divider:SetAlpha( 0.25, 0 )
	Divider:SetAnchorsAndPosition( 0, 1, 0, 0, _1080p * 39, _1080p * 41, _1080p * 2, _1080p * -2 )
	self:addElement( Divider )
	self.Divider = Divider
	
	local TeamIndex = nil
	
	TeamIndex = LUI.UIText.new()
	TeamIndex.id = "TeamIndex"
	TeamIndex:SetRGBFromTable( SWATCHES.text.primaryText, 0 )
	TeamIndex:setText( "1", 0 )
	TeamIndex:SetFont( FONTS.GetFont( FONTS.MainBold.File ) )
	TeamIndex:SetWordWrap( false )
	TeamIndex:SetAlignment( LUI.Alignment.Center )
	TeamIndex:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, _1080p * 5, _1080p * 34, _1080p * -12, _1080p * 12 )
	self:addElement( TeamIndex )
	self.TeamIndex = TeamIndex
	
	self._sequences.DefaultSequence = function ()
		
	end
	
	local f1_local14 = nil
	MicIcon:RegisterAnimationSequence( "Empty", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	SocialPlatformPresence:RegisterAnimationSequence( "Empty", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	InputMethod:RegisterAnimationSequence( "Empty", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Gamertag:RegisterAnimationSequence( "Empty", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * 30
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 195
		}
	} )
	ClanTag:RegisterAnimationSequence( "Empty", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	RankIcon:RegisterAnimationSequence( "Empty", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Rank:RegisterAnimationSequence( "Empty", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	HostIcon:RegisterAnimationSequence( "Empty", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Divider:RegisterAnimationSequence( "Empty", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.Empty = function ()
		menu:AnimateSequence( "Empty" )
		menu:AnimateSequence( "Empty" )
		menu:AnimateSequence( "Empty" )
		menu:AnimateSequence( "Empty" )
		menu:AnimateSequence( "Empty" )
		menu:AnimateSequence( "Empty" )
		menu:AnimateSequence( "Empty" )
		menu:AnimateSequence( "Empty" )
		menu:AnimateSequence( "Empty" )
	end
	
	local f1_local15 = nil
	SocialPlatformPresence:RegisterAnimationSequence( "Available", {
		{
			value = 5.297218497E-315,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	InputMethod:RegisterAnimationSequence( "Available", {
		{
			value = 8.029892509424649E+283,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Gamertag:RegisterAnimationSequence( "Available", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * 166
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 331
		}
	} )
	ClanTag:RegisterAnimationSequence( "Available", {
		{
			value = 8.029892509424649E+283,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	RankIcon:RegisterAnimationSequence( "Available", {
		{
			value = 8.029892509424649E+283,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Rank:RegisterAnimationSequence( "Available", {
		{
			value = 8.029892509424649E+283,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Divider:RegisterAnimationSequence( "Available", {
		{
			value = 5.289447516E-315,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.Available = function ()
		menu:AnimateSequence( "Available" )
		menu:AnimateSequence( "Available" )
		menu:AnimateSequence( "Available" )
		menu:AnimateSequence( "Available" )
		menu:AnimateSequence( "Available" )
		menu:AnimateSequence( "Available" )
		menu:AnimateSequence( "Available" )
	end
	
	local f1_local16 = nil
	TextBacker:RegisterAnimationSequence( "ButtonOver", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.Global.keyColorNormal
		}
	} )
	self._sequences.ButtonOver = function ()
		menu:AnimateSequence( "ButtonOver" )
	end
	
	local f1_local17 = nil
	TextBacker:RegisterAnimationSequence( "ButtonUp", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.RGB
		}
	} )
	self._sequences.ButtonUp = function ()
		menu:AnimateSequence( "ButtonUp" )
	end
	
	local f1_local18 = nil
	SocialPlatformPresence:RegisterAnimationSequence( "Solo", {
		{
			value = 5.297218497E-315,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	InputMethod:RegisterAnimationSequence( "Solo", {
		{
			value = 8.029892509424649E+283,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Gamertag:RegisterAnimationSequence( "Solo", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * 138
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 303
		}
	} )
	ClanTag:RegisterAnimationSequence( "Solo", {
		{
			value = 8.029892509424649E+283,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * 61
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 133
		}
	} )
	RankIcon:RegisterAnimationSequence( "Solo", {
		{
			value = 8.029892509424649E+283,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * 37
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 61
		}
	} )
	Rank:RegisterAnimationSequence( "Solo", {
		{
			value = 8.029892509424649E+283,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * 5
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 34
		}
	} )
	Divider:RegisterAnimationSequence( "Solo", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	TeamIndex:RegisterAnimationSequence( "Solo", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.Solo = function ()
		menu:AnimateSequence( "Solo" )
		menu:AnimateSequence( "Solo" )
		menu:AnimateSequence( "Solo" )
		menu:AnimateSequence( "Solo" )
		menu:AnimateSequence( "Solo" )
		menu:AnimateSequence( "Solo" )
		menu:AnimateSequence( "Solo" )
		menu:AnimateSequence( "Solo" )
	end
	
	f0_local0( self, f1_local1, controller )
	return self
end

MenuBuilder.registerType( "WarzonePrivateMatchSquadTeamMember", WarzonePrivateMatchSquadTeamMember )
LockTable( _M )
