-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 17-11-2025 01:22
module( ..., package.seeall )
local f0_local0 = 16
local f0_local1 = function ( f15_arg0, f15_arg1 )
	if f15_arg1 then
		f15_arg1:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * math.random( 0, 50 ) * 10, _1080p * f0_local0, _1080p * math.random( 0, 50 ) * 10, _1080p * f0_local0, 0 )
	end
end

local f0_local2 = function ( f12_arg0 )
	local f12_local0 = math.random( 1, #f12_arg0._circles )
	if f12_arg0._circles[f12_local0] then
		ACTIONS.AnimateSequence( f12_arg0._circles[f12_local0], "Hide" )
		local f12_local1 = f12_arg0:Wait( f12_arg0._circles[f12_local0]._transitionDuration )
		f12_local1.onComplete = function ()
			f12_arg0:PositionNode( f12_arg0._circles[f12_arg0] )
			f12_arg0._circles[f12_arg0]:PlayAnim()
		end
		
		local f12_local2 = f12_arg0:Wait( math.random( f12_arg0._circles[f12_local0]._transitionDuration + 5000, 10000 ) )
		f12_local2.onComplete = function ()
			f12_arg0:UpdateCircleNodes()
		end
		
	end
end

local f0_local3 = function ( f9_arg0 )
	local f9_local0 = math.random( 1, #f9_arg0._squares )
	if f9_arg0._squares[f9_local0] then
		ACTIONS.AnimateSequence( f9_arg0._squares[f9_local0], "Hide" )
		local f9_local1 = f9_arg0:Wait( f9_arg0._squares[f9_local0]._transitionDuration )
		f9_local1.onComplete = function ()
			f9_arg0:PositionNode( f9_arg0._squares[f9_arg0] )
			f9_arg0._squares[f9_arg0]:PlayAnim()
		end
		
	end
	local f9_local2 = f9_arg0:Wait( math.random( f9_arg0._squares[f9_local0]._transitionDuration + 5000, 8000 ) )
	f9_local2.onComplete = function ()
		f9_arg0:UpdateSquareNodes()
	end
	
end

local f0_local4 = function ( f6_arg0 )
	local f6_local0 = math.random( 1, #f6_arg0._triangles )
	if f6_arg0._triangles[f6_local0] then
		ACTIONS.AnimateSequence( f6_arg0._triangles[f6_local0], "Hide" )
		local f6_local1 = f6_arg0:Wait( f6_arg0._triangles[f6_local0]._transitionDuration )
		f6_local1.onComplete = function ()
			f6_arg0:PositionNode( f6_arg0._triangles[f6_arg0] )
			f6_arg0._triangles[f6_arg0]:PlayAnim()
		end
		
	end
	local f6_local2 = f6_arg0:Wait( math.random( f6_arg0._triangles[f6_local0]._transitionDuration + 1000, 2000 ) )
	f6_local2.onComplete = function ()
		f6_arg0:UpdateTriangleNodes()
	end
	
end

local f0_local5 = function ( f3_arg0 )
	local f3_local0 = math.random( 1, #f3_arg0._arrows )
	if f3_arg0._arrows[f3_local0] then
		ACTIONS.AnimateSequence( f3_arg0._arrows[f3_local0], "Hide" )
		local f3_local1 = f3_arg0:Wait( f3_arg0._arrows[f3_local0]._transitionDuration )
		f3_local1.onComplete = function ()
			f3_arg0:PositionNode( f3_arg0._arrows[f3_arg0] )
			f3_arg0._arrows[f3_arg0]:PlayAnim()
		end
		
	end
	local f3_local2 = f3_arg0:Wait( math.random( f3_arg0._arrows[f3_local0]._transitionDuration + 3000, 5000 ) )
	f3_local2.onComplete = function ()
		f3_arg0:UpdateArrowNodes()
	end
	
end

local f0_local6 = function ( f2_arg0, f2_arg1, f2_arg2 )
	f2_arg0.PositionNode = f0_local0
	f2_arg0.UpdateCircleNodes = f0_local0
	f2_arg0.UpdateSquareNodes = f0_local0
	f2_arg0.UpdateTriangleNodes = f0_local0
	f2_arg0.UpdateArrowNodes = f0_local0
	f2_arg0._triangles = {
		f2_arg0.Triangle1,
		f2_arg0.Triangle2,
		f2_arg0.Triangle3
	}
	f2_arg0._circles = {
		f2_arg0.Circle1
	}
	f2_arg0._squares = {
		f2_arg0.Square1,
		f2_arg0.Square2
	}
	f2_arg0._arrows = {
		f2_arg0.Arrow1,
		f2_arg0.Arrow2,
		f2_arg0.Arrow3
	}
	f2_arg0:UpdateCircleNodes()
	f2_arg0:UpdateSquareNodes()
	f2_arg0:UpdateTriangleNodes()
	f2_arg0:UpdateArrowNodes()
end

function LevelMapDecoration( menu, controller )
	local self = LUI.UIElement.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 500 * _1080p, 0, 500 * _1080p )
	self.id = "LevelMapDecoration"
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine.DDJFBBJAIG() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1 )
	local f1_local2 = self
	local Circle1 = nil
	
	Circle1 = MenuBuilder.BuildRegisteredType( "MapDecorationCircle", {
		controllerIndex = f1_local1
	} )
	Circle1.id = "Circle1"
	Circle1:SetAlpha( 0.75, 0 )
	Circle1:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 34, _1080p * 50, _1080p * 32, _1080p * 48 )
	self:addElement( Circle1 )
	self.Circle1 = Circle1
	
	local Triangle1 = nil
	
	Triangle1 = MenuBuilder.BuildRegisteredType( "MapDecorationTriangle", {
		controllerIndex = f1_local1
	} )
	Triangle1.id = "Triangle1"
	Triangle1:SetAlpha( 0.85, 0 )
	Triangle1:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 300, _1080p * 316, _1080p * 216, _1080p * 232 )
	self:addElement( Triangle1 )
	self.Triangle1 = Triangle1
	
	local Triangle2 = nil
	
	Triangle2 = MenuBuilder.BuildRegisteredType( "MapDecorationTriangle", {
		controllerIndex = f1_local1
	} )
	Triangle2.id = "Triangle2"
	Triangle2:SetAlpha( 0.85, 0 )
	Triangle2:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 178, _1080p * 194, _1080p * 292, _1080p * 308 )
	self:addElement( Triangle2 )
	self.Triangle2 = Triangle2
	
	local Triangle3 = nil
	
	Triangle3 = MenuBuilder.BuildRegisteredType( "MapDecorationTriangle", {
		controllerIndex = f1_local1
	} )
	Triangle3.id = "Triangle3"
	Triangle3:SetAlpha( 0.85, 0 )
	Triangle3:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 50, _1080p * 66, _1080p * 200, _1080p * 216 )
	self:addElement( Triangle3 )
	self.Triangle3 = Triangle3
	
	local Square1 = nil
	
	Square1 = MenuBuilder.BuildRegisteredType( "MapDecorationSquare", {
		controllerIndex = f1_local1
	} )
	Square1.id = "Square1"
	Square1:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 356, _1080p * 372, _1080p * 73, _1080p * 89 )
	self:addElement( Square1 )
	self.Square1 = Square1
	
	local Square2 = nil
	
	Square2 = MenuBuilder.BuildRegisteredType( "MapDecorationSquare", {
		controllerIndex = f1_local1
	} )
	Square2.id = "Square2"
	Square2:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 91, _1080p * 107, _1080p * 404, _1080p * 420 )
	self:addElement( Square2 )
	self.Square2 = Square2
	
	local Arrow1 = nil
	
	Arrow1 = MenuBuilder.BuildRegisteredType( "MapDecorationArrow", {
		controllerIndex = f1_local1
	} )
	Arrow1.id = "Arrow1"
	Arrow1:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 284, _1080p * 300, _1080p * 308, _1080p * 324 )
	self:addElement( Arrow1 )
	self.Arrow1 = Arrow1
	
	local Arrow2 = nil
	
	Arrow2 = MenuBuilder.BuildRegisteredType( "MapDecorationArrow", {
		controllerIndex = f1_local1
	} )
	Arrow2.id = "Arrow2"
	Arrow2:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 214, _1080p * 230, _1080p * 196, _1080p * 212 )
	self:addElement( Arrow2 )
	self.Arrow2 = Arrow2
	
	local Arrow3 = nil
	
	Arrow3 = MenuBuilder.BuildRegisteredType( "MapDecorationArrow", {
		controllerIndex = f1_local1
	} )
	Arrow3.id = "Arrow3"
	Arrow3:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 425, _1080p * 441, _1080p * 372, _1080p * 388 )
	self:addElement( Arrow3 )
	self.Arrow3 = Arrow3
	
	f0_local0( self, f1_local1, controller )
	return self
end

MenuBuilder.registerType( "LevelMapDecoration", LevelMapDecoration )
LockTable( _M )
