-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 04-10-2025 21:43
module( ..., package.seeall )
function LPRankPoint( menu, controller )
	local self = LUI.UIElement.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 20 * _1080p, 0, 20 * _1080p )
	self.id = "LPRankPoint"
	self._animationSets = self._animationSets or {}
	self._sequences = self._sequences or {}
	self._sequenceLengths = self._sequenceLengths or {}
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	f1_local1 = LUI.ValidateControllerIndex( self, f1_local1 )
	local f1_local2 = self
	local PointIconEmpty = nil
	
	PointIconEmpty = LUI.UIImage.new()
	PointIconEmpty.id = "PointIconEmpty"
	PointIconEmpty:SetRGBFromInt( 9211020, 0 )
	PointIconEmpty:setImage( RegisterMaterial( "ui_icon_rankedplay_star_empty" ), 0 )
	self:addElement( PointIconEmpty )
	self.PointIconEmpty = PointIconEmpty
	
	local PointIcon = nil
	
	PointIcon = LUI.UIImage.new()
	PointIcon.id = "PointIcon"
	PointIcon:setImage( RegisterMaterial( "ui_icon_rankedplay_star_filled" ), 0 )
	self:addElement( PointIcon )
	self.PointIcon = PointIcon
	
	self._sequences.DefaultSequence = function ()
		
	end
	
	self._sequenceLengths.DefaultSequence = 0
	local f1_local5 = nil
	PointIconEmpty:RegisterAnimationSequence( "SlamDown", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Scale
		},
		{
			value = 0,
			duration = 200,
			property = TWEEN_PROPERTY.Scale,
			easing = LUI.EASING.inOutQuadratic
		}
	} )
	PointIcon:RegisterAnimationSequence( "SlamDown", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Scale
		},
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 130,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.inOutQuadratic
		},
		{
			value = 0,
			duration = 200,
			property = TWEEN_PROPERTY.Scale,
			easing = LUI.EASING.inOutQuadratic
		},
		{
			value = 1,
			duration = 170,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.inOutQuadratic
		}
	} )
	self._sequences.SlamDown = function ()
		menu:AnimateSequence( "SlamDown" )
		menu:AnimateSequence( "SlamDown" )
	end
	
	self._sequenceLengths.SlamDown = 300
	return self
end

MenuBuilder.registerType( "LPRankPoint", LPRankPoint )
LockTable( _M )
