-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 04-10-2025 21:42
module( ..., package.seeall )
require( "ui.widgets.GenericEditBoxButton" )
require( "ui.widgets.MenuButton" )
function RecipeCreatePopupButtons( menu, controller )
	local self = LUI.UIVerticalList.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 384 * _1080p, 0, 277 * _1080p )
	self.id = "RecipeCreatePopupButtons"
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine[0x12586A3F4FB490E]() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1, "Missing controllerIndex!" )
	local f1_local2 = self
	self:SetSpacing( 10 * _1080p )
	local NameInputButton = nil
	
	NameInputButton = MenuBuilder.BuildRegisteredType( "GenericEditBoxButton", {
		controllerIndex = f1_local1
	} )
	NameInputButton.id = "NameInputButton"
	NameInputButton.Text:setText( Engine[0xED84C33EC5F01EA]( "LUA_MENU/CUSTOM_MODE_NAME" ), 0 )
	NameInputButton.Text:SetAlignment( LUI.Alignment.Left )
	NameInputButton:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 384, 0, _1080p * 45 )
	self:addElement( NameInputButton )
	self.NameInputButton = NameInputButton
	
	local DescriptionInputButton = nil
	
	DescriptionInputButton = MenuBuilder.BuildRegisteredType( "GenericEditBoxButton", {
		controllerIndex = f1_local1
	} )
	DescriptionInputButton.id = "DescriptionInputButton"
	DescriptionInputButton.Text:setText( Engine[0xED84C33EC5F01EA]( "LUA_MENU/CUSTOM_MODE_DESC" ), 0 )
	DescriptionInputButton.Text:SetAlignment( LUI.Alignment.Left )
	DescriptionInputButton:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 384, _1080p * 55, _1080p * 100 )
	self:addElement( DescriptionInputButton )
	self.DescriptionInputButton = DescriptionInputButton
	
	local Spacer = nil
	
	Spacer = LUI.UIImage.new()
	Spacer.id = "Spacer"
	Spacer:SetAlpha( 0, 0 )
	Spacer:SetAnchorsAndPosition( 0.5, 0.5, 0, 1, _1080p * -64, _1080p * 64, _1080p * 110, _1080p * 150 )
	self:addElement( Spacer )
	self.Spacer = Spacer
	
	local SaveButton = nil
	
	SaveButton = MenuBuilder.BuildRegisteredType( "MenuButton", {
		controllerIndex = f1_local1
	} )
	SaveButton.id = "SaveButton"
	SaveButton.Text:setText( Engine[0xED84C33EC5F01EA]( "MENU/SAVE" ), 0 )
	SaveButton.Text:SetAlignment( LUI.Alignment.Left )
	SaveButton:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 384, _1080p * 160, _1080p * 200 )
	self:addElement( SaveButton )
	self.SaveButton = SaveButton
	
	local CancelButton = nil
	
	CancelButton = MenuBuilder.BuildRegisteredType( "MenuButton", {
		controllerIndex = f1_local1
	} )
	CancelButton.id = "CancelButton"
	CancelButton.Text:setText( Engine[0xED84C33EC5F01EA]( "LUA_MENU/CANCEL" ), 0 )
	CancelButton.Text:SetAlignment( LUI.Alignment.Left )
	CancelButton:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 384, _1080p * 210, _1080p * 250 )
	self:addElement( CancelButton )
	self.CancelButton = CancelButton
	
	return self
end

MenuBuilder.registerType( "RecipeCreatePopupButtons", RecipeCreatePopupButtons )
LockTable( _M )
