-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 13-10-2025 14:16
CLIENT_MODEL = CLIENT_MODEL or {}
local f0_local0 = "military_carepackage_01"
local f0_local1 = "military_frontend_gunrange_01_paper_1"
local f0_local2 = "military_frontend_gunrange_01_paper_2"
local f0_local3 = "military_frontend_gunrange_01_paper_3"
local f0_local4 = nil
CLIENT_MODEL.launcherCaseModels = {
	JOKR = {
		useLootID = false,
		xmodelName = "military_frontend_launcher_case_jokr",
		ref = "iw9_la_juliet"
	},
	PILA = {
		useLootID = false,
		xmodelName = "military_frontend_launcher_case_pila",
		ref = "iw9_la_gromeo"
	},
	STRELA = {
		useLootID = false,
		xmodelName = "military_frontend_launcher_case_strela",
		ref = "iw9_la_kgolf"
	},
	RPG = {
		useLootID = false,
		xmodelName = "military_frontend_launcher_case_rpg",
		ref = "iw9_la_rpapa7"
	},
	RIOTSHIELD = {
		useLootID = false,
		xmodelName = "military_frontend_launcher_case_riotshield",
		ref = "iw9_me_riotshield"
	},
	CROSSBOW = {
		useLootID = false,
		xmodelName = "military_frontend_launcher_case_crossbow",
		ref = WEAPON.Crossbow
	},
	CHAINSAW = {
		xmodelName = "military_frontend_launcher_case_chainsaw",
		useLootID = true,
		ref = WEAPON.Chainsaw,
		lootID = WEAPON.ChainsawLootID
	}
}
CLIENT_MODEL.quartermasterModels = {
	CRATE = {
		name = "quartermaster_crate_1"
	},
	TARGET1 = {
		name = "quartermaster_target_1"
	},
	TARGET2 = {
		name = "quartermaster_target_2"
	},
	TARGET3 = {
		name = "quartermaster_target_3"
	}
}
CLIENT_MODEL.defaultTags = {
	TAG_ARM_FRONT = 3,
	TAG_ORIGIN = 2,
	TAG_GUN_ATTACH = 6,
	PATCH_TAG_1 = 0,
	TAG_CHILD = 5,
	PATCH_TAG_2 = 1,
	TAG_ACCESSORY = 7,
	TAG_ARM_REAR = 4
}
CLIENT_MODEL.NO_CLIENT_MODEL = "tag_origin"
local f0_local5 = "accessory_ui_perk_pouch_01_rig"
local f0_local6 = "accessory_ui_perk_pouch_02_rig"
local f0_local7 = "accessory_ui_perk_pouch_03_rig"
local f0_local8 = "accessory_ui_perk_patch_01"
local f0_local9 = "accessory_ui_perk_patch_01_hunter"
local f0_local10 = "accessory_ui_perk_patch_01_battle_hardened"
local f0_local11 = "military_gun_vise_base"
local f0_local12 = "military_gun_vise_arm_front1"
local f0_local13 = "military_gun_vise_arm_front2"
local f0_local14 = "military_gun_vise_arm_front3"
local f0_local15 = "military_gun_vise_claw_front"
local f0_local16 = "military_gun_vise_arm_rear1"
local f0_local17 = "military_gun_vise_arm_rear2"
local f0_local18 = "military_gun_vise_arm_rear3"
local f0_local19 = "military_gun_vise_claw_rear"
local f0_local20 = "military_gun_vise_ar_base"
local f0_local21 = "military_gun_vise_ar_insert"
local f0_local22 = "military_gun_vise_support_base"
local f0_local23 = "military_gun_vise_support_insert"
CLIENT_MODEL.MILITARY_GUNTABLE_CASE_SMALL = "military_guntable_case_01_small"
CLIENT_MODEL.MILITARY_GUNTABLE_CASE_MEDIUM = "military_guntable_case_01_medium"
CLIENT_MODEL.MILITARY_GUNTABLE_CASE_LARGE = "military_guntable_case_01_large"
local f0_local24 = 43
local f0_local25 = 27
local f0_local26, f0_local27 = nil
CLIENT_MODEL.meleeRotationOffset = 90
CLIENT_MODEL.batonRotationOffset = -180
CLIENT_MODEL.chainsawRotationOffset = -30
CLIENT_MODEL.knifeYOffset = 2
CLIENT_MODEL.secondaryWeaponOffset = -20
CLIENT_MODEL.pistolWeaponOffset = 10
CLIENT_MODEL.maxSecondaryWeaponLength = 55
CLIENT_MODEL.smallWeaponPivotOffset = -5
CLIENT_MODEL.mobileWeaponArmoryRotationOffset = 25
CLIENT_MODEL.mobileMeleePositionOffset = -17
CLIENT_MODEL.gunCaseSizes = {
	SMALL_GUN_CASE = 1,
	LARGE_GUN_CASE = 3,
	NO_GUN_CASE = 4,
	MEDIUM_GUN_CASE = 2
}
CLIENT_MODEL.coreMPModels = {
	LETHAL = {
		name = "loadout_lethal",
		tagAccessory = CLIENT_MODEL.defaultTags.TAG_ACCESSORY
	},
	TACTICAL = {
		name = "loadout_tactical",
		tagAccessory = CLIENT_MODEL.defaultTags.TAG_ACCESSORY
	},
	PERK = {
		name = "loadout_perk_1"
	},
	PERK_ACTIVE = {
		name = "loadout_perk_2"
	},
	PERK_PASSIVE = {
		name = "loadout_perk_3"
	},
	PERK_PATCH = {
		name = "loadout_perk_patch_1",
		patchTag = CLIENT_MODEL.defaultTags.PATCH_TAG_1
	},
	PERK_ACTIVE_PATCH = {
		name = "loadout_perk_patch_2",
		patchTag = CLIENT_MODEL.defaultTags.PATCH_TAG_1
	},
	PERK_PASSIVE_PATCH = {
		name = "loadout_perk_patch_3",
		patchTag = CLIENT_MODEL.defaultTags.PATCH_TAG_1
	},
	PERK_PATCH_SPECIALIST = {
		name = "loadout_specialist_patch_1"
	},
	PERK_ACTIVE_PATCH_SPECIALIST = {
		name = "loadout_specialist_patch_2"
	},
	PERK_PASSIVE_PATCH_SPECIALIST = {
		name = "loadout_specialist_patch_3"
	},
	PERK_BAG = {
		name = "loadout_big_bag"
	},
	GUN_VISE_BASE = {
		name = "vise_base",
		tagOrigin = CLIENT_MODEL.defaultTags.TAG_ORIGIN,
		tagArmFront = CLIENT_MODEL.defaultTags.TAG_ARM_FRONT,
		tagArmRear = CLIENT_MODEL.defaultTags.TAG_ARM_REAR
	},
	GUN_VISE_MAGWELL_BASE = {
		name = "vise_magwell_base",
		tagOrigin = CLIENT_MODEL.defaultTags.TAG_ORIGIN,
		tagChild = CLIENT_MODEL.defaultTags.TAG_CHILD
	},
	GUN_VISE_MAGWELL_INSERT = {
		name = "vise_magwell_insert",
		tagOrigin = CLIENT_MODEL.defaultTags.TAG_ORIGIN,
		tagGunAttach = CLIENT_MODEL.defaultTags.TAG_GUN_ATTACH
	},
	GUN_VISE_SUPPORT_BASE = {
		name = "vise_support_base",
		tagOrigin = CLIENT_MODEL.defaultTags.TAG_ORIGIN,
		tagChild = CLIENT_MODEL.defaultTags.TAG_CHILD
	},
	GUN_VISE_SUPPORT_INSERT = {
		name = "vise_support_insert",
		tagOrigin = CLIENT_MODEL.defaultTags.TAG_ORIGIN,
		tagGunAttach = CLIENT_MODEL.defaultTags.TAG_GUN_ATTACH
	},
	GUN_CASE = {
		name = "gun_case"
	},
	SECONDARY_WEAPON_CASE = {
		name = "weapon_launcher_case",
		tagOrigin = CLIENT_MODEL.defaultTags.TAG_ORIGIN
	},
	PRIMARY_WEAPON_CASE = {
		name = "riot_shield_case",
		tagOrigin = CLIENT_MODEL.defaultTags.TAG_ORIGIN
	},
	MAG_DISPLAY = {
		name = "vice_mag_loose_01",
		tagOrigin = CLIENT_MODEL.defaultTags.TAG_ORIGIN
	},
	GUN_VISE_MAG_LOC = {
		name = "gun_vise_mag_loc",
		tagOrigin = CLIENT_MODEL.defaultTags.TAG_ORIGIN
	},
	AMMO_DISPLAY = {
		name = "vice_ammo_loose_01",
		tagOrigin = CLIENT_MODEL.defaultTags.TAG_ORIGIN
	}
}
CLIENT_MODEL.battlePassModels = {
	WEAPON = {
		name = "bp_weapon_figurine_02"
	},
	CHARACTER = {
		name = "bp_character_figurine_01"
	},
	WEAPON_DETAIL = {
		name = "bp_weapon_figurine_01"
	},
	VEHICLE = {
		name = "bp_vehicle_figurine_01"
	},
	ITEMS = {
		name = "bp_items"
	},
	CHARACTER_BG = {
		name = "bp_character_bg"
	},
	WEAPON_BG = {
		name = "bp_blueprint_bg"
	},
	ITEMS_BG = {
		name = "bp_veh_item_bg"
	},
	BLACK_CELL_VEHICLE = {
		name = "bp_bc_vehicle_01"
	},
	BLACK_CELL_WEAPON = {
		name = "bp_bc_weapon_01"
	},
	BLACK_CELL_CHARACTER = {
		name = "bp_bc_character_01"
	}
}
CLIENT_MODEL.loadoutSelectModels = {
	CLIENT_MODEL.coreMPModels.LETHAL,
	CLIENT_MODEL.coreMPModels.TACTICAL,
	CLIENT_MODEL.coreMPModels.PERK,
	CLIENT_MODEL.coreMPModels.PERK_ACTIVE,
	CLIENT_MODEL.coreMPModels.PERK_PASSIVE,
	CLIENT_MODEL.coreMPModels.PERK_PATCH,
	CLIENT_MODEL.coreMPModels.PERK_ACTIVE_PATCH,
	CLIENT_MODEL.coreMPModels.PERK_PASSIVE_PATCH,
	CLIENT_MODEL.coreMPModels.GUN_CASE,
	CLIENT_MODEL.coreMPModels.PRIMARY_WEAPON_CASE,
	CLIENT_MODEL.coreMPModels.SECONDARY_WEAPON_CASE
}
CLIENT_MODEL.InitQuartermasterClientModels = function ()
	CLIENT_MODEL.SetModel( CLIENT_MODEL.quartermasterModels.CRATE, f0_local0 )
	CLIENT_MODEL.SetModel( CLIENT_MODEL.quartermasterModels.TARGET1, f0_local0 )
	CLIENT_MODEL.SetModel( CLIENT_MODEL.quartermasterModels.TARGET2, f0_local0 )
	CLIENT_MODEL.SetModel( CLIENT_MODEL.quartermasterModels.TARGET3, f0_local0 )
end

CLIENT_MODEL.InitGunViseModels = function ()
	if CONDITIONS.IsMobileOrMobileSim() then
		CLIENT_MODEL.HideAllGunViseAndAmmoModels()
		return 
	else
		CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.GUN_VISE_BASE, f0_local0 )
		CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.GUN_VISE_MAGWELL_BASE, f0_local0 )
		CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.GUN_VISE_MAGWELL_INSERT, f0_local0 )
		CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.GUN_VISE_SUPPORT_BASE, f0_local0 )
		CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.GUN_VISE_SUPPORT_INSERT, f0_local0 )
	end
end

CLIENT_MODEL.HideAllGunViseAndAmmoModels = function ()
	local f39_local0 = {
		CLIENT_MODEL.coreMPModels.GUN_VISE_BASE,
		CLIENT_MODEL.coreMPModels.GUN_VISE_MAGWELL_BASE,
		CLIENT_MODEL.coreMPModels.GUN_VISE_MAGWELL_INSERT,
		CLIENT_MODEL.coreMPModels.GUN_VISE_SUPPORT_BASE,
		CLIENT_MODEL.coreMPModels.GUN_VISE_SUPPORT_INSERT,
		CLIENT_MODEL.coreMPModels.MAG_DISPLAY,
		CLIENT_MODEL.coreMPModels.GUN_VISE_MAG_LOC,
		CLIENT_MODEL.coreMPModels.AMMO_DISPLAY
	}
	CLIENT_MODEL.SetModelsModifiable( f39_local0, true )
	for f39_local4, f39_local5 in pairs( f39_local0 ) do
		CLIENT_MODEL.SetModel( f39_local5, CLIENT_MODEL.NO_CLIENT_MODEL )
	end
end

CLIENT_MODEL.GetClientModelIndex = function ( f38_arg0 )
	assert( f38_arg0 )
	assert( f38_arg0.name )
	if not f38_arg0.index then
		f38_arg0.index = ClientModel[0x2718F08EFB3317D]( f38_arg0.name )
	end
	return f38_arg0.index
end

CLIENT_MODEL.IsInitialized = function ()
	return ClientModel[0xA988866C889EAAD]()
end

CLIENT_MODEL.UpdateModifiablesByMode = function ()
	if Engine[0x9258F49F515F97B]() then
		CLIENT_MODEL.SetModelsModifiable( CLIENT_MODEL.coreMPModels, true )
	else
		CLIENT_MODEL.SetModelsModifiable( CLIENT_MODEL.coreMPModels, false )
	end
end

CLIENT_MODEL.ForceEnableMPModelsAsModifiable = function ()
	CLIENT_MODEL.SetModelsModifiable( CLIENT_MODEL.coreMPModels, true )
end

CLIENT_MODEL.SetModelsModifiable = function ( f34_arg0, f34_arg1 )
	for f34_local3, f34_local4 in pairs( f34_arg0 ) do
		local f34_local5 = CLIENT_MODEL.GetClientModelIndex( f34_local4 )
		if f34_local5 then
			ClientModel[0xBBF366AC4378219]( f34_local5, f34_arg1 )
		end
	end
end

CLIENT_MODEL.AreModelsModifiable = function ( f33_arg0 )
	for f33_local3, f33_local4 in pairs( f33_arg0 ) do
		local f33_local5 = CLIENT_MODEL.GetClientModelIndex( f33_local4 )
		if f33_local5 and ClientModel[0x29E992BBC0F43DF]( f33_local5 ) == false then
			return false
		end
	end
	return true
end

CLIENT_MODEL.SetAllModelsModifiable = function ( f32_arg0 )
	local f32_local0 = {
		CLIENT_MODEL.coreMPModels.LETHAL,
		CLIENT_MODEL.coreMPModels.TACTICAL,
		CLIENT_MODEL.coreMPModels.PERK,
		CLIENT_MODEL.coreMPModels.PERK_ACTIVE,
		CLIENT_MODEL.coreMPModels.PERK_PASSIVE,
		CLIENT_MODEL.coreMPModels.PERK_PATCH,
		CLIENT_MODEL.coreMPModels.PERK_ACTIVE_PATCH,
		CLIENT_MODEL.coreMPModels.PERK_PASSIVE_PATCH,
		CLIENT_MODEL.coreMPModels.PERK_BAG,
		CLIENT_MODEL.coreMPModels.GUN_VISE_BASE,
		CLIENT_MODEL.coreMPModels.GUN_VISE_MAGWELL_BASE,
		CLIENT_MODEL.coreMPModels.GUN_VISE_MAGWELL_INSERT,
		CLIENT_MODEL.coreMPModels.GUN_VISE_SUPPORT_BASE,
		CLIENT_MODEL.coreMPModels.GUN_VISE_SUPPORT_INSERT,
		CLIENT_MODEL.coreMPModels.GUN_CASE,
		CLIENT_MODEL.coreMPModels.PRIMARY_WEAPON_CASE,
		CLIENT_MODEL.coreMPModels.SECONDARY_WEAPON_CASE,
		CLIENT_MODEL.coreMPModels.MAG_DISPLAY,
		CLIENT_MODEL.coreMPModels.GUN_VISE_MAG_LOC,
		CLIENT_MODEL.coreMPModels.AMMO_DISPLAY
	}
	if PROGRESSION.IsSpecialistPerkUnlocked( f32_arg0 ) or CONDITIONS.IsMobileOrMobileSim() then
		table.insert( f32_local0, CLIENT_MODEL.coreMPModels.PERK_PATCH_SPECIALIST )
		table.insert( f32_local0, CLIENT_MODEL.coreMPModels.PERK_ACTIVE_PATCH_SPECIALIST )
		table.insert( f32_local0, CLIENT_MODEL.coreMPModels.PERK_PASSIVE_PATCH_SPECIALIST )
	end
	CLIENT_MODEL.SetModelsModifiable( f32_local0, true )
	CLIENT_MODEL.SetRequiredModifiables( f32_local0 )
end

CLIENT_MODEL.SetModel = function ( f31_arg0, f31_arg1, f31_arg2 )
	if not String.IsNilOrEmpty( f31_arg1 ) then
		local f31_local0 = CLIENT_MODEL.GetClientModelIndex( f31_arg0 )
		if f31_local0 and ClientModel[0x29E992BBC0F43DF]( f31_local0 ) then
			ClientModel[0x340ADC76F008280]( f31_local0, f31_arg1, f31_arg2 )
		end
	end
end

CLIENT_MODEL.SetModelHUDOutline = function ( f30_arg0, f30_arg1 )
	if not String.IsNilOrEmpty( f30_arg1 ) then
		local f30_local0 = CLIENT_MODEL.GetClientModelIndex( f30_arg0 )
		if f30_local0 and ClientModel[0x29E992BBC0F43DF]( f30_local0 ) then
			ClientModel[0xA4C382FC0F92C04]( f30_local0, f30_arg1 )
		end
	end
end

CLIENT_MODEL.DisableHUDOutline = function ( f29_arg0 )
	local f29_local0 = CLIENT_MODEL.GetClientModelIndex( f29_arg0 )
	if f29_local0 and ClientModel[0x29E992BBC0F43DF]( f29_local0 ) then
		ClientModel[0x32386A31582BE2C]( f29_local0 )
	end
end

CLIENT_MODEL.SetAssetType = function ( f28_arg0, f28_arg1 )
	local f28_local0 = assert
	local f28_local1
	if f28_arg1 ~= Enum[0x4D1082DFC9AF660][0x21C02428B499A24] and f28_arg1 ~= Enum[0x4D1082DFC9AF660][0x912D6AEFE9657E7] then
		f28_local1 = false
	else
		f28_local1 = true
	end
	f28_local0( f28_local1 )
	f28_local0 = CLIENT_MODEL.GetClientModelIndex( f28_arg0 )
	if f28_local0 then
		ClientModel[0x4EC34B935AC45D]( f28_local0, f28_arg1 )
	end
end

CLIENT_MODEL.SetModelAttachedOrigin = function ( f27_arg0, f27_arg1, f27_arg2 )
	local f27_local0 = CLIENT_MODEL.GetClientModelIndex( f27_arg0 )
	local f27_local1 = CLIENT_MODEL.GetClientModelIndex( f27_arg1 )
	if f27_local1 and f27_local0 then
		ClientModel[0xA64FB358E8E1446]( f27_local0, f27_local1, f27_arg2 )
	end
end

CLIENT_MODEL.SetAnimation = function ( f26_arg0, f26_arg1, f26_arg2 )
	local f26_local0 = CLIENT_MODEL.GetClientModelIndex( f26_arg0 )
	if f26_local0 then
		ClientModel[0x2EF393F1650E09B]( f26_local0, f26_arg1, f26_arg2 )
	end
end

CLIENT_MODEL.SetRequiredModifiables = function ( f25_arg0 )
	local f25_local0 = {}
	for f25_local4, f25_local5 in pairs( f25_arg0 ) do
		local f25_local6 = CLIENT_MODEL.GetClientModelIndex( f25_local5 )
		if f25_local6 then
			table.insert( f25_local0, f25_local6 )
		end
	end
	ClientModel[0x6F8311E6071AD0D]( f25_local0 )
end

local f0_local28 = function ( f24_arg0 )
	for f24_local3, f24_local4 in pairs( f24_arg0 ) do
		f24_arg0[f24_local3] = "none"
	end
end

CLIENT_MODEL.SendClientModelTagDataToServer = function ( f23_arg0, f23_arg1, f23_arg2 )
	local f23_local0 = ClientWeapon[0x5DD69014A9C290]( FrontEndScene.ClientWeapons.GunTablePrimary )
	local f23_local1 = ClientWeapon[0x5DD69014A9C290]( FrontEndScene.ClientWeapons.GunTableSecondary )
	local f23_local2 = Engine[0xC3B7925CCAC9430]( Engine[0xF13D4623D3F6D4E]( 0 ), f23_local0, GUNSMITH.defaultTag )
	local f23_local3 = Engine[0xC3B7925CCAC9430]( Engine[0xF13D4623D3F6D4E]( 0 ), f23_local1, GUNSMITH.defaultTag )
	local f23_local4 = WEAPON.GetWeaponClass( f23_arg0 )
	local f23_local5 = WEAPON.GetWeaponClass( f23_arg1 )
	if String.IsNilOrEmpty( f23_local4 ) then
		f23_local4 = WEAPON.ARClass
	end
	if String.IsNilOrEmpty( f23_local5 ) then
		f23_local5 = WEAPON.ARClass
	end
	if not f23_local2.xPosition or not f23_local3.xPosition then
		f0_local0( f23_local2 )
		f0_local0( f23_local3 )
	end
	local f23_local6 = GUNSMITH.defaultTag .. "," .. f23_local4 .. "," .. f23_local2.xPosition .. "," .. f23_local2.yPosition .. "," .. f23_local2.zPosition .. "," .. f23_local2.xAngle .. "," .. f23_local2.yAngle .. "," .. f23_local2.zAngle
	local f23_local7 = GUNSMITH.defaultTag .. "," .. f23_local5 .. "," .. f23_local3.xPosition .. "," .. f23_local3.yPosition .. "," .. f23_local3.zPosition .. "," .. f23_local3.xAngle .. "," .. f23_local3.yAngle .. "," .. f23_local3.zAngle
	local f23_local8 = CLIENT_MODEL.GetClientModelIndex( CLIENT_MODEL.coreMPModels.LETHAL )
	local f23_local9 = ClientModel[0x9088CC2C1E6A1E9]( f23_local8, CLIENT_MODEL.coreMPModels.LETHAL.tagAccessory )
	local f23_local10 = ClientModel[0x7FE4C5AFE1F4377]( f23_local8 )
	if not f23_local9.xPosition or not f23_local10.xAngle then
		f0_local0( f23_local9 )
		f0_local0( f23_local10 )
	end
	local f23_local11 = CLIENT_MODEL.GetClientModelIndex( CLIENT_MODEL.coreMPModels.TACTICAL )
	local f23_local12 = ClientModel[0x9088CC2C1E6A1E9]( f23_local11, CLIENT_MODEL.coreMPModels.TACTICAL.tagAccessory )
	local f23_local13 = ClientModel[0x7FE4C5AFE1F4377]( f23_local11 )
	if not f23_local12.xPosition or not f23_local13.xAngle then
		f0_local0( f23_local12 )
		f0_local0( f23_local13 )
	end
	Engine[0x6055C55456F05DF]( f23_local6 .. "," .. f23_local7 .. "," .. "tag_origin," .. f23_local9.xPosition .. "," .. f23_local9.yPosition .. "," .. f23_local9.zPosition .. "," .. f23_local10.xAngle .. "," .. f23_local10.yAngle .. "," .. f23_local10.zAngle .. "," .. "tag_origin," .. f23_local12.xPosition .. "," .. f23_local12.yPosition .. "," .. f23_local12.zPosition .. "," .. f23_local13.xAngle .. "," .. f23_local13.yAngle .. "," .. f23_local13.zAngle, 1 )
end

CLIENT_MODEL.SetLauncherCase = function ( f22_arg0, f22_arg1, f22_arg2 )
	f0_local0 = false
	local f22_local0 = 180
	if CONDITIONS.IsMobileOrMobileSim() then
		CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.GUN_CASE, CLIENT_MODEL.NO_CLIENT_MODEL )
		return false
	else
		local f22_local1
		if f22_arg1 == 0 then
			f22_local1 = CLIENT_MODEL.coreMPModels.PRIMARY_WEAPON_CASE
			if not f22_local1 then
			
			else
				for f22_local9, f22_local10 in pairs( CLIENT_MODEL.launcherCaseModels ) do
					if f22_local10.ref == f22_arg0 or f22_local10.useLootID and f22_local10.lootID == f22_arg2 then
						CLIENT_MODEL.SetModel( f22_local1, f22_local10.xmodelName )
						local f22_local5 = CLIENT_MODEL.GetClientModelIndex( f22_local1 )
						if f22_local5 and 0 <= f22_local5 then
							local f22_local6 = ClientModel[0x9088CC2C1E6A1E9]( f22_local5, CLIENT_MODEL.defaultTags.TAG_ORIGIN )
							local f22_local7 = ClientModel[0x7FE4C5AFE1F4377]( f22_local5, CLIENT_MODEL.defaultTags.INVALID )
							ClientModel[0x9C89C00DF9B85ED]( f22_local5, f22_local6 )
							local f22_local8
							if f22_arg1 == 0 and not f22_local0 then
								f22_local8 = f22_local0
							else
								f22_local8 = 0
							end
							f22_local7.yAngle = f22_local8
							ClientModel[0xEFA1738E096A743]( f22_local5, f22_local7 )
							ClientWeapon[0x59B77D6F41ED417]( f22_arg1, false )
							f0_local0 = true
							return true
						end
					end
				end
				CLIENT_MODEL.SetModel( f22_local1, CLIENT_MODEL.NO_CLIENT_MODEL )
				return false
			end
		end
	end
	f22_local1 = CLIENT_MODEL.coreMPModels.SECONDARY_WEAPON_CASE
end

local f0_local29 = function ( f21_arg0, f21_arg1 )
	for f21_local3, f21_local4 in pairs( CLIENT_MODEL.launcherCaseModels ) do
		if f21_local4.ref == f21_arg0 then
			return true
		elseif f21_local4.useLootID and f21_local4.lootID == f21_arg1 then
			return true
		end
	end
	return false
end

CLIENT_MODEL.GetGunCaseModelSize = function ( f20_arg0, f20_arg1, f20_arg2 )
	if f0_local0 == nil then
		f0_local0 = f0_local0( f20_arg0, f20_arg1 )
	end
	if f20_arg2 or f0_local0 then
		return CLIENT_MODEL.gunCaseSizes.LARGE_GUN_CASE
	elseif CONDITIONS.IsMobileOrMobileSim() then
		return CLIENT_MODEL.gunCaseSizes.SMALL_GUN_CASE
	elseif CoD.IsDMZMatch() then
		return CLIENT_MODEL.gunCaseSizes.LARGE_GUN_CASE
	else
		local f20_local0 = Engine[0x929CB0A3C5047D]( FrontEndScene.ClientWeapons.GunTablePrimary )
		local f20_local1 = Engine[0x929CB0A3C5047D]( FrontEndScene.ClientWeapons.GunTableSecondary )
		local f20_local2 = math.max( f20_local0.y, f20_local1.y )
		if f0_local0 < f20_local2 then
			return CLIENT_MODEL.gunCaseSizes.LARGE_GUN_CASE
		elseif f0_local0 < f20_local2 then
			return CLIENT_MODEL.gunCaseSizes.MEDIUM_GUN_CASE
		else
			return CLIENT_MODEL.gunCaseSizes.SMALL_GUN_CASE
		end
	end
end

CLIENT_MODEL.UpdateGunCase = function ( f18_arg0, f18_arg1, f18_arg2 )
	local f18_local0 = false
	if not CoD.IsDMZMatch() then
		f18_local0 = PERK.DoesPerkPackageContainOverkill( PERK.GetPerkPackageData( f18_arg0, f18_arg1.equippedPerkPackageIndex:get() ) )
	end
	local f18_local1
	if f18_arg2 then
		f18_local1 = f18_arg2
	else
		f18_local1 = f18_arg2.weapon
	end
	if not f18_local1 or not WEAPON.GetWeaponClass( f18_local1 ) then
		local f18_local2 = ""
	end
	local f18_local3 = f18_arg1.weaponSetups[FrontEndScene.ClientWeapons.GunTablePrimary]
	local f18_local4 = WEAPON.GetWeaponClass( f18_local3.weapon:get() )
	local f18_local5 = f18_local3.lootItemID:get()
	local f18_local6 = f18_arg1.weaponSetups[FrontEndScene.ClientWeapons.GunTableSecondary]
	local f18_local7 = WEAPON.GetWeaponClass( f18_local6.weapon:get() )
	local f18_local8 = f18_local6.lootItemID:get()
	local f18_local9 = false
	if f18_local7 == WEAPON.pistolClass then
		local f18_local10
		if not f18_arg2 then
			f18_local10 = f18_arg2
		else
			f18_local10 = WEAPON.GenerateWeaponTable( f18_local6 )
		end
		for f18_local14, f18_local15 in ipairs( f18_local10.attachments ) do
			if f18_local15.ref ~= ATTACHMENT.none and ATTACHMENT.GetCategory( f18_local15.ref ) == ATTACHMENT.backpieceCategory then
				f18_local9 = true
				break
			end
		end
	end
	if not CONDITIONS.IsMobileOrMobileSim() then
		local f18_local10 = CLIENT_MODEL.GetGunCaseModelSize( f18_local0 )
		local f18_local12 = function ()
			local f19_local0
			if f18_arg0 ~= WEAPON.MELEEClass and f18_arg0 ~= WEAPON.MELEEClass and f18_arg0 ~= WEAPON.MELEEClass then
				f19_local0 = false
			else
				f19_local0 = true
			end
			local f19_local1
			if f18_arg0 ~= WEAPON.Crossbow and f18_arg0 ~= WEAPON.Crossbow and f18_arg0 ~= WEAPON.Crossbow then
				f19_local1 = false
			else
				f19_local1 = true
			end
			local f19_local2
			if f18_arg0 ~= WEAPON.LAUNCHERClass and f18_arg0 ~= WEAPON.LAUNCHERClass then
				f19_local2 = false
			else
				f19_local2 = true
			end
			local f19_local3
			if f18_arg0 ~= WEAPON.ChainsawLootID and f18_arg0 ~= WEAPON.ChainsawLootID then
				f19_local3 = false
			else
				f19_local3 = true
			end
			local f19_local4
			if not f19_local0 then
				f19_local4 = f19_local0
			elseif not f19_local1 then
				f19_local4 = f19_local1
			elseif not f19_local2 then
				f19_local4 = f19_local2
			else
				f19_local4 = f19_local3
			end
			return f19_local4
		end
		
		if f18_local12() then
			f18_local10 = CLIENT_MODEL.gunCaseSizes.LARGE_GUN_CASE
		elseif f18_local9 then
			f18_local12 = f18_local10 + 1
			if 3 >= f18_local12 or not f18_local10 then
				f18_local10 = f18_local12
			end
		end
		Engine[0x6055C55456F05DF]( "swap_gun_foam", f18_local10 )
		if f18_local10 == CLIENT_MODEL.gunCaseSizes.SMALL_GUN_CASE then
			CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.GUN_CASE, CLIENT_MODEL.MILITARY_GUNTABLE_CASE_SMALL )
		elseif f18_local10 == CLIENT_MODEL.gunCaseSizes.MEDIUM_GUN_CASE then
			CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.GUN_CASE, CLIENT_MODEL.MILITARY_GUNTABLE_CASE_MEDIUM )
		else
			CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.GUN_CASE, CLIENT_MODEL.MILITARY_GUNTABLE_CASE_LARGE )
		end
	end
end

local f0_local30 = function ( f17_arg0, f17_arg1, f17_arg2, f17_arg3 )
	local f17_local0 = CLIENT_MODEL.GetClientModelIndex( f17_arg0 )
	if f17_arg2.initialized:GetValue( f17_arg1 ) == true then
		local f17_local1 = {
			xPosition = f17_arg2.xPosition:GetValue( f17_arg1 ),
			yPosition = f17_arg2.yPosition:GetValue( f17_arg1 ),
			zPosition = f17_arg2.zPosition:GetValue( f17_arg1 )
		}
		local f17_local2 = {
			xAngle = f17_arg2.xAngle:GetValue( f17_arg1 ),
			yAngle = f17_arg2.yAngle:GetValue( f17_arg1 ),
			zAngle = f17_arg2.zAngle:GetValue( f17_arg1 )
		}
		ClientModel[0x9C89C00DF9B85ED]( f17_local0, f17_local1 )
		ClientModel[0xEFA1738E096A743]( f17_local0, f17_local2 )
	else
		local f17_local1 = ClientModel[0x9088CC2C1E6A1E9]( f17_local0, CLIENT_MODEL.defaultTags.TAG_ORIGIN )
		local f17_local2 = ClientModel[0x7FE4C5AFE1F4377]( f17_local0 )
		f17_arg2.initialized:SetValue( f17_arg1, true )
		f17_arg2.xPosition:SetValue( f17_arg1, f17_local1.xPosition )
		f17_arg2.yPosition:SetValue( f17_arg1, f17_local1.yPosition )
		f17_arg2.zPosition:SetValue( f17_arg1, f17_local1.zPosition )
		f17_arg2.xAngle:SetValue( f17_arg1, f17_local2.xAngle )
		f17_arg2.yAngle:SetValue( f17_arg1, f17_local2.yAngle )
		f17_arg2.zAngle:SetValue( f17_arg1, f17_local2.zAngle )
	end
	local f17_local1 = ClientModel[0x9088CC2C1E6A1E9]( f17_local0, CLIENT_MODEL.defaultTags.TAG_ORIGIN )
	local f17_local2 = ClientModel[0x7FE4C5AFE1F4377]( f17_local0 )
	f17_local1.xPosition = f17_local1.xPosition + (f17_arg3[0x257B2401CA14926] or 0)
	f17_local1.yPosition = f17_local1.yPosition + (f17_arg3[0xD800395FD294E5D] or 0)
	f17_local1.zPosition = f17_local1.zPosition + (f17_arg3[0xC2C18F1A5EA6920] or 0)
	f17_local2.xAngle = f17_local2.xAngle + (f17_arg3[0x4B4FCC28FA5366E] or 0)
	f17_local2.yAngle = f17_local2.yAngle + (f17_arg3[0x5AC21538E69CD69] or 0)
	f17_local2.zAngle = f17_local2.zAngle + (f17_arg3[0xBFB7DBA3D43AC1B] or 0)
	ClientModel[0x9C89C00DF9B85ED]( f17_local0, f17_local1 )
	ClientModel[0xEFA1738E096A743]( f17_local0, f17_local2 )
end

CLIENT_MODEL.ApplyEquipmentOffsets = function ( f16_arg0, f16_arg1, f16_arg2 )
	local f16_local0 = PROJECT[0x802F28C6B2B37E5]()
	assert( f16_local0 )
	for f16_local5, f16_local6 in ipairs( f16_local0[0x45E3BF48C371980] ) do
		if f16_local6[0x8B6F2336E5960E5] ~= nil then
			local f16_local4 = Engine[0x6093D047200548]( 0x117605451D279D0 .. (f16_local6[0x8B6F2336E5960E5] or "") )
			if f16_local4 ~= nil then
				if f16_arg1 == f16_local4[0x4BCADBA8E631B86] and f0_local0 then
					f0_local0( CLIENT_MODEL.coreMPModels.LETHAL, f16_arg0, f0_local0, f16_local4 )
				end
				if f16_arg2 == f16_local4[0x4BCADBA8E631B86] and f0_local0 then
					f0_local0( CLIENT_MODEL.coreMPModels.TACTICAL, f16_arg0, f0_local0, f16_local4 )
				end
			end
		end
	end
end

CLIENT_MODEL.ApplyEquipmentOffsetsForRefs = function ( f15_arg0, f15_arg1, f15_arg2 )
	local f15_local0 = EQUIPMENT.GetBundleByRef( f15_arg1 )
	local f15_local1 = EQUIPMENT.GetBundleByRef( f15_arg2 )
	if f15_local0 and f0_local0 then
		f0_local0( CLIENT_MODEL.coreMPModels.LETHAL, f15_arg0, f0_local0, f15_local0 )
	elseif f15_local1 and f0_local0 then
		f0_local0( CLIENT_MODEL.coreMPModels.TACTICAL, f15_arg0, f0_local0, f15_local1 )
	end
end

local f0_local31 = function ()
	if DataSources.frontEnd.MP.CAC.loadoutEquipmentOffsets == nil then
		DataSources.frontEnd.MP.CAC.loadoutEquipmentOffsets = {}
		DataSources.frontEnd.MP.CAC.loadoutEquipmentOffsets.lethalOffset = LUI.DataSourceInGlobalModel.new( "frontEnd.MP.CAC.loadoutEquipmentOffsets.lethalOffset" )
		f0_local0 = DataSources.frontEnd.MP.CAC.loadoutEquipmentOffsets.lethalOffset
		f0_local0.initialized = LUI.DataSourceInGlobalModel.new( "frontEnd.MP.CAC.loadoutEquipmentOffsets.lethalOffset.initialized" )
		f0_local0.xPosition = LUI.DataSourceInGlobalModel.new( "frontEnd.MP.CAC.loadoutEquipmentOffsets.lethalOffset.xPosition" )
		f0_local0.yPosition = LUI.DataSourceInGlobalModel.new( "frontEnd.MP.CAC.loadoutEquipmentOffsets.lethalOffset.yPosition" )
		f0_local0.zPosition = LUI.DataSourceInGlobalModel.new( "frontEnd.MP.CAC.loadoutEquipmentOffsets.lethalOffset.zPosition" )
		f0_local0.xAngle = LUI.DataSourceInGlobalModel.new( "frontEnd.MP.CAC.loadoutEquipmentOffsets.lethalOffset.xAngle" )
		f0_local0.yAngle = LUI.DataSourceInGlobalModel.new( "frontEnd.MP.CAC.loadoutEquipmentOffsets.lethalOffset.yAngle" )
		f0_local0.zAngle = LUI.DataSourceInGlobalModel.new( "frontEnd.MP.CAC.loadoutEquipmentOffsets.lethalOffset.zAngle" )
		DataSources.frontEnd.MP.CAC.loadoutEquipmentOffsets.tacticalOffset = LUI.DataSourceInGlobalModel.new( "frontEnd.MP.CAC.loadoutEquipmentOffsets.tacticalOffset" )
		f0_local0 = DataSources.frontEnd.MP.CAC.loadoutEquipmentOffsets.tacticalOffset
		f0_local0.initialized = LUI.DataSourceInGlobalModel.new( "frontEnd.MP.CAC.loadoutEquipmentOffsets.tacticalOffset.initialized" )
		f0_local0.xPosition = LUI.DataSourceInGlobalModel.new( "frontEnd.MP.CAC.loadoutEquipmentOffsets.tacticalOffset.xPosition" )
		f0_local0.yPosition = LUI.DataSourceInGlobalModel.new( "frontEnd.MP.CAC.loadoutEquipmentOffsets.tacticalOffset.yPosition" )
		f0_local0.zPosition = LUI.DataSourceInGlobalModel.new( "frontEnd.MP.CAC.loadoutEquipmentOffsets.tacticalOffset.zPosition" )
		f0_local0.xAngle = LUI.DataSourceInGlobalModel.new( "frontEnd.MP.CAC.loadoutEquipmentOffsets.tacticalOffset.xAngle" )
		f0_local0.yAngle = LUI.DataSourceInGlobalModel.new( "frontEnd.MP.CAC.loadoutEquipmentOffsets.tacticalOffset.yAngle" )
		f0_local0.zAngle = LUI.DataSourceInGlobalModel.new( "frontEnd.MP.CAC.loadoutEquipmentOffsets.tacticalOffset.zAngle" )
	end
end

CLIENT_MODEL.UpdateModelsForLoadout = function ( f13_arg0, f13_arg1, f13_arg2 )
	local f13_local0 = LOADOUT.GetLoadoutSquadMember( f13_arg1 )
	local f13_local1 = f13_local0.loadouts[f13_arg2]
	f0_local0()
	local f13_local2 = EQUIPMENT.GetEquippedEquipment( f13_arg1, f13_arg2, EQUIPMENT[0x74F9D21004E6324][0x2B1AD16803854BB] )
	local f13_local3 = EQUIPMENT.GetEquippedEquipment( f13_arg1, f13_arg2, EQUIPMENT[0x74F9D21004E6324][0x731F3C21BFD3FF4] )
	local f13_local4 = EQUIPMENT.GetModel( f13_local2 )
	local f13_local5 = EQUIPMENT.GetModel( f13_local3 )
	local f13_local6 = EQUIPMENT.GetBundleByRef( f13_local2 )
	local f13_local7 = EQUIPMENT.GetBundleByRef( f13_local3 )
	local f13_local8
	if f13_local6 ~= nil then
		f13_local8 = f13_local6[0x4BCADBA8E631B86]
		if not f13_local8 then
		
		else
			local f13_local9
			if f13_local7 ~= nil then
				f13_local9 = f13_local7[0x4BCADBA8E631B86]
				if not f13_local9 then
				
				else
					f13_local4 = GL_HACK.OverrideIfEquipmentVariant( f13_arg1, f13_arg2, EQUIPMENT[0x74F9D21004E6324][0x2B1AD16803854BB], f13_local2, f13_local4 )
					f13_local5 = GL_HACK.OverrideIfEquipmentVariant( f13_arg1, f13_arg2, EQUIPMENT[0x74F9D21004E6324][0x731F3C21BFD3FF4], f13_local3, f13_local5 )
					CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.LETHAL, f13_local4 )
					CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.TACTICAL, f13_local5 )
					CLIENT_MODEL.UpdateGunCase( f13_arg1, f13_local1 )
					CLIENT_MODEL.ApplyEquipmentOffsets( f13_arg1, f13_local8, f13_local9 )
					CLIENT_MODEL.UpdatePatchClientModels( f13_arg0, f13_local1 )
					if PROGRESSION.IsSpecialistPerkUnlocked( f13_arg1 ) and 0 < LOADOUT.GetLoadoutUsingSpecialist( f13_arg1, f13_arg2 ) and not CONDITIONS.IsThirdGameMode() then
						CLIENT_MODEL.UpdatePatchSpecialistClientModels( f13_local1 )
					else
						CLIENT_MODEL.HidePatchSpecialistClientModels()
					end
				end
			end
			f13_local9 = ""
		end
	end
	f13_local8 = ""
end

CLIENT_MODEL.UpdatePatchClientModels = function ( f12_arg0, f12_arg1 )
	CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.PERK_PATCH, PERK.GetModel(), PERK.GetBundleByRef( f12_arg1.loadoutPerks[0]:get() ) )
	CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.PERK_ACTIVE_PATCH, PERK.GetModel(), PERK.GetBundleByRef( f12_arg1.loadoutPerks[1]:get() ) )
	CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.PERK_PASSIVE_PATCH, PERK.GetModel(), PERK.GetBundleByRef( f12_arg1.loadoutPerks[2]:get() ) )
end

CLIENT_MODEL.UpdatePatchSpecialistClientModels = function ( f11_arg0 )
	if f11_arg0.extraPerks then
		local f11_local0 = PERK.GetSpecialistModel( PERK.GetBundleByRef( f11_arg0.extraPerks[0]:get() ) )
		local f11_local1 = PERK.GetSpecialistModel( PERK.GetBundleByRef( f11_arg0.extraPerks[1]:get() ) )
		local f11_local2 = PERK.GetSpecialistModel( PERK.GetBundleByRef( f11_arg0.extraPerks[2]:get() ) )
		if f11_local0 == nil or #f11_local0 == 0 then
			f11_local0 = PERK.GetModel( PERK.GetBundleByRef( f11_arg0.extraPerks[0]:get() ) )
		end
		if f11_local1 == nil or #f11_local1 == 0 then
			f11_local2 = PERK.GetModel( PERK.GetBundleByRef( f11_arg0.extraPerks[1]:get() ) )
		end
		if f11_local2 == nil or #f11_local2 == 0 then
			f11_local2 = PERK.GetModel( PERK.GetBundleByRef( f11_arg0.extraPerks[3]:get() ) )
		end
		CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.PERK_PATCH_SPECIALIST, f11_local0 )
		CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.PERK_ACTIVE_PATCH_SPECIALIST, f11_local1 )
		CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.PERK_PASSIVE_PATCH_SPECIALIST, f11_local2 )
	end
end

CLIENT_MODEL.HidePerkModels = function ()
	CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.PERK_BAG, CLIENT_MODEL.NO_CLIENT_MODEL )
	CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.PERK_PATCH, CLIENT_MODEL.NO_CLIENT_MODEL )
	CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.PERK_ACTIVE_PATCH, CLIENT_MODEL.NO_CLIENT_MODEL )
	CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.PERK_PASSIVE_PATCH, CLIENT_MODEL.NO_CLIENT_MODEL )
	CLIENT_MODEL.HidePatchSpecialistClientModels()
end

CLIENT_MODEL.HidePatchSpecialistClientModels = function ()
	CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.PERK_PATCH_SPECIALIST, CLIENT_MODEL.NO_CLIENT_MODEL )
	CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.PERK_ACTIVE_PATCH_SPECIALIST, CLIENT_MODEL.NO_CLIENT_MODEL )
	CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.PERK_PASSIVE_PATCH_SPECIALIST, CLIENT_MODEL.NO_CLIENT_MODEL )
end

CLIENT_MODEL.InitPatchClientModels = function ( f7_arg0, f7_arg1 )
	if CONDITIONS.IsMobileOrMobileSim() then
		CLIENT_MODEL.HidePerkModels()
	end
	CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.PERK, f0_local0 )
	CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.PERK_ACTIVE, f0_local0 )
	CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.PERK_PASSIVE, f0_local0 )
	if PROGRESSION.IsSpecialistPerkUnlocked( f7_arg1 ) then
		CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.PERK_PATCH_SPECIALIST, f0_local0 )
		CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.PERK_ACTIVE_PATCH_SPECIALIST, f0_local0 )
		CLIENT_MODEL.SetModel( CLIENT_MODEL.coreMPModels.PERK_PASSIVE_PATCH_SPECIALIST, f0_local0 )
	else
		CLIENT_MODEL.HidePatchSpecialistClientModels()
	end
	local f7_local0 = f7_arg0:Wait( 5 )
	f7_local0.onComplete = function ()
		CLIENT_MODEL.SetModelAttachedOrigin( CLIENT_MODEL.coreMPModels.PERK, CLIENT_MODEL.coreMPModels.PERK_PATCH, CLIENT_MODEL.coreMPModels.PERK_PATCH.patchTag )
		CLIENT_MODEL.SetModelAttachedOrigin( CLIENT_MODEL.coreMPModels.PERK_ACTIVE, CLIENT_MODEL.coreMPModels.PERK_ACTIVE_PATCH, CLIENT_MODEL.coreMPModels.PERK_ACTIVE_PATCH.patchTag )
		CLIENT_MODEL.SetModelAttachedOrigin( CLIENT_MODEL.coreMPModels.PERK_PASSIVE, CLIENT_MODEL.coreMPModels.PERK_PASSIVE_PATCH, CLIENT_MODEL.coreMPModels.PERK_PASSIVE_PATCH.patchTag )
	end
	
end

CLIENT_MODEL.HideModels = function ( f6_arg0 )
	for f6_local3, f6_local4 in pairs( f6_arg0 ) do
		CLIENT_MODEL.SetAssetType( f6_local4, Enum[0x4D1082DFC9AF660][0x21C02428B499A24] )
		CLIENT_MODEL.SetModel( f6_local4, CLIENT_MODEL.NO_CLIENT_MODEL )
	end
end

CLIENT_MODEL.SetBattlePassModelsRequired = function ()
	CLIENT_MODEL.SetRequiredModifiables( CLIENT_MODEL.battlePassModels )
end

CLIENT_MODEL.InitBattlePassModels = function ()
	CLIENT_MODEL.SetModelsModifiable( CLIENT_MODEL.battlePassModels, true )
	CLIENT_MODEL.SetBattlePassModelsRequired()
	local f4_local0, f4_local1, f4_local2 = pairs( CLIENT_MODEL.battlePassModels )
	goto basicblock_4:
end

CLIENT_MODEL.HideAllBattlePassModels = function ()
	CLIENT_MODEL.HideModels( CLIENT_MODEL.battlePassModels )
end

CLIENT_MODEL.HideNonBGBattlepassModels = function ()
	CLIENT_MODEL.HideModels( {
		CLIENT_MODEL.battlePassModels.CHARACTER,
		CLIENT_MODEL.battlePassModels.ITEMS,
		CLIENT_MODEL.battlePassModels.VEHICLE,
		CLIENT_MODEL.battlePassModels.WEAPON
	} )
end

CLIENT_MODEL.HideBattlepassBGModels = function ()
	CLIENT_MODEL.HideModels( {
		CLIENT_MODEL.battlePassModels.CHARACTER_BG,
		CLIENT_MODEL.battlePassModels.ITEMS_BG,
		CLIENT_MODEL.battlePassModels.VEHICLE,
		CLIENT_MODEL.battlePassModels.WEAPON_BG
	} )
end

