-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 13-10-2025 14:16
local f0_local0 = 0.001
local f0_local1 = function ( f34_arg0, f34_arg1 )
	f34_arg0._action( f34_arg0._currentValue, f34_arg1 )
	f34_arg0._initialValue = f34_arg0._currentValue
end

local f0_local2 = function ( f33_arg0, f33_arg1, f33_arg2, f33_arg3 )
	local f33_local0 = f33_arg0._currentValue
	f33_arg0._currentValue = f33_arg1
	f33_arg0:UpdateContent()
	if not f33_arg0._applyable and f33_local0 ~= f33_arg1 and f33_arg0.autoFunctionCall then
		f33_arg0._action( f33_arg0._currentValue, f33_arg2 )
	end
	if f33_arg0._onRefresh then
		f33_arg0:_onRefresh( f33_arg2, f33_arg0._currentValue, f33_arg3 )
	end
end

local f0_local3 = function ( f32_arg0, f32_arg1 )
	if f32_arg0.dividedRangeValue == nil then
		f32_arg1 = f32_arg0.min + f32_arg0.step * math.floor( (f32_arg1 - f32_arg0.min) / f32_arg0.step + 0.5 )
	elseif f32_arg1 < f32_arg0.dividedRangeValue then
		f32_arg1 = f32_arg0.dividedRangeValue - f32_arg0.step * math.floor( (f32_arg0.dividedRangeValue - f32_arg1) / f32_arg0.step + 0.5 )
	elseif f32_arg0.dividedRangeValue < f32_arg1 then
		f32_arg1 = f32_arg0.dividedRangeValue + f32_arg0.dividedRangeStep * math.floor( (f32_arg1 - f32_arg0.dividedRangeValue) / f32_arg0.dividedRangeStep + 0.5 )
	end
	if f32_arg1 < f32_arg0.min then
		f32_arg1 = f32_arg1 + f32_arg0.step
	elseif f32_arg0.max < f32_arg1 then
		if f32_arg0.dividedRangeValue == nil then
			f32_arg1 = f32_arg1 - f32_arg0.step
		else
			f32_arg1 = f32_arg1 - f32_arg0.dividedRangeStep
		end
	end
	return f32_arg1
end

local f0_local4 = function ( f31_arg0, f31_arg1 )
	if f31_arg0.dividedRangeValue == nil then
		return f31_arg1 + f31_arg0.step
	elseif f31_arg0.dividedRangeValue - f31_arg0.step <= f31_arg1 and f31_arg1 < f31_arg0.dividedRangeValue then
		return f31_arg0.dividedRangeValue
	elseif f31_arg1 < f31_arg0.dividedRangeValue then
		return f31_arg1 + f31_arg0.step
	else
		return f31_arg1 + f31_arg0.dividedRangeStep
	end
end

local f0_local5 = function ( f30_arg0, f30_arg1 )
	if f30_arg0.dividedRangeValue == nil then
		return f30_arg1 - f30_arg0.step
	elseif f30_arg0.dividedRangeValue < f30_arg1 and f30_arg1 < f30_arg0.dividedRangeValue + f30_arg0.dividedRangeStep then
		return f30_arg0.dividedRangeValue
	elseif f30_arg1 < f30_arg0.dividedRangeValue then
		return f30_arg1 - f30_arg0.step
	else
		return f30_arg1 - f30_arg0.dividedRangeStep
	end
end

local f0_local6 = function ( f9_arg0, f9_arg1, f9_arg2 )
	assert( f9_arg2.action )
	assert( f9_arg0.min )
	assert( f9_arg0.max )
	assert( f9_arg0.UpdateContent )
	f9_arg0.wrapAround = f9_arg2.wrapAround ~= false
	f9_arg0.autoFunctionCall = f9_arg2.autoFunctionCall ~= false
	f9_arg0.decimalPlacesToRound = f9_arg2.decimalPlacesToRound
	f9_arg0._action = f9_arg2.action
	f9_arg0._defaultValueGetter = f9_arg2.defaultValueGetter
	f9_arg0._valueGetter = f9_arg2.valueGetter
	f9_arg0._onRefresh = f9_arg2.onRefresh
	f9_arg0._onReset = f9_arg2.onReset
	f9_arg0._onDependencyParentRefresh = f9_arg2.onDependencyParentRefresh
	f9_arg0._applyable = f9_arg2.applyable == true
	if not f9_arg2.defaultValue and f9_arg0._valueGetter then
		f9_arg0._currentValue = f9_arg0._valueGetter( f9_arg1 )
	else
		f9_arg0._currentValue = f9_arg2.defaultValue or f9_arg0.min
	end
	local f9_local0 = assert
	local f9_local1
	if f9_arg0.min - f0_local0 > f9_arg0._currentValue or f9_arg0._currentValue > f9_arg0.max + f0_local0 then
		f9_local1 = false
	else
		f9_local1 = true
	end
	f9_local0( f9_local1 )
	f9_arg0._initialValue = f9_arg0._currentValue
	f9_arg0:UpdateContent()
	if not f9_arg0.wrapAround then
		if f9_arg0._currentValue == f9_arg0.min then
			f9_arg0:processEvent( {
				name = "arrow_button_left_blocked"
			} )
		elseif f9_arg0._currentValue == f9_arg0.max then
			f9_arg0:processEvent( {
				name = "arrow_button_right_blocked"
			} )
		end
	end
	if not f9_arg0.autoFunctionCall then
		f9_arg0:addEventHandler( "button_action", function ( f29_arg0, f29_arg1 )
			f9_arg0._action( f9_arg0._currentValue, f29_arg1.controller )
		end )
	end
	f9_arg0.SetCurrentValue = function ( f28_arg0, f28_arg1, f28_arg2 )
		f9_arg0( f28_arg0, f28_arg1, f9_arg0, f28_arg2 )
	end
	
	if f9_arg0.initialized then
		return true
	end
	f9_arg0:registerEventHandler( "popup_inactive", function ( element, event )
		
	end )
	f9_local0 = function ( f26_arg0, f26_arg1 )
		if f26_arg0:IsDisabled() then
			return 
		end
		local f26_local0 = f9_arg0( f9_arg0, f9_arg0._currentValue )
		if f9_arg0.decimalPlacesToRound then
			f26_local0 = LUI.Round( f26_local0, f9_arg0.decimalPlacesToRound )
		end
		f26_local0 = math.max( f9_arg0.min, f26_local0 )
		if f9_arg0._currentValue <= f9_arg0.min then
			if f9_arg0.wrapAround then
				f26_local0 = f9_arg0.max
			else
				return 
			end
		end
		f26_local0 = f9_arg0( f9_arg0, f26_local0 )
		if f26_local0 == f9_arg0.min and not f9_arg0.wrapAround then
			f9_arg0:processEvent( {
				name = "arrow_button_left_blocked"
			} )
		else
			f9_arg0:processEvent( {
				name = "arrow_button_left_moved"
			} )
		end
		f9_arg0:processEvent( {
			name = "arrow_button_right_not_blocked"
		} )
		if f9_arg0.fillElement then
			Engine[0xC4146BA76D0F982]( SOUND_SETS.default.adjustSlider )
		else
			Engine[0xC4146BA76D0F982]( CoD.SFX.OtherAdjust )
		end
		f9_arg0( f9_arg0, f26_local0, f26_arg1.controller, true )
		return true
	end
	
	local f9_local2 = function ( f25_arg0, f25_arg1 )
		if f25_arg0:IsDisabled() then
			return 
		end
		local f25_local0 = f9_arg0( f9_arg0, f9_arg0._currentValue )
		if f9_arg0.decimalPlacesToRound then
			f25_local0 = LUI.Round( f25_local0, f9_arg0.decimalPlacesToRound )
		end
		f25_local0 = math.min( f9_arg0.max, f25_local0 )
		if f9_arg0._currentValue == f9_arg0.max then
			if f9_arg0.wrapAround then
				f25_local0 = f9_arg0.min
			else
				return 
			end
		end
		f25_local0 = f9_arg0( f9_arg0, f25_local0 )
		if f25_local0 == f9_arg0.max and not f9_arg0.wrapAround then
			f9_arg0:processEvent( {
				name = "arrow_button_right_blocked"
			} )
		else
			f9_arg0:processEvent( {
				name = "arrow_button_right_moved"
			} )
		end
		f9_arg0:processEvent( {
			name = "arrow_button_left_not_blocked"
		} )
		if f9_arg0.fillElement then
			Engine[0xC4146BA76D0F982]( SOUND_SETS.default.adjustSlider )
		else
			Engine[0xC4146BA76D0F982]( CoD.SFX.OtherAdjust )
		end
		f9_arg0( f9_arg0, f25_local0, f25_arg1.controller, true )
		return true
	end
	
	if f9_arg2.enableButtonInput ~= false then
		f9_arg0:AddGamepadEventCallback( "button_left", function ( f24_arg0, f24_arg1 )
			if f24_arg0:isInFocus() then
				return f9_arg0( f24_arg0, f24_arg1 )
			else
				
			end
		end )
		f9_arg0:AddGamepadEventCallback( "button_right", function ( f23_arg0, f23_arg1 )
			if f23_arg0:isInFocus() then
				return f9_arg0( f23_arg0, f23_arg1 )
			else
				
			end
		end )
	end
	if Dvar[0x9E5BE3B4BBA4E0E]( 0xD7862EAA83B3B27 ) then
		f9_arg0.ArrowLeft:addEventHandler( "button_action", f9_local0 )
		f9_arg0.ArrowRight:addEventHandler( "button_action", f9_local2 )
	else
		f9_arg0:addEventHandler( "left_arrow_clicked", f9_local0 )
		f9_arg0:addEventHandler( "right_arrow_clicked", f9_local2 )
	end
	f9_arg0:registerEventHandler( "refresh_values", function ( element, event )
		element:SetCurrentValue( element._currentValue )
		return true
	end )
	f9_arg0:registerEventHandler( "seek_value", function ( element, event )
		if element._valueGetter then
			element:SetCurrentValue( element._valueGetter( event.controllerIndex or f9_arg0 ) )
		end
	end )
	f9_arg0:addEventHandler( "update_initial_value", function ( f20_arg0, f20_arg1 )
		f9_arg0._initialValue = f9_arg0._currentValue
	end )
	f9_arg0:registerEventHandler( "reset_value", function ( element, event )
		if element._defaultValueGetter then
			element:SetCurrentValue( element._defaultValueGetter( event.controllerIndex or f9_arg0 ) )
			element:_onReset( event.controllerIndex )
		end
	end )
	f9_arg0:registerEventHandler( "apply_value", function ( element, event )
		if element._applyable then
			f9_arg0( f9_arg0, event.controllerIndex or f9_arg0 )
		end
	end )
	f9_arg0:registerEventHandler( "parent_value_changed", function ( element, event )
		if element._onDependencyParentRefresh then
			local f17_local0 = element:_onDependencyParentRefresh( event.controllerIndex or f9_arg0, element._currentValue, event.parentId, event.parentValue )
			if f17_local0 == true then
				element:_onRefresh( event.controllerIndex, element._currentValue )
			elseif f17_local0 ~= nil then
				element:SetCurrentValue( f17_local0 )
			end
		end
	end )
	f9_arg0:registerEventHandler( "refresh_option", function ( element, event )
		element:_onRefresh( event.controllerIndex, element._currentValue )
	end )
	f9_local1 = 350
	if f9_arg0.ArrowLeft then
		local f9_local3, f9_local4 = nil
		f9_local4 = function ()
			if f9_arg0.ArrowLeft.m_mouseOver and f9_arg0.ArrowLeft.m_leftMouseDown and f9_arg0.ArrowLeft:isInFocus() and not f9_arg0.ArrowLeft:IsDisabled() then
				f9_arg0:processEvent( {
					name = "left_arrow_clicked",
					controller = f9_arg0
				} )
				if not f9_arg0.clickRepeatDisabled then
					f9_arg0 = f9_arg0:Wait( f9_arg0 )
					f9_arg0.onComplete = f9_arg0
				end
			else
				f9_arg0 = nil
			end
		end
		
		f9_arg0.ArrowLeft:addEventHandler( "leftmousedown", function ()
			if f9_arg0 then
				f9_arg0.onComplete = function ()
					
				end
				
				f9_arg0 = nil
			end
			f9_arg0()
		end )
	end
	if f9_arg0.ArrowRight then
		local f9_local3, f9_local4 = nil
		f9_local4 = function ()
			if f9_arg0.ArrowRight.m_mouseOver and f9_arg0.ArrowRight.m_leftMouseDown and f9_arg0.ArrowRight:isInFocus() and not f9_arg0.ArrowRight:IsDisabled() then
				f9_arg0:processEvent( {
					name = "right_arrow_clicked",
					controller = f9_arg0
				} )
				if not f9_arg0.clickRepeatDisabled then
					f9_arg0 = f9_arg0:Wait( f9_arg0 )
					f9_arg0.onComplete = f9_arg0
				end
			else
				f9_arg0 = nil
			end
		end
		
		f9_arg0.ArrowRight:addEventHandler( "leftmousedown", function ()
			if f9_arg0 then
				f9_arg0.onComplete = function ()
					
				end
				
				f9_arg0 = nil
			end
			f9_arg0()
		end )
	end
	f9_arg0.initialized = true
end

LUI.AddUICustomArrowButtonLogic = function ( f8_arg0, f8_arg1, f8_arg2 )
	assert( f8_arg2.max )
	assert( f8_arg2.min )
	assert( f8_arg2.UpdateContent )
	f8_arg0.max = f8_arg2.max
	f8_arg0.min = f8_arg2.min
	f8_arg0.UpdateContent = f8_arg2.UpdateContent
	f8_arg0.step = f8_arg2.step or 1
	f0_local0( f8_arg0, f8_arg1, f8_arg2 )
end

local f0_local7 = function ( f7_arg0 )
	assert( f7_arg0.updateDuration )
	f7_arg0.Text:setText( f7_arg0._labels[f7_arg0._currentValue], f7_arg0.updateDuration )
	if f7_arg0.SetPipPosition and f7_arg0._currentValue then
		f7_arg0:SetPipPosition( f7_arg0._currentValue )
	end
end

LUI.AddUIArrowTextButtonLogic = function ( f6_arg0, f6_arg1, f6_arg2 )
	assert( f6_arg2.labels )
	assert( f6_arg0.Text )
	f6_arg0._labels = f6_arg2.labels
	f6_arg0.max = #f6_arg0._labels
	f6_arg0.min = 1
	f6_arg0.step = 1
	f6_arg0.updateDuration = f6_arg2.updateDuration or 0
	f6_arg0.UpdateContent = f6_arg2.UpdateContent or f0_local0
	f6_arg0:SetButtonDisabled( f6_arg0.max == f6_arg0.min )
	f0_local0( f6_arg0, f6_arg1, f6_arg2 )
end

ArrowBarFillDirections = {
	LEFT_TO_RIGHT,
	RIGHT_TO_LEFT
}
local f0_local8 = function ( f5_arg0 )
	local f5_local0 = assert
	local f5_local1
	if f5_arg0._currentValue > f5_arg0.max + f0_local0 or f5_arg0.min - f0_local0 > f5_arg0._currentValue then
		f5_local1 = false
	else
		f5_local1 = true
	end
	f5_local0( f5_local1 )
	assert( f5_arg0.updateDuration )
	f5_local0 = 0
	if f5_arg0.dividedRangeValue == nil then
		f5_local0 = (f5_arg0._currentValue - f5_arg0.min) / (f5_arg0.max - f5_arg0.min)
	elseif f5_arg0._currentValue <= f5_arg0.dividedRangeValue then
		f5_local0 = (f5_arg0._currentValue - f5_arg0.min) / (f5_arg0.dividedRangeValue - f5_arg0.min) * f5_arg0.dividedRangeFraction
	else
		f5_local0 = (f5_arg0._currentValue - f5_arg0.dividedRangeValue) / (f5_arg0.max - f5_arg0.dividedRangeValue) * (1 - f5_arg0.dividedRangeFraction) + f5_arg0.dividedRangeFraction
	end
	if f5_arg0.direction == ArrowBarFillDirections.LEFT_TO_RIGHT then
		f5_arg0.fillElement:SetAnchors( 0, 1 - f5_local0, 0, 0, f5_arg0.updateDuration )
		if f5_arg0.fillMarkerElement then
			f5_local2, f5_local1, f5_local3, f5_local4 = f5_arg0.fillMarkerElement:getLocalRect()
			local f5_local5 = (f5_local3 / _1080p - f5_local2 / _1080p) / 2
			f5_arg0.fillMarkerElement:SetAnchorsAndPosition( f5_local0, 1 - f5_local0, 0, 0, _1080p * -f5_local5, _1080p * f5_local5, 0, 0 )
		end
	else
		f5_arg0.fillElement:SetAnchors( 1 - f5_local0, 0, 0, 0, f5_arg0.updateDuration )
		if f5_arg0.fillMarkerElement then
			f5_local2, f5_local1, f5_local3, f5_local4 = f5_arg0.fillMarkerElement:getLocalRect()
			local f5_local5 = (f5_local3 / _1080p - f5_local2 / _1080p) / 2
			f5_arg0.fillMarkerElement:SetAnchorsAndPosition( 1 - f5_local0, f5_local0, 0, 0, _1080p * -f5_local5, _1080p * f5_local5, 0, 0 )
		end
	end
	if f5_arg0.showTextLabel then
		f5_arg0.Text:setText( string.format( "%.2f", f5_arg0._currentValue ), f5_arg0.updateDuration )
		f5_arg0.ShowNumberFunction( true )
	end
end

local f0_local9 = function ( f4_arg0, f4_arg1 )
	local f4_local0 = f4_arg1.percent
	local f4_local1 = f4_arg0.min
	if f4_arg0.dividedRangeValue == nil then
		f4_local1 = Lerp( f4_local0, f4_arg0.min, f4_arg0.max )
	elseif f4_local0 <= f4_arg0.dividedRangeFraction then
		f4_local1 = Lerp( f4_local0 / f4_arg0.dividedRangeFraction, f4_arg0.min, f4_arg0.dividedRangeValue )
	else
		f4_local1 = Lerp( (f4_local0 - f4_arg0.dividedRangeFraction) / (1 - f4_arg0.dividedRangeFraction), f4_arg0.dividedRangeValue, f4_arg0.max )
	end
	if f4_arg0.decimalPlacesToRound ~= nil then
		f4_local1 = LUI.Round( f4_local1, f4_arg0.decimalPlacesToRound )
	end
	if f4_arg0.snapToStep then
		f4_local1 = f0_local0( f4_arg0, f4_local1 )
	end
	f4_local1 = LUI.clamp( f4_local1, f4_arg0.min, f4_arg0.max )
	if f4_local1 == f4_arg0.min and not f4_arg0.wrapAround then
		f4_arg0:processEvent( {
			name = "arrow_button_left_blocked"
		} )
	else
		f4_arg0:processEvent( {
			name = "arrow_button_left_not_blocked"
		} )
	end
	if f4_local1 == f4_arg0.max and not f4_arg0.wrapAround then
		f4_arg0:processEvent( {
			name = "arrow_button_right_blocked"
		} )
	else
		f4_arg0:processEvent( {
			name = "arrow_button_right_not_blocked"
		} )
	end
	f4_arg0:SetCurrentValue( f4_local1 )
end

LUI.AddMouseSliderLogic = function ( f2_arg0 )
	local f2_local0 = function ( f3_arg0, f3_arg1 )
		if not f3_arg0:IsDisabled() then
			local f3_local0 = f3_arg0:getWidth()
			local f3_local1, f3_local2, f3_local3, f3_local4 = f3_arg0:getRect()
			f3_local1, f3_local2 = f3_arg1.root:PixelsToUnits( f3_local1, f3_local2 )
			local f3_local5, f3_local6 = f3_arg1.root:PixelsToUnits( f3_arg1.x, f3_arg1.y )
			f3_arg0:dispatchEventToParent( {
				name = "set_bar_fill_percent",
				percent = LUI.clamp( (f3_local5 - f3_local1) / f3_local0, 0, 1 )
			} )
		end
	end
	
	f2_arg0.GenericFillBar:SetHandleMouse( true )
	f2_arg0.GenericFillBar:registerEventHandler( "leftmousedown", f2_local0 )
	f2_arg0.GenericFillBar:registerEventHandler( "mousedrag", f2_local0 )
end

LUI.AddUIArrowFillBarButtonLogic = function ( f1_arg0, f1_arg1, f1_arg2 )
	assert( f1_arg2.fillElement )
	assert( f1_arg2.max )
	assert( f1_arg2.min )
	f1_arg0.fillElement = f1_arg2.fillElement
	f1_arg0.fillMarkerElement = f1_arg2.fillMarkerElement
	f1_arg0.max = f1_arg2.max
	f1_arg0.min = f1_arg2.min
	f1_arg0.step = f1_arg2.step or 1
	if Engine[0x575E9C5B9AAB6F4]() and f1_arg2.pcstep then
		f1_arg0.step = f1_arg2.pcstep
	end
	if f1_arg2.snapToStep == nil then
		f1_arg0.snapToStep = Engine[0x575E9C5B9AAB6F4]()
	else
		f1_arg0.snapToStep = f1_arg2.snapToStep
	end
	local f1_local0 = f1_arg2.direction
	if not f1_local0 then
		f1_local0 = ArrowBarFillDirections.LEFT_TO_RIGHT
	end
	f1_arg0.direction = f1_local0
	f1_local0 = assert
	local f1_local1
	if f1_arg0.direction ~= ArrowBarFillDirections.LEFT_TO_RIGHT and f1_arg0.direction ~= ArrowBarFillDirections.RIGHT_TO_LEFT then
		f1_local1 = false
	else
		f1_local1 = true
	end
	f1_local0( f1_local1 )
	f1_arg0.updateDuration = f1_arg2.updateDuration or 0
	f1_arg0.UpdateContent = f1_arg2.UpdateContent or f0_local0
	f1_arg0.showTextLabel = f1_arg2.showTextLabel
	f1_arg0.dividedRangeValue = f1_arg2.dividedRangeValue
	f1_arg0.dividedRangeFraction = f1_arg2.dividedRangeFraction or 0.5
	f1_arg0.dividedRangeStep = f1_arg2.dividedRangeStep or f1_arg0.step
	f1_local0 = assert
	if f1_arg0.dividedRangeValue ~= nil and (f1_arg0.min >= f1_arg0.dividedRangeValue or f1_arg0.dividedRangeValue >= f1_arg0.max) then
		f1_local1 = false
	else
		f1_local1 = true
	end
	f1_local0( f1_local1 )
	f1_local0 = assert
	if 0 >= f1_arg0.dividedRangeFraction or f1_arg0.dividedRangeFraction >= 1 then
		f1_local1 = false
	else
		f1_local1 = true
	end
	f1_local0( f1_local1 )
	f0_local0( f1_arg0, f1_arg1, f1_arg2 )
	f1_arg0:registerEventHandler( "set_bar_fill_percent", f0_local0 )
end

