-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 04-10-2025 21:43
module( ..., package.seeall )
require( "ui.widgets.AttachmentDot" )
local f0_local0 = function ( f16_arg0, f16_arg1, f16_arg2, f16_arg3, f16_arg4 )
	local f16_local0 = 0
	for f16_local1 = 1, ATTACHMENT.count, 1 do
		local f16_local4 = f16_arg3[f16_local1]
		if type( f16_arg3[f16_local1] ) == "table" then
			f16_local4 = f16_arg3[f16_local1].ref
		end
		if f16_local4 and f16_local4 ~= "none" then
			f16_local0 = f16_local0 + 1
		end
	end
	f16_arg0.currentAttachmentCount = f16_local0
	if f16_local0 == 0 then
		ACTIONS.AnimateSequence( f16_arg0, "Empty" )
		return 
	else
		ACTIONS.AnimateSequence( f16_arg0, "Fill" .. f16_local0 )
	end
end

local f0_local1 = function ( f15_arg0 )
	return f15_arg0.currentAttachmentCount
end

local f0_local2 = function ( f14_arg0, f14_arg1, f14_arg2 )
	f14_arg0.Setup = f0_local0
	f14_arg0.GetCurrentNumOfAttachments = f0_local0
	f14_arg0.currentAttachmentCount = 0
end

function MiniAttachments( menu, controller )
	local self = LUI.UIHorizontalStackedLayout.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 222 * _1080p, 0, 24 * _1080p )
	self.id = "MiniAttachments"
	self._animationSets = self._animationSets or {}
	self._sequences = self._sequences or {}
	self._sequenceLengths = self._sequenceLengths or {}
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	f1_local1 = LUI.ValidateControllerIndex( self, f1_local1 )
	local f1_local2 = self
	self:SetSpacing( -2 * _1080p )
	local Dot10 = nil
	
	Dot10 = MenuBuilder.BuildRegisteredType( "AttachmentDot", {
		controllerIndex = f1_local1
	} )
	Dot10.id = "Dot10"
	Dot10:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, 0, _1080p * 24, _1080p * -12, _1080p * 12 )
	self:addElement( Dot10 )
	self.Dot10 = Dot10
	
	local Dot9 = nil
	
	Dot9 = MenuBuilder.BuildRegisteredType( "AttachmentDot", {
		controllerIndex = f1_local1
	} )
	Dot9.id = "Dot9"
	Dot9:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, _1080p * 22, _1080p * 46, _1080p * -12, _1080p * 12 )
	self:addElement( Dot9 )
	self.Dot9 = Dot9
	
	local Dot8 = nil
	
	Dot8 = MenuBuilder.BuildRegisteredType( "AttachmentDot", {
		controllerIndex = f1_local1
	} )
	Dot8.id = "Dot8"
	Dot8:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, _1080p * 44, _1080p * 68, _1080p * -12, _1080p * 12 )
	self:addElement( Dot8 )
	self.Dot8 = Dot8
	
	local Dot7 = nil
	
	Dot7 = MenuBuilder.BuildRegisteredType( "AttachmentDot", {
		controllerIndex = f1_local1
	} )
	Dot7.id = "Dot7"
	Dot7:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, _1080p * 66, _1080p * 90, _1080p * -12, _1080p * 12 )
	self:addElement( Dot7 )
	self.Dot7 = Dot7
	
	local Dot6 = nil
	
	Dot6 = MenuBuilder.BuildRegisteredType( "AttachmentDot", {
		controllerIndex = f1_local1
	} )
	Dot6.id = "Dot6"
	Dot6:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, _1080p * 88, _1080p * 112, _1080p * -12, _1080p * 12 )
	self:addElement( Dot6 )
	self.Dot6 = Dot6
	
	local Dot5 = nil
	
	Dot5 = MenuBuilder.BuildRegisteredType( "AttachmentDot", {
		controllerIndex = f1_local1
	} )
	Dot5.id = "Dot5"
	Dot5:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, _1080p * 110, _1080p * 134, _1080p * -12, _1080p * 12 )
	self:addElement( Dot5 )
	self.Dot5 = Dot5
	
	local Dot4 = nil
	
	Dot4 = MenuBuilder.BuildRegisteredType( "AttachmentDot", {
		controllerIndex = f1_local1
	} )
	Dot4.id = "Dot4"
	Dot4:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, _1080p * 132, _1080p * 156, _1080p * -12, _1080p * 12 )
	self:addElement( Dot4 )
	self.Dot4 = Dot4
	
	local Dot3 = nil
	
	Dot3 = MenuBuilder.BuildRegisteredType( "AttachmentDot", {
		controllerIndex = f1_local1
	} )
	Dot3.id = "Dot3"
	Dot3:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, _1080p * 154, _1080p * 178, _1080p * -12, _1080p * 12 )
	self:addElement( Dot3 )
	self.Dot3 = Dot3
	
	local Dot2 = nil
	
	Dot2 = MenuBuilder.BuildRegisteredType( "AttachmentDot", {
		controllerIndex = f1_local1
	} )
	Dot2.id = "Dot2"
	Dot2:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, _1080p * 176, _1080p * 200, _1080p * -12, _1080p * 12 )
	self:addElement( Dot2 )
	self.Dot2 = Dot2
	
	local Dot1 = nil
	
	Dot1 = MenuBuilder.BuildRegisteredType( "AttachmentDot", {
		controllerIndex = f1_local1
	} )
	Dot1.id = "Dot1"
	Dot1:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, _1080p * 198, _1080p * 222, _1080p * -12, _1080p * 12 )
	self:addElement( Dot1 )
	self.Dot1 = Dot1
	
	local f1_local13 = nil
	Dot10:RegisterAnimationSequence( "DefaultSequence", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot9:RegisterAnimationSequence( "DefaultSequence", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot8:RegisterAnimationSequence( "DefaultSequence", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot7:RegisterAnimationSequence( "DefaultSequence", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot6:RegisterAnimationSequence( "DefaultSequence", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot5:RegisterAnimationSequence( "DefaultSequence", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot4:RegisterAnimationSequence( "DefaultSequence", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot3:RegisterAnimationSequence( "DefaultSequence", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot2:RegisterAnimationSequence( "DefaultSequence", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot1:RegisterAnimationSequence( "DefaultSequence", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	self._sequences.DefaultSequence = function ()
		menu:AnimateSequence( "DefaultSequence" )
		menu:AnimateSequence( "DefaultSequence" )
		menu:AnimateSequence( "DefaultSequence" )
		menu:AnimateSequence( "DefaultSequence" )
		menu:AnimateSequence( "DefaultSequence" )
		menu:AnimateSequence( "DefaultSequence" )
		menu:AnimateSequence( "DefaultSequence" )
		menu:AnimateSequence( "DefaultSequence" )
		menu:AnimateSequence( "DefaultSequence" )
		menu:AnimateSequence( "DefaultSequence" )
	end
	
	self._sequenceLengths.DefaultSequence = 0
	local f1_local14 = nil
	Dot10:RegisterAnimationSequence( "Fill1", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot9:RegisterAnimationSequence( "Fill1", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot8:RegisterAnimationSequence( "Fill1", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot7:RegisterAnimationSequence( "Fill1", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot6:RegisterAnimationSequence( "Fill1", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot5:RegisterAnimationSequence( "Fill1", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot4:RegisterAnimationSequence( "Fill1", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot3:RegisterAnimationSequence( "Fill1", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot2:RegisterAnimationSequence( "Fill1", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot1:RegisterAnimationSequence( "Fill1", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	self._sequences.Fill1 = function ()
		menu:AnimateSequence( "Fill1" )
		menu:AnimateSequence( "Fill1" )
		menu:AnimateSequence( "Fill1" )
		menu:AnimateSequence( "Fill1" )
		menu:AnimateSequence( "Fill1" )
		menu:AnimateSequence( "Fill1" )
		menu:AnimateSequence( "Fill1" )
		menu:AnimateSequence( "Fill1" )
		menu:AnimateSequence( "Fill1" )
		menu:AnimateSequence( "Fill1" )
	end
	
	self._sequenceLengths.Fill1 = 0
	local f1_local15 = nil
	Dot10:RegisterAnimationSequence( "Fill2", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot9:RegisterAnimationSequence( "Fill2", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot8:RegisterAnimationSequence( "Fill2", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot7:RegisterAnimationSequence( "Fill2", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot6:RegisterAnimationSequence( "Fill2", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot5:RegisterAnimationSequence( "Fill2", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot4:RegisterAnimationSequence( "Fill2", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot3:RegisterAnimationSequence( "Fill2", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot2:RegisterAnimationSequence( "Fill2", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot1:RegisterAnimationSequence( "Fill2", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	self._sequences.Fill2 = function ()
		menu:AnimateSequence( "Fill2" )
		menu:AnimateSequence( "Fill2" )
		menu:AnimateSequence( "Fill2" )
		menu:AnimateSequence( "Fill2" )
		menu:AnimateSequence( "Fill2" )
		menu:AnimateSequence( "Fill2" )
		menu:AnimateSequence( "Fill2" )
		menu:AnimateSequence( "Fill2" )
		menu:AnimateSequence( "Fill2" )
		menu:AnimateSequence( "Fill2" )
	end
	
	self._sequenceLengths.Fill2 = 0
	local f1_local16 = nil
	Dot10:RegisterAnimationSequence( "Fill3", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot9:RegisterAnimationSequence( "Fill3", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot8:RegisterAnimationSequence( "Fill3", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot7:RegisterAnimationSequence( "Fill3", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot6:RegisterAnimationSequence( "Fill3", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot5:RegisterAnimationSequence( "Fill3", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot4:RegisterAnimationSequence( "Fill3", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot3:RegisterAnimationSequence( "Fill3", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot2:RegisterAnimationSequence( "Fill3", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot1:RegisterAnimationSequence( "Fill3", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	self._sequences.Fill3 = function ()
		menu:AnimateSequence( "Fill3" )
		menu:AnimateSequence( "Fill3" )
		menu:AnimateSequence( "Fill3" )
		menu:AnimateSequence( "Fill3" )
		menu:AnimateSequence( "Fill3" )
		menu:AnimateSequence( "Fill3" )
		menu:AnimateSequence( "Fill3" )
		menu:AnimateSequence( "Fill3" )
		menu:AnimateSequence( "Fill3" )
		menu:AnimateSequence( "Fill3" )
	end
	
	self._sequenceLengths.Fill3 = 0
	local f1_local17 = nil
	Dot10:RegisterAnimationSequence( "Fill4", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot9:RegisterAnimationSequence( "Fill4", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot8:RegisterAnimationSequence( "Fill4", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot7:RegisterAnimationSequence( "Fill4", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot6:RegisterAnimationSequence( "Fill4", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot5:RegisterAnimationSequence( "Fill4", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot4:RegisterAnimationSequence( "Fill4", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot3:RegisterAnimationSequence( "Fill4", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot2:RegisterAnimationSequence( "Fill4", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot1:RegisterAnimationSequence( "Fill4", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	self._sequences.Fill4 = function ()
		menu:AnimateSequence( "Fill4" )
		menu:AnimateSequence( "Fill4" )
		menu:AnimateSequence( "Fill4" )
		menu:AnimateSequence( "Fill4" )
		menu:AnimateSequence( "Fill4" )
		menu:AnimateSequence( "Fill4" )
		menu:AnimateSequence( "Fill4" )
		menu:AnimateSequence( "Fill4" )
		menu:AnimateSequence( "Fill4" )
		menu:AnimateSequence( "Fill4" )
	end
	
	self._sequenceLengths.Fill4 = 0
	local f1_local18 = nil
	Dot10:RegisterAnimationSequence( "Fill5", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot9:RegisterAnimationSequence( "Fill5", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot8:RegisterAnimationSequence( "Fill5", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot7:RegisterAnimationSequence( "Fill5", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot6:RegisterAnimationSequence( "Fill5", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot5:RegisterAnimationSequence( "Fill5", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot4:RegisterAnimationSequence( "Fill5", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot3:RegisterAnimationSequence( "Fill5", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot2:RegisterAnimationSequence( "Fill5", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot1:RegisterAnimationSequence( "Fill5", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	self._sequences.Fill5 = function ()
		menu:AnimateSequence( "Fill5" )
		menu:AnimateSequence( "Fill5" )
		menu:AnimateSequence( "Fill5" )
		menu:AnimateSequence( "Fill5" )
		menu:AnimateSequence( "Fill5" )
		menu:AnimateSequence( "Fill5" )
		menu:AnimateSequence( "Fill5" )
		menu:AnimateSequence( "Fill5" )
		menu:AnimateSequence( "Fill5" )
		menu:AnimateSequence( "Fill5" )
	end
	
	self._sequenceLengths.Fill5 = 0
	local f1_local19 = nil
	Dot10:RegisterAnimationSequence( "Empty", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot9:RegisterAnimationSequence( "Empty", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot8:RegisterAnimationSequence( "Empty", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot7:RegisterAnimationSequence( "Empty", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot6:RegisterAnimationSequence( "Empty", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot5:RegisterAnimationSequence( "Empty", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot4:RegisterAnimationSequence( "Empty", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot3:RegisterAnimationSequence( "Empty", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot2:RegisterAnimationSequence( "Empty", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot1:RegisterAnimationSequence( "Empty", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	self._sequences.Empty = function ()
		menu:AnimateSequence( "Empty" )
		menu:AnimateSequence( "Empty" )
		menu:AnimateSequence( "Empty" )
		menu:AnimateSequence( "Empty" )
		menu:AnimateSequence( "Empty" )
		menu:AnimateSequence( "Empty" )
		menu:AnimateSequence( "Empty" )
		menu:AnimateSequence( "Empty" )
		menu:AnimateSequence( "Empty" )
		menu:AnimateSequence( "Empty" )
	end
	
	self._sequenceLengths.Empty = 0
	local f1_local20 = nil
	Dot10:RegisterAnimationSequence( "Fill6", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot9:RegisterAnimationSequence( "Fill6", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot8:RegisterAnimationSequence( "Fill6", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot7:RegisterAnimationSequence( "Fill6", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot6:RegisterAnimationSequence( "Fill6", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot5:RegisterAnimationSequence( "Fill6", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot4:RegisterAnimationSequence( "Fill6", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot3:RegisterAnimationSequence( "Fill6", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot2:RegisterAnimationSequence( "Fill6", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot1:RegisterAnimationSequence( "Fill6", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	self._sequences.Fill6 = function ()
		menu:AnimateSequence( "Fill6" )
		menu:AnimateSequence( "Fill6" )
		menu:AnimateSequence( "Fill6" )
		menu:AnimateSequence( "Fill6" )
		menu:AnimateSequence( "Fill6" )
		menu:AnimateSequence( "Fill6" )
		menu:AnimateSequence( "Fill6" )
		menu:AnimateSequence( "Fill6" )
		menu:AnimateSequence( "Fill6" )
		menu:AnimateSequence( "Fill6" )
	end
	
	self._sequenceLengths.Fill6 = 0
	local f1_local21 = nil
	Dot10:RegisterAnimationSequence( "Fill7", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot9:RegisterAnimationSequence( "Fill7", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot8:RegisterAnimationSequence( "Fill7", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot7:RegisterAnimationSequence( "Fill7", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot6:RegisterAnimationSequence( "Fill7", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot5:RegisterAnimationSequence( "Fill7", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot4:RegisterAnimationSequence( "Fill7", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot3:RegisterAnimationSequence( "Fill7", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot2:RegisterAnimationSequence( "Fill7", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot1:RegisterAnimationSequence( "Fill7", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	self._sequences.Fill7 = function ()
		menu:AnimateSequence( "Fill7" )
		menu:AnimateSequence( "Fill7" )
		menu:AnimateSequence( "Fill7" )
		menu:AnimateSequence( "Fill7" )
		menu:AnimateSequence( "Fill7" )
		menu:AnimateSequence( "Fill7" )
		menu:AnimateSequence( "Fill7" )
		menu:AnimateSequence( "Fill7" )
		menu:AnimateSequence( "Fill7" )
		menu:AnimateSequence( "Fill7" )
	end
	
	self._sequenceLengths.Fill7 = 0
	local f1_local22 = nil
	Dot10:RegisterAnimationSequence( "Fill8", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot9:RegisterAnimationSequence( "Fill8", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot8:RegisterAnimationSequence( "Fill8", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot7:RegisterAnimationSequence( "Fill8", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot6:RegisterAnimationSequence( "Fill8", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot5:RegisterAnimationSequence( "Fill8", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot4:RegisterAnimationSequence( "Fill8", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot3:RegisterAnimationSequence( "Fill8", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot2:RegisterAnimationSequence( "Fill8", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot1:RegisterAnimationSequence( "Fill8", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	self._sequences.Fill8 = function ()
		menu:AnimateSequence( "Fill8" )
		menu:AnimateSequence( "Fill8" )
		menu:AnimateSequence( "Fill8" )
		menu:AnimateSequence( "Fill8" )
		menu:AnimateSequence( "Fill8" )
		menu:AnimateSequence( "Fill8" )
		menu:AnimateSequence( "Fill8" )
		menu:AnimateSequence( "Fill8" )
		menu:AnimateSequence( "Fill8" )
		menu:AnimateSequence( "Fill8" )
	end
	
	self._sequenceLengths.Fill8 = 0
	local f1_local23 = nil
	Dot10:RegisterAnimationSequence( "Fill9", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Hidden
		}
	} )
	Dot9:RegisterAnimationSequence( "Fill9", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot8:RegisterAnimationSequence( "Fill9", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot7:RegisterAnimationSequence( "Fill9", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot6:RegisterAnimationSequence( "Fill9", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot5:RegisterAnimationSequence( "Fill9", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot4:RegisterAnimationSequence( "Fill9", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot3:RegisterAnimationSequence( "Fill9", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot2:RegisterAnimationSequence( "Fill9", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot1:RegisterAnimationSequence( "Fill9", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	self._sequences.Fill9 = function ()
		menu:AnimateSequence( "Fill9" )
		menu:AnimateSequence( "Fill9" )
		menu:AnimateSequence( "Fill9" )
		menu:AnimateSequence( "Fill9" )
		menu:AnimateSequence( "Fill9" )
		menu:AnimateSequence( "Fill9" )
		menu:AnimateSequence( "Fill9" )
		menu:AnimateSequence( "Fill9" )
		menu:AnimateSequence( "Fill9" )
		menu:AnimateSequence( "Fill9" )
	end
	
	self._sequenceLengths.Fill9 = 0
	local f1_local24 = nil
	Dot10:RegisterAnimationSequence( "Fill10", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot9:RegisterAnimationSequence( "Fill10", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot8:RegisterAnimationSequence( "Fill10", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot7:RegisterAnimationSequence( "Fill10", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot6:RegisterAnimationSequence( "Fill10", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot5:RegisterAnimationSequence( "Fill10", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot4:RegisterAnimationSequence( "Fill10", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot3:RegisterAnimationSequence( "Fill10", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot2:RegisterAnimationSequence( "Fill10", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	Dot1:RegisterAnimationSequence( "Fill10", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Visibility,
			value = LUI.Visibility.Visible
		}
	} )
	self._sequences.Fill10 = function ()
		menu:AnimateSequence( "Fill10" )
		menu:AnimateSequence( "Fill10" )
		menu:AnimateSequence( "Fill10" )
		menu:AnimateSequence( "Fill10" )
		menu:AnimateSequence( "Fill10" )
		menu:AnimateSequence( "Fill10" )
		menu:AnimateSequence( "Fill10" )
		menu:AnimateSequence( "Fill10" )
		menu:AnimateSequence( "Fill10" )
		menu:AnimateSequence( "Fill10" )
	end
	
	self._sequenceLengths.Fill10 = 0
	f0_local0( self, f1_local1, controller )
	ACTIONS.AnimateSequence( self, "DefaultSequence" )
	return self
end

MenuBuilder.registerType( "MiniAttachments", MiniAttachments )
LockTable( _M )
