-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 04-10-2025 21:43
module( ..., package.seeall )
local f0_local0 = function ( f9_arg0, f9_arg1, f9_arg2 )
	if IsLanguageJapanese() then
		ACTIONS.AnimateSequence( f9_arg0, "JP" )
	end
	if IsLanguageArabic() then
		ACTIONS.AnimateSequence( f9_arg0, "AR" )
	end
end

function MouseCursorContextualMenuAction( menu, controller )
	local self = LUI.UIButton.new()
	self:SetAnchorsAndPosition( 0.5, 0.5, 0.5, 0.5, -150 * _1080p, 150 * _1080p, -15 * _1080p, 15 * _1080p )
	self.id = "MouseCursorContextualMenuAction"
	self._animationSets = self._animationSets or {}
	self._sequences = self._sequences or {}
	self._sequenceLengths = self._sequenceLengths or {}
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	f1_local1 = LUI.ValidateControllerIndex( self, f1_local1 )
	local f1_local2 = self
	local Background = nil
	
	Background = LUI.UIImage.new()
	Background.id = "Background"
	Background:SetRGBFromTable( SWATCHES.genericMenu.objectiveComplete, 0 )
	Background:SetAlpha( 0, 0 )
	self:addElement( Background )
	self.Background = Background
	
	local Keybind = nil
	
	Keybind = LUI.UIStyledText.new()
	Keybind.id = "Keybind"
	Keybind:SetRGBFromTable( SWATCHES.text.primaryText, 0 )
	Keybind:SetHorizontalPivot( LUI.HorizontalPivot.Right )
	Keybind:setText( "", 0 )
	Keybind:SetFont( FONTS.GetFont( FONTS.MainRegular.File ) )
	Keybind:SetFontSize( 24 * _PT )
	Keybind:SetMinFontSize( 24 * _PT )
	Keybind:SetWordWrap( false )
	Keybind:SetAlignment( LUI.Alignment.Right )
	Keybind:SetVerticalAlignment( LUI.Alignment.Center )
	Keybind:SetOptOutRightToLeftAlignmentFlip( true )
	Keybind:SetAnchorsAndPosition( 1, 0, 0.5, 0.5, _1080p * -86, _1080p * -16, _1080p * -13, _1080p * 11 )
	self:addElement( Keybind )
	self.Keybind = Keybind
	
	local ActionName = nil
	
	ActionName = LUI.UIStyledText.new()
	ActionName.id = "ActionName"
	ActionName:SetRGBFromTable( SWATCHES.text.vTextOffWhite, 0 )
	ActionName:setText( "", 0 )
	ActionName:SetFont( FONTS.GetFont( FONTS.MainRegular.File ) )
	ActionName:SetFontSize( 20 * _PT )
	ActionName:SetMinFontSize( 20 * _PT )
	ActionName:SetWordWrap( false )
	ActionName:SetLeading( -2 * _1080p, 0 )
	ActionName:SetAlignment( LUI.Alignment.Left )
	ActionName:SetAutoScroll( AUTOSCROLL.enabled_default )
	ActionName:SetAutoScrollStyle( LUI.UIStyledText.AutoScrollStyle.ScrollH )
	ActionName:SetAnchorsAndPosition( 0, 0, 0.5, 0.5, _1080p * 16, _1080p * -16, _1080p * -8, _1080p * 10 )
	self:addElement( ActionName )
	self.ActionName = ActionName
	
	local f1_local6 = nil
	Background:RegisterAnimationSequence( "DefaultSequence", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	ActionName:RegisterAnimationSequence( "DefaultSequence", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Text_Style_Vertical_Alignment,
			value = LUI.Alignment.Center
		}
	} )
	self._sequences.DefaultSequence = function ()
		menu:AnimateSequence( "DefaultSequence" )
		menu:AnimateSequence( "DefaultSequence" )
	end
	
	self._sequenceLengths.DefaultSequence = 0
	local f1_local7 = nil
	Background:RegisterAnimationSequence( "ButtonOver", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Material,
			value = RegisterMaterial( "ui_default_white" )
		},
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Left
		},
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Right
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.text.vTextOffWhite
		},
		{
			value = 5.289447516E-315,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	ActionName:RegisterAnimationSequence( "ButtonOver", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.text.buttonTextHighlighted
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Text_Style_Vertical_Alignment,
			value = LUI.Alignment.Center
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Text_Style_Font,
			value = FONTS.MainBold.File
		}
	} )
	self._sequences.ButtonOver = function ()
		menu:AnimateSequence( "ButtonOver" )
		menu:AnimateSequence( "ButtonOver" )
	end
	
	self._sequenceLengths.ButtonOver = 0
	local f1_local8 = nil
	Background:RegisterAnimationSequence( "ButtonUp", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	ActionName:RegisterAnimationSequence( "ButtonUp", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Text_Style_Font,
			value = FONTS.MainRegular.File
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.text.primaryText
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Text_Style_Vertical_Alignment,
			value = LUI.Alignment.Center
		}
	} )
	self._sequences.ButtonUp = function ()
		menu:AnimateSequence( "ButtonUp" )
		menu:AnimateSequence( "ButtonUp" )
	end
	
	self._sequenceLengths.ButtonUp = 0
	local f1_local9 = nil
	ActionName:RegisterAnimationSequence( "JP", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * -54
		}
	} )
	self._sequences.JP = function ()
		menu:AnimateSequence( "JP" )
		menu:SetWordWrap( true )
	end
	
	self._sequenceLengths.JP = 0
	local f1_local10 = nil
	f1_local10 = {}
	self._sequences.AR = function ()
		menu:SetOptOutRightToLeftAlignmentFlip( true )
	end
	
	self._sequenceLengths.AR = 0
	self:addEventHandler( "button_over", function ( f3_arg0, f3_arg1 )
		local f3_local0 = f3_arg1.controller or menu
		ACTIONS.AnimateSequence( menu, "ButtonOver", menu )
	end )
	self:addEventHandler( "button_up", function ( f2_arg0, f2_arg1 )
		local f2_local0 = f2_arg1.controller or menu
		ACTIONS.AnimateSequence( menu, "ButtonUp", menu )
	end )
	f0_local0( self, f1_local1, controller )
	ACTIONS.AnimateSequence( self, "DefaultSequence" )
	return self
end

MenuBuilder.registerType( "MouseCursorContextualMenuAction", MouseCursorContextualMenuAction )
LockTable( _M )
