-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 04-10-2025 21:43
module( ..., package.seeall )
local f0_local0 = function ( f3_arg0, f3_arg1, f3_arg2 )
	local f3_local0 = function ( f4_arg0, f4_arg1 )
		local f4_local0 = "v_ui_icon_chatMessaging"
		local f4_local1 = Engine[0x363C9B5AE5CC5ED]( f4_arg1.controllerIndex ) == LUI.INPUT_TYPE.gamepad
		if f4_local1 then
			f4_local0 = "button_select"
			if (Engine[0xDB367F0BBBFBABA]( f3_arg0 ) or Engine[0x2AB3689798DD031]( f3_arg0 )) and not Engine[0xFB1B6E36ABE59B8]() then
				f4_local0 = f4_local0 .. "_ps4"
			end
		end
		if not Engine[0x7B17D94988FD5D0]( "textChatEnabled", f4_arg1.controllerIndex ) and not f4_local1 then
			f4_local0 = f4_local0 .. "_disabled"
		end
		f4_arg0.ChatButton:setImage( RegisterMaterial( f4_local0 ), 0 )
	end
	
	f3_arg0:registerAndCallEventHandler( "update_input_type", f3_local0, {
		controllerIndex = f3_arg1
	} )
	f3_arg0.UpdateInputType = f3_local0
end

function TextChatButton( menu, controller )
	local self = LUI.UIButton.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 32 * _1080p, 0, 32 * _1080p )
	self.id = "TextChatButton"
	self._animationSets = self._animationSets or {}
	self._sequences = self._sequences or {}
	self._sequenceLengths = self._sequenceLengths or {}
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine[0x12586A3F4FB490E]() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1, "Missing controllerIndex!" )
	local f1_local2 = self
	local ChatButton = nil
	
	ChatButton = LUI.UIImage.new()
	ChatButton.id = "ChatButton"
	ChatButton:SetRGBFromTable( SWATCHES.text.vTextOffWhite, 0 )
	ChatButton:setImage( RegisterMaterial( "v_ui_icon_chatmessaging" ), 0 )
	self:addElement( ChatButton )
	self.ChatButton = ChatButton
	
	local f1_local4 = nil
	ChatButton:RegisterAnimationSequence( "DefaultSequence", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.genericButton.contentFocus
		},
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.DefaultSequence = function ()
		menu:AnimateSequence( "DefaultSequence" )
	end
	
	self._sequenceLengths.DefaultSequence = 0
	f0_local0( self, f1_local1, controller )
	ACTIONS.AnimateSequence( self, "DefaultSequence" )
	return self
end

MenuBuilder.registerType( "TextChatButton", TextChatButton )
LockTable( _M )
