-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 13-07-2025 21:51
module( ..., package.seeall )
local f0_local0 = 190
local f0_local1 = 250
local f0_local2 = function ( f32_arg0, f32_arg1, f32_arg2 )
	if not f32_arg0._isPlayingDismiss then
		ACTIONS.AnimateSequence( f32_arg0, f32_arg2 )
	end
end

local f0_local3 = function ( f17_arg0, f17_arg1 )
	assert( f17_arg0.Text )
	assert( f17_arg0.InteractiveObjectButtonIcon )
	local f17_local0 = f17_arg0.Text
	f17_local0:SetShadowUOffset( -0.001 )
	f17_local0:SetShadowVOffset( -0.001 )
	f17_arg0.UniqueImageSet = false
	if Engine.BGGJFFFAFG( f17_arg1 ) then
		ACTIONS.AnimateSequence( f17_arg0, "KeyboardOff" )
	else
		ACTIONS.AnimateSequence( f17_arg0, "KeyboardOn" )
	end
	if IsLanguageJapanese( f17_arg0 ) then
		ACTIONS.AnimateSequence( f17_arg0, "JA" )
	elseif IsLanguageArabic( f17_arg0 ) then
		ACTIONS.AnimateSequence( f17_arg0, "AR" )
	end
	local f17_local1 = DataSources.inGame.HUD.hints.interactiveObject.button.targetEntity:GetModel( f17_arg1 )
	local f17_local2 = function ()
		return f17_arg0:GetEntityNum() == DataModel.JJEHAEBDF( f17_arg0 )
	end
	
	f17_arg0:SubscribeToModelThroughElement( f17_arg0, "material", function ( f30_arg0 )
		assert( f17_arg0.UniqueImage )
		local f30_local0 = f17_arg0:GetDataSource()
		f30_local0 = f30_local0.material:GetValue( f17_arg0 )
		local f30_local1 = false
		if CONDITIONS.IsBRGameType( f17_arg0 ) then
			f30_local1 = BRLOOT.ShouldShowLootCard( f17_arg0 )
		end
		if f30_local0 ~= nil and f30_local0 ~= "hud_interaction_prompt_center_standard" and f30_local1 == false then
			f17_arg0.UniqueImageSet = true
			local f30_local2 = RegisterMaterial( f30_local0 )
			local f30_local3 = Engine.DFEIGFBEH( f30_local2 )
			f17_arg0.UniqueImage:setImage( f30_local2, 0 )
			local f30_local4, f30_local5, f30_local6, f30_local7 = f17_arg0.UniqueImage:getLocalRect()
			local f30_local8 = f30_local7 - f30_local5
			f17_arg0.UniqueImage:SetLeft( -f30_local8 / 2 * f30_local3 )
			f17_arg0.UniqueImage:SetRight( f30_local8 / 2 * f30_local3 )
			f17_arg0( f17_arg0, f17_arg0, "ShowUniqueImage" )
		else
			f17_arg0.UniqueImageSet = false
			ACTIONS.AnimateSequence( f17_arg0, "HideUniqueImage" )
		end
	end )
	f17_arg0:SubscribeToModelThroughElement( f17_arg0, "obstructed", function ( f29_arg0 )
		if f17_arg0() then
			f17_arg0:SetAlpha( 1, 150 )
		end
	end )
	local f17_local3 = function ()
		if f17_arg0() then
			local f28_local0 = DataModel.JJEHAEBDF
			local f28_local1 = f17_arg0:GetDataSource( f17_arg0 )
			f28_local0 = f28_local0( f28_local1.operable:GetModel( f17_arg0 ) )
			local f28_local2 = nil
			f28_local1 = false
			if not f28_local0 then
				f28_local2 = "Inoperable"
			else
				local f28_local3 = false
				if Engine.ECHCFGDDDF() or Dvar.IBEGCHEFE( "LTMMNMRLTP" ) then
					f28_local3 = true
				end
				local f28_local4 = DataModel.JJEHAEBDF
				local f28_local5 = f17_arg0:GetDataSource( f17_arg0 )
				if f28_local4( f28_local5.range:GetModel( f17_arg0 ) ) == HintRange.USE_RANGE then
					f28_local1 = not Engine.BGGJFFFAFG( f17_arg0 )
					if f28_local1 then
						f28_local2 = "InRangeKBM"
					else
						f28_local2 = "InRange"
					end
					f17_arg0:SetSnapToLocation( f28_local3 )
					f17_arg0:SetScreenSnapOffsets( Dvar.BJJCJHDBII( "LMPPLNSRK" ), Dvar.BJJCJHDBII( "MLTSLNNNKN" ) )
				else
					f28_local2 = "TooFar"
					f17_arg0:SetSnapToLocation( false )
				end
			end
			if f17_arg0.currentStateAnim ~= f28_local2 then
				f17_arg0.currentStateAnim = f28_local2
				f17_arg0( f17_arg0, f17_arg0, f28_local2 )
				if range == HintRange.USE_RANGE then
					if f28_local1 then
						ACTIONS.AnimateSequence( f17_arg0, "KeyboardOn" )
					else
						ACTIONS.AnimateSequence( f17_arg0, "KeyboardOff" )
					end
				end
			end
		end
	end
	
	f17_arg0:SubscribeToModelThroughElement( f17_arg0, "range", f17_local3 )
	f17_arg0:SubscribeToModelThroughElement( f17_arg0, "operable", f17_local3 )
	local f17_local4 = DataSources.inGame.player.holdKBMEnabled:GetModel( f17_arg1 )
	local f17_local5 = DataSources.inGame.HUD.hints.interactiveObject.progress.duration:GetModel( f17_arg1 )
	local f17_local6 = DataSources.inGame.HUD.hints.interactiveObject.button.isHintValid:GetModel( f17_arg1 )
	local f17_local7 = function ()
		if DataModel.JJEHAEBDF( f17_arg0 ) and 0 < (DataModel.JJEHAEBDF( f17_arg0 ) or -1) and DataModel.JJEHAEBDF( f17_arg0 ) and not f17_arg0._isPlayingDismiss then
			f17_arg0.KBMProgress:SetHoldAnimation()
		end
	end
	
	f17_arg0.KBMHoldAnimationHandle = f17_local7
	f17_arg0:SubscribeToModelThroughElement( f17_arg0, "requiresHolding", function ()
		local f26_local0 = f17_arg0:GetDataSource()
		if f26_local0.requiresHolding:GetValue( f17_arg0 ) ~= nil then
			f26_local0 = f17_arg0:GetDataSource()
			if f26_local0.requiresHolding:GetValue( f17_arg0 ) == true then
				f17_arg0.KBMProgress:SetHoldAnimation()
			end
		end
		f26_local0 = f17_arg0:GetDataSource()
		if f26_local0.requiresHolding:GetValue( f17_arg0 ) ~= nil then
			f26_local0 = f17_arg0:GetDataSource()
			if f26_local0.requiresHolding:GetValue( f17_arg0 ) == false then
				f17_arg0.KBMProgress:SetPressAnimation()
			end
		end
		f17_arg0.KBMHoldAnimationHandle()
	end )
	f17_arg0:SubscribeToModel( f17_local4, f17_local7 )
	f17_arg0:SubscribeToModel( f17_local5, f17_local7 )
	local f17_local8 = DataSources.inGame.HUD.hints.interactiveObject.progress:GetModel( f17_arg1 )
	local f17_local9 = DataSources.inGame.HUD.hints.interactiveObject.progress.entity:GetModel( f17_arg1 )
	local f17_local10 = function ()
		if not f17_arg0.GetEntityNum then
			return 
		end
		local f25_local0 = DataModel.JJEHAEBDF( f17_arg0 )
		local f25_local1 = DataModel.JJEHAEBDF( f17_arg0 )
		local f25_local2 = f17_arg0:GetEntityNum()
		local f25_local3 = nil
		if f25_local0 < 1 then
			f17_arg0.hasBeenIncomplete = true
		end
		if f25_local2 == f25_local1 and 1 <= f25_local0 and f17_arg0.hasBeenIncomplete then
			f25_local3 = "Completed"
		elseif f25_local1 == GameScriptConstants.EntityNumNone and 0 < f25_local0 and f17_arg0.hasBeenIncomplete then
			f25_local3 = "NotCompleted"
		end
		if f25_local3 and Engine.BGGJFFFAFG( f17_arg0 ) then
			f17_arg0( f17_arg0, f17_arg0, f25_local3 )
		end
	end
	
	f17_arg0:SubscribeToModelThroughElement( f17_arg0, "targetEntity", f17_local10 )
	f17_arg0:SubscribeToModel( f17_local9, f17_local10 )
	f17_arg0:SubscribeToModel( f17_local8, f17_local10 )
	assert( f17_arg0.Arrow )
	assert( f17_arg0.ProgressBar )
	local f17_local11 = function ()
		if not f17_arg0.GetEntityNum then
			
		else
			
		end
		local f23_local0 = DataModel.JJEHAEBDF( f17_arg0 )
		if f23_local0 == f17_arg0:GetEntityNum() then
			if not f17_arg0.ProgressBar.progressSubscription then
				f17_arg0.ProgressBar.progressSubscription = f17_arg0.ProgressBar:SubscribeToModel( f17_arg0, function ()
					local f24_local0 = DataModel.JJEHAEBDF( f23_local0 )
					if f23_local0.hasBeenIncomplete then
						if Engine.BGGJFFFAFG( f23_local0 ) then
							f23_local0.ProgressBar:SetProgress( f24_local0 )
							f23_local0.ProgressBar:SetAlpha( 1, 0 )
						else
							f23_local0.KBMProgress:SetProgress( f24_local0 )
						end
						if f23_local0.UniqueImageSet then
							f23_local0.Arrow:SetAlpha( 0, 0 )
						end
					end
				end )
			end
		elseif f17_arg0.ProgressBar.progressSubscription then
			f17_arg0.KBMProgress:SetProgress( 0 )
			f17_arg0.ProgressBar:SetProgress( 0 )
			f17_arg0.ProgressBar:UnsubscribeFromModel( f17_arg0.ProgressBar.progressSubscription )
			f17_arg0.ProgressBar.progressSubscription = nil
			f17_arg0.ProgressBar:SetAlpha( 0, 0 )
			if f17_arg0.UniqueImageSet then
				f17_arg0.Arrow:SetAlpha( 1, 0 )
			end
		end
	end
	
	f17_arg0:SubscribeToModelThroughElement( f17_arg0, "targetEntity", f17_local11 )
	f17_arg0:SubscribeToModel( f17_local9, f17_local11 )
	f17_arg0:SubscribeToModelThroughElement( f17_arg0, "dismiss", function ( f21_arg0 )
		if DataModel.JJEHAEBDF( f21_arg0 ) then
			ACTIONS.AnimateSequence( f17_arg0, "Dismiss" )
			f17_arg0._isPlayingDismiss = true
			local f21_local0 = f17_arg0:Wait( f17_arg0 )
			f21_local0.onComplete = function ()
				f21_arg0._isPlayingDismiss = false
				if f21_arg0._removeTextOnDismiss then
					LAYOUT.SetTextBoxSizeWithButton( f21_arg0.Text, f21_arg0.Background, "", 20, nil, 0, nil, f21_arg0.KBMProgress )
					f21_arg0._removeTextOnDismiss = false
				end
			end
			
			if f17_arg0.UniqueImageSet then
				ACTIONS.AnimateSequence( f17_arg0, "HideUniqueImage" )
			end
		end
	end )
	f17_arg0.ProgressBar:SetAlpha( 0, 0 )
	local f17_local12 = function ( f20_arg0, f20_arg1 )
		assert( f20_arg0.KBMProgress )
		local f20_local0 = f20_arg0:GetDataSource( f17_arg0 )
		if f20_local0 then
			local f20_local1 = Engine.BGGJFFFAFG( f17_arg0 )
			if f20_local0.requiresHolding and not f20_local1 then
				local f20_local2 = DataSources.inGame.HUD.hints.interactiveObject.progress.duration:GetValue( f17_arg0 )
				local f20_local3 = DataSources.inGame.HUD.hints.interactiveObject.button.isHintValid:GetValue( f17_arg0 )
				if f20_local0.requiresHolding:GetValue( f17_arg0 ) ~= nil then
					if f20_local0.requiresHolding:GetValue( f17_arg0 ) and f17_arg0 < f20_local2 and f20_local3 then
						f20_arg0.KBMProgress:SetHoldAnimation()
					else
						f20_arg0.KBMProgress:SetPressAnimation()
					end
					f20_arg0:KBMHoldAnimationHandle()
				end
			end
			if f20_local0.range and DataModel.JJEHAEBDF( f20_local0.range:GetModel( f17_arg0 ) ) == HintRange.USE_RANGE then
				if f20_local1 then
					ACTIONS.AnimateSequence( f20_arg0, "KeyboardOff" )
				else
					ACTIONS.AnimateSequence( f20_arg0, "KeyboardOn" )
				end
			end
			if f20_local0.keyBind then
				local f20_local2 = f20_local0.keyBind:GetValue( f17_arg0 )
				if f20_local2 ~= nil then
					if f20_local1 then
						f20_arg0.InteractiveObjectButtonIcon.UpdateIcon()
					else
						f20_arg0.KBMProgress:SetPromptText( StripColorMarkers( LocalizeString( f20_local2 ) ) )
					end
				end
			end
		end
	end
	
	f17_arg0:registerAndCallEventHandler( "key_bindings_update", f17_local12 )
	f17_arg0:registerEventHandler( "empty_menu_stack", f17_local12 )
	f17_arg0.Text:SubscribeToModelThroughElement( f17_arg0, "string", function ()
		local f19_local0 = f17_arg0:GetDataSource()
		f19_local0 = f19_local0.string:GetValue( f17_arg0 )
		local f19_local1 = CONDITIONS.IsMagmaGameMode()
		if f19_local1 then
			f19_local1 = CONDITIONS.IsRealismMode( f17_arg0, f17_arg0 )
			if f19_local1 then
				f19_local1 = BRLOOT.ShouldShowLootCard( f17_arg0 )
			end
		end
		if f19_local1 then
			local f19_local2 = Game.DFFJEIIAD( f17_arg0 )
			if f19_local2 and f19_local2.name and f19_local2.name ~= "" then
				local f19_local3 = BRLOOT.GetLootDataForLookupKeys( {
					nameRef = f19_local2.name
				} )
				if f19_local3 and f19_local3.title and f19_local3.title ~= "" then
					f19_local0 = Engine.CBBHFCGDIC( f19_local3.title )
				end
			end
		end
		if f19_local0 ~= nil then
			if f19_local0 == "" then
				f17_arg0._removeTextOnDismiss = true
			else
				f17_arg0._removeTextOnDismiss = false
				LAYOUT.SetTextBoxSizeWithButton( f17_arg0.Text, f17_arg0.Background, f19_local0, 20, nil, 0, nil, f17_arg0.KBMProgress )
			end
		end
	end )
	f17_arg0.KBMProgress:SubscribeToModel( DataSources.inGame.HUD.hints.interactiveObject.button.keyBind:GetModel( f17_arg1 ), function ()
		local f18_local0 = DataSources.inGame.HUD.hints.interactiveObject.button.keyBind:GetValue( f17_arg0 )
		if f18_local0 ~= nil then
			f17_arg0.KBMProgress:SetPromptText( StripFromPattern( LocalizeString( f18_local0 ), "(%^.)" ) )
		end
	end )
	f17_arg0.InteractiveObjectButtonIcon:SetOnlyOneIcon( true )
end

function InteractiveObjectButton( menu, controller )
	local self = LUI.UIElement.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 40 * _1080p, 0, 40 * _1080p )
	self.id = "InteractiveObjectButton"
	self._animationSets = self._animationSets or {}
	self._sequences = self._sequences or {}
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine.DDJFBBJAIG() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1 )
	local f1_local2 = self
	local Background = nil
	
	Background = LUI.UIImage.new()
	Background.id = "Background"
	Background:SetRGBFromTable( SWATCHES.HUD.HUDShadow, 0 )
	Background:SetAlpha( 0.22, 0 )
	Background:setImage( RegisterMaterial( "hud_bkgd_glow" ), 0 )
	Background:SetBlendMode( BLEND_MODE.multiply )
	Background:Setup9SliceImage( _1080p * 30, _1080p * 20, 0.3, 0.3 )
	Background:SetAnchorsAndPosition( 0, 0, 0.5, 0.5, _1080p * -19, _1080p * 19, _1080p * -32, _1080p * 32 )
	self:addElement( Background )
	self.Background = Background
	
	local CircleCenterIcon = nil
	
	CircleCenterIcon = LUI.UIImage.new()
	CircleCenterIcon.id = "CircleCenterIcon"
	CircleCenterIcon:SetRGBFromTable( SWATCHES.HUD.HUDMain, 0 )
	CircleCenterIcon:setImage( RegisterMaterial( "dpad_circle_whole" ), 0 )
	CircleCenterIcon:SetAnchorsAndPosition( 0.5, 0.5, 0.5, 0.5, _1080p * -4, _1080p * 4, _1080p * -4, _1080p * 4 )
	self:addElement( CircleCenterIcon )
	self.CircleCenterIcon = CircleCenterIcon
	
	local ProgressBacker = nil
	
	ProgressBacker = LUI.UIImage.new()
	ProgressBacker.id = "ProgressBacker"
	ProgressBacker:SetRGBFromTable( SWATCHES.HUD.active, 0 )
	ProgressBacker:SetAlpha( 0, 0 )
	ProgressBacker:setImage( RegisterMaterial( "dpad_circle_whole" ), 0 )
	ProgressBacker:SetAnchorsAndPosition( 0.5, 0.5, 0.5, 0.5, _1080p * -16, _1080p * 16, _1080p * -16, _1080p * 16 )
	self:addElement( ProgressBacker )
	self.ProgressBacker = ProgressBacker
	
	local Text = nil
	
	Text = LUI.UIStyledText.new()
	Text.id = "Text"
	Text:SetRGBFromTable( SWATCHES.HUD.HUDMain, 0 )
	Text:setText( "", 0 )
	Text:SetFont( FONTS.GetFont( FONTS.MainRegular.File ) )
	Text:SetAlignment( LUI.Alignment.Left )
	Text:SetOptOutRightToLeftAlignmentFlip( true )
	Text:SetShadowMinDistance( -0.2, 0 )
	Text:SetShadowMaxDistance( 0.2, 0 )
	Text:SetShadowUOffset( -0.001, 0 )
	Text:SetShadowVOffset( -0.001, 0 )
	Text:SetShadowRGBFromTable( SWATCHES.HUD.HUDShadow, 0 )
	Text:SetAnchorsAndPosition( 0.5, 0.5, 0.5, 0.5, _1080p * 28, _1080p * 578, _1080p * -14, _1080p * 14 )
	self:addElement( Text )
	self.Text = Text
	
	local InteractiveObjectButtonIcon = nil
	
	InteractiveObjectButtonIcon = MenuBuilder.BuildRegisteredType( "InteractiveObjectButtonIcon", {
		controllerIndex = f1_local1
	} )
	InteractiveObjectButtonIcon.id = "InteractiveObjectButtonIcon"
	InteractiveObjectButtonIcon:SetAlpha( 0, 0 )
	InteractiveObjectButtonIcon:SetDataSourceThroughElement( self, nil )
	InteractiveObjectButtonIcon:SetAnchorsAndPosition( 0.5, 0.5, 0.5, 0.5, _1080p * -16, _1080p * 16, _1080p * -16, _1080p * 16 )
	self:addElement( InteractiveObjectButtonIcon )
	self.InteractiveObjectButtonIcon = InteractiveObjectButtonIcon
	
	local ProgressBar = nil
	
	ProgressBar = MenuBuilder.BuildRegisteredType( "UIRadialProgressBar", {
		segmentMaterial = "dpad_circle_segment",
		snapToMultiplesOfAngle = 0,
		maskMaterial = "dpad_circle_mask",
		segmentCount = 2,
		controllerIndex = f1_local1
	} )
	ProgressBar.id = "ProgressBar"
	ProgressBar:SetRGBFromTable( SWATCHES.Global.keyColor, 0 )
	ProgressBar:setImage( RegisterMaterial( "dpad_circle_segment" ), 0 )
	ProgressBar:SetProgress( 0 )
	ProgressBar:SetAnchorsAndPosition( 0.5, 0.5, 0.5, 0.5, _1080p * -20, _1080p * 20, _1080p * -20, _1080p * 20 )
	self:addElement( ProgressBar )
	self.ProgressBar = ProgressBar
	
	local UniqueImage = nil
	
	UniqueImage = LUI.UIImage.new()
	UniqueImage.id = "UniqueImage"
	UniqueImage:SetRGBFromTable( SWATCHES.HUD.HUDMain, 0 )
	UniqueImage:SetAlpha( 0, 0 )
	UniqueImage:setImage( RegisterMaterial( "icon_equipment_slot_c4" ), 0 )
	UniqueImage:SetAnchorsAndPosition( 0.5, 0.5, 0, 1, _1080p * -32, _1080p * 32, _1080p * -84, _1080p * -20 )
	self:addElement( UniqueImage )
	self.UniqueImage = UniqueImage
	
	local Arrow = nil
	
	Arrow = LUI.UIImage.new()
	Arrow.id = "Arrow"
	Arrow:SetRGBFromTable( SWATCHES.Global.keyColor, 0 )
	Arrow:SetAlpha( 0, 0 )
	Arrow:setImage( RegisterMaterial( "icon_arrow_up" ), 0 )
	Arrow:SetAnchorsAndPosition( 0.5, 0.5, 0.5, 0.5, _1080p * -16, _1080p * 16, _1080p * -36, _1080p * -20 )
	self:addElement( Arrow )
	self.Arrow = Arrow
	
	local KBMProgress = nil
	
	KBMProgress = MenuBuilder.BuildRegisteredType( "KBMButtonWithProgress", {
		controllerIndex = f1_local1
	} )
	KBMProgress.id = "KBMProgress"
	KBMProgress:SetAlpha( 0, 0 )
	KBMProgress.KeyString:setText( StripFromPattern( LocalizeString( "Space" ), "(%^.)" ), 0 )
	KBMProgress:SetAnchorsAndPosition( 1, 0, 0.5, 0.5, _1080p * -34, _1080p * -6, _1080p * -14, _1080p * 14 )
	self:addElement( KBMProgress )
	self.KBMProgress = KBMProgress
	
	self._sequences.DefaultSequence = function ()
		
	end
	
	local f1_local12 = nil
	Background:RegisterAnimationSequence( "TooFar", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	CircleCenterIcon:RegisterAnimationSequence( "TooFar", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Scale
		},
		{
			value = 2,
			duration = 200,
			property = TWEEN_PROPERTY.Scale,
			easing = LUI.EASING.outBack
		}
	} )
	Text:RegisterAnimationSequence( "TooFar", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	InteractiveObjectButtonIcon:RegisterAnimationSequence( "TooFar", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	KBMProgress:RegisterAnimationSequence( "TooFar", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.TooFar = function ()
		menu:AnimateSequence( "TooFar" )
		menu:AnimateSequence( "TooFar" )
		menu:AnimateSequence( "TooFar" )
		menu:AnimateSequence( "TooFar" )
		menu:AnimateSequence( "TooFar" )
	end
	
	local f1_local13 = nil
	Background:RegisterAnimationSequence( "InRange", {
		{
			value = -4310086187397.1196,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.outBack
		}
	} )
	CircleCenterIcon:RegisterAnimationSequence( "InRange", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 5.30239915E-315,
			duration = 0,
			property = TWEEN_PROPERTY.Scale
		},
		{
			value = 0,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 5.30628464E-315,
			duration = 200,
			property = TWEEN_PROPERTY.Scale
		}
	} )
	Text:RegisterAnimationSequence( "InRange", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.outBack
		}
	} )
	InteractiveObjectButtonIcon:RegisterAnimationSequence( "InRange", {
		{
			value = 1.590719745E-314,
			duration = 0,
			property = TWEEN_PROPERTY.Scale
		},
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 200,
			property = TWEEN_PROPERTY.Scale,
			easing = LUI.EASING.outBack
		},
		{
			value = 1,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.outBack
		}
	} )
	self._sequences.InRange = function ()
		menu:AnimateSequence( "InRange" )
		menu:AnimateSequence( "InRange" )
		menu:AnimateSequence( "InRange" )
		menu:AnimateSequence( "InRange" )
	end
	
	local f1_local14 = nil
	Background:RegisterAnimationSequence( "Dismiss", {
		{
			value = 0,
			duration = 190,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	CircleCenterIcon:RegisterAnimationSequence( "Dismiss", {
		{
			value = -8.679223799257849E+209,
			duration = 0,
			property = TWEEN_PROPERTY.Scale
		},
		{
			value = 0,
			duration = 190,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 5.31049392E-315,
			duration = 190,
			property = TWEEN_PROPERTY.Scale
		}
	} )
	Text:RegisterAnimationSequence( "Dismiss", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	InteractiveObjectButtonIcon:RegisterAnimationSequence( "Dismiss", {
		{
			value = 0,
			duration = 190,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	KBMProgress:RegisterAnimationSequence( "Dismiss", {
		{
			value = 0,
			duration = 190,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.Dismiss = function ()
		menu:AnimateSequence( "Dismiss" )
		menu:AnimateSequence( "Dismiss" )
		menu:AnimateSequence( "Dismiss" )
		menu:AnimateSequence( "Dismiss" )
		menu:AnimateSequence( "Dismiss" )
	end
	
	local f1_local15 = nil
	CircleCenterIcon:RegisterAnimationSequence( "Inoperable", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.HUD.warning
		},
		{
			value = 7,
			duration = 0,
			property = TWEEN_PROPERTY.Scale
		},
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1.9035983721108212E+185,
			duration = 200,
			property = TWEEN_PROPERTY.Scale,
			easing = LUI.EASING.outBack
		},
		{
			value = -2.353438279577766E-185,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.outBack
		}
	} )
	self._sequences.Inoperable = function ()
		menu:AnimateSequence( "Inoperable" )
	end
	
	local f1_local16 = nil
	Background:RegisterAnimationSequence( "KeyboardOn", {
		{
			value = -4310086187397.1196,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	CircleCenterIcon:RegisterAnimationSequence( "KeyboardOn", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	InteractiveObjectButtonIcon:RegisterAnimationSequence( "KeyboardOn", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	ProgressBar:RegisterAnimationSequence( "KeyboardOn", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	KBMProgress:RegisterAnimationSequence( "KeyboardOn", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.KeyboardOn = function ()
		menu:AnimateSequence( "KeyboardOn" )
		menu:AnimateSequence( "KeyboardOn" )
		menu:AnimateSequence( "KeyboardOn" )
		menu:AnimateSequence( "KeyboardOn" )
		menu:AnimateSequence( "KeyboardOn" )
	end
	
	local f1_local17 = nil
	CircleCenterIcon:RegisterAnimationSequence( "KeyboardOff", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	InteractiveObjectButtonIcon:RegisterAnimationSequence( "KeyboardOff", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	ProgressBar:RegisterAnimationSequence( "KeyboardOff", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	KBMProgress:RegisterAnimationSequence( "KeyboardOff", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.KeyboardOff = function ()
		menu:AnimateSequence( "KeyboardOff" )
		menu:AnimateSequence( "KeyboardOff" )
		menu:AnimateSequence( "KeyboardOff" )
		menu:AnimateSequence( "KeyboardOff" )
	end
	
	local f1_local18 = nil
	UniqueImage:RegisterAnimationSequence( "ShowUniqueImage", {
		{
			value = 1,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Arrow:RegisterAnimationSequence( "ShowUniqueImage", {
		{
			value = 1,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.ShowUniqueImage = function ()
		menu:AnimateSequence( "ShowUniqueImage" )
		menu:AnimateSequence( "ShowUniqueImage" )
	end
	
	local f1_local19 = nil
	ProgressBacker:RegisterAnimationSequence( "HideUniqueImage", {
		{
			value = 5.289447516E-315,
			duration = 0,
			property = TWEEN_PROPERTY.Scale
		}
	} )
	ProgressBar:RegisterAnimationSequence( "HideUniqueImage", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Scale
		}
	} )
	UniqueImage:RegisterAnimationSequence( "HideUniqueImage", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Arrow:RegisterAnimationSequence( "HideUniqueImage", {
		{
			value = 0,
			duration = -28,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.HideUniqueImage = function ()
		menu:AnimateSequence( "HideUniqueImage" )
		menu:AnimateSequence( "HideUniqueImage" )
		menu:AnimateSequence( "HideUniqueImage" )
		menu:AnimateSequence( "HideUniqueImage" )
	end
	
	local f1_local20 = nil
	InteractiveObjectButtonIcon:RegisterAnimationSequence( "NotCompleted", {
		{
			value = 16777215,
			duration = 0,
			property = TWEEN_PROPERTY.RGB
		},
		{
			duration = -48,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.HUD.background
		},
		{
			value = 16777215,
			duration = -48,
			property = TWEEN_PROPERTY.RGB
		},
		{
			duration = -48,
			property = TWEEN_PROPERTY.RGB,
			value = SWATCHES.HUD.background
		},
		{
			value = 16777215,
			duration = -48,
			property = TWEEN_PROPERTY.RGB
		}
	} )
	self._sequences.NotCompleted = function ()
		menu:AnimateSequence( "NotCompleted" )
	end
	
	local f1_local21 = nil
	ProgressBacker:RegisterAnimationSequence( "Completed", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 5.289447516E-315,
			duration = 0,
			property = TWEEN_PROPERTY.Scale
		},
		{
			value = 0,
			duration = 30,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.snap
		},
		{
			value = 5.289447516E-315,
			duration = 180,
			property = TWEEN_PROPERTY.Scale
		},
		{
			value = 1,
			duration = 30,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.snap
		},
		{
			value = 0,
			duration = 30,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.snap
		},
		{
			value = 1,
			duration = 30,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.snap
		},
		{
			value = 0,
			duration = 30,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.snap
		},
		{
			value = 1,
			duration = 30,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.snap
		},
		{
			value = 1,
			duration = 220,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 320,
			property = TWEEN_PROPERTY.Scale,
			easing = LUI.EASING.inBack
		},
		{
			value = 0,
			duration = -28,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	ProgressBar:RegisterAnimationSequence( "Completed", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Arrow:RegisterAnimationSequence( "Completed", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * -16
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 16
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Top,
			value = _1080p * -26
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Bottom,
			value = _1080p * -10
		},
		{
			value = 8.029892509424649E+283,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha,
			easing = LUI.EASING.outBack
		},
		{
			duration = 200,
			property = TWEEN_PROPERTY.Left,
			value = _1080p * -16,
			easing = LUI.EASING.outBack
		},
		{
			duration = 200,
			property = TWEEN_PROPERTY.Right,
			value = _1080p * 16,
			easing = LUI.EASING.outBack
		},
		{
			duration = 200,
			property = TWEEN_PROPERTY.Top,
			value = _1080p * -38,
			easing = LUI.EASING.outBack
		},
		{
			duration = 200,
			property = TWEEN_PROPERTY.Bottom,
			value = _1080p * -22,
			easing = LUI.EASING.outBack
		}
	} )
	self._sequences.Completed = function ()
		menu:AnimateSequence( "Completed" )
		menu:AnimateSequence( "Completed" )
		menu:AnimateSequence( "Completed" )
	end
	
	local f1_local22 = nil
	Background:RegisterAnimationSequence( "InRangeKBM", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = -4310086187397.1196,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	Text:RegisterAnimationSequence( "InRangeKBM", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	KBMProgress:RegisterAnimationSequence( "InRangeKBM", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.InRangeKBM = function ()
		menu:AnimateSequence( "InRangeKBM" )
		menu:AnimateSequence( "InRangeKBM" )
		menu:AnimateSequence( "InRangeKBM" )
	end
	
	local f1_local23 = nil
	Text:RegisterAnimationSequence( "AR", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Top,
			value = _1080p * -22
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Bottom,
			value = _1080p * 22
		}
	} )
	self._sequences.AR = function ()
		menu:AnimateSequence( "AR" )
	end
	
	local f1_local24 = nil
	Text:RegisterAnimationSequence( "JA", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Top,
			value = _1080p * -15
		},
		{
			duration = 0,
			property = TWEEN_PROPERTY.Bottom,
			value = _1080p * 15
		}
	} )
	self._sequences.JA = function ()
		menu:AnimateSequence( "JA" )
	end
	
	InteractiveObjectButtonIcon:SetDataSourceThroughElement( self, nil )
	self:SubscribeToModelThroughElement( self, "requiresMashing", function ()
		local f2_local0 = menu:GetDataSource()
		if f2_local0.requiresMashing:GetValue( menu ) ~= nil then
			f2_local0 = menu:GetDataSource()
			if f2_local0.requiresMashing:GetValue( menu ) == true then
				ACTIONS.AnimateSequenceByElement( menu, {
					elementPath = "self.InteractiveObjectButtonIcon",
					sequenceName = "Mash",
					elementName = "InteractiveObjectButtonIcon"
				} )
			end
		end
		f2_local0 = menu:GetDataSource()
		if f2_local0.requiresMashing:GetValue( menu ) ~= nil then
			f2_local0 = menu:GetDataSource()
			if f2_local0.requiresMashing:GetValue( menu ) == false then
				ACTIONS.AnimateSequenceByElement( menu, {
					elementPath = "self.InteractiveObjectButtonIcon",
					sequenceName = "DontMash",
					elementName = "InteractiveObjectButtonIcon"
				} )
			end
		end
	end )
	f0_local0( self, f1_local1, controller )
	return self
end

MenuBuilder.registerType( "InteractiveObjectButton", InteractiveObjectButton )
LockTable( _M )
