-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 13-07-2025 21:51
module( ..., package.seeall )
local f0_local0 = function ( f3_arg0, f3_arg1 )
	local f3_local0 = f3_arg1.attacker
	if f3_local0 then
		f3_local0 = f3_arg1.attacker ~= f3_arg1.victim
	end
	if not f3_local0 then
		if f3_arg0.Attacker:getParent() then
			f3_arg0:RemoveElement( f3_arg0.Attacker )
		end
	else
		if not f3_arg0.Attacker:getParent() then
			f3_arg0.Attacker:addElementBefore( f3_arg0.Icon )
		end
		local f3_local1 = Game.DEAIDCJCEH( f3_arg1.attacker )
		if MLG.FBFGBEC() then
			local f3_local2 = CODCASTER_PLAYERLIST.GetCompetitiveName( f3_local1, f3_arg1.attacker, true )
			if f3_local2 then
				f3_local1 = f3_local2
			end
		end
		f3_arg0.Attacker:setText( f3_local1 )
		f3_arg0.Attacker:SetRGBFromTable( HUDUtils.GetPlayerColor( f3_arg1.attacker, f3_arg0._controllerIndex, true ) )
	end
	local f3_local1 = nil
	local f3_local2 = false
	local f3_local3 = nil
	assert( f3_arg1.isMod ~= nil )
	if f3_arg1.isMod then
		f3_local1 = RegisterMaterial( StringTable.CBGJCDIHCE( CSV.obituaryMod.file, f3_arg1.modIndex, CSV.obituaryMod.cols.iconName ) )
		f3_local2 = tonumber( StringTable.CBGJCDIHCE( CSV.obituaryMod.file, f3_arg1.modIndex, CSV.obituaryMod.cols.flip ) ) == 1
		f3_local3 = StringTable.CBGJCDIHCE( CSV.obituaryMod.file, f3_arg1.modIndex, CSV.obituaryMod.cols.imageRatio )
	else
		if f3_arg1.icon then
			f3_local1 = f3_arg1.icon
		else
			f3_local1 = StringTable.CBGJCDIHCE( CSV.obituaryMod.file, 0, CSV.obituaryMod.cols.iconName )
		end
		f3_local2 = f3_arg1.flip
		if f3_arg1.imageRatio then
			local f3_local4 = f3_arg1.imageRatio
			if not f3_local4 then
				f3_local3 = f3_local4
			else
				f3_local3 = 1
			end
		end
		f3_local3 = 1
	end
	f3_arg0.Icon:setImage( f3_local1 )
	local f3_local4, f3_local5, f3_local6, f3_local7 = f3_arg0.Icon:getLocalRect()
	local f3_local8 = f3_local7 - f3_local5
	local f3_local9 = f3_local8 * f3_local3
	local f3_local10
	if f3_local2 then
		f3_local10 = -1
	else
		f3_local10 = 1
	end
	f3_arg0.Icon:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, 0, f3_local10 * f3_local9, -f3_local8 / 2, f3_local8 / 2 )
	assert( f3_arg1.victim )
	f3_arg0.ObituaryKillSub:Update( f3_arg1, HUDUtils.GetPlayerColor( f3_arg1.victim, f3_arg0._controllerIndex, true ) )
	f3_arg0.messageIconWidth = f3_local9
end

local f0_local1 = function ( f2_arg0, f2_arg1 )
	assert( f2_arg0.Icon )
	assert( f2_arg0.Attacker )
	f2_arg0._controllerIndex = f2_arg1
	f2_arg0.Update = f0_local0
	f2_arg0.messageIconWidth = 0
end

function ObituaryKill( menu, controller )
	local self = LUI.UIHorizontalStackedLayout.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 600 * _1080p, 0, 22 * _1080p )
	self.id = "ObituaryKill"
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine.DDJFBBJAIG() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1 )
	local f1_local2 = self
	self:SetSpacing( 10 * _1080p )
	local Attacker = nil
	
	Attacker = LUI.UIStyledText.new()
	Attacker.id = "Attacker"
	Attacker:setText( "", 0 )
	Attacker:SetFont( FONTS.GetFont( FONTS.BattleNetRegular.File ) )
	Attacker:SetWordWrap( false )
	Attacker:SetAlignment( LUI.Alignment.Left )
	Attacker:SetShadowMinDistance( -0.2, 0 )
	Attacker:SetShadowMaxDistance( 0.2, 0 )
	Attacker:SetShadowUOffset( -0.001, 0 )
	Attacker:SetShadowVOffset( -0.001, 0 )
	Attacker:SetShadowRGBFromTable( SWATCHES.HUD.HUDShadow, 0 )
	Attacker:SetAnchorsAndPosition( 0, 1, 1, 0, 0, _1080p * 120, _1080p * -22, 0 )
	self:addElement( Attacker )
	self.Attacker = Attacker
	
	local Icon = nil
	
	Icon = LUI.UIImage.new()
	Icon.id = "Icon"
	Icon:setImage( RegisterMaterial( "icon_obit_headshot" ), 0 )
	Icon:SetAnchorsAndPosition( 0, 1, 1, 0, _1080p * 130, _1080p * 154, _1080p * -23, _1080p * 1 )
	self:addElement( Icon )
	self.Icon = Icon
	
	local ObituaryKillSub = nil
	
	ObituaryKillSub = MenuBuilder.BuildRegisteredType( "ObituaryKillSub", {
		controllerIndex = f1_local1
	} )
	ObituaryKillSub.id = "ObituaryKillSub"
	ObituaryKillSub:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 164, _1080p * 564, _1080p * -1, _1080p * 23 )
	self:addElement( ObituaryKillSub )
	self.ObituaryKillSub = ObituaryKillSub
	
	f0_local0( self, f1_local1, controller )
	return self
end

MenuBuilder.registerType( "ObituaryKill", ObituaryKill )
LockTable( _M )
