-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 13-07-2025 21:53
module( ..., package.seeall )
local f0_local0 = -1
function UpdateFeedSubscriptionHelper( f5_arg0, f5_arg1, f5_arg2 )
	return function ()
		local f6_local0 = 5
		local f6_local1 = f5_arg0:GetValue( f5_arg0 )
		if f6_local1 < 0 or f6_local1 == f5_arg0 then
			if f6_local1 < 0 then
				f5_arg0 = -1
			end
			return -1
		end
		local f6_local2 = "ui_score_event_list_"
		if f5_arg0.isPOTG == true then
			f6_local2 = "ui_potg_score_event_list_"
		end
		local f6_local3 = f6_local1 % f6_local0
		assert( f6_local3 < f6_local0 )
		local f6_local4 = (f5_arg0 + 1) % f6_local0
		local f6_local5 = (f6_local3 + 1) % f6_local0
		local f6_local6 = f6_local4
		f5_arg0 = f6_local1
	end
	
end

function SetupPOTG( f4_arg0, f4_arg1 )
	local f4_local0 = LUI.DataSourceFromOmnvar.new( "ui_potg_score_event_control" )
	f4_arg0:SubscribeToModel( f4_local0:GetModel( f4_arg1 ), UpdateFeedSubscriptionHelper( f4_arg0, f4_local0, f4_arg1 ), true )
	f4_arg0.isPOTG = true
end

function PostLoadFunc( f2_arg0, f2_arg1 )
	local Feed = nil
	
	Feed = LUI.UIDataSourceFeed.new( {
		maxVisibleColumns = 1,
		maxVelocity = 5000,
		maxVisibleRows = 5,
		forcePrimaryAxisScrolling = true,
		springCoefficient = 400,
		primaryAxis = LUI.DIRECTION.vertical,
		controllerIndex = f2_arg1,
		buildChild = function ()
			return MenuBuilder.BuildRegisteredType( "ScoreEventLine", {
				controllerIndex = f2_arg0
			} )
		end,
		dataSource = DataSources.inGame.MP.scoreEvents,
		spacingX = _1080p * 2,
		spacingY = _1080p * 2,
		columnWidth = _1080p * 1200,
		rowHeight = _1080p * 24,
		horizontalAlignment = LUI.Alignment.Left,
		verticalAlignment = LUI.Alignment.Top
	} )
	Feed:SetRGBFromTable( SWATCHES.HUD.HUDMain, 0 )
	Feed:setUseStencil( false )
	Feed:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 1200, 0, _1080p * 210 )
	f2_arg0:addElement( Feed )
	f2_arg0.Feed = Feed
	
	f2_arg0.SetupPOTG = SetupPOTG
	local f2_local1 = LUI.DataSourceFromOmnvar.new( "ui_score_event_control" )
	f2_arg0:SubscribeToModel( f2_local1:GetModel( f2_arg1 ), UpdateFeedSubscriptionHelper( f2_arg0, f2_local1, f2_arg1 ), true )
	local f2_local2 = LUI.DataSourceInControllerModel.new( "cg.MP.scoreEvents.push.TTL" )
	f2_local2:SetValue( f2_arg1, 1450 )
	DataSources.inGame.MP.scoreEvents:ClearContent( f2_arg1 )
end

function ScoreEventFeed( menu, controller )
	local self = LUI.UIElement.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 1200 * _1080p, 0, 210 * _1080p )
	self.id = "ScoreEventFeed"
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine.DDJFBBJAIG() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1 )
	local f1_local2 = self
	PostLoadFunc( self, f1_local1, controller )
	return self
end

MenuBuilder.registerType( "ScoreEventFeed", ScoreEventFeed )
LockTable( _M )
