-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 30-11-2025 17:03
module( ..., package.seeall )
function LeaveMenu()
	return function ( f18_arg0, f18_arg1 )
		LUI.FlowManager.RequestLeaveMenu( f18_arg0 )
	end
	
end

local f0_local0 = {}
local f0_local1 = {}
local f0_local2 = {}
local f0_local3 = {}
helpers = {
	LeaveMenu = LeaveMenu
}
local f0_local4 = function ( menu, controller )
	local self = LUI.UIElement.new()
	self:setUseStencil( true )
	return self
end

local f0_local5 = function ( menu, controller )
	local self = LUI.UIElement.new()
	self:setupWorldBlur()
	return self
end

function buildOwnerDraw( menu, controller )
	local self = LUI.UIElement.new()
	self:setupOwnerdraw( controller.ownerDraw, controller.ownerDrawTextScale, controller.ownerDrawTextStyle )
	return self
end

function buildTextEdit( menu, controller )
	local self = LUI.UIElement.new()
	self:setupTextEdit( controller.maxLength, controller.isPassword, controller.useAutoAlign, controller.disableAfterEdit, controller.isNumeric, controller.autoConfirmOnTab, controller.autoConfirmOnOutsideClick, controller.autoSelectAllOnActive, controller.wantTabButtonEvent, controller.letGamepadInputsGoThrough, controller.alwaysSendTypingEvents, controller.autoHideShowPassword, controller.cancelOnOutsideClick, controller.controllerIndex )
	if not String.IsNilOrEmpty( controller.defaultValue ) then
		local f13_local1 = String.RemoveLocalizedMark( controller.defaultValue )
		local f13_local2 = nil
		if controller.maxLength < #f13_local1 then
			local f13_local3 = controller.maxLength
			controller.maxLength = nil
			local f13_local4 = MenuBuilder.BuildRegisteredType( "UIText", controller )
			controller.maxLength = f13_local3
			f13_local4.id = "defaultText"
			self.defaultText = f13_local4
			self:addElement( f13_local4 )
			f13_local4:SetAnchorsAndPosition( 0, 0, 0, 0, 0, 0, 0, 0 )
			f13_local4:SetFont( controller.font )
			f13_local4:SetAlignment( controller.alignment )
			f13_local4:setTextSelectionHighlightColor( controller.textSelectionColor.r, controller.textSelectionColor.g, controller.textSelectionColor.b, controller.textSelectionColor.a )
			f13_local2 = f13_local4
		else
			f13_local2 = self
		end
		if CONDITIONS.IsGamepadActiveInputMethodForPrompts( controller.controllerIndex ) then
			f13_local2:setTextEditText( "" )
		else
			f13_local2:setTextEditText( f13_local1 )
		end
	end
	if controller.useAutoAlign then
		self:setUseStencil( true )
	end
	return self
end

local f0_local6 = {
	[0x153F79AC897F00D] = LUI.UIElement.build,
	[0xCC947913CC4D16C] = LUI.UIText.build,
	[0x6DDC9E0081A8540] = LUI.UIImage.build,
	[0x950F5B9DBDA4EA3] = LUI.UIButton.build,
	[0xD9EFEA750625F40] = LUI.UITimer.build,
	[0x7520D2B60F772E9] = f0_local4,
	[0x5D96CD16B9533B9] = LUI.UIVerticalList.build,
	[0x3140B5F00A687FB] = LUI.UIHorizontalList.build,
	[0xA05ED7808CB87E2] = LUI.UICountdown.build,
	[0xB4A8CCB5801EA90] = LUI.UITechyDigits.build,
	[0x40FCA7B7BB7D124] = f0_local5,
	[0x97AC010F0885B88] = buildOwnerDraw,
	[0x3597B23B8036D78] = buildTextEdit
}
function registerType( f12_arg0, f12_arg1 )
	if type( f12_arg0 ) == "string" then
		f12_arg0 = 0x0 .. f12_arg0
	end
	f0_local0[f12_arg0] = f12_arg1
end

function unregisterType( f11_arg0 )
	f0_local0[f11_arg0] = nil
end

function buildMenu( f10_arg0, f10_arg1 )
	if not f10_arg1 then
		f10_arg1 = {}
	end
	return BuildRegisteredType( f10_arg0, f10_arg1 )
end

function RemoveTypeRef( f9_arg0 )
	local f9_local0 = f0_local0[f9_arg0]
	if f9_local0 and 0 < f9_local0 then
		local f9_local1 = f9_local0 - 1
		f0_local0[f9_arg0] = f9_local1
		if f9_local1 == 0 then
			table.insert( f0_local0, f9_arg0 )
		else
			
		end
	end
end

function AddRequirePath( f8_arg0, f8_arg1 )
	if type( f8_arg0 ) == "string" then
		
	else
		
	end
	f0_local0[f8_arg0] = f8_arg1
end

function IsRequirePathRegistered( f7_arg0 )
	if type( f7_arg0 ) == "string" then
		f7_arg0 = 0x0 .. f7_arg0
	end
	return f0_local0[f7_arg0] ~= nil
end

function LoadFile( f6_arg0, f6_arg1 )
	if type( f6_arg0 ) == "string" then
		f6_arg0 = 0x0 .. f6_arg0
	end
	local f6_local0 = f6_arg0
	if MenuBuilder.IsRequirePathRegistered( f6_arg0 ) then
		local f6_local1 = f0_local0[f6_arg0]
		if f6_local1 == nil then
			f0_local0[f6_arg0] = 0
			f6_local1 = 0
		end
		if f6_local1 < 1 then
			Engine[0xD75F5E555D60E1]( "Load file " .. tostring( f6_local0 ) )
			requireInC( f0_local0[f6_arg0] )
			Engine[0x4D47DEF7D5ED4B9]()
			if not f6_arg1 and f6_local1 == 0 then
				table.insert( f0_local0, f6_arg0 )
			end
		end
	end
end

function BuildRegisteredType( f5_arg0, f5_arg1 )
	Engine[0xD75F5E555D60E1]( "Build widget type " .. tostring( f5_arg0 ) )
	local f5_local0 = Engine[0x5F84BCD38F63878]()
	if RequiresDb then
		local f5_local1 = Engine[0xEE6F69FEA944B13]()
		for f5_local5, f5_local6 in ipairs( RequiresDb.AlwaysLoadedWidgetRequires ) do
			local f5_local7, f5_local8, f5_local9 = string.find( f5_local6, "%.(%a-)$" )
			if 0x0 .. f5_local9 == f5_arg0 then
				if f5_local1 then
				
				else
					require( f5_local6 )
					break
				end
				f5_local1:AddPreviewDependency( f5_local6 )
			end
		end
	end
	local f5_local1 = f5_arg0
	if type( f5_arg0 ) == "string" then
		f5_arg0 = 0x0 .. f5_arg0
	end
	if f5_local0 then
		local f5_local2 = f0_local0[f5_arg0]
		LoadFile( f5_arg0, true )
	end
	local f5_local2 = f0_local0[f5_arg0]
	if not f5_local2 then
		Engine[0x4D47DEF7D5ED4B9]()
		return nil
	end
	Engine[0xD75F5E555D60E1]( "Exec widget constructor " .. tostring( f5_local1 ) )
	local f5_local3 = f5_local2( nil, f5_arg1 )
	Engine[0x4D47DEF7D5ED4B9]()
	if f5_local0 then
		local f5_local4 = f0_local0[f5_arg0]
		if f5_local4 then
			f0_local0[f5_arg0] = f5_local4 + 1
		end
		if Engine[0x5F84BCD38F63878]() and IsRequirePathRegistered( f5_arg0 ) and f5_local3[0x5A2686A1843D38D] then
			if f5_local3[0xF23A0A02C0DD494] == nil then
				f5_local3[0xF23A0A02C0DD494] = {}
			end
			table.insert( f5_local3[0xF23A0A02C0DD494], f5_local3[0x5A2686A1843D38D] )
		end
	end
	f5_local3[0x5A2686A1843D38D] = f5_arg0
	if f5_arg1 and f5_arg1.dataContext then
		f5_local3:SetDataSource( f5_arg1.dataContext, f5_arg1.controllerIndex )
	end
	Engine[0x4D47DEF7D5ED4B9]()
	return f5_local3
end

function IsTypeAvailable( f4_arg0 )
	if type( f4_arg0 ) == "string" then
		f4_arg0 = 0x0 .. f4_arg0
	end
	local f4_local0 = IsTypeRegistered( f4_arg0 )
	if not f4_local0 then
		f4_local0 = MenuBuilder.IsRequirePathRegistered( f4_arg0 )
	end
	return f4_local0
end

function IsTypeRegistered( f3_arg0 )
	if type( f3_arg0 ) == "string" then
		f3_arg0 = 0x0 .. f3_arg0
	end
	return f0_local0[f3_arg0] ~= nil
end

function HotloadCleanup()
	Engine[0xD75F5E555D60E1]( "Hotload Cleanup" )
	if Dvar[0x1FAB6D9A30481F8]( 0xC920AB801DA50D4 ) and Dvar[0x9E5BE3B4BBA4E0E]( 0xC920AB801DA50D4 ) then
		if 0 < #f0_local0 then
			local f2_local0 = f0_local0[1]
			table.remove( f0_local0, 1 )
			if f0_local0[f2_local0] == 0 then
				Engine[0xD75F5E555D60E1]( "Unload file " .. tostring( f2_local0 ) )
				DiscardFile( f0_local0[f2_local0], f2_local0 )
				Engine[0x4D47DEF7D5ED4B9]()
				f0_local0[f2_local0] = nil
			end
		end
	else
		f0_local0 = {}
	end
	Engine[0x4D47DEF7D5ED4B9]()
end

function ReportUnusedRegisteredTypes()
	
end

LockTable( _M )
