-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 04-10-2025 21:43
module( ..., package.seeall )
local f0_local0 = function ( f10_arg0, f10_arg1, f10_arg2 )
	f10_arg0.PromptText:SetAlpha( 1 )
	if f10_arg2 then
		f10_arg0.PromptText:SetWordWrap( false )
		f10_arg0.PromptText:SetAlignment( LUI.Alignment.Right )
		f10_arg0.PromptText:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, 0, _1080p * 43, _1080p * -12, _1080p * 12 )
		f10_arg0.PromptText:SetFontSize( 24 * _1080p )
	else
		f10_arg0.PromptText:SetWordWrap( true )
		f10_arg0.PromptText:SetAlignment( LUI.Alignment.Center )
		f10_arg0.PromptText:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, 0, _1080p * 60, _1080p * -15, _1080p * 15 )
		f10_arg0.PromptText:SetFontSize( 30 * _1080p )
	end
end

local f0_local1 = function ( f9_arg0, f9_arg1, f9_arg2 )
	f9_arg0.SetupSelected = f0_local0
end

function StreakPromptIcon( menu, controller )
	local self = LUI.UIElement.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 60 * _1080p, 0, 60 * _1080p )
	self.id = "StreakPromptIcon"
	self._animationSets = self._animationSets or {}
	self._sequences = self._sequences or {}
	self._sequenceLengths = self._sequenceLengths or {}
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine[0x12586A3F4FB490E]() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1, "Missing controllerIndex!" )
	local f1_local2 = self
	local GamepadBG = nil
	
	GamepadBG = LUI.UIImage.new()
	GamepadBG.id = "GamepadBG"
	GamepadBG:SetRGBFromTable( SWATCHES.vColors.DarkBackground, 0 )
	GamepadBG:SetAlpha( 0.3, 0 )
	GamepadBG:setImage( RegisterMaterial( "widg_glow_circle" ), 0 )
	GamepadBG:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, _1080p * 9, _1080p * 51, _1080p * -21, _1080p * 21 )
	self:addElement( GamepadBG )
	self.GamepadBG = GamepadBG
	
	local PromptText = nil
	
	PromptText = LUI.UIStyledText.new()
	PromptText.id = "PromptText"
	PromptText:SetRGBFromTable( SWATCHES.HUD.vHUDDefault, 0 )
	PromptText:setText( "B", 0 )
	PromptText:SetFont( FONTS.GetFont( FONT_STYLES.fontStyle_LSubHeader.font.File ) )
	PromptText:SetFontSize( 42 * _PT )
	PromptText:SetMinFontSize( 30 * _PT )
	PromptText:SetWordWrap( false )
	PromptText:SetAlignment( LUI.Alignment.Center )
	PromptText:SetTintFontIcons( true )
	PromptText:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, 0, _1080p * 60, _1080p * -15, _1080p * 15 )
	self:addElement( PromptText )
	self.PromptText = PromptText
	
	self._sequences.DefaultSequence = function ()
		
	end
	
	self._sequenceLengths.DefaultSequence = 0
	local f1_local5 = nil
	GamepadBG:RegisterAnimationSequence( "Unavailable", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	PromptText:RegisterAnimationSequence( "Unavailable", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.Unavailable = function ()
		menu:AnimateSequence( "Unavailable" )
		menu:AnimateSequence( "Unavailable" )
	end
	
	self._sequenceLengths.Unavailable = 0
	local f1_local6 = nil
	GamepadBG:RegisterAnimationSequence( "Available", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	PromptText:RegisterAnimationSequence( "Available", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.Available = function ()
		menu:AnimateSequence( "Available" )
		menu:AnimateSequence( "Available" )
	end
	
	self._sequenceLengths.Available = 0
	local f1_local7 = nil
	GamepadBG:RegisterAnimationSequence( "Used", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	PromptText:RegisterAnimationSequence( "Used", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.Used = function ()
		menu:AnimateSequence( "Used" )
		menu:AnimateSequence( "Used" )
	end
	
	self._sequenceLengths.Used = 0
	local f1_local8 = nil
	GamepadBG:RegisterAnimationSequence( "Selected", {
		{
			value = 4.667261640415006E-62,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	PromptText:RegisterAnimationSequence( "Selected", {
		{
			value = 1,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.Selected = function ()
		menu:AnimateSequence( "Selected" )
		menu:AnimateSequence( "Selected" )
	end
	
	self._sequenceLengths.Selected = 0
	local f1_local9 = nil
	GamepadBG:RegisterAnimationSequence( "NotSelected", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	PromptText:RegisterAnimationSequence( "NotSelected", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.NotSelected = function ()
		menu:AnimateSequence( "NotSelected" )
		menu:AnimateSequence( "NotSelected" )
	end
	
	self._sequenceLengths.NotSelected = 0
	local f1_local10 = nil
	GamepadBG:RegisterAnimationSequence( "KeyboardSelected", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	PromptText:RegisterAnimationSequence( "KeyboardSelected", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.KeyboardSelected = function ()
		menu:AnimateSequence( "KeyboardSelected" )
		menu:AnimateSequence( "KeyboardSelected" )
	end
	
	self._sequenceLengths.KeyboardSelected = 0
	f0_local0( self, f1_local1, controller )
	return self
end

MenuBuilder.registerType( "StreakPromptIcon", StreakPromptIcon )
LockTable( _M )
