-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 02-09-2025 10:42
module( ..., package.seeall )
local f0_local0 = function ( f8_arg0 )
	if f8_arg0.PromptButton then
		ACTIONS.AnimateSequence( f8_arg0.PromptButton, "OnSale" )
	end
end

local f0_local1 = function ( f7_arg0 )
	if not f7_arg0._expanded then
		f7_arg0._expanded = true
		ACTIONS.AnimateSequence( f7_arg0, "Expanded" )
		if f7_arg0.PromptButton then
			ACTIONS.AnimateSequence( f7_arg0.PromptButton, "Expanded" )
			ACTIONS.AnimateSequence( f7_arg0.PromptButton, "GlowPulse" )
		end
	end
end

local f0_local2 = function ( f6_arg0, f6_arg1 )
	if f6_arg0._expanded then
		f6_arg0._expanded = false
		ACTIONS.AnimateSequence( f6_arg0, "Contracted" )
		if f6_arg0.PromptButton then
			if f6_arg1 then
				ACTIONS.AnimateSequence( f6_arg0.PromptButton, "ContractedSmaller" )
			else
				ACTIONS.AnimateSequence( f6_arg0.PromptButton, "Contracted" )
			end
		end
	elseif f6_arg1 and f6_arg0.PromptButton then
		ACTIONS.AnimateSequence( f6_arg0.PromptButton, "SetContractedSmaller" )
	end
end

local f0_local3 = function ( f5_arg0, f5_arg1, f5_arg2 )
	f5_arg0.FlagOnSale = f0_local0
	f5_arg0.FlagExpanded = f0_local0
	f5_arg0.FlagContracted = f0_local0
end

function MainMenuBladeStoreOverlay( menu, controller )
	local self = LUI.UIElement.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 512 * _1080p, 0, 1080 * _1080p )
	self.id = "MainMenuBladeStoreOverlay"
	self._animationSets = self._animationSets or {}
	self._sequences = self._sequences or {}
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine.DDJFBBJAIG() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1 )
	local f1_local2 = self
	local PromptButton = nil
	
	PromptButton = MenuBuilder.BuildRegisteredType( "MainMenuBladePromptButton", {
		controllerIndex = f1_local1
	} )
	PromptButton.id = "PromptButton"
	PromptButton.PurchaseText:setText( Engine.CBBHFCGDIC( "BATTLEPASS/PURCHASE_HERE" ), 0 )
	PromptButton:SetAnchorsAndPosition( 0.5, 0.5, 1, 0, _1080p * -211, _1080p * 211, _1080p * -220, _1080p * -90 )
	self:addElement( PromptButton )
	self.PromptButton = PromptButton
	
	self._sequences.DefaultSequence = function ()
		
	end
	
	local f1_local4 = nil
	PromptButton:RegisterAnimationSequence( "Contracted", {
		{
			value = 4.667261642226141E-62,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.Contracted = function ()
		menu:AnimateSequence( "Contracted" )
	end
	
	local f1_local5 = nil
	PromptButton:RegisterAnimationSequence( "Expanded", {
		{
			value = 1,
			duration = 130,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.Expanded = function ()
		menu:AnimateSequence( "Expanded" )
	end
	
	f0_local0( self, f1_local1, controller )
	return self
end

MenuBuilder.registerType( "MainMenuBladeStoreOverlay", MainMenuBladeStoreOverlay )
LockTable( _M )
