-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 27-09-2025 22:41
module( ..., package.seeall )
local f0_local0 = function ( f19_arg0, f19_arg1 )
	local f19_local0 = MenuBuilder.BuildRegisteredType( "PopupOK", {
		controllerIndex = f19_arg1.controllerIndex,
		title = Engine.CBBHFCGDIC( "MENU/ERROR" ),
		message = f19_arg1.message
	} )
	f19_local0.id = "RegimentRestrictionPopup"
	return f19_local0
end

MenuBuilder.registerType( "RegimentRestrictionPopup", f0_local0 )
local f0_local1 = function ( f18_arg0, f18_arg1, f18_arg2, f18_arg3 )
	local f18_local0 = true
	local f18_local1 = true
	if not f18_arg2 or #f18_arg2 == 0 or #f18_arg2 > FRIENDS.CLANS_MAX_NAME_LENGTH then
		f18_local0 = false
	end
	if not f18_arg3 or #f18_arg3 == 0 or #f18_arg3 > FRIENDS.CLANS_CLANTAG_LENGTH then
		f18_local1 = false
	end
	if f18_local0 and not Engine.HEIIHIEH( f18_arg2 ) then
		if f18_arg0.PopupButtons == nil or f18_arg0.PopupButtons.NameInputButton:GetErrorState() == false then
			LUI.FlowManager.RequestPopupMenu( f18_arg0, "RegimentRestrictionPopup", true, f18_arg1, false, {
				controllerIndex = f18_arg1,
				message = Engine.CBBHFCGDIC( "REGIMENTS/DIGITS_RESTRICTION_ERROR", FRIENDS.MAX_DIGITS_IN_CLAN_NAME )
			} )
		end
		f18_local0 = false
	end
	if f18_local0 and f18_local1 and OSK.CJAFGACAFH then
		local f18_local2 = OSK.CJAFGACAFH( f18_arg1, f18_arg3 .. f18_arg2 )
		if 0 < #f18_local2 then
			LUI.FlowManager.RequestPopupMenu( f18_arg0, "RegimentRestrictionPopup", true, f18_arg1, false, {
				controllerIndex = f18_arg1,
				message = Engine.CBBHFCGDIC( f18_local2 )
			} )
			f18_local0 = false
			f18_local1 = false
		end
	end
	if f18_arg0.PopupButtons then
		f18_arg0.PopupButtons.NameInputButton:SetErrorState( not f18_local0 )
		f18_arg0.PopupButtons.TagInputButton:SetErrorState( not f18_local1 )
	end
	local f18_local3
	if f18_local0 then
		f18_local3 = f18_local0
	else
		f18_local3 = f18_local1
	end
	return f18_local3
end

local f0_local2 = function ( f17_arg0, f17_arg1 )
	local f17_local0 = f17_arg0:IsInputValid( f17_arg1, f17_arg0._name, f17_arg0._tag )
	if f17_arg0.PopupButtons then
		f17_arg0.PopupButtons.CreateButton:SetButtonDisabled( not f17_local0 )
	end
end

function PostLoadFunc( f4_arg0, f4_arg1, f4_arg2 )
	assert( f4_arg0.PopupButtons.NameInputButton )
	assert( f4_arg0.PopupButtons.TagInputButton )
	assert( f4_arg0.PopupButtons.CreateButton )
	assert( f4_arg0.MenuTitle )
	f4_arg0.MenuTitle:SetTitle( ToUpperCase( Engine.CBBHFCGDIC( "LUA_MENU/REGIMENT_CREATE" ) ) )
	f4_arg0.UpdateRegimentCreateStatus = f0_local0
	f4_arg0.IsInputValid = f0_local0
	f4_arg0._isInit = f4_arg2.init
	f4_arg0._name = nil
	f4_arg0._tag = nil
	local f4_local0 = Engine.CBBHFCGDIC( "LUA_MENU/REGIMENT_ENTER_NAME" )
	local f4_local1 = Engine.CBBHFCGDIC( "LUA_MENU/REGIMENT_ENTER_TAG" )
	f4_arg0.PopupButtons.NameInputButton:SetupUITextEdit( f4_arg1, FRIENDS.CLANS_MAX_NAME_LENGTH, f4_local0, true )
	f4_arg0.PopupButtons.TagInputButton:SetupUITextEdit( f4_arg1, FRIENDS.CLANS_CLANTAG_LENGTH, f4_local1, true )
	f4_arg0.PopupButtons.NameCharacters:setText( Engine.CBBHFCGDIC( "LUA_MENU/CHARACTERS_USED", 0, FRIENDS.CLANS_MAX_NAME_LENGTH ) )
	f4_arg0.PopupButtons.TagCharacters:setText( Engine.CBBHFCGDIC( "LUA_MENU/CHARACTERS_USED", 0, FRIENDS.CLANS_CLANTAG_LENGTH ) )
	f4_arg0.PopupButtons.NameInputButton.isTypingCallbackFunc = function ( f16_arg0, f16_arg1 )
		local f16_local0 = #f16_arg1
		f4_arg0._name = f16_arg1
		f4_arg0.PopupButtons.NameCharacters:setText( Engine.CBBHFCGDIC( "LUA_MENU/CHARACTERS_USED", f16_local0, FRIENDS.CLANS_MAX_NAME_LENGTH ) )
		if f16_local0 > FRIENDS.CLANS_MAX_NAME_LENGTH then
			f4_arg0.PopupButtons.NameCharacters:SetRGBFromTable( SWATCHES.HUDWarnings.danger )
		else
			f4_arg0.PopupButtons.NameCharacters:SetRGBFromTable( SWATCHES.text.primaryText )
		end
	end
	
	f4_arg0.PopupButtons.NameInputButton:addEventHandler( "text_edit_is_typing", function ( f15_arg0, f15_arg1 )
		if f15_arg0._textEditingActive then
			f15_arg0.isTypingCallbackFunc( f15_arg1.isTyping, f15_arg1.text or "" )
		end
	end )
	f4_arg0.PopupButtons.NameInputButton.buttonActionCallbackFunc = function ()
		if LUI.IsLastInputGamepad( f4_arg0 ) and Engine.HDGDBCJFG() then
			f4_arg0.PopupButtons.NameInputButton:TextEditOff()
			local f13_local0 = f4_arg0.PopupButtons.NameInputButton.textEdit:getText()
			OSK.CBJGJDGFC( f4_arg0, Engine.CBBHFCGDIC( "LUA_MENU/REGIMENT_NAME" ), f13_local0, FRIENDS.CLANS_MAX_NAME_LENGTH, true, true, true, function ( f14_arg0, f14_arg1, f14_arg2 )
				if f14_arg1 then
					f13_local0._name = f14_arg1
					f13_local0:UpdateRegimentCreateStatus( f14_arg0 )
					f13_local0.PopupButtons.NameInputButton.textEdit:setTextEditText( f14_arg1 )
					if f14_arg1 ~= "" and not f13_local0.PopupButtons.NameInputButton:GetErrorState() then
						f13_local0.PopupButtons.NameInputButton:processEvent( {
							name = "lose_focus"
						} )
						f13_local0.PopupButtons.TagInputButton:processEvent( {
							name = "gain_focus"
						} )
					else
						f13_local0.PopupButtons.NameInputButton:SetErrorState( true )
					end
					f13_local0.PopupButtons.NameInputButton.isTypingCallbackFunc( nil, f14_arg1 )
				elseif f13_local0._name == nil then
					f13_local0.PopupButtons.NameInputButton:SetErrorState( true )
				end
			end )
		end
	end
	
	f4_arg0.PopupButtons.TagInputButton.isTypingCallbackFunc = function ( f12_arg0, f12_arg1 )
		local f12_local0 = #f12_arg1
		f4_arg0._tag = f12_arg1
		f4_arg0.PopupButtons.TagCharacters:setText( Engine.CBBHFCGDIC( "LUA_MENU/CHARACTERS_USED", f12_local0, FRIENDS.CLANS_CLANTAG_LENGTH ) )
		if f12_local0 > FRIENDS.CLANS_CLANTAG_LENGTH then
			f4_arg0.PopupButtons.TagCharacters:SetRGBFromTable( SWATCHES.HUDWarnings.danger )
		else
			f4_arg0.PopupButtons.TagCharacters:SetRGBFromTable( SWATCHES.text.primaryText )
		end
	end
	
	f4_arg0.PopupButtons.TagInputButton:addEventHandler( "text_edit_is_typing", function ( f11_arg0, f11_arg1 )
		if f11_arg0._textEditingActive then
			f11_arg0.isTypingCallbackFunc( f11_arg1.isTyping, f11_arg1.text or "" )
		end
	end )
	f4_arg0.PopupButtons.TagInputButton.buttonActionCallbackFunc = function ()
		if LUI.IsLastInputGamepad( f4_arg0 ) and Engine.HDGDBCJFG() then
			f4_arg0.PopupButtons.TagInputButton:TextEditOff()
			local f9_local0 = f4_arg0.PopupButtons.TagInputButton.textEdit:getText()
			OSK.CBJGJDGFC( f4_arg0, Engine.CBBHFCGDIC( "LUA_MENU/REGIMENT_TAG" ), f9_local0, FRIENDS.CLANS_CLANTAG_LENGTH, true, true, true, function ( f10_arg0, f10_arg1, f10_arg2 )
				if f10_arg1 then
					f9_local0._tag = f10_arg1
					f9_local0:UpdateRegimentCreateStatus( f10_arg0 )
					f9_local0.PopupButtons.TagInputButton.textEdit:setTextEditText( f10_arg1 )
					if f10_arg1 ~= "" then
						f9_local0.PopupButtons.TagInputButton:processEvent( {
							name = "lose_focus"
						} )
						f9_local0.PopupButtons.CreateButton:processEvent( {
							name = "gain_focus"
						} )
					end
					f9_local0.PopupButtons.TagInputButton.isTypingCallbackFunc( nil, f10_arg1 )
				elseif f9_local0._tag == nil then
					f9_local0.PopupButtons.TagInputButton:SetErrorState( true )
				end
			end )
		end
	end
	
	f4_arg0:addEventHandler( "text_edit_complete", function ( f8_arg0, f8_arg1 )
		if Engine.CGABICJHAI() or not LUI.IsLastInputGamepad( f4_arg0 ) then
			f4_arg0:UpdateRegimentCreateStatus( f4_arg0 )
		end
	end )
	f4_arg0.PopupButtons.CreateButton:addEventHandler( "button_action", function ( f7_arg0, f7_arg1 )
		local f7_local0 = f4_arg0.PopupButtons.NameInputButton.textEdit
		local f7_local1 = f4_arg0.PopupButtons.TagInputButton.textEdit
		local f7_local2
		if not f7_local0._firstInteraction then
			f7_local2 = f7_local0:getText()
			if not f7_local2 then
			
			else
				local f7_local3
				if not f7_local1._firstInteraction then
					f7_local3 = f7_local1:getText()
					if not f7_local3 then
					
					else
						if f4_arg0:IsInputValid( f4_arg0, f7_local2, f7_local3 ) then
							LUI.FlowManager.RequestPopupMenu( nil, "CreateRegimentConfirmationPopup", true, f7_arg1.controller, false, {
								regimentName = f7_local2,
								regimentTag = f7_local3,
								IsInputValid = f4_arg0.IsInputValid
							} )
						end
					end
				end
				f7_local3 = ""
			end
		end
		f7_local2 = ""
	end )
	f4_arg0:registerEventHandler( "clans_notification", function ( element, event )
		local f6_local0 = event.options
		if f6_local0.genEventName == "clans_initialized_clan" then
			LUI.FlowManager.RequestLeaveMenuByName( "RegimentsFenceDialogPopup", true, true )
			if f6_local0.success then
				LUI.FlowManager.RequestPopupMenu( nil, "RegimentsFenceDialogPopup", true, event.controller, false, {
					controllerIndex = f4_arg0,
					message = Engine.CBBHFCGDIC( "LUA_MENU/SWITCHING_REGIMENTS" )
				} )
				if not Clans.FAFJFADBJ( f4_arg0, f6_local0.clanId ) then
					LUI.FlowManager.RequestLeaveMenuByName( "RegimentsFenceDialogPopup", true, true )
					LUI.FlowManager.RequestPopupMenu( f4_arg0, "PopupOK", true, f4_arg0, false, {
						title = Engine.CBBHFCGDIC( "MENU/ERROR" ),
						message = Engine.CBBHFCGDIC( "LUA_MENU/REGIMENT_GENERIC_ERROR" )
					} )
				end
			else
				local f6_local1 = f6_local0.error
				LUI.FlowManager.RequestPopupMenu( f4_arg0, "PopupOK", true, f4_arg0, false, {
					title = Engine.CBBHFCGDIC( "MENU/ERROR" ),
					message = Engine.CBBHFCGDIC( "LUA_MENU/REGIMENT_GENERIC_ERROR" )
				} )
			end
		end
	end )
	f4_arg0.backButtonOverride = function ( f5_arg0, f5_arg1 )
		f4_arg0.PopupButtons.NameInputButton:TextEditOff()
		f4_arg0.PopupButtons.TagInputButton:TextEditOff()
	end
	
	if IsLanguageArabic() then
		ACTIONS.AnimateSequence( f4_arg0, "AR" )
	end
end

function RegimentsCreatePopup( menu, controller )
	local self = LUI.UIElement.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 700 * _1080p, 0, 1080 * _1080p )
	self.id = "RegimentsCreatePopup"
	self._animationSets = self._animationSets or {}
	self._sequences = self._sequences or {}
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine.DDJFBBJAIG() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1 )
	local f1_local2 = self
	local MenuTitle = nil
	
	MenuTitle = MenuBuilder.BuildRegisteredType( "MenuTitle", {
		controllerIndex = f1_local1
	} )
	MenuTitle.id = "MenuTitle"
	MenuTitle.MenuTitle:setText( ToUpperCase( Engine.CBBHFCGDIC( "LUA_MENU/REGIMENT_CREATE" ) ), 0 )
	MenuTitle.Line:SetLeft( 0, 0 )
	MenuTitle:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 1020, 0, _1080p * 100 )
	self:addElement( MenuTitle )
	self.MenuTitle = MenuTitle
	
	local PopupButtons = nil
	
	PopupButtons = MenuBuilder.BuildRegisteredType( "RegimentsCreatePopupButtons", {
		controllerIndex = f1_local1
	} )
	PopupButtons.id = "PopupButtons"
	PopupButtons:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 130, _1080p * 570, _1080p * 200, _1080p * 470 )
	self:addElement( PopupButtons )
	self.PopupButtons = PopupButtons
	
	local WarningLabel = nil
	
	WarningLabel = LUI.UIStyledText.new()
	WarningLabel.id = "WarningLabel"
	WarningLabel:SetRGBFromTable( SWATCHES.genericMenu.bodycopy, 0 )
	WarningLabel:setText( Engine.CBBHFCGDIC( "REGIMENTS/NAME_WARNING" ), 0 )
	WarningLabel:SetFont( FONTS.GetFont( FONTS.BodyRegular.File ) )
	WarningLabel:SetAlignment( LUI.Alignment.Left )
	WarningLabel:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 130, _1080p * 570, _1080p * 480, _1080p * 502 )
	self:addElement( WarningLabel )
	self.WarningLabel = WarningLabel
	
	self._sequences.DefaultSequence = function ()
		
	end
	
	local f1_local6 = nil
	WarningLabel:RegisterAnimationSequence( "AR", {
		{
			duration = 0,
			property = TWEEN_PROPERTY.Bottom,
			value = _1080p * 510
		}
	} )
	self._sequences.AR = function ()
		menu:AnimateSequence( "AR" )
	end
	
	PostLoadFunc( self, f1_local1, controller )
	return self
end

MenuBuilder.registerType( "RegimentsCreatePopup", RegimentsCreatePopup )
LockTable( _M )
