-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 27-09-2025 22:41
module( ..., package.seeall )
local f0_local0 = function ( f4_arg0, f4_arg1, f4_arg2 )
	local f4_local0, f4_local1 = Engine.CBCJIDDIED( f4_arg1 )
	assert( COLOR_BLIND.UIFilter[COLOR_BLIND.modes.none][f4_arg2] )
	f4_arg0._swatchWidgets = {}
	for f4_local5, f4_local6 in pairs( COLOR_BLIND.UIFilter[COLOR_BLIND.modes.none][f4_arg2] ) do
		local f4_local7 = MenuBuilder.BuildRegisteredType( "ColorblindSwatch", {
			controllerIndex = f4_arg1
		} )
		f4_local7:Setup( f4_arg1, f4_arg2, f4_local5 )
		f4_arg0:addElement( f4_local7 )
		table.insert( f4_arg0._swatchWidgets, f4_local7 )
	end
end

local f0_local1 = function ( f3_arg0, f3_arg1 )
	for f3_local3, f3_local4 in ipairs( f3_arg0._swatchWidgets ) do
		f3_local4:UpdateSwatch( f3_arg1 )
	end
end

local f0_local2 = function ( f2_arg0, f2_arg1, f2_arg2 )
	f2_arg0.Setup = f0_local0
	f2_arg0.Update = f0_local0
end

function ColorblindSwatchList( menu, controller )
	local self = LUI.UIHorizontalStackedLayout.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 250 * _1080p, 0, 30 * _1080p )
	self.id = "ColorblindSwatchList"
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine.DDJFBBJAIG() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1 )
	local f1_local2 = self
	self:SetSpacing( 5 * _1080p )
	local SwatchCat = nil
	
	SwatchCat = LUI.UIText.new()
	SwatchCat.id = "SwatchCat"
	SwatchCat:setText( "", 0 )
	SwatchCat:SetFont( FONTS.GetFont( FONTS.MainRegular.File ) )
	SwatchCat:SetAlignment( LUI.Alignment.Left )
	SwatchCat:SetAnchorsAndPosition( 0, 1, 0.5, 0.5, 0, _1080p * 123, _1080p * -9, _1080p * 9 )
	self:addElement( SwatchCat )
	self.SwatchCat = SwatchCat
	
	f0_local0( self, f1_local1, controller )
	return self
end

MenuBuilder.registerType( "ColorblindSwatchList", ColorblindSwatchList )
LockTable( _M )
