-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 21-11-2025 08:48
LUI.AsyncPagedDataProviderWithFilter = LUI.Class( LUI.AsyncPagedDataProvider )
local f0_local0 = function ( f17_arg0, f17_arg1, f17_arg2 )
	f17_arg0:DebugPrint( "*> " .. f17_arg1, f17_arg2 )
end

LUI.AsyncPagedDataProviderWithFilter.GetLastAvailableItemIndex = function ( f16_arg0 )
	return #f16_arg0._indexRemap
end

local f0_local1 = function ( f15_arg0 )
	f15_arg0._sortingOutdated = true
	local f15_local0 = #f15_arg0._indexRemap
	local f15_local1 = f15_arg0._numRawItemsFiltered + 1
	f15_arg0._numRawItemsFiltered = LUI.AsyncPagedDataProvider.GetLastAvailableItemIndex( f15_arg0 )
	f0_local0( f15_arg0, "FilterMoreItems: " .. f15_local1 .. " -> " .. f15_arg0._numRawItemsFiltered )
	for f15_local2 = f15_local1, f15_arg0._numRawItemsFiltered, 1 do
		if f15_arg0._filterFunc( f15_arg0._owner, LUI.AsyncPagedDataProvider.Get( f15_arg0, f15_local2 ) ) then
			f15_arg0._indexRemap[f15_local0 + 1] = f15_local2
		end
	end
end

local f0_local2 = function ( f14_arg0, f14_arg1 )
	if f14_arg0._backendAllPagesFetched then
		return false
	end
	local f14_local0 = 1
	if f14_arg0._lastAvailablePageId then
		assert( f14_arg0._pageSize )
		f14_local0 = f14_arg0._pageSize * (f14_arg0._lastAvailablePageId + 1) + 1
	end
	f0_local0( f14_arg0, "FetchNextPage, item: " .. f14_local0 )
	LUI.AsyncPagedDataProvider.Get( f14_arg0, f14_local0, f14_arg1 )
	return true
end

local f0_local3 = function ( f13_arg0, f13_arg1, f13_arg2 )
	f13_arg0:UpdateDataSorting()
	if f13_arg0._indexRemap[f13_arg1] then
		LUI.AsyncPagedDataProvider.Get( f13_arg0, f13_arg0._indexRemap[f13_arg1], f13_arg2 )
	elseif f13_arg2 then
		f13_arg2( f13_arg0._owner, nil )
	end
end

local f0_local4 = nil
f0_local4 = function ( f11_arg0, f11_arg1, f11_arg2 )
	if f0_local0( f11_arg0, function ( f12_arg0 )
		f11_arg0( f11_arg0 )
		if f11_arg0._indexRemap[f11_arg0] then
			f11_arg0( f11_arg0, f11_arg0, f11_arg0 )
		else
			f11_arg0( f11_arg0, f11_arg0, f11_arg0 )
		end
	end
	 ) == false then
		f0_local0( f11_arg0, f11_arg1, f11_arg2 )
	end
end

LUI.AsyncPagedDataProviderWithFilter.UpdateDataFiltering = function ( f10_arg0, f10_arg1, f10_arg2 )
	if f10_arg0._owner == nil then
		return 
	end
	f0_local0( f10_arg0, "UpdateDataFiltering", f10_arg0.DebugLevel.IMPORTANT )
	f10_arg0._indexRemap = {}
	f10_arg0._numRawItemsFiltered = 0
	f0_local0( f10_arg0 )
	if f10_arg1 and #f10_arg0._indexRemap < f10_arg1 then
		f10_arg0:FetchRange( f10_arg1, f10_arg1, f10_arg2 )
	else
		f10_arg0:UpdateDataSorting()
		if f10_arg2 then
			f10_arg2( f10_arg0._owner )
		end
	end
end

LUI.AsyncPagedDataProviderWithFilter.UpdateDataSorting = function ( f8_arg0 )
	if not f8_arg0._sortFunc or f8_arg0._owner == nil then
		
	end
	f0_local0( f8_arg0, "UpdateDataSorting", f8_arg0.DebugLevel.IMPORTANT )
	local f8_local0 = f8_arg0._debugLvl
	f8_arg0._debugLvl = f8_arg0.DebugLevel.NONE
	table.sort( f8_arg0._indexRemap, function ( f9_arg0, f9_arg1 )
		return f8_arg0._sortFunc( f8_arg0._owner, LUI.AsyncPagedDataProvider.Get( f8_arg0, f9_arg0 ), LUI.AsyncPagedDataProvider.Get( f8_arg0, f9_arg1 ) )
	end )
	f8_arg0._debugLvl = f8_local0
end

LUI.AsyncPagedDataProviderWithFilter.Get = function ( f7_arg0, f7_arg1, f7_arg2, f7_arg3 )
	if f7_arg0._indexRemap[f7_arg1] == nil then
		if f7_arg0._backendAllPagesFetched and f7_arg0._numRawItemsFiltered == LUI.AsyncPagedDataProvider.GetLastAvailableItemIndex( f7_arg0 ) then
			if f7_arg2 then
				f7_arg2( f7_arg0._owner, nil )
			end
			return nil
		else
			f0_local0( f7_arg0, "FilteredGet, item: " .. f7_arg1 .. " -> Ask more pages" )
			f0_local0( f7_arg0, f7_arg1, f7_arg2 )
			return nil
		end
	else
		return LUI.AsyncPagedDataProvider.Get( f7_arg0, f7_arg0._indexRemap[f7_arg1], f7_arg2, f7_arg3 )
	end
end

LUI.AsyncPagedDataProviderWithFilter.FetchRange = function ( f6_arg0, f6_arg1, f6_arg2, f6_arg3, f6_arg4 )
	if f6_arg4 then
		LUI.AsyncPagedDataProvider.FetchRange( f6_arg0, f6_arg1, f6_arg2, f6_arg3, f6_arg4 )
	else
		LUI.AsyncPagedDataProvider.FetchRange( f6_arg0, f6_arg2, f6_arg2, f6_arg3, f6_arg4 )
	end
end

LUI.AsyncPagedDataProviderWithFilter.SetFilterFunc = function ( f5_arg0, f5_arg1 )
	f5_arg0._filterFunc = f5_arg1
end

LUI.AsyncPagedDataProviderWithFilter.SetSortFunc = function ( f4_arg0, f4_arg1 )
	f4_arg0._sortFunc = f4_arg1
end

LUI.AsyncPagedDataProviderWithFilter.ResetData = function ( f3_arg0, f3_arg1, f3_arg2 )
	f3_arg0._indexRemap = {}
	f3_arg0._numRawItemsFiltered = 0
	LUI.AsyncPagedDataProvider.ResetData( f3_arg0, f3_arg1, f3_arg2 )
end

LUI.AsyncPagedDataProviderWithFilter.init = function ( f1_arg0, f1_arg1, f1_arg2 )
	LUI.AsyncPagedDataProvider.init( f1_arg0, f1_arg1, f1_arg2 )
	f1_arg0:SetConsecutiveFetchMode( true )
	f1_arg0:SetFilterFunc( function ( f2_arg0 )
		return true
	end )
end

