-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 13-07-2025 21:52
module( ..., package.seeall )
local f0_local0 = function ( f8_arg0 )
	if f8_arg0.PromptButton then
		ACTIONS.AnimateSequence( f8_arg0.PromptButton, "OnSale" )
	end
end

local f0_local1 = function ( f7_arg0 )
	if not f7_arg0._expanded then
		f7_arg0._expanded = true
		ACTIONS.AnimateSequence( f7_arg0, "Expanded" )
		if f7_arg0.PromptButton then
			ACTIONS.AnimateSequence( f7_arg0.PromptButton, "Expanded" )
			ACTIONS.AnimateSequence( f7_arg0.PromptButton, "GlowPulse" )
		end
	end
end

local f0_local2 = function ( f6_arg0, f6_arg1 )
	if f6_arg0._expanded then
		f6_arg0._expanded = false
		ACTIONS.AnimateSequence( f6_arg0, "Contracted" )
		if f6_arg0.PromptButton then
			if f6_arg1 then
				ACTIONS.AnimateSequence( f6_arg0.PromptButton, "ContractedSmaller" )
			else
				ACTIONS.AnimateSequence( f6_arg0.PromptButton, "Contracted" )
			end
		end
	elseif f6_arg1 and f6_arg0.PromptButton then
		ACTIONS.AnimateSequence( f6_arg0.PromptButton, "SetContractedSmaller" )
	end
end

local f0_local3 = function ( f5_arg0, f5_arg1, f5_arg2 )
	f5_arg0.FlagOnSale = f0_local0
	f5_arg0.FlagExpanded = f0_local0
	f5_arg0.FlagContracted = f0_local0
	ACTIONS.AnimateSequence( f5_arg0.ReviewQuote1, "Variant1" )
	ACTIONS.AnimateSequence( f5_arg0.ReviewQuote2, "Variant2" )
	ACTIONS.AnimateSequence( f5_arg0.ReviewQuote3, "Variant3" )
	ACTIONS.AnimateSequence( f5_arg0.ReviewQuote4, "Variant4" )
end

function MainMenuBladeUpsellOverlay( menu, controller )
	local self = LUI.UIElement.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 512 * _1080p, 0, 1080 * _1080p )
	self.id = "MainMenuBladeUpsellOverlay"
	self._animationSets = self._animationSets or {}
	self._sequences = self._sequences or {}
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine.DDJFBBJAIG() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1 )
	local f1_local2 = self
	local f1_local3 = nil
	if not CONDITIONS.HideBuyMWPromptMagmaBlades() then
		f1_local3 = MenuBuilder.BuildRegisteredType( "MainMenuBladePromptButton", {
			controllerIndex = f1_local1
		} )
		f1_local3.id = "PromptButton"
		f1_local3:SetAlpha( 0.6, 0 )
		f1_local3.PurchaseText:setText( Engine.CBBHFCGDIC( "LUA_MENU/PURCHASE_MW" ), 0 )
		f1_local3:SetAnchorsAndPosition( 0.5, 0.5, 1, 0, _1080p * -211, _1080p * 211, _1080p * -220, _1080p * -90 )
		self:addElement( f1_local3 )
		self.PromptButton = f1_local3
	end
	local AdditionalInfoGradient = nil
	
	AdditionalInfoGradient = LUI.UIImage.new()
	AdditionalInfoGradient.id = "AdditionalInfoGradient"
	AdditionalInfoGradient:SetRGBFromInt( 0, 0 )
	AdditionalInfoGradient:SetAlpha( 0, 0 )
	AdditionalInfoGradient:setImage( RegisterMaterial( "widg_gradient_center_out" ), 0 )
	AdditionalInfoGradient:SetAnchorsAndPosition( 0, 0, 0, 1, _1080p * 72, _1080p * -72, _1080p * 293, _1080p * 338 )
	self:addElement( AdditionalInfoGradient )
	self.AdditionalInfoGradient = AdditionalInfoGradient
	
	local AdditionalInfo = nil
	
	AdditionalInfo = LUI.UIStyledText.new()
	AdditionalInfo.id = "AdditionalInfo"
	AdditionalInfo:SetRGBFromTable( SWATCHES.genericButton.textFocus, 0 )
	AdditionalInfo:SetAlpha( 0, 0 )
	AdditionalInfo:setText( Engine.CBBHFCGDIC( "LUA_MENU/MAGMA_UPSELL_TAGLINE" ), 0 )
	AdditionalInfo:SetFont( FONTS.GetFont( FONTS.MainBold.File ) )
	AdditionalInfo:SetAlignment( LUI.Alignment.Center )
	AdditionalInfo:SetVerticalAlignment( LUI.Alignment.Center )
	AdditionalInfo:SetAnchorsAndPosition( 0, 0, 0, 1, 0, 0, _1080p * 302, _1080p * 330 )
	self:addElement( AdditionalInfo )
	self.AdditionalInfo = AdditionalInfo
	
	local GameContentGradient = nil
	
	GameContentGradient = LUI.UIImage.new()
	GameContentGradient.id = "GameContentGradient"
	GameContentGradient:SetRGBFromTable( SWATCHES.CAC.attachmentEmpty, 0 )
	GameContentGradient:SetAlpha( 0, 0 )
	GameContentGradient:setImage( RegisterMaterial( "widg_gradient_center_out" ), 0 )
	GameContentGradient:SetAnchorsAndPosition( 0, 0, 0, 1, _1080p * -110, _1080p * 110, _1080p * 239, _1080p * 293 )
	self:addElement( GameContentGradient )
	self.GameContentGradient = GameContentGradient
	
	local GameContent = nil
	
	GameContent = LUI.UIStyledText.new()
	GameContent.id = "GameContent"
	GameContent:SetAlpha( 0, 0 )
	GameContent:setText( ToUpperCase( Engine.CBBHFCGDIC( "LUA_MENU/MAGMA_UPSELL_HEADER" ) ), 0 )
	GameContent:SetFont( FONTS.GetFont( FONTS.MainBold.File ) )
	GameContent:SetWordWrap( false )
	GameContent:SetTracking( 2 * _1080p, 0 )
	GameContent:SetAlignment( LUI.Alignment.Center )
	GameContent:SetVerticalAlignment( LUI.Alignment.Center )
	GameContent:SetAnchorsAndPosition( 0, 0, 0, 1, 0, 0, _1080p * 246, _1080p * 282 )
	self:addElement( GameContent )
	self.GameContent = GameContent
	
	local ReviewQuote4 = nil
	
	ReviewQuote4 = MenuBuilder.BuildRegisteredType( "ReviewQuote", {
		controllerIndex = f1_local1
	} )
	ReviewQuote4.id = "ReviewQuote4"
	ReviewQuote4:SetAlpha( 0, 0 )
	ReviewQuote4:SetAnchorsAndPosition( 1, 0, 0, 1, _1080p * -268, _1080p * -18, _1080p * 299, _1080p * 419 )
	self:addElement( ReviewQuote4 )
	self.ReviewQuote4 = ReviewQuote4
	
	local ReviewQuote3 = nil
	
	ReviewQuote3 = MenuBuilder.BuildRegisteredType( "ReviewQuote", {
		controllerIndex = f1_local1
	} )
	ReviewQuote3.id = "ReviewQuote3"
	ReviewQuote3:SetAlpha( 0, 0 )
	ReviewQuote3:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 18, _1080p * 268, _1080p * 299, _1080p * 419 )
	self:addElement( ReviewQuote3 )
	self.ReviewQuote3 = ReviewQuote3
	
	local ReviewQuote2 = nil
	
	ReviewQuote2 = MenuBuilder.BuildRegisteredType( "ReviewQuote", {
		controllerIndex = f1_local1
	} )
	ReviewQuote2.id = "ReviewQuote2"
	ReviewQuote2:SetAlpha( 0, 0 )
	ReviewQuote2:SetAnchorsAndPosition( 1, 0, 0, 1, _1080p * -268, _1080p * -18, _1080p * 73, _1080p * 193 )
	self:addElement( ReviewQuote2 )
	self.ReviewQuote2 = ReviewQuote2
	
	local ReviewQuote1 = nil
	
	ReviewQuote1 = MenuBuilder.BuildRegisteredType( "ReviewQuote", {
		controllerIndex = f1_local1
	} )
	ReviewQuote1.id = "ReviewQuote1"
	ReviewQuote1:SetAlpha( 0, 0 )
	ReviewQuote1:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 18, _1080p * 268, _1080p * 82, _1080p * 202 )
	self:addElement( ReviewQuote1 )
	self.ReviewQuote1 = ReviewQuote1
	
	self._sequences.DefaultSequence = function ()
		
	end
	
	local f1_local12 = nil
	if not CONDITIONS.HideBuyMWPromptMagmaBlades() then
		f1_local3:RegisterAnimationSequence( "Expanded", {
			{
				value = 4.667261642226141E-62,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			},
			{
				duration = 130,
				property = TWEEN_PROPERTY.Left,
				value = _1080p * -211
			},
			{
				duration = 130,
				property = TWEEN_PROPERTY.Right,
				value = _1080p * 211
			},
			{
				value = 1,
				duration = 130,
				property = TWEEN_PROPERTY.Alpha
			}
		} )
	end
	AdditionalInfoGradient:RegisterAnimationSequence( "Expanded", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = -8,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = -2.3534382788928255E-185,
			duration = -48,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	AdditionalInfo:RegisterAnimationSequence( "Expanded", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = -8,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = -48,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	GameContentGradient:RegisterAnimationSequence( "Expanded", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = -2.3534382792352958E-185,
			duration = -8,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	GameContent:RegisterAnimationSequence( "Expanded", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = -9.255965340288647E+61,
			duration = -8,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	ReviewQuote4:RegisterAnimationSequence( "Expanded", {
		{
			value = 1.9991592789737117E+37,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 300,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = -8,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	ReviewQuote3:RegisterAnimationSequence( "Expanded", {
		{
			value = 1.9991592789737117E+37,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 300,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = -8,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	ReviewQuote2:RegisterAnimationSequence( "Expanded", {
		{
			value = 1.9991592789737117E+37,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = -28,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	ReviewQuote1:RegisterAnimationSequence( "Expanded", {
		{
			value = 1.9991592789737117E+37,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 0,
			duration = 200,
			property = TWEEN_PROPERTY.Alpha
		},
		{
			value = 1,
			duration = -28,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.Expanded = function ()
		if not CONDITIONS.HideBuyMWPromptMagmaBlades() then
			menu:AnimateSequence( "Expanded" )
		end
		menu:AnimateSequence( "Expanded" )
		menu:AnimateSequence( "Expanded" )
		menu:AnimateSequence( "Expanded" )
		menu:AnimateSequence( "Expanded" )
		menu:AnimateSequence( "Expanded" )
		menu:AnimateSequence( "Expanded" )
		menu:AnimateSequence( "Expanded" )
		menu:AnimateSequence( "Expanded" )
	end
	
	local f1_local13 = nil
	if not CONDITIONS.HideBuyMWPromptMagmaBlades() then
		f1_local3:RegisterAnimationSequence( "Contracted", {
			{
				value = 4.667261642226141E-62,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			}
		} )
	end
	AdditionalInfoGradient:RegisterAnimationSequence( "Contracted", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	AdditionalInfo:RegisterAnimationSequence( "Contracted", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	GameContentGradient:RegisterAnimationSequence( "Contracted", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	GameContent:RegisterAnimationSequence( "Contracted", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	ReviewQuote4:RegisterAnimationSequence( "Contracted", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	ReviewQuote3:RegisterAnimationSequence( "Contracted", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	ReviewQuote2:RegisterAnimationSequence( "Contracted", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	ReviewQuote1:RegisterAnimationSequence( "Contracted", {
		{
			value = 0,
			duration = 0,
			property = TWEEN_PROPERTY.Alpha
		}
	} )
	self._sequences.Contracted = function ()
		if not CONDITIONS.HideBuyMWPromptMagmaBlades() then
			menu:AnimateSequence( "Contracted" )
		end
		menu:AnimateSequence( "Contracted" )
		menu:AnimateSequence( "Contracted" )
		menu:AnimateSequence( "Contracted" )
		menu:AnimateSequence( "Contracted" )
		menu:AnimateSequence( "Contracted" )
		menu:AnimateSequence( "Contracted" )
		menu:AnimateSequence( "Contracted" )
		menu:AnimateSequence( "Contracted" )
	end
	
	f0_local0( self, f1_local1, controller )
	return self
end

MenuBuilder.registerType( "MainMenuBladeUpsellOverlay", MainMenuBladeUpsellOverlay )
LockTable( _M )
