-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 13-07-2025 21:51
module( ..., package.seeall )
local f0_local0 = function ( f2_arg0, f2_arg1 )
	f2_arg0.Gamertag:SubscribeToModelThroughElement( f2_arg0, "gamertag", function ()
		local f3_local0 = f2_arg0:GetDataSource()
		local f3_local1 = f3_local0.gamertag:GetValue( f2_arg0 )
		if f3_local1 ~= nil then
			f2_arg0.Gamertag:setText( f3_local1 )
		end
	end )
end

function PlayerFocusDetails( menu, controller )
	local self = LUI.UIElement.new()
	self:SetAnchorsAndPosition( 0, 1, 0, 1, 0, 550 * _1080p, 0, 825 * _1080p )
	self.id = "PlayerFocusDetails"
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine.DDJFBBJAIG() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1 )
	local f1_local2 = self
	local Gamertag = nil
	
	Gamertag = LUI.UIText.new()
	Gamertag.id = "Gamertag"
	Gamertag:setText( "", 0 )
	Gamertag:SetFont( FONTS.GetFont( FONTS.MainBold.File ) )
	Gamertag:SetAlignment( LUI.Alignment.Left )
	Gamertag:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 1, _1080p * 450, 0, _1080p * 30 )
	self:addElement( Gamertag )
	self.Gamertag = Gamertag
	
	local TopStats = nil
	
	TopStats = LUI.UIStyledText.new()
	TopStats.id = "TopStats"
	TopStats:SetRGBFromTable( SWATCHES.genericMenu.default, 0 )
	TopStats:setText( Engine.CBBHFCGDIC( "LUA_MENU/TOP_STATS" ), 0 )
	TopStats:SetFont( FONTS.GetFont( FONTS.MainRegular.File ) )
	TopStats:SetAlignment( LUI.Alignment.Left )
	TopStats:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 279, _1080p * 90, _1080p * 114 )
	self:addElement( TopStats )
	self.TopStats = TopStats
	
	local Line = nil
	
	Line = LUI.UIImage.new()
	Line.id = "Line"
	Line:SetRGBFromTable( SWATCHES.genericMenu.default, 0 )
	Line:SetAlpha( 0.6, 0 )
	Line:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 550, _1080p * 120, _1080p * 121 )
	self:addElement( Line )
	self.Line = Line
	
	local Kills = nil
	
	Kills = MenuBuilder.BuildRegisteredType( "PlayerFocusStats", {
		controllerIndex = f1_local1
	} )
	Kills.id = "Kills"
	Kills.StatsImage:setImage( RegisterMaterial( "gamemode_team_deathmatch" ), 0 )
	Kills.StatsName:setText( Engine.CBBHFCGDIC( "LUA_MENU/STATS_KILLS" ), 0 )
	Kills:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 2, _1080p * 182, _1080p * 133, _1080p * 283 )
	self:addElement( Kills )
	self.Kills = Kills
	
	local KD = nil
	
	KD = MenuBuilder.BuildRegisteredType( "PlayerFocusStats", {
		controllerIndex = f1_local1
	} )
	KD.id = "KD"
	KD.StatsImage:setImage( RegisterMaterial( "gamemode_team_deathmatch" ), 0 )
	KD.StatsName:setText( Engine.CBBHFCGDIC( "LUA_MENU/STATS_KD" ), 0 )
	KD:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 182, _1080p * 362, _1080p * 133, _1080p * 283 )
	self:addElement( KD )
	self.KD = KD
	
	local SPM = nil
	
	SPM = MenuBuilder.BuildRegisteredType( "PlayerFocusStats", {
		controllerIndex = f1_local1
	} )
	SPM.id = "SPM"
	SPM.StatsImage:setImage( RegisterMaterial( "gamemode_team_deathmatch" ), 0 )
	SPM.StatsName:setText( Engine.CBBHFCGDIC( "LUA_MENU/STATS_SPM" ), 0 )
	SPM:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 362, _1080p * 542, _1080p * 133, _1080p * 283 )
	self:addElement( SPM )
	self.SPM = SPM
	
	f0_local0( self, f1_local1, controller )
	return self
end

MenuBuilder.registerType( "PlayerFocusDetails", PlayerFocusDetails )
LockTable( _M )
