-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 13-07-2025 21:51
module( ..., package.seeall )
local f0_local0 = function ( f19_arg0, f19_arg1 )
	local f19_local0 = f19_arg0.Tabs:GetCurrentTab()
	local f19_local1 = function ( f21_arg0, f21_arg1 )
		if f21_arg0.bindEquipOperatorButton then
			f21_arg0:RemoveButtonPrompt( {
				helper_text = nil,
				button_ref = "button_alt2"
			} )
			f21_arg0.bindEquipOperatorButton:closeTree()
		end
	end
	
	if f19_local0._tabData.index == OPERATOR.OPERATOR_INFO_TAB_DATA.MISSION.index then
		local f19_local2 = LUI.FlowManager.GetScopedData( f19_arg0._menuRef )
		assert( f19_local2, "The current operator scoped data could not be found." )
		local f19_local3 = f19_local2.operatorData.operatorInfo
		if not f19_local3.isSelected and OPERATOR.IsUnlocked( f19_arg1, f19_local3.ref ) then
			f19_arg0:AddButtonHelperText( {
				side = "left",
				button_ref = "button_alt2",
				priority = 1,
				helper_text = Engine.CBBHFCGDIC( "LUA_MENU/SELECT_OPERATOR" )
			} )
			f19_arg0.bindEquipOperatorButton = LUI.UIBindButton.new()
			f19_arg0.bindEquipOperatorButton.id = "bindEquipOperatorButton"
			f19_arg0:addElement( f19_arg0.bindEquipOperatorButton )
			f19_arg0.bindEquipOperatorButton.data = f19_local3
			f19_arg0.bindEquipOperatorButton:addEventHandler( "button_alt2", function ( f20_arg0, f20_arg1 )
				local f20_local0 = LUI.FlowManager.GetScopedData( f19_arg0:getParent() )
				f20_local0.operatorData.operatorInfo.isSelected = false
				f20_local0.operatorData.operatorInfo = f19_arg0
				f20_local0.operatorData.useEquippedOperatorFocusIndex = true
				f20_local0.operatorData.useSelectedOperatorIndexForFocus = false
				LUI.FlowManager.ClearSavedMenuStatesByControllerIndex( f19_arg0, "BRMainMenu" )
				OPERATOR.EquipOperator( f19_arg0, f19_arg0, {
					selectedOutsideOfGrid = true,
					operatorInfo = f19_arg0
				} )
				f19_arg0( f19_arg0, f19_arg0 )
			end )
		end
	end
	f19_local1( f19_arg0, f19_arg1 )
end

local f0_local1 = function ( f18_arg0 )
	if not f18_arg0._isVanguardOperator then
		return 
	end
	local f18_local0 = f18_arg0.Tabs
	if not f18_local0._tabs then
		return 
	end
	local f18_local1 = LUI.FlowManager.GetScopedData( f18_arg0 )
	local f18_local2 = f18_local1.activeTabIndex
	f18_arg0.WZWipOperatorProgress._cannotPreview = f18_local0._tabs[f18_local1.activeTabIndex + 1].name == OPERATOR.OPERATOR_INFO_TAB_DATA.MISSION.name
	local f18_local3 = ACTIONS.AnimateSequence
	local f18_local4 = f18_arg0
	local f18_local5
	if f18_arg0.WZWipOperatorProgress._cannotPreview then
		f18_local5 = "HideProgressionInfo"
	else
		f18_local5 = "ShowProgressionInfo"
	end
	f18_local3( f18_local4, f18_local5 )
end

local f0_local2 = function ( f17_arg0, f17_arg1, f17_arg2, f17_arg3 )
	local f17_local0 = f17_arg0._tabs[f17_arg2 + 1]
	local f17_local1 = f17_arg0:getParent()
	local f17_local2 = LUI.FlowManager.GetScopedData( f17_local1 )
	f17_local1.MenuTitle:SetTitle( Engine.CBBHFCGDIC( f17_local0.title, f17_local0.insertOperator and Engine.CBBHFCGDIC( f17_local1._operatorNameForTitle ) or "" ) )
	TAB.UpdateBuiltWidgetOnTabChange( f17_local1, f17_local2.activeTabIndex, "activeTabWidget", f17_arg2, f17_arg3, f17_local0.menuName, {
		buildPriority = 2,
		controllerIndex = f17_arg1,
		callback = f17_local0.callback,
		scopedData = f17_local2
	} )
	f17_local2.activeTabIndex = f17_arg2
	f0_local0( f17_local1, f17_arg1 )
	f0_local0( f17_local1 )
end

local f0_local3 = function ( f16_arg0, f16_arg1, f16_arg2 )
	assert( f16_arg2.operatorInfo )
	local f16_local0 = f16_arg2.operatorInfo
	local f16_local1 = OPERATOR.IsT9Operator( f16_local0.ref )
	if not f16_local1 then
		f16_local1 = OPERATOR.IsMWOperator( f16_local0.ref )
	end
	local f16_local2 = false
	if f16_local1 then
		local f16_local3 = f16_local0.outfitMissionQuests
		if not OPERATOR.IsUnlocked( f16_arg1, f16_local0.ref ) or not f16_local3 or 0 >= #f16_local3 then
			f16_local2 = false
		else
			f16_local2 = true
		end
	end
	if OPERATOR.IsS4Operator( f16_local0.ref ) then
		local f16_local3 = f16_local0.challenges
		if not OPERATOR.IsUnlocked( f16_arg1, f16_local0.ref ) or not f16_local3 or 0 >= #f16_local3 then
			f16_local2 = false
		else
			f16_local2 = true
		end
	end
	return f16_local2
end

local f0_local4 = function ( f14_arg0, f14_arg1, f14_arg2 )
	local f14_local0 = {}
	local f14_local1 = LUI.ShallowCopy( OPERATOR.OPERATOR_INFO_TAB_DATA )
	local f14_local2 = f14_arg2.startTabIndex
	local f14_local3 = 1
	if not f14_arg2.showProgressionTab then
		f14_local1.PROGRESSION = nil
		if not f14_arg2.showMissions then
			f14_local1.MISSION = nil
		end
	end
	if not f14_arg2.showBio then
		f14_local1.BIO = nil
	end
	for f14_local7, f14_local8 in pairs( f14_local1 ) do
		f14_local0[f14_local3] = {
			id = f14_local8.id,
			menuName = f14_local8.asset,
			index = f14_local8.index,
			callback = f14_arg2.operatorSelectCallback,
			name = f14_local8.name,
			title = f14_local8.title,
			insertOperator = f14_local8.insertOperator,
			hasDefaultFocus = f14_local7 == 1,
			focusFunction = f0_local0
		}
		f14_local3 = f14_local3 + 1
	end
	table.sort( f14_local0, function ( f15_arg0, f15_arg1 )
		return f15_arg0.index < f15_arg1.index
	end )
	f14_local3 = 0
	for f14_local7, f14_local8 in ipairs( f14_local0 ) do
		if f14_local8.index == f14_arg2.startTabIndex then
			f14_local2 = f14_local3
			break
		end
		f14_local3 = f14_local3 + 1
	end
	f14_local4 = LUI.FlowManager.GetScopedData( f14_arg0 )
	f14_local4.activeTabIndex = f14_local2
	f14_arg0.Tabs:SetTabs( f14_local0 )
	f14_arg0.Tabs:FocusTab( f14_arg1, f14_local2 )
end

local f0_local5 = function ( f13_arg0, f13_arg1, f13_arg2 )
	assert( f13_arg2.operatorInfo )
	local f13_local0 = f0_local0( f13_arg0, f13_arg1, f13_arg2 )
	local f13_local1 = f13_arg0:getParent()
	local f13_local2 = f13_local1.Tabs
	local f13_local3 = LUI.FlowManager.GetScopedData( f13_local1 )
	f13_local3.operatorData.operatorInfo = f13_arg2.operatorInfo
	f13_local1._operatorNameForTitle = f13_arg2.operatorInfo.name
	local f13_local4 = #f13_local2._tabs
	if not f13_local0 then
		for f13_local8, f13_local9 in pairs( f13_local2._tabElements ) do
			if f13_local9._tabData.index == OPERATOR.OPERATOR_INFO_TAB_DATA.MISSION.index then
				LUI.TabManager.RemoveTabAtIndex( f13_local2, f13_local8 )
				LUI.TabManager.UpdateButtonHelperVisibility( f13_local2, f13_arg1, {
					isSingleTab = #f13_local2._tabElements == 1
				} )
				break
			end
		end
	end
	if f13_local0 and #f13_local2._tabs == 1 then
		local f13_local5 = LUI.ShallowCopy( OPERATOR.OPERATOR_INFO_TAB_DATA.MISSION )
		table.insert( f13_local2._tabs, {
			hasDefaultFocus = false,
			id = f13_local5.id,
			menuName = f13_local5.asset,
			index = f13_local5.index,
			callback = f13_arg2.operatorSelectCallback,
			name = f13_local5.name,
			title = f13_local5.title,
			insertOperator = f13_local5.insertOperator,
			focusFunction = f0_local0
		} )
		f13_local4 = #f13_local2._tabs
		local f13_local7 = LUI.TabManager.AddNewTab( f13_local2, f13_local4 - 1 )
		if f13_local7.Setup then
			f13_local7:Setup( f13_local2._tabs[f13_local4] )
		end
		LUI.TabManager.UpdateButtonHelperVisibility( f13_local2, f13_arg1 )
	end
	f13_local1.activeTabWidget.Grid:RefreshContent()
	if OPERATOR.IsS4Operator( f13_arg2.operatorInfo.ref ) then
		f13_local1.WZWipOperatorProgress:SetupProgression( f13_arg2.operatorInfo.ref )
	end
end

local f0_local6 = function ( f12_arg0, f12_arg1, f12_arg2 )
	assert( f12_arg2.operatorInfo )
	f0_local0( f12_arg0, f12_arg1, {
		showBio = OPERATOR.IsOperatorBioAvailable( f12_arg0, f12_arg1, {
			operatorRef = f12_arg2.operatorInfo.ref
		} ),
		showMissions = f0_local0( f12_arg0, f12_arg1, f12_arg2 ),
		startTabIndex = f12_arg2.startTabIndex or 0,
		operatorSelectCallback = f12_arg0.UpdateTabsIfAvailableMissions
	} )
end

local f0_local7 = function ( f11_arg0, f11_arg1 )
	local f11_local0 = f11_arg0:getParent()
	f11_local0.frontendCameraMover:ResetCamera()
	LUI.FlowManager.RequestLeaveMenu( f11_local0, true )
end

local f0_local8 = function ( f10_arg0 )
	f10_arg0:AddButtonHelperText( {
		side = "left",
		button_ref = "button_secondary",
		priority = 0,
		helper_text = Engine.CBBHFCGDIC( "LUA_MENU/BACK" )
	} )
	
	local bindButton = LUI.UIBindButton.new()
	bindButton.id = "bindButton"
	f10_arg0:addElement( bindButton )
	f10_arg0.bindButton = bindButton
	
	f10_arg0.bindButton:addEventHandler( "button_secondary", f0_local0 )
end

local f0_local9 = function ( f9_arg0 )
	local frontendCameraMover = MenuBuilder.BuildRegisteredType( "FrontendCameraMover", {
		useMousePan = false,
		snapToCenter = true,
		enableZoom = true,
		enableHoldZoom = true,
		useLeftStick = false,
		enableWheelZoom = false,
		enableSway = false,
		controllerIndex = f9_arg0._controllerIndex
	} )
	frontendCameraMover:SetScreenOrigin( 0, 100 )
	frontendCameraMover:SetMaxZoom( 30 )
	frontendCameraMover:SetMinZoom( 0 )
	frontendCameraMover:SetAnchorsAndPosition( 0.5, 0.5, 0.5, 0.5, _1080p * -440, _1080p * 500, _1080p * -540, _1080p * 480 )
	f9_arg0:addElement( frontendCameraMover )
	f9_arg0.frontendCameraMover = frontendCameraMover
	
	f9_arg0.frontendCameraMover:SetZoomWheel( 30 )
end

local f0_local10 = function ( f7_arg0, f7_arg1, f7_arg2 )
	if not f7_arg2 or type( f7_arg2 ) ~= "table" or not f7_arg2.operatorData then
		assert( false )
	end
	f7_arg0._controllerIndex = f7_arg1
	f7_arg0._menuRef = f7_arg2.menuRef
	f7_arg0._operatorNameForTitle = f7_arg2.operatorData.operatorInfo.name
	f7_arg0.menuInitialized = false
	f7_arg0.UpdateTabsIfAvailableMissions = f0_local0
	f7_arg0:addEventHandler( "menu_create", function ( f8_arg0, f8_arg1 )
		f7_arg0( f8_arg0 )
		f7_arg0( f8_arg0 )
		OPERATOR.SetupScene( f8_arg0, f7_arg0 )
		f7_arg0( f8_arg0, f7_arg0, {
			operatorInfo = f7_arg0,
			startTabIndex = f7_arg0.operatorData.menuData.startTabIndex
		} )
		f8_arg0._idleAnimationsTable, f8_arg0._equipAnimationsTable = OPERATOR.GetSceneCharacterModelAnimations()
		OPERATOR.SetSceneCharacterModel( f8_arg0, f7_arg0, {
			showARandomSkin = true,
			element = f8_arg0,
			operatorInfo = f7_arg0,
			menuRef = f8_arg0._menuRef
		} )
		OPERATOR.PlayEquippedAnimAndQueueIdle( f8_arg0, f7_arg0, {
			newEquipped = false,
			operatorInfo = f7_arg0
		} )
		local f8_local0 = "ShowBattlePassInfo"
		if OPERATOR.IsS4Operator( f7_arg0.ref ) then
			f8_arg0._isVanguardOperator = true
			f8_local0 = "ShowProgressionInfo"
			f8_arg0.WZWipOperatorProgress:SetupProgression( f7_arg0.ref )
		end
		ACTIONS.AnimateSequence( f8_arg0, f8_local0 )
		f7_arg0( f8_arg0 )
	end )
	LAYOUT.SetupCommonScaleableLayoutElements( f7_arg0, f7_arg1 )
	if CONDITIONS.IsWZWipDvarEnabled() then
		LAYOUT.SetupScalingBackgroundVignette( f7_arg0 )
	end
end

function WZOperatorInformation( menu, controller )
	local self = LUI.UIElement.new()
	self.id = "WZOperatorInformation"
	self._animationSets = self._animationSets or {}
	self._sequences = self._sequences or {}
	local f1_local1
	if controller then
		f1_local1 = controller
	else
		f1_local1 = controller.controllerIndex
	end
	if not f1_local1 and not Engine.DDJFBBJAIG() then
		f1_local1 = self:getRootController()
	end
	assert( f1_local1 )
	self.HelperBar = MenuBuilder.BuildRegisteredType( "ButtonHelperBar", {
		controllerIndex = f1_local1
	} )
	self.HelperBar.id = "HelperBar"
	self.HelperBar:SetAnchorsAndPosition( 0, 0, 1, 0, 0, 0, _1080p * -85, 0 )
	self.HelperBar:setPriority( 10 )
	self:addElement( self.HelperBar )
	local f1_local2 = self
	local Vignette = nil
	
	Vignette = MenuBuilder.BuildRegisteredType( "WZAccentMenuOverlay", {
		controllerIndex = f1_local1
	} )
	Vignette.id = "Vignette"
	Vignette:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 1920, 0, _1080p * 1080 )
	self:addElement( Vignette )
	self.Vignette = Vignette
	
	local TabBacker = nil
	
	TabBacker = MenuBuilder.BuildRegisteredType( "TabBacker", {
		controllerIndex = f1_local1
	} )
	TabBacker.id = "TabBacker"
	TabBacker:SetAnchorsAndPosition( 0, 0, 0, 1, 0, 0, 0, _1080p * 160 )
	self:addElement( TabBacker )
	self.TabBacker = TabBacker
	
	local MenuTitle = nil
	
	MenuTitle = MenuBuilder.BuildRegisteredType( "MenuTitle", {
		controllerIndex = f1_local1
	} )
	MenuTitle.id = "MenuTitle"
	MenuTitle.MenuTitle:setText( ToUpperCase( Engine.CBBHFCGDIC( "LUA_MENU/OPERATOR_BIO_TITLE" ) ), 0 )
	MenuTitle.Line:SetLeft( 0, 0 )
	MenuTitle:SetAnchorsAndPosition( 0, 1, 0, 1, 0, _1080p * 1024, 0, _1080p * 100 )
	self:addElement( MenuTitle )
	self.MenuTitle = MenuTitle
	
	local HelperBar = nil
	
	HelperBar = MenuBuilder.BuildRegisteredType( "ButtonHelperBar", {
		controllerIndex = f1_local1
	} )
	HelperBar.id = "HelperBar"
	HelperBar.Background:SetAlpha( 0.2, 0 )
	HelperBar:SetAnchorsAndPosition( 0, 0, 1, 0, 0, 0, _1080p * -85, 0 )
	self:addElement( HelperBar )
	self.HelperBar = HelperBar
	
	local Tabs = nil
	
	Tabs = LUI.TabManager.new( {
		spacing = 4,
		wrap = true,
		tabHeight = _1080p * 52,
		buildTab = function ()
			return MenuBuilder.BuildRegisteredType( "SubMenuTab", {
				controllerIndex = menu
			} )
		end,
		controllerIndex = f1_local1
	} )
	Tabs.id = "Tabs"
	Tabs:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 100, _1080p * 997, _1080p * 108, _1080p * 160 )
	self:addElement( Tabs )
	self.Tabs = Tabs
	
	local LobbyMembersFooter = nil
	
	LobbyMembersFooter = MenuBuilder.BuildRegisteredType( "LobbyMembersFooter", {
		controllerIndex = f1_local1
	} )
	LobbyMembersFooter.id = "LobbyMembersFooter"
	LobbyMembersFooter:SetAnchorsAndPosition( 0, 0, 0, 1, 0, 0, 0, _1080p * 150 )
	self:addElement( LobbyMembersFooter )
	self.LobbyMembersFooter = LobbyMembersFooter
	
	local ItemsCollected = nil
	
	ItemsCollected = LUI.UIStyledText.new()
	ItemsCollected.id = "ItemsCollected"
	ItemsCollected:SetRGBFromTable( SWATCHES.genericButton.description, 0 )
	ItemsCollected:SetAlpha( 0, 0 )
	ItemsCollected:setText( Engine.CBBHFCGDIC( "LUA_MENU/COLLECTED_X_OF_Y" ), 0 )
	ItemsCollected:SetFont( FONTS.GetFont( FONTS.BodyRegular.File ) )
	ItemsCollected:SetWordWrap( false )
	ItemsCollected:SetAlignment( LUI.Alignment.Left )
	ItemsCollected:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 130, _1080p * 315, _1080p * 178, _1080p * 200 )
	self:addElement( ItemsCollected )
	self.ItemsCollected = ItemsCollected
	
	local f1_local10 = nil
	if CONDITIONS.IsBattlePassEnabled() then
		f1_local10 = MenuBuilder.BuildRegisteredType( "BattlePassSeasonResetStatus", {
			controllerIndex = f1_local1
		} )
		f1_local10.id = "BattlePassSeasonResetStatus"
		f1_local10.ResetText:SetLeft( _1080p * 83, 0 )
		f1_local10.ResetText:SetRight( _1080p * 375, 0 )
		f1_local10.ResetText:SetTop( _1080p * 24, 0 )
		f1_local10.ResetText:SetBottom( _1080p * 52, 0 )
		f1_local10.ResetText:SetAlignment( LUI.Alignment.Left )
		f1_local10:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 1449, _1080p * 1824, _1080p * 52, _1080p * 132 )
		self:addElement( f1_local10 )
		self.BattlePassSeasonResetStatus = f1_local10
	end
	local f1_local11 = nil
	if CONDITIONS.IsWZWipOperatorFlowEnabled() then
		f1_local11 = MenuBuilder.BuildRegisteredType( "WZOperatorProgress", {
			controllerIndex = f1_local1
		} )
		f1_local11.id = "WZWipOperatorProgress"
		f1_local11:SetAnchorsAndPosition( 0, 1, 0, 1, _1080p * 1324, _1080p * 1824, _1080p * 55, _1080p * 179 )
		self:addElement( f1_local11 )
		self.WZWipOperatorProgress = f1_local11
	end
	self._sequences.DefaultSequence = function ()
		
	end
	
	local f1_local12 = nil
	if CONDITIONS.IsBattlePassEnabled() then
		f1_local10:RegisterAnimationSequence( "ShowBattlePassInfo", {
			{
				value = 1,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			}
		} )
	end
	if CONDITIONS.IsWZWipOperatorFlowEnabled() then
		f1_local11:RegisterAnimationSequence( "ShowBattlePassInfo", {
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			}
		} )
	end
	self._sequences.ShowBattlePassInfo = function ()
		if CONDITIONS.IsBattlePassEnabled() then
			menu:AnimateSequence( "ShowBattlePassInfo" )
		end
		if CONDITIONS.IsWZWipOperatorFlowEnabled() then
			menu:AnimateSequence( "ShowBattlePassInfo" )
		end
	end
	
	local f1_local13 = nil
	if CONDITIONS.IsBattlePassEnabled() then
		f1_local10:RegisterAnimationSequence( "ShowProgressionInfo", {
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			}
		} )
	end
	if CONDITIONS.IsWZWipOperatorFlowEnabled() then
		f1_local11:RegisterAnimationSequence( "ShowProgressionInfo", {
			{
				value = 1,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			}
		} )
	end
	self._sequences.ShowProgressionInfo = function ()
		if CONDITIONS.IsBattlePassEnabled() then
			menu:AnimateSequence( "ShowProgressionInfo" )
		end
		if CONDITIONS.IsWZWipOperatorFlowEnabled() then
			menu:AnimateSequence( "ShowProgressionInfo" )
		end
	end
	
	local f1_local14 = nil
	if CONDITIONS.IsWZWipOperatorFlowEnabled() then
		f1_local11:RegisterAnimationSequence( "HideProgressionInfo", {
			{
				value = 0,
				duration = 0,
				property = TWEEN_PROPERTY.Alpha
			}
		} )
	end
	self._sequences.HideProgressionInfo = function ()
		if CONDITIONS.IsWZWipOperatorFlowEnabled() then
			menu:AnimateSequence( "HideProgressionInfo" )
		end
	end
	
	f0_local0( self, f1_local1, controller )
	return self
end

MenuBuilder.registerType( "WZOperatorInformation", WZOperatorInformation )
LockTable( _M )
