-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 13-10-2025 14:16
module( ..., package.seeall )
local f0_local0 = 10
local f0_local1 = 1
local f0_local2 = 2
local f0_local3 = "ReticleCrosshairDot"
local f0_local4 = function ( f27_arg0, f27_arg1, f27_arg2, f27_arg3, f27_arg4, f27_arg5, f27_arg6, f27_arg7, f27_arg8, f27_arg9, f27_arg10, f27_arg11, f27_arg12 )
	if not MenuBuilder.IsTypeAvailable( f27_arg1 ) then
		DebugPrint( "ERROR: Attempting to use unknown widget " .. f27_arg1 .. ". Ensure this widget is properly included for your game mode!" )
		return nil
	end
	local f27_local0 = MenuBuilder.BuildRegisteredType( f27_arg1, {
		controllerIndex = f27_arg3
	} )
	local f27_local1 = {
		useLeftHandIfAkimbo = true,
		entityTag = f27_arg2,
		isLockedToTag = f27_arg6,
		tagOffsetX = f27_arg7,
		naturalDistance = f27_arg8,
		naturalFOV = f27_arg9,
		defaultScale = f27_arg10,
		minScale = f27_arg11,
		maxScale = f27_arg12
	}
	f27_local0.id = "weaponWidget" .. f27_arg1
	f27_local0:SetupAnchoredElement( f27_local1 )
	if f27_arg4 then
		f27_local0:AttachToReticleViewModel()
	else
		f27_local0:AttachToViewModel( f27_arg5 )
	end
	f27_arg0:addElement( f27_local0 )
	return f27_local0
end

local f0_local5 = function ( f26_arg0, f26_arg1, f26_arg2 )
	if Dvar[0x1FAB6D9A30481F8]( 0xF423F0B65FD75EF ) then
		local f26_local0 = Dvar[0x9E5BE3B4BBA4E0E]( 0xF423F0B65FD75EF )
	end
	if not MenuBuilder.IsTypeAvailable( f26_arg2 ) then
		DebugPrint( "ERROR: Attempting to use unknown widget " .. f26_arg2 .. ". Ensure this widget is properly included for your game mode!" )
		return nil
	end
	local f26_local1 = MenuBuilder.BuildRegisteredType( f26_arg2, {
		isBlockedCrosshair = false,
		controllerIndex = f26_arg1
	} )
	f26_local1.id = "crosshairWidget" .. f26_arg2
	f26_local1:SetAnchors( 0, 0, 0, 0, 0 )
	if f26_local1.ReticleCrosshairBase then
		f26_local1.ReticleCrosshairBase.ReticleCrosshairBaseOuter:SetupDynamicCrosshairPips()
		f26_local1.ReticleCrosshairBase.Dot:SetupDynamicCrosshairCenterDot()
	elseif f26_arg2 == f0_local0 then
		f26_local1:SetupDynamicCrosshairCenterDot()
	else
		f26_local1:SetupDynamicCrosshairPips()
	end
	if Engine[0x84287BE93239E99]() then
		f26_local1:dispatchEventToChildren( {
			dispatchChildren = true,
			name = "mobile_crosshair_style",
			scale = Dvar[0xEDCFC612B39E0C0]( 0x35998EFB7A1DB92 )
		} )
	end
	f26_arg0:addElement( f26_local1 )
	return f26_local1
end

local f0_local6 = function ( f25_arg0, f25_arg1, f25_arg2 )
	if not MenuBuilder.IsTypeAvailable( f25_arg2 ) then
		DebugPrint( "ERROR: Attempting to use unknown widget " .. f25_arg2 .. ". Ensure this widget is properly included for your game mode!" )
		return nil
	end
	local f25_local0 = MenuBuilder.BuildRegisteredType( f25_arg2, {
		isBlockedCrosshair = true,
		controllerIndex = f25_arg1
	} )
	f25_local0.id = "blockedCrosshairWidget" .. f25_arg2
	f25_local0:SetAnchors( 0, 0, 0, 0, 0 )
	if f25_local0.ReticleCrosshairBase then
		f25_local0.ReticleCrosshairBase.ReticleCrosshairBaseOuter:SetupDynamicCrosshairPips()
		f25_local0.ReticleCrosshairBase.Dot:SetupDynamicCrosshairCenterDot()
	elseif f25_arg2 == f0_local0 then
		f25_local0:SetupDynamicCrosshairCenterDot()
	else
		f25_local0:SetupDynamicCrosshairPips()
	end
	f25_local0:SetRGBFromTable( SWATCHES.HUD.enemyTeam )
	f25_arg0:addElement( f25_local0 )
	return f25_local0
end

local f0_local7 = function ( f24_arg0, f24_arg1, f24_arg2 )
	assert( f24_arg2.isPrimary ~= nil )
	assert( f24_arg2.isAlternate ~= nil )
	assert( f24_arg2.reticleIndex )
	local f24_local0 = "tag_reticle_attach"
	if f24_arg2.isAlternate then
		f24_local0 = "tag_reticle_attach2"
	end
	local f24_local1 = f24_arg0.reticleNames
	local f24_local2
	if f24_arg2.isAlternate then
		f24_local2 = 2
	else
		f24_local2 = 1
	end
	f24_local1 = f24_local1[f24_local2] ~= f24_arg2.reticleName
	if f24_arg0.reticles[f24_arg2.reticleIndex] and f24_local1 then
		f24_arg0.reticles[f24_arg2.reticleIndex]:closeTree()
		f24_arg0.reticles[f24_arg2.reticleIndex] = nil
	end
	if f24_arg2.reticleType ~= nil and 0 < #f24_arg2.reticleType and f24_local1 then
		f24_local2, f24_local3, f24_local4, f24_local5 = nil
		if f24_arg2.isPrimary then
			f24_local2 = Reticle[0x23742A69D7F5825]( f24_arg1, f24_arg2.isAlternate )
			f24_local5 = Reticle[0x13F7AE89DFC6E16]( f24_arg1, f24_arg2.isAlternate )
			if Reticle[0xCD0510EC63A89E4]( f24_arg1, f24_arg2.isAlternate ) then
				f24_local3 = Reticle[0x15A6B7714FD0AD9]( f24_arg1, f24_arg2.isAlternate )
			end
			f24_local4 = Reticle[0xFE4A5D4DCA4A4A8]( f24_arg1, f24_arg2.isAlternate )
		else
			f24_local2 = Reticle[0xC73A641E79EA3B9]( f24_arg1, f24_arg2.isAlternate )
			f24_local5 = Reticle[0x363F203268F2372]( f24_arg1, f24_arg2.isAlternate )
			f24_local4 = Reticle[0x2525D75712F8AC0]( f24_arg1, f24_arg2.isAlternate )
		end
		f24_arg0.reticles[f24_arg2.reticleIndex] = f0_local0( f24_arg0, f24_arg2.reticleType, f24_local0, f24_arg1, true, true, f24_local2, f24_local5, Reticle[0xC64ABFE83750AD5]( f24_arg1, f24_arg2.isAlternate ), f24_local3, f24_local4, Reticle[0xE9F5513A2E6BE7F]( f24_arg1, f24_arg2.isAlternate ), Reticle[0x35F2FC1A4A30C05]( f24_arg1, f24_arg2.isAlternate ) )
	end
end

local f0_local8 = function ( f23_arg0, f23_arg1, f23_arg2 )
	local f23_local0 = nil
	local f23_local1 = false
	if f23_arg2 ~= nil and 0 < #f23_arg2 then
		f23_local0 = Game[0x452777EC5FA7DD5]( f23_arg1 )
		f23_local1 = Game[0xD1C271BEBA20F99]( f23_arg1, f23_local0 )
	end
	local f23_local2 = f23_arg0.weaponWidgetType ~= f23_arg2
	if f23_arg0.weaponWidget and (f23_local2 or (f23_arg0.weaponWidgetBone ~= f23_local0) or not f23_local1) then
		f23_arg0.weaponWidget:closeTree()
		f23_arg0.weaponWidget = nil
	end
	if f23_arg2 ~= nil and 0 < #f23_arg2 and f23_local2 and f23_local1 then
		f23_arg0.weaponWidget = f0_local0( f23_arg0, f23_arg2, f23_local0, f23_arg1, false, Game[0xCBB6EBCF8D8D4AB]( f23_arg1 ), true, nil, f0_local0, nil, f0_local0, f0_local0, nil )
		f23_arg0.weaponWidgetType = f23_arg2
		f23_arg0.weaponWidgetBone = f23_local0
	else
		f23_arg0.weaponWidgetType = nil
		f23_arg0.weaponWidgetBone = nil
	end
end

local f0_local9 = function ( f22_arg0, f22_arg1, f22_arg2 )
	if f22_arg0.maxNumAttachments ~= f22_arg2 then
		return true
	elseif not f22_arg0.attachmentsInfo then
		return true
	end
	local f22_local0 = 0
	for f22_local1 = 0, f22_arg2 - 1, 1 do
		local f22_local4 = Game[0x1CE94E268E8474D]( f22_arg1, f22_local1 )
		local f22_local5 = Game[0xCE362F53EEDC7AE]( f22_arg1, f22_local1 )
		local f22_local6 = Game[0xE9123A0DB7B03D6]( f22_arg1, f22_local1 )
		if f22_local4 ~= nil and 0 < #f22_local4 then
			f22_local0 = f22_local0 + 1
			if not f22_arg0.attachmentsInfo[f22_local0] then
				return true
			end
			if (f22_local4 ~= f22_arg0.attachmentsInfo[f22_local0].widgetType) or (f22_local5 ~= f22_arg0.attachmentsInfo[f22_local0].widgetAttachPoint) or f22_local6 ~= f22_arg0.attachmentsInfo[f22_local0].widgetUsesScopeStencil then
				return true
			end
		end
	end
	if f22_local0 ~= #f22_arg0.attachmentsList then
		return true
	end
	return false
end

local f0_local10 = function ( f21_arg0, f21_arg1, f21_arg2 )
	if f21_arg0.attachmentsList then
		for f21_local3, f21_local4 in ipairs( f21_arg0.attachmentsList ) do
			f21_arg0.attachmentsList[f21_local3]:closeTree()
			f21_arg0.attachmentsList[f21_local3] = nil
		end
	end
	f21_arg0.attachmentsList = nil
	f21_arg0.attachmentsInfo = nil
	f21_arg0.attachmentsList = {}
	f21_arg0.attachmentsInfo = {}
	f21_arg0.maxNumAttachments = f21_arg2
	for f21_local0 = 0, f21_arg2 - 1, 1 do
		local f21_local4 = Game[0x1CE94E268E8474D]( f21_arg1, f21_local0 )
		local f21_local5 = Game[0xCE362F53EEDC7AE]( f21_arg1, f21_local0 )
		local f21_local6 = Game[0xE9123A0DB7B03D6]( f21_arg1, f21_local0 )
		if f21_local4 ~= nil and 0 < #f21_local4 then
			f21_arg0.attachmentsList[#f21_arg0.attachmentsList + 1] = f0_local0( f21_arg0, f21_local4, f21_local5, f21_arg1, false, f21_local6, true, nil, f0_local0, nil, f0_local0, f0_local0, nil )
			f21_arg0.attachmentsInfo[#f21_arg0.attachmentsInfo + 1] = {
				widgetType = f21_local4,
				widgetAttachPoint = f21_local5,
				widgetUsesScopeStencil = f21_local6
			}
		end
	end
end

local f0_local11 = function ( f20_arg0, f20_arg1, f20_arg2 )
	if f20_arg0.crosshairWidget then
		f20_arg0.crosshairWidget:closeTree()
		f20_arg0.crosshairWidget = nil
	end
	if f20_arg0.blockedCrosshairWidget then
		f20_arg0.blockedCrosshairWidget:closeTree()
		f20_arg0.blockedCrosshairWidget = nil
	end
	if f20_arg2 ~= nil and 0 < #f20_arg2 then
		f20_arg0.crosshairWidget = f0_local0( f20_arg0, f20_arg1, f20_arg2 )
		f20_arg0.blockedCrosshairWidget = f0_local0( f20_arg0, f20_arg1, f20_arg2 )
	end
	f20_arg0.crosshairWidgetType = f20_arg2
end

local f0_local12 = function ( f19_arg0, f19_arg1 )
	local f19_local0 = LUI.DataSourceInControllerModel.new( "cg.player.currentWeapon.primaryReticleVisible" )
	f19_local0 = f19_local0:GetValue( f19_arg1 )
	local f19_local1 = LUI.DataSourceInControllerModel.new( "cg.player.currentWeapon.altReticleVisible" )
	f19_local1 = f19_local1:GetValue( f19_arg1 )
	local f19_local2 = LUI.DataSourceInControllerModel.new( "cg.player.currentWeapon.weaponInfoLUIWidgetsVisible" )
	f19_local2 = f19_local2:GetValue( f19_arg1 )
	local f19_local3 = LUI.DataSourceInControllerModel.new( "cg.player.currentWeapon.hipfireCrosshairVisible" )
	f19_local3 = f19_local3:GetValue( f19_arg1 )
	local f19_local4 = LUI.DataSourceInControllerModel.new( "cg.player.currentWeapon.blockedCrosshairVisible" )
	f19_local4 = f19_local4:GetValue( f19_arg1 )
	if f19_local1 and not f19_local0 and not f19_arg0.reticles[3] then
		f19_local0 = true
		f19_local1 = false
	end
	if f19_arg0.doNotHideHybridPrimaryScope and f19_local1 then
		f19_local0 = true
	end
	if f19_arg0.reticles[1] then
		local f19_local5 = f19_arg0.reticles[1]
		local f19_local6 = f19_local5
		f19_local5 = f19_local5.SetAlpha
		local f19_local7
		if f19_local0 then
			f19_local7 = 1
		else
			f19_local7 = 0
		end
		f19_local5( f19_local6, f19_local7, 0 )
	end
	if f19_arg0.reticles[3] then
		local f19_local5 = f19_arg0.reticles[3]
		local f19_local6 = f19_local5
		f19_local5 = f19_local5.SetAlpha
		local f19_local7
		if f19_local1 then
			f19_local7 = 1
		else
			f19_local7 = 0
		end
		f19_local5( f19_local6, f19_local7, 0 )
	end
	if f19_arg0.weaponWidget then
		local f19_local5 = f19_arg0.weaponWidget
		local f19_local6 = f19_local5
		f19_local5 = f19_local5.SetAlpha
		local f19_local7
		if f19_local2 then
			f19_local7 = 1
		else
			f19_local7 = 0
		end
		f19_local5( f19_local6, f19_local7, 0 )
	end
	if f19_arg0.attachmentsList then
		for f19_local7, f19_local10 in ipairs( f19_arg0.attachmentsList ) do
			local f19_local11 = f19_arg0.attachmentsList[f19_local7]
			local f19_local12 = f19_local11
			f19_local11 = f19_local11.SetAlpha
			local f19_local9
			if f19_local2 then
				f19_local9 = 1
			else
				f19_local9 = 0
			end
			f19_local11( f19_local12, f19_local9, 0 )
		end
	end
	if f19_arg0.crosshairWidget then
		if Dvar[0x9E5BE3B4BBA4E0E]( 0x2B7DA075887F96F ) then
			f19_local3 = false
		end
		local f19_local5 = f19_arg0.crosshairWidget
		local f19_local6 = f19_local5
		f19_local5 = f19_local5.SetAlpha
		local f19_local7
		if f19_local3 then
			f19_local7 = 1
		else
			f19_local7 = 0
		end
		f19_local5( f19_local6, f19_local7, 0 )
	end
	if f19_arg0.blockedCrosshairWidget then
		if Dvar[0x9E5BE3B4BBA4E0E]( 0x2B7DA075887F96F ) then
			f19_local4 = false
		end
		local f19_local5 = f19_arg0.blockedCrosshairWidget
		local f19_local6 = f19_local5
		f19_local5 = f19_local5.SetAlpha
		local f19_local7
		if f19_local4 then
			f19_local7 = 1
		else
			f19_local7 = 0
		end
		f19_local5( f19_local6, f19_local7, 0 )
	end
end

local f0_local13 = function ( f18_arg0 )
	f18_arg0.reticleShakeProperties = {}
	f18_arg0.defaultReticleShakeProperties = {
		numRapidFireBullets = 1,
		multiplier = 1,
		magnitude = 0,
		settleDuration = 0,
		duration = 0
	}
	f18_arg0.reticleShake = {
		timer = 0,
		minMagnitude = 0,
		epsilon = 1.9991592787261236E+37,
		currentNumBullets = 0,
		maxMagnitude = 60,
		burstFireResetTime = 600
	}
end

local f0_local14 = function ( f17_arg0 )
	local f17_local0 = f17_arg0.reticleShakeProperties.magnitude
	if f17_arg0.reticleShakeProperties.numRapidFireBullets < f17_arg0.reticleShake.currentNumBullets then
		f17_local0 = f17_local0 * f17_arg0.reticleShakeProperties.multiplier
	end
	local f17_local1 = LUI.Lerp( f17_arg0.reticleShake.minMagnitude, f17_arg0.reticleShake.maxMagnitude, f17_local0 ) * math.random()
	local f17_local2 = math.random() * 2 * math.pi
	f17_arg0.reticles[1]:SetScreenOffsets( f17_local1 * math.cos( f17_local2 ), f17_local1 * math.sin( f17_local2 ) )
end

local f0_local15 = function ( f16_arg0 )
	if not f16_arg0.reticles[1] then
		return 
	end
	local f16_local0 = 0
	f16_local0 = CoD.GetUTC()
	local f16_local1 = f16_local0 - f16_arg0.previousTime
	if f16_arg0.reticleShake.burstFireResetTime < f16_local0 - f16_arg0.lastShotFiredTime then
		f16_arg0.reticleShake.currentNumBullets = 0
	end
	if 0 < f16_arg0.reticleShake.timer then
		f16_arg0.reticleShake.timer = f16_arg0.reticleShake.timer - f16_local1
		f0_local0( f16_arg0 )
	else
		f16_arg0.reticleShake.timer = 0
		local f16_local2 = f16_arg0.reticles[1]:GetScreenOffsets()
		if math.abs( f16_local2.x ) <= f16_arg0.reticleShake.epsilon and math.abs( f16_local2.y ) <= f16_arg0.reticleShake.epsilon then
			f16_arg0.reticles[1]:SetScreenOffsets( 0, 0 )
			return 
		end
		local f16_local3 = 1
		if 0 < f16_arg0.reticleShakeProperties.settleDuration then
			f16_local3 = (f16_local0 - f16_arg0.lastShotFiredTime) / f16_arg0.reticleShakeProperties.settleDuration
		end
		f16_local3 = LUI.clamp( f16_local3, 0, 1 )
		f16_local2.x = LUI.Lerp( f16_local2.x, 0, f16_local3 )
		f16_local2.y = LUI.Lerp( f16_local2.y, 0, f16_local3 )
		f16_arg0.reticles[1]:SetScreenOffsets( f16_local2.x, f16_local2.y )
	end
	f16_arg0.previousTime = f16_local0
end

local f0_local16 = function ( f15_arg0 )
	if not f15_arg0.reticles[1] then
		return 
	end
	f15_arg0.reticleShake.currentNumBullets = f15_arg0.reticleShake.currentNumBullets + 1
	if f15_arg0.reticleShake.timer <= 0 then
		f15_arg0.reticleShake.timer = f15_arg0.reticleShakeProperties.duration
	end
end

local f0_local17 = function ( f14_arg0 )
	f0_local0( f14_arg0 )
end

local f0_local18 = nil
f0_local18 = function ( f12_arg0, f12_arg1 )
	local f12_local0 = f12_arg0:Wait( 50 )
	f0_local0( f12_arg0 )
	f12_local0.onComplete = function ()
		return f12_arg0( f12_arg0, f12_arg0 )
	end
	
end

local f0_local19 = function ( f11_arg0, f11_arg1 )
	f11_arg0.lastShotFiredTime = CoD.GetUTC()
	f0_local0( f11_arg0 )
end

function FrontendScopeReticleManager( menu, controller )
	local self = LUI.UIElement.new()
	self.id = "FrontendScopeReticleManager"
	self.reticles = {}
	self.reticleNames = {}
	self.doNotHideHybridPrimaryScope = false
	local f1_local1 = controller.controllerIndex or 0
	local f1_local2 = LUI.DataSourceInControllerModel.new( "cg.player.currentWeapon.crosshairWidget" )
	f0_local0( self )
	self.previousTime = 0
	self.lastShotFiredTime = 0
	self:addEventHandler( "post_restart", function ( f10_arg0, f10_arg1 )
		f10_arg0.previousTime = 0
		f10_arg0.lastShotFiredTime = 0
		menu.reticleShake.timer = 0
	end )
	local f1_local3 = function ()
		if Dvar[0x9E5BE3B4BBA4E0E]( 0xA0375D33FC78DBA ) then
			local f9_local0 = Reticle[0x65D4365B16E06F]( menu, false )
			local f9_local1 = Reticle[0x6893E8D5F9CA3BB]( menu, false )
			local f9_local2 = Reticle[0x565048F9E3C3A64]( menu, false )
			local f9_local3, f9_local4, f9_local5 = nil
			f9_local3 = Reticle[0x65D4365B16E06F]( menu, true )
			f9_local4 = Reticle[0x6893E8D5F9CA3BB]( menu, true )
			f9_local5 = Reticle[0x565048F9E3C3A64]( menu, true )
			if f9_local0 and f9_local0 == f9_local3 then
				menu.doNotHideHybridPrimaryScope = true
			else
				menu.doNotHideHybridPrimaryScope = false
			end
			local f9_local6 = DataModel[0x614D394F6F9A18D]( menu:GetModel( menu ) )
			menu( menu, menu, {
				isAlternate = false,
				reticleIndex = 1,
				isPrimary = true,
				reticleType = f9_local0,
				reticleName = f9_local2
			} )
			menu( menu, menu, {
				isAlternate = false,
				reticleIndex = 2,
				isPrimary = false,
				reticleType = f9_local1,
				reticleName = f9_local2
			} )
			menu.reticleNames[1] = f9_local2
			menu( menu, menu, {
				isAlternate = true,
				reticleIndex = 3,
				isPrimary = true,
				reticleType = f9_local3,
				reticleName = f9_local5
			} )
			menu( menu, menu, {
				isAlternate = true,
				reticleIndex = 4,
				isPrimary = false,
				reticleType = f9_local4,
				reticleName = f9_local5
			} )
			menu.reticleNames[2] = f9_local5
			menu.reticleShakeProperties = menu.defaultReticleShakeProperties
			if menu.crosshairWidgetType ~= f9_local6 then
				menu( menu, menu, f9_local6 )
			end
			menu( menu, menu )
		end
	end
	
	local f1_local4 = DataSources.alwaysLoaded.player.currentWeapon.scopeVariation
	local f1_local5 = DataSources.alwaysLoaded.player.currentWeapon.scopeIndex
	local f1_local6 = DataSources.alwaysLoaded.player.currentWeapon.displayName
	local f1_local7 = DataSources.alwaysLoaded.player.currentWeapon.isDefaultWeapon
	local f1_local8 = DataSources.alwaysLoaded.player.currentWeapon.weaponAttachmentsString
	local f1_local9 = DataSources.alwaysLoaded.player.currentWeapon.isNull
	self:SubscribeToModel( f1_local4:GetModel( f1_local1 ), f1_local3, true )
	self:SubscribeToModel( f1_local5:GetModel( f1_local1 ), f1_local3, true )
	self:SubscribeToModel( f1_local6:GetModel( f1_local1 ), f1_local3, true )
	self:SubscribeToModel( f1_local7:GetModel( f1_local1 ), f1_local3, true )
	self:SubscribeToModel( f1_local8:GetModel( f1_local1 ), f1_local3, true )
	self:SubscribeToModel( f1_local2:GetModel( f1_local1 ), f1_local3, true )
	self:SubscribeToModel( f1_local9:GetModel( f1_local1 ), f1_local3, true )
	self:SubscribeToModel( DataSources.alwaysLoaded.player.currentWeapon.shotCounter:GetModel( f1_local1 ), function ()
		menu( menu, menu )
	end, true )
	self:SubscribeToModel( DataSources.alwaysLoaded.player.currentWeapon.primaryReticleVisible:GetModel( f1_local1 ), function ()
		menu( menu, menu )
	end, true )
	self:SubscribeToModel( DataSources.alwaysLoaded.player.currentWeapon.altReticleVisible:GetModel( f1_local1 ), function ()
		menu( menu, menu )
	end, true )
	self:SubscribeToModel( DataSources.alwaysLoaded.player.currentWeapon.weaponInfoLUIWidgetsVisible:GetModel( f1_local1 ), function ()
		menu( menu, menu )
	end, true )
	self:SubscribeToModel( DataSources.alwaysLoaded.player.currentWeapon.hipfireCrosshairVisible:GetModel( f1_local1 ), function ()
		menu( menu, menu )
	end, true )
	self:SubscribeToModel( DataSources.alwaysLoaded.player.currentWeapon.blockedCrosshairVisible:GetModel( f1_local1 ), function ()
		menu( menu, menu )
	end, true )
	local f1_local10 = LUI.DataSourceInControllerModel.new( "cg.player.currentWeapon.inWorldAttachmentsAlpha" )
	self:BindAlphaToModel( f1_local10:GetModel( f1_local1 ) )
	f1_local3()
	local f1_local11 = self:Wait( 50 )
	f1_local11.onComplete = function ()
		return menu( menu, menu )
	end
	
	return self
end

MenuBuilder.registerType( "FrontendScopeReticleManager", FrontendScopeReticleManager )
LockTable( _M )
