-- Generated by CoDLuaDecompiler
-- Version: 2.4.2
-- Date: 27-09-2025 22:41
SEASONAL_EVENT = SEASONAL_EVENT or {}
SEASONAL_EVENT.BUTTON_LOCK_TIME = 2000
SEASONAL_EVENT.UNLOCK_SEEN_SIZE = 18
SEASONAL_EVENT.IDS = {
	ZOMBIES = 3,
	LEP = 10,
	SUMMER_OF_ACTION = 6,
	ADLER = 4,
	HAUNT = 9,
	MILITARY_APPRECIATION = 5,
	ATLANTIS = 2,
	NUMBERS = 8,
	HALLOWEEN = 1,
	SATELLITE = 7
}
SEASONAL_EVENT.MOD_ANIM_EVENT_NAME = "update_season_event_mod_anim"
local f0_local0 = {
	{
		useStackedCards = true,
		useTacMapChallengeTracker = true,
		isGiftDisabled = true,
		completionBink = "mp_lep_collected",
		onboardingBink = "mp_lep_onboarding",
		isFinalRewardAutomatic = true,
		useSquareProgressPanel = true,
		initSetupSequenceName = "SetupLEPEvent",
		tabName = "BR_LEP_EVENT/LEP_TITLE",
		id = SEASONAL_EVENT.IDS.LEP,
		onboardingData = Onboarding.LEP,
		fullscreenCinematic = {
			video = "mp_lep_collected"
		},
		crossLaunchButtonData = {
			gameSourceID = LUI.GAME_SOURCE_ID.VANGUARD,
			deepLinkMode = LUI.DEEP_LINK_GAME_MODE.MP
		},
		gameSourceData = {
			[LUI.GAME_SOURCE_ID.VANGUARD] = {
				modAnim = "ModVA"
			},
			[LUI.GAME_SOURCE_ID.WARZONE] = {
				modAnim = "ModWZ"
			}
		},
		inGameSplashData = {
			textHeaderParameterized = "SEASONAL_EVENT/SPLASH_X_CHALLENGE_COMPLETE_HEADER",
			textSeasonComplete = "SEASONAL_EVENT/SEASONAL_EVENT_COMPLETE",
			textBodyParameterized = "SEASONAL_EVENT/SPLASH_LOOTFOUND_SUBHEADER",
			sound = SOUND_SETS.seasonalEvents.seasonalEventSplash
		},
		menuSubTab = {
			layoutAnim = "LimitedTimeVariantLEP"
		},
		notActiveChallengeHoverSFX = SOUND_SETS.seasonalEvents.seasonalEventLepHighlight,
		activeChallengeHoverSFX = SOUND_SETS.battlePass.bpCardHighlight,
		toggleButtonActionSFX = SOUND_SETS.seasonalEvents.seasonalEventLepHighlight,
		widgetIncludeList = {
			SeasonalEventMenu = {
				nil,
				"ChallengeCompletedImage",
				"VignetteLeft",
				"VignetteRight"
			},
			SeasonalEventChallengesIndicator = {
				nil,
				"IconChallenge"
			},
			SeasonalEventSquareProgressPanel = {
				nil,
				"Backer"
			},
			SeasonalEventIntroPopup = {
				nil,
				"GenericButton"
			}
		}
	},
	{
		useStackedCards = true,
		binkBackground = true,
		isGiftDisabled = true,
		completionBink = "mp_haunt_collected",
		baseWeaponReward = true,
		onboardingBink = "mp_haunt_onboarding",
		isFinalRewardAutomatic = true,
		shareFinalReward = true,
		useSquareProgressPanel = true,
		initSetupSequenceName = "SetupHauntEvent",
		tabName = "SEASONAL_EVENT/HAUNT_EVENT_TITLE",
		id = SEASONAL_EVENT.IDS.HAUNT,
		onboardingData = Onboarding.SeasonalEvent,
		fullscreenCinematic = {
			video = "mp_haunt_collected"
		},
		crossLaunchButtonData = {
			gameSourceID = LUI.GAME_SOURCE_ID.COLD_WAR,
			deepLinkMode = LUI.DEEP_LINK_GAME_MODE.MP
		},
		storeBundleButtonData = {
			layoutAnim = "StoreHauntStoreBundleLayout",
			hidePromptWhenCompleted = true
		},
		gameSourceData = {
			[LUI.GAME_SOURCE_ID.COLD_WAR] = {
				modAnim = "ModCW"
			},
			[LUI.GAME_SOURCE_ID.WARZONE] = {
				modAnim = "ModWZ"
			}
		},
		inGameSplashData = {
			textHeaderParameterized = "SEASONAL_EVENT/SPLASH_X_CHALLENGE_COMPLETE_HEADER",
			textSeasonComplete = "SEASONAL_EVENT/SEASONAL_EVENT_COMPLETE",
			textBodyParameterized = "SEASONAL_EVENT/SPLASH_LOOTFOUND_SUBHEADER",
			sound = SOUND_SETS.seasonalEvents.seasonalEventSplashNumbers
		},
		eventMenuBinkBackground = {
			isEncrypted = false,
			wzBinkBackground = "ui_menu_event_s6_menu_backer_cw_10sec_1080p",
			t9BinkBackground = "ui_menu_event_s6_menu_backer_wz_10sec_1080p"
		},
		widgetIncludeList = {
			SeasonalEventMenu = {
				nil,
				"StoreBundlePrompt"
			},
			SeasonalEventIntroPopup = {
				nil,
				"GenericButton"
			}
		}
	},
	{
		isFinalRewardAutomatic = true,
		binkBackground = true,
		useTacMapChallengeTracker = true,
		isGiftDisabled = true,
		completionBink = "seasonal_event_outro",
		baseWeaponReward = true,
		onboardingBink = "seasonal_event_intro",
		useStackedCards = true,
		shareFinalReward = true,
		useSquareProgressPanel = true,
		initSetupSequenceName = "SetupNumbersEvent",
		tabName = "SEASONAL_EVENT/SEASONAL_EVENT_TITLE",
		id = SEASONAL_EVENT.IDS.NUMBERS,
		onboardingData = Onboarding.SeasonalEvent,
		fullscreenCinematic = {
			video = "seasonal_event_outro"
		},
		crossLaunchButtonData = {
			gameSourceID = LUI.GAME_SOURCE_ID.COLD_WAR,
			deepLinkMode = LUI.DEEP_LINK_GAME_MODE.MP
		},
		storeBundleButtonData = {
			layoutAnim = "SetupNumbersStoreBundleLayout"
		},
		gameSourceData = {
			[LUI.GAME_SOURCE_ID.COLD_WAR] = {
				modAnim = "ModCW"
			},
			[LUI.GAME_SOURCE_ID.WARZONE] = {
				modAnim = "ModWZ"
			}
		},
		inGameSplashData = {
			textHeaderParameterized = "SEASONAL_EVENT/SPLASH_X_CHALLENGE_COMPLETE_HEADER",
			textSeasonComplete = "SEASONAL_EVENT/SEASONAL_EVENT_COMPLETE",
			textBodyParameterized = "SEASONAL_EVENT/SPLASH_LOOTFOUND_SUBHEADER",
			sound = SOUND_SETS.seasonalEvents.seasonalEventSplashNumbers
		},
		eventMenuBinkBackground = {
			isEncrypted = false,
			wzBinkBackground = "ui_menu_event_s5_5_menu_backer_cw_10sec_1080p",
			t9BinkBackground = "ui_menu_event_s5_5_menu_backer_wz_10sec_1080p"
		},
		menuSubTab = {
			layoutAnim = "LimitedTimeVariantNumbers"
		},
		widgetIncludeList = {
			SeasonalEventMenu = {
				nil,
				"StoreBundlePrompt"
			},
			SeasonalEventIntroPopup = {
				nil,
				"GenericButton"
			}
		}
	},
	{
		shareFinalReward = true,
		useSquareProgressPanel = true,
		initSetupSequenceName = "SetupSeasonalEvent",
		isGiftDisabled = true,
		completionBink = "seasonal_event_outro",
		tabName = "SEASONAL_EVENT/SEASONAL_EVENT_TITLE",
		onboardingBink = "seasonal_event_intro",
		isFinalRewardAutomatic = true,
		id = SEASONAL_EVENT.IDS.SATELLITE,
		onboardingData = Onboarding.SeasonalEvent,
		fullscreenCinematic = {
			video = "seasonal_event_outro"
		},
		crossLaunchButtonData = {
			gameSourceID = LUI.GAME_SOURCE_ID.COLD_WAR,
			deepLinkMode = LUI.DEEP_LINK_GAME_MODE.MP
		},
		gameSourceData = {
			[LUI.GAME_SOURCE_ID.COLD_WAR] = {
				modAnim = "ModCW"
			},
			[LUI.GAME_SOURCE_ID.WARZONE] = {
				modAnim = "ModWZ"
			}
		},
		inGameSplashData = {
			textHeaderParameterized = "SEASONAL_EVENT/SPLASH_X_CHALLENGE_COMPLETE_HEADER",
			textSeasonComplete = "SEASONAL_EVENT/SEASONAL_EVENT_COMPLETE",
			textBodyParameterized = "SEASONAL_EVENT/SPLASH_LOOTFOUND_SUBHEADER",
			sound = SOUND_SETS.seasonalEvents.seasonalEventSplash
		},
		widgetIncludeList = {
			SeasonalEventIntroPopup = {
				nil,
				"GenericButton"
			}
		}
	},
	{
		isFinalRewardAutomatic = true,
		isGiftDisabled = true,
		completionBink = "seasonal_event_outro",
		onboardingBink = "seasonal_event_intro",
		useStackedCards = true,
		useSquareProgressPanel = true,
		initSetupSequenceName = "SetupSeasonalEvent",
		tabName = "SEASONAL_EVENT/SEASONAL_EVENT_TITLE",
		id = SEASONAL_EVENT.IDS.SUMMER_OF_ACTION,
		onboardingData = Onboarding.SoAEvent,
		fullscreenCinematic = {
			video = "seasonal_event_outro"
		},
		crossLaunchButtonData = {
			gameSourceID = LUI.GAME_SOURCE_ID.COLD_WAR,
			deepLinkMode = LUI.DEEP_LINK_GAME_MODE.MP
		},
		storeBundleButtonData = {
			layoutAnim = "StoreBundleLayout"
		},
		gameSourceData = {
			[LUI.GAME_SOURCE_ID.COLD_WAR] = {
				modAnim = "ModCW"
			},
			[LUI.GAME_SOURCE_ID.WARZONE] = {
				modAnim = "ModWZ"
			}
		},
		inGameSplashData = {
			textHeaderParameterized = "SEASONAL_EVENT/SPLASH_X_CHALLENGE_COMPLETE_HEADER",
			textSeasonComplete = "SEASONAL_EVENT/SEASONAL_EVENT_COMPLETE",
			textBodyParameterized = "SEASONAL_EVENT/SPLASH_LOOTFOUND_SUBHEADER",
			sound = SOUND_SETS.seasonalEvents.seasonalEventSplash
		},
		challengeCardHoverSound = SOUND_SETS.seasonalEvents.adlerChallengeCardSFX,
		widgetIncludeList = {
			SeasonalEventMenu = {
				nil,
				"StoreBundlePrompt"
			},
			SeasonalEventSquareProgressPanel = {
				nil,
				"XPBG",
				"XPIcon",
				"XPReward"
			}
		},
		widgetExcludeList = {
			SeasonalEventChallengesIndicator = {
				nil,
				"XPReward"
			},
			SeasonalEventSquareProgressPanel = {
				nil,
				"Divider"
			}
		}
	},
	{
		initSetupSequenceName = "ShowMilitaryAppreciation",
		id = SEASONAL_EVENT.IDS.MILITARY_APPRECIATION,
		inGameSplashData = {
			textHeaderParameterized = "SEASONAL_EVENT/SPLASH_MILITARY_APPRECIATION_CHALLENGE_COMPLETE_HEADER",
			textSeasonComplete = "SEASONAL_EVENT/SPLASH_MILITARY_APPRECIATION_CHALLENGE_COMPLETE_HEADER",
			textBodyParameterized = "SEASONAL_EVENT/SPLASH_MILITARY_APPRECIATION_CHALLENGE_COMPLETE_DESC",
			sound = SOUND_SETS.seasonalEvents.militaryAppreciationMonthInGameSplash
		},
		widgetIncludeList = {
			BRBannerHeader = {
				nil,
				"Glow2",
				"ButtonGlowTop",
				"BodyBold",
				"HeaderNoWrap",
				"Reward"
			}
		}
	},
	{
		useSquareProgressPanel = true,
		initSetupSequenceName = "SetupAdlerEvent",
		isGiftDisabled = true,
		completionBink = "mp_adlerhunt_collected",
		tabName = "SEASONAL_EVENT/HUNT_FOR_ADLER_TITLE",
		onboardingBink = "mp_adlerhunt_onboarding",
		isFinalRewardAutomatic = true,
		id = SEASONAL_EVENT.IDS.ADLER,
		onboardingData = Onboarding.AdlerEvent,
		fullscreenCinematic = {
			video = "mp_adlerhunt_collected"
		},
		crossLaunchButtonData = {
			gameSourceID = LUI.GAME_SOURCE_ID.COLD_WAR,
			deepLinkMode = LUI.DEEP_LINK_GAME_MODE.MP
		},
		gameSourceData = {
			[LUI.GAME_SOURCE_ID.COLD_WAR] = {
				modAnim = "ModCW"
			},
			[LUI.GAME_SOURCE_ID.WARZONE] = {
				modAnim = "ModWZ"
			}
		},
		inGameSplashData = {
			textHeaderParameterized = "SEASONAL_EVENT/SPLASH_X_CHALLENGE_COMPLETE_HEADER",
			textSeasonComplete = "SEASONAL_EVENT/H4A_EVENT_COMPLETE",
			textBodyParameterized = "SEASONAL_EVENT/SPLASH_LOOTFOUND_SUBHEADER",
			sound = SOUND_SETS.seasonalEvents.adlerInGameSplash
		},
		challengeCardHoverSound = SOUND_SETS.seasonalEvents.adlerChallengeCardSFX,
		widgetIncludeList = {
			SeasonalEventChallengesIndicator = {
				nil,
				"Divider",
				"Border0"
			},
			SeasonalEventIntroPopup = {
				nil,
				"GenericButton"
			}
		}
	},
	{
		onboardingBinkKorea15Unsafe = true,
		initSetupSequenceName = "SetupZombiesEvent",
		isGiftDisabled = true,
		completionBink = "mp_outbreak_collected",
		tabName = "SEASONAL_EVENT/OUTBREAK_TITLE",
		onboardingBink = "mp_outbreak_onboarding",
		isFinalRewardAutomatic = true,
		id = SEASONAL_EVENT.IDS.ZOMBIES,
		soundSetOnboarding = SOUND_SETS.seasonalEvents.zombiesOnboarding,
		onboardingData = Onboarding.ZombiesEvent,
		fullscreenCinematic = {
			video = "mp_outbreak_collected",
			soundSetCollected = SOUND_SETS.seasonalEvents.zombiesCollected
		},
		crossLaunchButtonData = {
			layoutAnim = "CrossLaunchLayout",
			gameSourceID = LUI.GAME_SOURCE_ID.COLD_WAR,
			deepLinkMode = LUI.DEEP_LINK_GAME_MODE.ZM
		},
		storeBundleButtonData = {
			layoutAnim = "StoreBundleLayout"
		},
		gameSourceData = {
			[LUI.GAME_SOURCE_ID.COLD_WAR] = {
				findAllText = "SEASONAL_EVENT/COMPLETE_X_OUTBREAK_CHALLENGES",
				bonusLootText = "SEASONAL_EVENT/BONUS_OUTBREAK_REWARD",
				modAnim = "ModCW"
			},
			[LUI.GAME_SOURCE_ID.WARZONE] = {
				findAllText = "SEASONAL_EVENT/COMPLETE_X_VERDANSK_CHALLENGES",
				bonusLootText = "SEASONAL_EVENT/BONUS_WARZONE_REWARD",
				modAnim = "ModWZ"
			}
		},
		inGameSplashData = {
			textHeaderParameterized = "SEASONAL_EVENT/SPLASH_X_CHALLENGE_COMPLETE_HEADER",
			textSeasonComplete = "SEASONAL_EVENT/H4A_EVENT_COMPLETE",
			textBodyParameterized = "SEASONAL_EVENT/SPLASH_LOOTFOUND_SUBHEADER",
			sound = SOUND_SETS.seasonalEvents.zombiesInGameSplash
		},
		widgetIncludeList = {
			SeasonalEventMenu = {
				nil,
				"ProgressPanel",
				"CrossLaunchPrompt"
			},
			SeasonalEventChallenges = {
				nil,
				"Image"
			},
			SeasonalEventIntroPopup = {
				nil,
				"GenericButton"
			}
		}
	},
	{
		initSetupSequenceName = "AtlantisEvent",
		completionBink = "mp_atlantis_collected",
		tabName = "SEASONAL_EVENT/ATLANTIS_TITLE",
		onboardingBink = "mp_atlantis_onboarding",
		isFinalRewardAutomatic = true,
		id = SEASONAL_EVENT.IDS.ATLANTIS,
		soundSetOnboarding = SOUND_SETS.seasonalEvents.atlantisOnboarding,
		onboardingData = Onboarding.RebirthEvent,
		fullscreenCinematic = {
			video = "mp_atlantis_collected",
			soundSetCollected = SOUND_SETS.seasonalEvents.atlantisCollected
		},
		gameSourceData = {
			[LUI.GAME_SOURCE_ID.WARZONE] = {
				findAllText = "SEASONAL_EVENT/COMPLETE_X_CHALLENGES"
			}
		}
	},
	{
		usingMap = true,
		initSetupSequenceName = "Halloween",
		completionBink = "mp_halloween_collected",
		tabName = "SEASONAL_EVENT/HALLOWEEN",
		onboardingBink = "mp_halloween_onboarding",
		id = SEASONAL_EVENT.IDS.HALLOWEEN,
		soundSetOnboarding = SOUND_SETS.seasonalEvents.halloweenOnboarding,
		onboardingData = Onboarding.HalloweenOnboarding,
		fullscreenCinematic = {
			video = "mp_halloween_collected",
			soundSetCollected = SOUND_SETS.seasonalEvents.halloweenCollected
		},
		inGameSplashData = {
			textHeaderParameterized = "SEASONAL_EVENT/SPLASH_LOOTFOUND_HEADER",
			textSeasonComplete = "SEASONAL_EVENT/SPLASH_EVENT_COMPLETE",
			textBodyParameterized = "SEASONAL_EVENT/SPLASH_LOOTFOUND_SUBHEADER",
			sound = SOUND_SETS.seasonalEvents.halloweenInGameSplash
		}
	}
}
local f0_local1 = function ()
	return Dvar.CFHDGABACF( "MLNNMOPQOP" )
end

local f0_local2 = function ()
	local f50_local0 = f0_local0()
	return f50_local0 - math.floor( f50_local0 ) ~= 0
end

SEASONAL_EVENT.GetCurrentEventID = function ()
	return math.floor( f0_local0() )
end

SEASONAL_EVENT.GetPopupOnboardingWatchFlag = function ()
	return f0_local0() and Onboarding.tutorials.SEASON_MID_EVENT_POPUP_WATCH_FLAG or Onboarding.tutorials.SEASON_EVENT_POPUP_WATCH_FLAG
end

SEASONAL_EVENT.RegisterElementToModAnimEvent = function ( f46_arg0 )
	assert( f46_arg0._sequences, "SEASONAL_EVENT.RegisterElementToModAnimEvent -> expecting non-nil sequences on elementToRegister -> " .. tostring( f46_arg0.id ) )
	f46_arg0:registerEventHandler( SEASONAL_EVENT.MOD_ANIM_EVENT_NAME, function ( element, event )
		assert( element._sequences[event.animToUse], "SEASONAL_EVENT.RegisterElementToModAnimEvent -> expecting sequence ( " .. tostring( event.animToUse ) .. " ) defined on element -> " .. tostring( element.id ) )
		ACTIONS.AnimateSequence( element, event.animToUse )
	end )
end

SEASONAL_EVENT.GetCurrentSeasonalEventData = function ( f45_arg0 )
	if not CONDITIONS.IsSeasonalEventActive() and not f45_arg0 then
		return nil
	end
	for f45_local3, f45_local4 in ipairs( f0_local0 ) do
		if (not f45_local4.condition or f45_local4.condition and f45_local4.condition()) and f45_local4.id == SEASONAL_EVENT.GetCurrentEventID() then
			return f45_local4
		end
	end
end

SEASONAL_EVENT.GetCurrentSeasonalEventIsMap = function ()
	local f44_local0 = SEASONAL_EVENT.GetCurrentSeasonalEventData()
	if f44_local0 then
		return f44_local0.usingMap
	else
		return true
	end
end

local f0_local3 = function ( f43_arg0, f43_arg1, f43_arg2 )
	if not f43_arg0 or f43_arg0[f43_arg1] == nil then
		return false
	end
	for f43_local3, f43_local4 in ipairs( f43_arg0[f43_arg1] ) do
		if f43_local4 == f43_arg2 then
			return true
		end
	end
	return false
end

SEASONAL_EVENT.IsWidgetInCurrentEventIncludeList = function ( f42_arg0, f42_arg1 )
	local f42_local0 = SEASONAL_EVENT.GetCurrentSeasonalEventData()
	if not f42_local0 or f42_local0 == nil then
		return false
	else
		return f0_local0( f42_local0.widgetIncludeList, f42_arg0, f42_arg1 )
	end
end

SEASONAL_EVENT.IsWidgetInCurrentEventExcludeList = function ( f41_arg0, f41_arg1 )
	local f41_local0 = SEASONAL_EVENT.GetCurrentSeasonalEventData()
	if not f41_local0 or f41_local0 == nil then
		return false
	else
		return f0_local0( f41_local0.widgetExcludeList, f41_arg0, f41_arg1 )
	end
end

SEASONAL_EVENT.GetCurrentSeasonalEventIsLEP = function ()
	return SEASONAL_EVENT.GetCurrentEventID() == SEASONAL_EVENT.IDS.LEP
end

SEASONAL_EVENT.GetCurrentSeasonalEventIsHaunt = function ()
	return SEASONAL_EVENT.GetCurrentEventID() == SEASONAL_EVENT.IDS.HAUNT
end

SEASONAL_EVENT.GetCurrentSeasonalEventIsNumbers = function ()
	return SEASONAL_EVENT.GetCurrentEventID() == SEASONAL_EVENT.IDS.NUMBERS
end

SEASONAL_EVENT.GetCurrentSeasonalEventIsSatellite = function ()
	return SEASONAL_EVENT.GetCurrentEventID() == SEASONAL_EVENT.IDS.SATELLITE
end

SEASONAL_EVENT.GetCurrentSeasonalEventIsSummerOfAction = function ()
	return SEASONAL_EVENT.GetCurrentEventID() == SEASONAL_EVENT.IDS.SUMMER_OF_ACTION
end

SEASONAL_EVENT.GetCurrentSeasonalEventIsMilitaryAppreciation = function ()
	return SEASONAL_EVENT.GetCurrentEventID() == SEASONAL_EVENT.IDS.MILITARY_APPRECIATION
end

SEASONAL_EVENT.GetCurrentSeasonalEventIsAdler = function ()
	return SEASONAL_EVENT.GetCurrentEventID() == SEASONAL_EVENT.IDS.ADLER
end

SEASONAL_EVENT.GetCurrentSeasonalEventIsAtlantis = function ()
	return SEASONAL_EVENT.GetCurrentEventID() == SEASONAL_EVENT.IDS.ATLANTIS
end

SEASONAL_EVENT.GetCurrentSeasonalEventIsZombies = function ()
	return SEASONAL_EVENT.GetCurrentEventID() == SEASONAL_EVENT.IDS.ZOMBIES
end

SEASONAL_EVENT.GetCurrentSeasonalEventIsHaunt = function ()
	return SEASONAL_EVENT.GetCurrentEventID() == SEASONAL_EVENT.IDS.HAUNT
end

SEASONAL_EVENT.GetCurrentInitSetupSequenceName = function ()
	local f30_local0 = SEASONAL_EVENT.GetCurrentSeasonalEventData()
	if f30_local0 and f30_local0.initSetupSequenceName then
		return f30_local0.initSetupSequenceName
	else
		return ""
	end
end

SEASONAL_EVENT.GetCurrentSeasonalEventTabName = function ()
	local f29_local0 = SEASONAL_EVENT.GetCurrentSeasonalEventData()
	if f29_local0 then
		DebugPrint( "SEASONAL_EVENT.GetCurrentSeasonalEventTabName - seasonal currentEventID : " .. tostring( SEASONAL_EVENT.GetCurrentEventID() ) )
		DebugPrint( "SEASONAL_EVENT.GetCurrentSeasonalEventTabName - data.tabName : " .. tostring( f29_local0.tabName ) )
		return f29_local0.tabName
	else
		return ""
	end
end

SEASONAL_EVENT.GetCurrentSeasonalEventBinkName = function ()
	local f28_local0 = SEASONAL_EVENT.GetCurrentSeasonalEventData()
	if f28_local0 then
		return f28_local0.completionBink
	else
		return ""
	end
end

SEASONAL_EVENT.GetCurrentSeasonalEventOnboadingData = function ()
	local f27_local0 = SEASONAL_EVENT.GetCurrentSeasonalEventData()
	if f27_local0 then
		return f27_local0.onboardingData
	else
		return nil
	end
end

SEASONAL_EVENT.GetCurrentSeasonalEventHasCompletionSplash = function ()
	local f26_local0 = SEASONAL_EVENT.GetCurrentSeasonalEventData( true )
	if f26_local0 then
		return f26_local0.inGameSplashData ~= nil
	else
		return false
	end
end

SEASONAL_EVENT.GetCompletionChallengeData = function ()
	local f25_local0 = SEASONAL_EVENT.GetCurrentSeasonalEventData()
	local f25_local1 = {}
	table.insert( f25_local1, {
		key = 1,
		col = CSV.seasonalEvent.cols.isFinalReward
	} )
	table.insert( f25_local1, {
		col = CSV.seasonalEvent.cols.eventID,
		key = f25_local0.id
	} )
	local f25_local2 = CSV.ReadRow( CSV.seasonalEvent, StringTable.BABCABFJEJ( CSV.seasonalEvent.file, f25_local1 ) )
	if f25_local2 then
		return f25_local2.lootID, f25_local2.challengeRef, f25_local2.backendChallengeRef
	else
		
	end
end

SEASONAL_EVENT.GetData = function ( f24_arg0 )
	assert( f24_arg0, "Usage: SEASONAL_EVENT.GetData( <controllerIndex> )" )
	if not f24_arg0 then
		return 
	end
	local f24_local0 = {}
	local f24_local1 = StringTable.BFHCAIIDA( CSV.seasonalEvent.file )
	local f24_local2 = SEASONAL_EVENT.GetCurrentSeasonalEventData()
	local f24_local3 = -1
	if f24_local2 and f24_local2.id then
		f24_local3 = f24_local2.id
	end
	for f24_local4 = 0, f24_local1 - 1, 1 do
		local f24_local7 = CSV.ReadRowWithFile( CSV.seasonalEvent, CSV.seasonalEvent.file, f24_local4 )
		if f24_local7 and f24_local7.eventID then
			local f24_local8 = tonumber( f24_local7.eventID )
			if f24_local8 and f24_local8 == f24_local3 then
				local f24_local9 = tonumber( f24_local7.targetProgress )
				if f24_local7.challengeRef and 0 < #f24_local7.challengeRef and f24_local9 then
					if Engine.DDJFBBJAIG() or CONDITIONS.IsOnlineMatch() then
						local f24_local10 = MiscChallenges.CJJHIEDGGG( f24_arg0, f24_local7.challengeRef )
						if f24_local10 and f24_local10.Challenges and f24_local10.Challenges.Progress then
							f24_local7.isComplete = f24_local9 <= f24_local10.Challenges.Progress
							f24_local7.currentValue = math.min( f24_local10.Challenges.Progress, f24_local9 )
							f24_local7.maxValue = f24_local9
						end
					else
						f24_local7.isComplete = false
						f24_local7.currentValue = 0
						f24_local7.maxValue = f24_local9
					end
				end
				table.insert( f24_local0, f24_local7 )
			end
		end
	end
	return f24_local0
end

SEASONAL_EVENT.SetupCountdown = function ( f22_arg0, f22_arg1 )
	assert( f22_arg0, "Usage: SEASONAL_EVENT.SetupCountdown( <label> )" )
	if not f22_arg0 then
		DebugPrint( "SEASONAL_EVENT.SetupCountdown called without a label element" )
	end
	local f22_local0 = Dvar.CFHDGABACF( "NKRNRKQPSQ" ) or 0
	f22_arg0.eventTimer = LUI.UITimer.new( {
		interval = 1000,
		event = "update_seasonal_event_timer"
	} )
	f22_arg0.eventTimer.id = "seasonalEventTimer"
	f22_arg0:addElement( f22_arg0.eventTimer )
	f22_arg0:addAndCallEventHandler( "update_seasonal_event_timer", function ()
		local f23_local0 = Engine.DEIDGHDBHD()
		local f23_local1
		if f23_local0 < f22_arg0 then
			f23_local1 = f22_arg0 - f23_local0
			if not f23_local1 then
			
			else
				if f23_local1 == 0 then
					f22_arg0.eventTimer:closeTree()
					f22_arg0.eventTimer = nil
				end
				f23_local1 = Engine.JCBDICCAH( Engine.BJCFFHAIFA( f23_local1 ) )
				if f22_arg0 and f22_arg0.singleLineDisplayString then
					assert( type( "singleLineDisplayString" ) == "string", "The singleLineDisplayString must be of type 'string'." )
					f22_arg0:setText( ToUpperCase( Engine.CBBHFCGDIC( f22_arg0.singleLineDisplayString, f23_local1 ) ) )
				else
					f22_arg0:setText( ToUpperCase( f23_local1 ) )
				end
			end
		end
		f23_local1 = 0
	end )
end

SEASONAL_EVENT.AreAllSeasonalEventsCompleted = function ( f21_arg0 )
	assert( f21_arg0, "Usage: SEASONAL_EVENT.AreAllSeasonalEventsCompleted( <controllerIndex> )" )
	if not f21_arg0 then
		DebugPrint( "SEASONAL_EVENT.AreAllSeasonalEventsCompleted requires controllerIndex" )
		return 
	end
	local f21_local0, f21_local1, f21_local2 = SEASONAL_EVENT.GetOverallWZProgress( f21_arg0 )
	local f21_local3
	if f21_local0 == f21_local1 then
		f21_local3 = f21_local2
	else
		f21_local3 = false
	end
	return f21_local3
end

SEASONAL_EVENT.GetOverallWZProgress = function ( f20_arg0 )
	assert( f20_arg0, "Usage: SEASONAL_EVENT.GetOverallProgress( <controllerIndex> )" )
	if not f20_arg0 then
		DebugPrint( "SEASONAL_EVENT.GetOverallProgress requires controller index" )
		return 
	end
	local f20_local0 = 0
	local f20_local1 = 0
	local f20_local2 = false
	for f20_local6, f20_local7 in ipairs( SEASONAL_EVENT.GetData( f20_arg0 ) ) do
		if f20_local7.isFinalReward ~= "1" and f20_local7.isIntroGift ~= "1" and f20_local7.isEarlyAccessGift ~= "1" and f20_local7.gameSource == LUI.GAME_SOURCE_ID.WARZONE then
			f20_local1 = f20_local1 + 1
			if f20_local7.isComplete then
				f20_local0 = f20_local0 + 1
			end
		end
		if f20_local7.isFinalReward ~= "1" and f20_local7.isComplete then
			f20_local2 = true
		end
	end
	if f20_local1 == f20_local0 then
		f20_local3 = SEASONAL_EVENT.GetCurrentSeasonalEventData()
		if f20_local3 and f20_local3.isFinalRewardAutomatic then
			f20_local2 = true
		end
	end
	return f20_local0, f20_local1, f20_local2
end

SEASONAL_EVENT.IsSeasonalEventCompleteBinkSeen = function ( f19_arg0 )
	local f19_local0 = PlayerData.BFFBGAJGD( f19_arg0, CoD.StatsGroup.NonGame )
	f19_local0 = f19_local0.isSeasonalEventComplete
	local f19_local1 = nil
	if f19_local0 then
		f19_local1 = f19_local0:get()
	end
	local f19_local2
	if f19_local1 then
		f19_local2 = f19_local1
	else
		f19_local2 = f19_local1 == 1
	end
	return f19_local2
end

SEASONAL_EVENT.MarkSeasonalEventCompleteBink = function ( f18_arg0, f18_arg1 )
	local f18_local0 = PlayerData.BFFBGAJGD( f18_arg0, CoD.StatsGroup.NonGame )
	f18_local0 = f18_local0.isSeasonalEventComplete
	if f18_local0 then
		local f18_local1 = f18_local0
		local f18_local2 = f18_local0.set
		local f18_local3
		if f18_arg1 then
			f18_local3 = 1
		else
			f18_local3 = 0
		end
		f18_local2( f18_local1, f18_local3 )
		ACTIONS.UploadStats( nil, f18_arg0 )
	end
end

SEASONAL_EVENT.DisplayGiftPopups = function ()
	local f17_local0 = Dvar.IBEGCHEFE( "lui_seasonal_content_show_gifts" )
	if f17_local0 ~= nil then
		return f17_local0
	end
	local f17_local1 = SEASONAL_EVENT.GetCurrentSeasonalEventData()
	local f17_local2
	if f17_local1 then
		f17_local2 = f17_local1
	else
		f17_local2 = f17_local1.isGiftDisabled
	end
	return not f17_local2
end

SEASONAL_EVENT.GetIntroGiftDetails = function ()
	local f16_local0 = SEASONAL_EVENT.GetCurrentSeasonalEventData()
	local f16_local1 = {}
	table.insert( f16_local1, {
		key = 1,
		col = CSV.seasonalEvent.cols.isIntroGift
	} )
	table.insert( f16_local1, {
		col = CSV.seasonalEvent.cols.eventID,
		key = f16_local0.id
	} )
	local f16_local2 = CSV.ReadRow( CSV.seasonalEvent, StringTable.BABCABFJEJ( CSV.seasonalEvent.file, f16_local1 ) )
	if f16_local2 then
		return f16_local2.lootID, f16_local2.challengeRef
	else
		
	end
end

SEASONAL_EVENT.IsIntroGiftRecieved = function ( f15_arg0 )
	assert( f15_arg0, "Usage: SEASONAL_EVENT.IsIntroGiftRecieved( <controllerIndex> )" )
	local f15_local0, f15_local1 = SEASONAL_EVENT.GetIntroGiftDetails()
	assert( f15_local1, "Need gift challenge ref" )
	local f15_local2 = MiscChallenges.CJJHIEDGGG( f15_arg0, f15_local1 )
	local f15_local3
	if f15_local2 then
		f15_local3 = f15_local2
	else
		f15_local3 = f15_local2.Challenges
		if f15_local3 then
			f15_local3 = f15_local2.Challenges.Progress
			if f15_local3 then
				f15_local3 = 1 <= f15_local2.Challenges.Progress
			end
		end
	end
	return f15_local3
end

SEASONAL_EVENT.GetEarlyAccessGiftDetails = function ()
	local f14_local0 = SEASONAL_EVENT.GetCurrentSeasonalEventData()
	local f14_local1 = {}
	table.insert( f14_local1, {
		key = 1,
		col = CSV.seasonalEvent.cols.isEarlyAccessGift
	} )
	table.insert( f14_local1, {
		col = CSV.seasonalEvent.cols.eventID,
		key = f14_local0.id
	} )
	local f14_local2 = StringTable.BABCABFJEJ( CSV.seasonalEvent.file, f14_local1 )
	if 0 <= f14_local2 then
		local f14_local3 = CSV.ReadRow( CSV.seasonalEvent, f14_local2 )
		if f14_local3 then
			return f14_local3.lootID, f14_local3.challengeRef
		end
	end
	return nil
end

SEASONAL_EVENT.IsEarlyAccessGiftRecieved = function ( f13_arg0 )
	assert( f13_arg0, "Usage: SEASONAL_EVENT.IsEarlyAccessGiftRecieved( <controllerIndex> )" )
	local f13_local0, f13_local1 = SEASONAL_EVENT.GetEarlyAccessGiftDetails()
	if f13_local0 and f13_local1 then
		local f13_local2 = MiscChallenges.CJJHIEDGGG( f13_arg0, f13_local1 )
		local f13_local3
		if f13_local2 then
			f13_local3 = f13_local2
		else
			f13_local3 = f13_local2.Challenges
			if f13_local3 then
				f13_local3 = f13_local2.Challenges.Progress
				if f13_local3 then
					f13_local3 = 1 <= f13_local2.Challenges.Progress
				end
			end
		end
		return f13_local3
	else
		return nil
	end
end

SEASONAL_EVENT.GetSeasonalChallengeDetailsForChallengeId = function ( f12_arg0, f12_arg1 )
	local f12_local0 = MiscChallenges.DFHEFHDCFC( f12_arg0, f12_arg1 )
	if f12_local0 then
		local f12_local1 = f12_local0.Challenges.Ref
		if f12_local1 and 0 < #f12_local1 then
			local f12_local2 = StringTable.BJJBBCJGEJ( CSV.seasonalEvent.file, CSV.seasonalEvent.cols.challengeRef, f12_local1 )
			if f12_local2 and 0 <= f12_local2 then
				local f12_local3 = CSV.ReadRow( CSV.seasonalEvent, f12_local2 )
				if f12_local3 then
					return f12_local3
				end
			end
		end
	end
end

SEASONAL_EVENT.IsSeasonalChallenge = function ( f11_arg0, f11_arg1 )
	return SEASONAL_EVENT.GetSeasonalChallengeDetailsForChallengeId( f11_arg0, f11_arg1 ) ~= nil
end

SEASONAL_EVENT.IsSeasonalFinalChallenge = function ( f10_arg0, f10_arg1 )
	local f10_local0 = SEASONAL_EVENT.GetSeasonalChallengeDetailsForChallengeId( f10_arg0, f10_arg1 )
	local f10_local1
	if f10_local0 ~= nil then
		f10_local1 = f10_local0.isFinalReward
		if f10_local1 then
			if tonumber( f10_local0.isFinalReward ) ~= 1 then
				f10_local1 = false
			else
				f10_local1 = true
			end
		end
	else
		f10_local1 = false
	end
	return f10_local1
end

SEASONAL_EVENT.GetSeenUnlockID = function ( f9_arg0, f9_arg1 )
	local f9_local0 = assert
	local f9_local1
	if f9_arg0 then
		f9_local1 = f9_arg0
	else
		f9_local1 = f9_arg1
	end
	f9_local0( f9_local1, "Usage: SEASONAL_EVENT.GetSeenUnlockID( <controllerIndex>, <seasonalEventID> )" )
	if not f9_arg0 or not f9_arg1 then
		DebugPrint( "SEASONAL_EVENT.GetSeenUnlockID: missing controller index or sesaonal event ID" )
		return nil
	else
		f9_arg1 = tonumber( f9_arg1 )
		if not f9_arg1 or f9_arg1 <= 0 or f9_arg1 > SEASONAL_EVENT.UNLOCK_SEEN_SIZE then
			DebugPrint( "SEASONAL_EVENT.GetSeenUnlockID: seasonalEventID not in range, expected: [1-" .. SEASONAL_EVENT.UNLOCK_SEEN_SIZE .. "]" )
			return nil
		else
			f9_local0 = PlayerData.BFFBGAJGD( f9_arg0, CoD.StatsGroup.NonGame )
			f9_local0 = f9_local0.isSeasonalEventUnlockSeen
			if f9_local0 then
				return f9_local0[f9_arg1 - 1]:get() == 1
			else
				DebugPrint( "SEASONAL_EVENT.GetSeenUnlockID: nongamedata entry isSeasonalEventUnlockSeen does not exist" )
				return nil
			end
		end
	end
end

SEASONAL_EVENT.SetSeenUnlockID = function ( f8_arg0, f8_arg1 )
	local f8_local0 = assert
	local f8_local1
	if f8_arg0 then
		f8_local1 = f8_arg0
	else
		f8_local1 = f8_arg1
	end
	f8_local0( f8_local1, "Usage: SEASONAL_EVENT.SetSeenUnlockID( <controllerIndex>, <seasonalEventID> )" )
	if not f8_arg0 or not f8_arg1 then
		DebugPrint( "SEASONAL_EVENT.SetSeenUnlockID: missing controller index or seasonal event ID" )
		return 
	end
	f8_arg1 = tonumber( f8_arg1 )
	if not f8_arg1 or f8_arg1 <= 0 or f8_arg1 > SEASONAL_EVENT.UNLOCK_SEEN_SIZE then
		DebugPrint( "SEASONAL_EVENT.SetSeenUnlockID: seasonalEventID not in range, expected: [1-" .. SEASONAL_EVENT.UNLOCK_SEEN_SIZE .. "]" )
		return 
	end
	f8_local0 = PlayerData.BFFBGAJGD( f8_arg0, CoD.StatsGroup.NonGame )
	f8_local0 = f8_local0.isSeasonalEventUnlockSeen
	if f8_local0 then
		f8_local0[f8_arg1 - 1]:set( 1 )
		ACTIONS.UploadStats( nil, f8_arg0 )
	else
		DebugPrint( "SEASONAL_EVENT.SetSeenUnlockID: nongamedata entry isSeasonalEventUnlockSeen does not exist" )
	end
end

SEASONAL_EVENT.ResetUnlocksSeen = function ( f7_arg0 )
	assert( f7_arg0, "Usage: SEASONAL_EVENT.ResetUnlocksSeen( <controllerIndex> )" )
	if not f7_arg0 then
		return 
	end
	local f7_local0 = PlayerData.BFFBGAJGD( f7_arg0, CoD.StatsGroup.NonGame )
	f7_local0 = f7_local0.isSeasonalEventUnlockSeen
	if f7_local0 then
		local f7_local1 = 0
		local f7_local2 = StringTable.BFHCAIIDA( CSV.seasonalEvent.file )
		for f7_local3 = 0, f7_local2 - 1, 1 do
			if f7_local3 < SEASONAL_EVENT.UNLOCK_SEEN_SIZE then
				f7_local1 = f7_local1 + 1
				f7_local0[f7_local3]:set( 0 )
			end
		end
		ACTIONS.UploadStats( nil, f7_arg0 )
		if f7_local1 == f7_local2 then
			DebugPrint( "SeasonalEvent: Successfully reset nongamedata.isSeasonalEventUnlockSeen." )
		end
		DebugPrint( "SeasonalEvent: Size of " .. CSV.seasonalEvent.file .. " and nongamedata.isSeasonalEventUnlockSeen are out of sync." )
	end
end

local f0_local4 = 10000
SEASONAL_EVENT.TryAwardSeasonalEventsComplete = function ( f4_arg0, f4_arg1 )
	local f4_local0 = function ()
		LUI.FlowManager.RequestAddMenu( "StoreFullScreenCinematic", true, f4_arg0, false, {
			skipVideoOnPartyJoin = true,
			disableQuickAccess = true,
			isSeasonalEvent = true,
			isComplete = true,
			skipImmediate = true,
			video = SEASONAL_EVENT.GetCurrentSeasonalEventBinkName()
		}, true )
		SEASONAL_EVENT.MarkSeasonalEventCompleteBink( f4_arg0, true )
	end
	
	local f4_local1 = SEASONAL_EVENT.GetCurrentSeasonalEventData()
	if f4_local1 and f4_local1.isFinalRewardAutomatic then
		local f4_local2, f4_local3, f4_local4 = SEASONAL_EVENT.GetCompletionChallengeData()
		if f4_local3 then
			local f4_local5 = MiscChallenges.CJJHIEDGGG( f4_arg1, f4_local3 )
			if f4_local5 and f4_local5.Challenges and f4_local5.Challenges.Progress and f4_local5.Challenges.Progress < 1 then
				f4_arg0:addEventHandler( "completed_misc_challenge", function ( f5_arg0, f5_arg1 )
					f4_arg0()
				end )
				Challenges.DFGEFGFCFC( f4_arg1, "collect_item", f4_local4 )
			elseif not SEASONAL_EVENT.IsSeasonalEventCompleteBinkSeen( f4_arg1 ) then
				f4_local0()
			end
		end
	end
end

SEASONAL_EVENT.SetupProgressionEntries = function ( f3_arg0, f3_arg1 )
	local f3_local0 = nil
	for f3_local9, f3_local10 in ipairs( f3_arg0 ) do
		if Engine.DIEEIEFCFF() then
			if f3_local10.id == SEASONAL_EVENT.IDS.ZOMBIES and f3_local10.order == "2" then
				f3_local0 = f3_local10
			elseif f3_local0 == nil and f3_local10.id ~= SEASONAL_EVENT.IDS.ZOMBIES and f3_local10.order == "1" then
				f3_local0 = f3_local10
			end
		elseif f3_local0 == nil and f3_local10.order == "1" then
			f3_local0 = f3_local10
		end
		local f3_local4 = f3_local10.isFinalReward == "1"
		local f3_local5
		if f3_local10.isIntroGift == "1" or f3_local10.isEarlyAccessGift == "1" then
			f3_local5 = false
		else
			f3_local5 = true
		end
		local f3_local6 = f3_local10.gameSource
		if not f3_local6 then
			f3_local6 = LUI.GAME_SOURCE_ID.WARZONE
		end
		if not f3_arg1[f3_local6] then
			f3_arg1[f3_local6] = {
				_numChallenges = 0,
				_numComplete = 0,
				_finalLootID = 0
			}
		end
		if f3_local4 then
			local f3_local7 = f3_arg1[f3_local6]
			local f3_local8 = tonumber( f3_local10.lootID )
			if not f3_local8 then
				f3_local8 = 0
			end
			f3_local7._finalLootID = f3_local8
			f3_local7 = f3_arg1[f3_local6]
			f3_local8 = f3_local10.challengeRef
			if not f3_local8 then
				f3_local8 = ""
			end
			f3_local7._challengeRef = f3_local8
		end
		if f3_local5 then
			f3_arg1[f3_local6]._numChallenges = f3_arg1[f3_local6]._numChallenges + 1
			if f3_local10.isComplete then
				f3_arg1[f3_local6]._numComplete = f3_arg1[f3_local6]._numComplete + 1
			end
		end
	end
	return f3_local0
end

SEASONAL_EVENT.SetupProgressionPanel = function ( f2_arg0, f2_arg1 )
	assert( f2_arg1, "ProgressPanel:Setup requires seasonal event data" )
	if not f2_arg1 then
		f2_arg0.FinalReward:SetAlpha( 0 )
		return 
	else
		f2_arg0.Preview:setText( Engine.CBBHFCGDIC( "SEASONAL_EVENT/PREVIEW" ) )
		local f2_local0 = SEASONAL_EVENT.SetupProgressionEntries( f2_arg1, f2_arg0._csvEntryListData )
		if f2_local0 and f2_local0.gameSource then
			return f2_local0.gameSource
		else
			
		end
	end
end

SEASONAL_EVENT.GetLepChallengeName = function ( f1_arg0 )
	local f1_local0 = BitwiseOperators.band( Game.BFEEGCHICA( f1_arg0, "ui_br_lep_data_client" ) or 0, 7 )
	if 0 < f1_local0 then
		local f1_local1 = {
			nil,
			"BR_LEP_EVENT/CH_HINT_TITLE_WZ_1",
			"BR_LEP_EVENT/CH_HINT_TITLE_WZ_2",
			"BR_LEP_EVENT/CH_HINT_TITLE_WZ_3",
			"BR_LEP_EVENT/CH_HINT_TITLE_WZ_4",
			"BR_LEP_EVENT/CH_HINT_TITLE_WZ_5",
			"BR_LEP_EVENT/CH_HINT_TITLE_WZ_6"
		}
		return f1_local1[f1_local0]
	else
		return ""
	end
end

